### ISSUE TITLE
TransferUtilityUploadRequest.UploadProgressEvent event not firing

### ISSUE THREAD

**Issue by Abhiram-Kasu** [aws/aws-sdk-net#3308] opened 2024-04-30 06:05 UTC
### Describe the bug

Any delegates added to the UploadProgressEvent are not being activated. Files are still uploaded at the end, but callbacks are not being invoked. Tried downgrading sdk version to 3.7.0 and the callbacks **DID WORK** and were called.

### Expected Behavior

Expected delegates to activate to give progress updates on the current file upload request

### Current Behavior

Delegates are never called, as in the code inside the event handler is never ran regardless of the file size and the time taken

### Reproduction Steps

Create a TransferUtility object
```csharp
        var transferUtility = new TransferUtility(S3Client);
```

Create TransferUtilityUploadRequest with a file **stream** and attach handler to the UploadProgressEvent event
```csharp
               var req = new TransferUtilityUploadRequest
                {
                    ContentType = "application/pdf",
                    InputStream = stream,
                    BucketName = "(Any bucket name)",

                };
                
                req.UploadProgressEvent +=  (sender, args) =>
                    Logger.LogInformation("Progress: {percent}", args.PercentDone);
```

await upload
```csharp
                await transferUtility.UploadAsync(req);
```

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.307.25

### Targeted .NET Platform

.NET 8

### Operating System and version

Mac OS Sonoma M3 Pro

**Comment by ashishdhingra** [comment] 2024-04-30 17:15
@Abhiram-Kasu Good morning. Could you please share the following:
- Execution environment for your code
- You code uses `InputStream` in `TransferUtilityUploadRequest` object:
  - What is the source of this stream?
  - Is this stream seekable? We added support for uploading non-seekable stream few months back, in that case it might not be possible to capture the transfer progress since the stream is not seekable to get the file size.
  -  Could you try uploading the file directly (instead of using the stream) by using `FilePath` property of `TransferUtilityUploadRequest` and see if callback delegate is invoked.

Thanks,
Ashish

**Comment by Abhiram-Kasu** [comment] 2024-04-30 20:52
Hello @ashishdhingra,
 The execution environment for my code is an ASP.NET .NET 8 Web App running in SSR and InteractiveServer. This code is called inside of a blazor page.

The size of the file that I am trying to upload is 12 mb, but I also have tried with bigger and smaller files

The source of the stream is from an IBrowserFile and from calling the OpenReadStream();
```csharp
            await using var stream = file.OpenReadStream(MAX_FILE_SIZE);
```
As for trying to upload with a file, it does work when I copy the full file to the server, but it is not feasible for my blazor application as the file sizes can vary and grow.

Is there a way for me to achieve progress updates with a stream without copying the full file to the server?

**Comment by ashishdhingra** [comment] 2024-04-30 22:40
> As for trying to upload with a file, it does work when I copy the full file to the server, but it is not feasible for my blazor application as the file sizes can vary and grow.
> 
> Is there a way for me to achieve progress updates with a stream without copying the full file to the server?

@Abhiram-Kasu We would need to investigate. So are you executing S3 upload using TransferUtility from the Blazor client side code? Could you check in .NET code, what is the value of `CanSeek` property of stream returned by `file.OpenReadStream()`?

**Comment by Abhiram-Kasu** [comment] 2024-05-01 02:33
The code is technically server-side code that runs over the web-scoket, if that helps anything. The CanSeek property did in fact return false. Here is any more information about the stream: 
<img width="896" alt="image" src="https://github.com/aws/aws-sdk-net/assets/79026503/226ac004-736d-43be-b6a1-92357f3e727a">

**Comment by ashishdhingra** [comment] 2024-05-02 18:25
Reproducible using code below:
```C#
long MEG_SIZE = (int)Math.Pow(2, 20);
var fileName = GenerateName(@"SimpleUploadTest\SmallFile");
var path = Path.Combine(Path.GetTempPath(), fileName);
var fileSize = 20 * MEG_SIZE;
GenerateFile(path, fileSize);
//take the generated file and turn it into an unseekable stream

var stream = GenerateBrowserFileUnseekableStreamFromFile(path);
using (var tu = new Amazon.S3.Transfer.TransferUtility(client))
{
    TransferUtilityUploadRequest transferUtilityUploadRequest = new TransferUtilityUploadRequest()
    {
        BucketName = bucketName,
        Key = fileName,
        InputStream = stream
    };

    transferUtilityUploadRequest.UploadProgressEvent += (object? sender, UploadProgressArgs e) => Console.WriteLine($"Progress: {e.PercentDone}");
    transferUtilityUploadRequest.Metadata.Add("testmetadata", "testmetadatavalue");
    transferUtilityUploadRequest.Headers["Content-Disposition"] = "attachment; filename=\"" + fileName + "\"";

    tu.Upload(transferUtilityUploadRequest);
}

BrowserFileUnseekableStream GenerateBrowserFileUnseekableStreamFromFile(string filePath)
{
    try
    {
        BrowserFileUnseekableStream unseekableStream = new BrowserFileUnseekableStream(filePath);
        return unseekableStream;
    }
    catch (Exception ex)
    {
        Console.WriteLine($"An error occurred while generating the stream: {ex.Message}");
        throw;
    }
}

static string GenerateName(string name)
{
    return name + new Random().Next();
}

static void GenerateFile(string path, long size)
{
    string contents = GenerateTestContents(size);
    WriteFile(path, contents);
}

static void WriteFile(string path, string contents)
{
    string fullPath = Path.GetFullPath(path);
    new DirectoryInfo(Path.GetDirectoryName(fullPath)).Create();
    File.WriteAllText(fullPath, contents);
}

static string GenerateTestContents(long size)
{
    StringBuilder sb = new StringBuilder();
    for (long i = 0; i < size; i++)
    {
        char c = (char)('a' + (i % 26));
        sb.Append(c);
    }
    string contents = sb.ToString();
    return contents;
}

public class BrowserFileUnseekableStream : MemoryStream
{
    MemoryStream inner;
    public BrowserFileUnseekableStream(string path)
    {
        this.inner = new MemoryStream(File.ReadAllBytes(path));
    }

    public override bool CanSeek
    {
        get => false;
    }
    public override long Length
    {
        get
        {
            if (inner.Length >= -1)
            {
                return inner.Length;
            }
            throw new NotSupportedException();
        }
    }
}
```

Needs review with the team. Based on user provided screenshot in https://github.com/aws/aws-sdk-net/issues/3308#issuecomment-2087888223, `CanSeek` for stream is `false` and `Length` has a value.

**Comment by peterrsongg** [comment] 2024-05-22 18:24
@Abhiram-Kasu Hello, I've been trying to reproduce the scenario where you said it **did work**. You mentioned versions 3.7.0? Can you give me the exact version and maybe attach some logs for me to look at? I created a wrapper around the FileStream class where it wasn't seekable but did contain a content length. I tried to upload via the TransferUtility with version 3.7.0 and the upload wasn't even going through in those cases, so I'm curious how it was working in the previous versions.

Unseekable stream upload support was added in the last year or so, so the reason the delegates aren't being called now is because it's going through a different code path. We could add some progress handlers but first I want to make sure that it was working before and perhaps just route it to the previous code path where it was working.

**Comment by peterrsongg** [comment] 2024-05-22 20:55
The stream looks exactly the same, but for S3 version 3.7.0 it failes
![unseekable_3 7 0_fail](https://github.com/aws/aws-sdk-net/assets/37608646/012d6599-d860-4295-83d6-c32c44be26ef)

**Comment by Abhiram-Kasu** [comment] 2024-05-24 05:34
Sorry for no response, glad to see you can reproduce. I did in fact just use version 3.7.0 though.

**Comment by peterrsongg** [comment] 2024-05-29 21:01
@Abhiram-Kasu No problem, the fix for this has been released in AWSSDK.S3 [3.7.308.6](https://www.nuget.org/packages/AWSSDK.S3/3.7.308.6). Going to close this out now, feel free to re-open if you find something wrong!

**Closed by peterrsongg** 2024-05-29 21:01 UTC
Labels: bug, p1, s3, queued
