### ISSUE TITLE
GetCommandInvocation don't return StandardOutputContent & StandardErrorContent

### ISSUE THREAD

**Issue by Aivanovac** [aws/aws-sdk-net#535] opened 2017-01-24 06:50 UTC
i try to run simple script "dir c:\" on my ec2 instance by SimpleSystemsManagement, everything looks good, but i can't get StandardOutputContent & StandardErrorContent of my script. And important, i can't use s3 service

i use such code
```csharp
string _awsInstanceId = null;
string _awsAccessKeyId = null;
string _awsSecretAccessKey = null;
string _awsRegion = null;

var ssmClient = new Amazon.SimpleSystemsManagement.AmazonSimpleSystemsManagementClient(_awsAccessKeyId, _awsSecretAccessKey, _awsRegion);
var request = new Amazon.SimpleSystemsManagement.Model.SendCommandRequest();
request.DocumentName = "AWS-RunPowerShellScript";
request.InstanceIds = new List<string>() { _awsInstanceId };
request.Parameters = new Dictionary<string, List<string>>()
{
    { "commands", new List<string>() { @"dir c:\"} },
    { "workingDirectory", new List<string>() { @"c:\" } }
};

var responce = ssmClient.SendCommand(request);
var commandResultRequest = new Amazon.SimpleSystemsManagement.Model.GetCommandInvocationRequest();
commandResultRequest.CommandId = responce.Command.CommandId;
commandResultRequest.InstanceId = _awsInstanceId;
    
while (true)
{
    var results = ssmClient.GetCommandInvocation(commandResultRequest);
    if (results.Status != Amazon.SimpleSystemsManagement.CommandInvocationStatus.InProgress)
    {
        //  StandardOutputContent & StandardErrorContent empty        
        break;
    }
    else
        System.Threading.Thread.Sleep(2000);
}
```

i check responce from AWS by Fiddler, and it really didn't return values
{"CommandId":"8820ed1a-5f5e-4a6d-8fed-e2ae063d5b50","Comment":"","DocumentName":"AWS-RunPowerShellScript","ExecutionElapsedTime":"PT6.379S","ExecutionEndDateTime":"2017-01-24T06:16:57.557Z","ExecutionStartDateTime":"2017-01-24T06:16:51.557Z","InstanceId":"i-0da2da65ef4b5bd7d","PluginName":"aws:runPowerShellScript","ResponseCode":0,"StandardErrorContent":"","StandardErrorUrl":"","StandardOutputContent":"","StandardOutputUrl":"","Status":"Success","StatusDetails":"Success"}

is there any other way to get output of script ?

**Comment by sstevenkang** [comment] 2017-01-25 18:39
I was able to repro this problem.  From the documentation, it looks like the powershell plugin simply does not emit anything to stdout.  I've reached out to SSM team to verify that this is the intended behavior.

**Comment by sstevenkang** [comment] 2017-01-30 20:10
@Aivanovac I got a confirmation that this is a service side issue.  There's nothing SDK team can do at this point.  I'll keep this report open until a fix is in place.

**Comment by sstevenkang** [comment] 2017-03-09 01:12
@Aivanovac we are still waiting on the service team to get back to us.  Because there's no actionable item on our part, we'll close this issue.  Please try reaching out directly to the service team on AWS forums or open a support ticket.

**Closed by sstevenkang** 2017-03-09 01:12 UTC
Labels: Service Issue

**Comment by meyerbro** [comment] 2017-04-24 18:32
I'm having the same issue with AWS-RunShellScript...
