### ISSUE TITLE
DynamoDbV2 Unmanaged / Virtual Memory Leak

### ISSUE THREAD

**Issue by dazrulez** [aws/aws-sdk-net#1171] opened 2019-01-10 11:28 UTC
There appears to be a memory leak between the following versions of core and dynamodb:
Core Version: 3.3.24.8 - 3.3.31
DB Version: 3.3.10.4 - 3.3.16.3

I upgraded packages to the latest from the version above and instantly noticed gains in unmanaged memory that wouldn't subside. GC Memory remained constant while unmanaged memory rose (10mb~ per hour)

I'm using the dynamodb sdk and performing mostly write operations, I could only recreate the issue under moderate load (500+ read/writes per second). 

## Expected Behavior
Unmanaged memory shouldnt consistently rise over time when objects are being cleaned up. If i complete 100000 read/write operations, unmanaged memory should remain constant when comparing before and after

## Current Behavior
Unmanaged memory continues to rise and gc memory remains constant before and after heavy read/write operations

## Possible Solution
Unknown - rolling back the package version to 
Core Version: 3.3.24.8
DB Version: 3.3.10.4
Fixed my issue, but unknown as to which version is affected

## Steps to Reproduce (for bugs)
Perform a moderate amount of read / write operations per second (500+) and watch unmanaged memory rise

## Context
My server application usually remains constant at about 14mb unmanaged / virtual memory (excluding GC Heap) and 60mb GC heap. With the issue described above, after leaving my server running over night i saw an increase to 200mb+ unmanaged / virtual memory while the GC Heap remained constant at 60mb

## Your Environment

* AWSSDK.Core version used:  3.3.31
* Service assembly and version used: 3.3.16.3
* Operating System and version: Windows Server 2016
* Visual Studio version: VS 2017 15.8.1
* Targeted .NET platform: Net 4.6.2 and 4.5.2 (I saw the issue in both as I wanted to eliminate this as being the fault when narrowing down the problem)

## .NET Core Info
N/A

**Comment by klaytaybai** [comment] 2019-01-12 00:54
Hi @dazrulez, we are sorry you are seeing memory issues.  Thank you for the information you provided, especially the original version that may have been working better. This may be a duplicate of #1061.  We'll get back to you if we find anything out.

**Comment by robvanpamel** [comment] 2019-06-27 09:52
Hi  @klaytaybai 
We are having the same issue which is leading towards threadpool starvation. I have attached a stacktrace of what we are facing in issue #1061 . We have this issue at this moment with approx 500 concurrent users. 
I'll add over here as well to make it easier

     Blocking method has been invoked and blocked, this can lead to threadpool starvation.
     {StackTrace}","@l":"Warning","stackTrace":"   at System.Net.Http.HttpConnection.HttpContentReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)
       at ThirdParty.Ionic.Zlib.CrcCalculatorStream.Read(Byte[] buffer, Int32 offset, Int32 count)
       at System.IO.StreamReader.ReadBuffer()
       at System.IO.StreamReader.Read()
       at ThirdParty.Json.LitJson.Lexer.State19(FsmContext ctx)
       at ThirdParty.Json.LitJson.Lexer.NextToken()
       at ThirdParty.Json.LitJson.JsonReader.ReadToken()
       at ThirdParty.Json.LitJson.JsonReader.Read()
       at Amazon.Runtime.Internal.Transform.JsonUnmarshallerContext.Read()
       at Amazon.Runtime.Internal.Transform.JsonUnmarshallerContext.Peek(JsonToken token)
       at Amazon.Runtime.Internal.Transform.DictionaryUnmarshaller`4.Unmarshall(JsonUnmarshallerContext context)
       at Amazon.Runtime.Internal.Transform.ListUnmarshaller`2.Unmarshall(JsonUnmarshallerContext context)
       at Amazon.DynamoDBv2.Model.Internal.MarshallTransformations.QueryResponseUnmarshaller.Unmarshall(JsonUnmarshallerContext context)
       at Amazon.Runtime.Internal.Transform.JsonResponseUnmarshaller.Unmarshall(UnmarshallerContext input)
       at Amazon.Runtime.Internal.Transform.ResponseUnmarshaller.UnmarshallResponse(UnmarshallerContext context)
       at Amazon.Runtime.Internal.Unmarshaller.UnmarshallResponse(UnmarshallerContext context, IRequestContext requestContext)
       at Amazon.Runtime.Internal.Unmarshaller.UnmarshallAsync(IExecutionContext executionContext)
       at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
       at Amazon.Runtime.Internal.Unmarshaller.UnmarshallAsync(IExecutionContext executionContext)
       at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
       at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
       at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
       at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
       at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
       at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
       at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
       at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
       at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
       at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
       at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
       at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
       at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
       at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
       at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
       at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
       at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
       at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
       at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
       at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
       at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
       at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
       at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
       at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
       at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
       at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
       at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
       at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
       at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
       at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
       at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
       at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
       at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
       at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
       at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
       at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
       at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
       at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
       at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
       at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
       at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
       at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
       at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
       at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
       at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
       at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
       at System.Net.Http.HttpConnection.FillAsync()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
       at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
       at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
       at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
       at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
       at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
       at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
       at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
       at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
       at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
       at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
       at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
       at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync)
       at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs _)
       at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(Int32 bytesTransferred, SocketFlags flags)
       at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketFlags flags, SocketError socketError)
       at System.Net.Sockets.SocketAsyncEventArgs.TransferCompletionCallbackCore(Int32 bytesTransferred, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError socketError)
       at System.Net.Sockets.SocketAsyncContext.BufferMemoryReceiveOperation.InvokeCallback(Boolean allowPooling)
       at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessAsyncOperation(TOperation op)
       at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.<>c.<.cctor>b__18_0(Object op)
       at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by klaytaybai** [comment] 2019-11-18 21:44
I'm going to close this issue out in favor of putting any other DynamoDB memory issues on #1061.

**Closed by klaytaybai** 2019-11-18 21:44 UTC
Labels: duplicate
