### ISSUE TITLE
Crashes in Visual Studio 2017 in Team Explorer Manage Connections

### ISSUE THREAD

**Issue by rgutierrezatx** [aws/aws-sdk-net#1243] opened 2019-04-03 04:31 UTC
Install toolkit for visual studio 2017..  open Visual Studio and get this error inside the Team explorer tab:
`System.TypeInitializationException: The type initializer for 'Amazon.AWSToolkit.VisualStudio.TeamExplorer.CredentialManagement.TeamExplorerConnection' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Amazon.AWSToolkit.VisualStudio.TeamExplorer.CredentialManagement.TeamExplorerConnection..cctor()
   --- End of inner exception stack trace ---
   at Amazon.AWSToolkit.VisualStudio.TeamExplorer.CredentialManagement.TeamExplorerConnection.add_OnTeamExplorerBindingChanged(TeamExplorerBindingChanged value)
   at Amazon.AWSToolkit.VisualStudio.TeamExplorer.CodeCommit.Model.ConnectSectionViewModel..ctor()
   at Amazon.AWSToolkit.VisualStudio.TeamExplorer.CodeCommit.Connect.ConnectionSection.CreateViewModel(SectionInitializeEventArgs e)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.TeamExplorerSectionBase.Initialize(Object sender, SectionInitializeEventArgs e)
   at Amazon.AWSToolkit.VisualStudio.TeamExplorer.CodeCommit.Connect.ConnectionSection.Initialize(Object sender, SectionInitializeEventArgs e)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)`
`Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "Amazon.AWSToolkit.VisualStudio.TeamExplorer.CodeCommit.Connect.InvitationSection". ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Amazon.AWSToolkit.VisualStudio.TeamExplorer.CodeCommit.Connect.InvitationSection..ctor()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass13_0.<CreateExportFactory>b__0()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass54_0.<CreateExportFactory>b__0()
   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.VisualStudio.TeamFoundation.TeamExplorer.ConnectPage.InvitationViewModel..ctor(InvitationSectionViewModel sectionViewModel, ExportFactory`2 factory)
   at Microsoft.VisualStudio.TeamFoundation.TeamExplorer.ConnectPage.InvitationSectionViewModel..ctor(List`1 factories)
   at Microsoft.VisualStudio.TeamFoundation.TeamExplorer.ConnectPage.InvitationSection.CreateViewModel(SectionInitializeEventArgs e)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.TeamExplorerSectionBase.Initialize(Object sender, SectionInitializeEventArgs e)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)`

**Comment by normj** [comment] 2019-04-03 05:35
This is a duplicate of the following issue and we are working on a fix.
https://github.com/aws/aws-sdk-net/issues/1238

**Closed by normj** 2019-04-03 05:35 UTC
