### ISSUE TITLE
Gettings records from dynamodb RANDOMLY throws exceptions. 

### ISSUE THREAD

**Issue by bilal-fazlani** [aws/aws-sdk-net#334] opened 2016-04-04 14:31 UTC
Gettings records from dynamodb RANDOMLY throws exceptions. 

Tested OS: Linux
Runtime: Core clr
Nuget Package: "AWSSDK.DynamoDBv2": "3.2.3-beta"

```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Failure when receiving data from the peer\n   
at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(EasyRequest completedOperation, Int32 messageResult)\n   --- End of inner exception stack trace ---\n   
at Amazon.Runtime.HttpWebRequestMessage.GetResponse()\n   
at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)\n   
at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)\n   
at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)\n   
at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)\n   
at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)\n   
at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)\n   
at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)\n   
at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)\n   
at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)\n   
at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller)\n   
at Amazon.DynamoDBv2.DocumentModel.Table.GetItemHelper(Key key, GetItemOperationConfig config, Boolean isAsync)\n   
at Amazon.DynamoDBv2.DataModel.DynamoDBContext.LoadHelper[T](Key key, DynamoDBFlatConfig flatConfig, ItemStorageConfig storageConfig, Boolean isAsync)\n   
at System.Threading.Tasks.Task`1.InnerInvoke()\n  
at System.Threading.Tasks.Task.Execute()\n--- End of stack trace from previous location where exception was thrown ---\n   
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   
at Notifications.Messaging.Recommendations.Dynamo.DynamoReader`1.<>c__DisplayClass4_0.<<GetAsync>b__0>d.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\n   
at StatsdClient.Statsd.<SendAsync>d__36`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   
at StatsdClient.Statsd.<SendAsync>d__36`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\n   
at StatsdClient.Metrics.<TimeAsync>d__11`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   
at Notifications.Messaging.Recommendations.Dynamo.DynamoReader`1.<GetAsync>d__4.MoveNext()
```

**Comment by jimfl** [comment] 2016-04-05 20:48
Thanks for reporting this.

The exception you're getting is generally indicative of intermittent network issues. Normally, the SDK would retry these transparently, but the inner exception with Linux/libcurl is a novel one, and the SDK doesn't recognize it. 

We're working on making the retry facility work in this environment.

**Comment by bilal-fazlani** [comment] 2016-04-06 09:31
Hi @jimfl 

I am running this in the aws ecs cluster, so I think it's very unlikely that there are intermittent network issues. But I am not an expert, so you might be right. 

Just to give you some statistics,
I made about 430000 calls to dynamodb and out of them about 500 had this exception. It has nothing to with data for sure, because if tried again for the same record that threw exception, it works. So my plan was to implement a retry mechanism in my application around the dynamodb call. 

If you guys can do it in the sdk, that would be great. I am going live with this.

**Comment by bilal-fazlani** [comment] 2016-04-06 18:12
I added a retry pattern. Which solved the problem for me. 
Then I realised that exception was because I was crossing my dynamodb read throughput capacity. I wish the exception had useful message.

Without a proper exception, debugging becomes nightmare. If you can, please fix the exception Thank you.

**Comment by PavelSafronov** [comment] 2016-08-03 01:03
Can you explain how you realized that this exception was caused by DynamoDB throttling?
Have you experienced this error using the latest version of the SDK?

**Comment by bilal-fazlani** [comment] 2016-08-03 04:49
@PavelSafronov 
I looked at cloudwatch. Saw that dynamodb usage was crossing the threshold.
Then I increased the threshold and this problem went away.

**Comment by sstevenkang** [comment] 2017-03-16 17:20
Since there's no actionable item on our side, we are closing this issue. Feel free to reopen it if there is anything else we can help with!

**Closed by sstevenkang** 2017-03-16 17:20 UTC
Labels: Information Requested, Question
