### ISSUE TITLE
ListObjectsV2Request and GetObjectRequest requests provide different object modified date

### ISSUE THREAD

**Issue by recepaslan** [aws/aws-sdk-net#1485] opened 2019-12-11 20:16 UTC
## Expected Behavior
List and Get object requests to provide same `LastModified`. 

## Current Behavior
List and Get object requests on same objects provide different DateTime.Kind information which causes `LastModified` to be different.
* `GetObjectRequest` LastModified have Datetime.Kind a s`Utc` whereas `ListObjectsV2Response` provides `Local`
![image](https://user-images.githubusercontent.com/43689229/70656853-d9689200-1c28-11ea-8477-b75332694c27.png)
![image](https://user-images.githubusercontent.com/43689229/70656865-dff70980-1c28-11ea-953c-8eb4fc43f620.png)

## Steps to Reproduce (for bugs)
``` csharp
 class Program
    {
        private const string bucketName = "**bucket name***";
        private const string keyName = "** file key name **";
        // Specify your bucket region (an example region is shown).
        private static readonly RegionEndpoint bucketRegion = RegionEndpoint.USWest2;
        private static IAmazonS3 client;

        static void Main(string[] args)
        {
            AmazonS3Config s3Config = new AmazonS3Config();
            AWSCredentials credentials = new BasicAWSCredentials("** access key **", "** secret access key **");
            s3Config.RegionEndpoint = RegionEndpoint.USEast1;
            client = new AmazonS3Client(credentials,s3Config);
            ReadObjectDataAsync().Wait();
            ListingObjectsAsync().Wait();
        }

        static async Task ReadObjectDataAsync()
        {
            string responseBody = "";
            try
            {
                GetObjectRequest request = new GetObjectRequest
                {
                    BucketName = bucketName,
                    Key = keyName
                };
                using (GetObjectResponse response = await client.GetObjectAsync(request))
                using (Stream responseStream = response.ResponseStream)
                using (StreamReader reader = new StreamReader(responseStream))
                {

                    Console.WriteLine($"GetObjectRequest LastModified: {response.LastModified}");

                    responseBody = reader.ReadToEnd(); // Now you process the response body.
                }
            }
            catch (AmazonS3Exception e)
            {
                Console.WriteLine("Error encountered ***. Message:'{0}' when writing an object", e.Message);
            }
            catch (Exception e)
            {
                Console.WriteLine("Unknown encountered on server. Message:'{0}' when writing an object", e.Message);
            }
        }
        static async Task ListingObjectsAsync()
        {
            try
            {
                ListObjectsV2Request request = new ListObjectsV2Request
                {
                    BucketName = bucketName,
                    MaxKeys = 10,
                    Prefix= keyName

                };
                ListObjectsV2Response response;
                do
                {
                    response = await client.ListObjectsV2Async(request);

                    // Process the response.
                    foreach (S3Object entry in response.S3Objects)
                    {
                        Console.WriteLine($"ListObjectsV2Request LastModified: {entry.LastModified}");
                    }
                
                    request.ContinuationToken = response.NextContinuationToken;
                } while (response.IsTruncated);
            }
            catch (AmazonS3Exception amazonS3Exception)
            {
                Console.WriteLine("S3 error occurred. Exception: " + amazonS3Exception.ToString());
                Console.ReadKey();
            }
            catch (Exception e)
            {
                Console.WriteLine("Exception: " + e.ToString());
                Console.ReadKey();
            }
        }
    }
```

Possible duplication of #1224 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment] 2019-12-12 19:29
Thanks for the feedback.  I'm going to close this out as a duplicate of #1224.

**Closed by klaytaybai** 2019-12-12 19:29 UTC
Labels: bug, duplicate
