### ISSUE TITLE
Inserting object into DynamoDB DateTime Properties are not consistent between UTC and local

### ISSUE THREAD

**Issue by sukanzubair** [aws/aws-sdk-net#1770] opened 2021-01-09 07:02 UTC
## Description
When inserting an object with mutiple DateTime properties into DynamoDb Table, some of these properties are converted to UTC and some are saved as Local even though all the DateTime properties are of SpecifyKind= Unspecified

### Environment

AWSSDK.Core 3.5.1.58
AWSSDK.DynamDBv2 3.5.4.17

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment] 2021-01-11 17:26
Duplicate of https://github.com/aws/aws-sdk-net/issues/1450. Please try using workaround mentioned in https://github.com/aws/aws-sdk-net/issues/1450#issuecomment-613448020 until the issue #1450 is fixed.

**Closed by ashishdhingra** 2021-01-11 17:26 UTC
Labels: bug, duplicate, module/dynamodb
