### ISSUE TITLE
Empty Serverless Application fresh template will not publish

### ISSUE THREAD

**Issue by 13neno** [aws/aws-sdk-net#726] opened 2017-08-14 03:58 UTC
I am trying to publish an out of the box AWS Serverless Application project, choosing the Empty Blueprint.

## Expected Behavior
I expect the Serverless Application to be uploaded successfully - the Lambda Function to be created and visible in the console as well as being able to complete a simple test to hit the function.

## Current Behavior
1. Right click the project
2. Click Publish to AWS Lambda...
3. Chose my account profile to use => region: (Asia Pacific (Sydney))
4. Configuration: Release => Framework: netcoreapp1.0
5. Stack Name: "RandomName" => S3 Bucket - "MyS3BucketWhichIveCreated"
6. Click Publish
7. While publishing I receive this error: "Error creating CloudFormation change set: Parameter values specified for a template which does not require them."

## Context
I am just trying to test this relatively new technology to see if it is a viable option for our organization.

## Your Environment
* Installed AWS Toolkit for Visual Studio 2017 via Visual Studio's Extensions and Updates window (VSIX)
* Windows 7 (virtual machine)
* Visual Studio 2017 v15.2
* .NetCoreApp 1.0
* .Net Core SDK 1.0.4 (x64)

Everything is from the template and I have not touched a thing in the solution. Any help is much appreciated!

**Comment by wizofaus** [comment] 2017-10-11 02:29
Just got the same. Not sure what I can change...

**Comment by normj** [comment] 2017-10-11 18:17
In the aws-lambda-tools-defaults.json file in the project is there anything set for the template-parameters property? If so clear it out. I'm wondering if we have a validation issue with parameters being set in that file and we aren't making sure the parameter are valid for the current template.

**Comment by n8allan** [comment] 2018-01-25 18:15
Just got this error.  This is the appropriate excerpt from aws-lambda-tools-defaults.json:
`"template-parameters": ""`

**Comment by normj** [comment] 2018-01-25 18:47
@n8allan What version of the toolkit are you running? Is this your first deployment of the application or are  you redeploying to an existing stack?

**Comment by VascoArreaza** [comment] 2018-01-25 18:56
I have the same problem and I am deploy for the first time

**Comment by n8allan** [comment] 2018-01-25 19:13
AWS Toolkit for Visual Studio 2017 - 1.14.0.1

The error must be wrong; I was able to get it to work by typing in a new stack name rather than selecting an existing one as suggested by wizofaus in this thread,  Once the stack is created by the first deployment, subsequent deployments work correctly.

**Comment by normj** [comment] 2018-01-26 18:40
@n8allan Interesting, did the existing stack have any parameters?

**Comment by n8allan** [comment] 2018-01-26 18:45
No, it didn't.  This was the out of the box project template resulting from the Visual Studio new project wizard.  I suspect you can reproduce this by:
1. creating a new project using the AWS Serverless Application template from the AWS VS SDK.
2. attempt to deploy said application, selecting an already existing stack.

It may be that deploying into an existing stack isn't supported, but at the very least the error should be improved so as not to cause frustration and/or confusion.  Thanks!

**Comment by normj** [comment] 2018-01-26 19:03
Deploying into an existing stack is definitely supported and is a common scenario which is why I'm puzzled you are getting this error. So to be clear your repro steps are

1) Create a severless project, (Empty Serverless Application blueprint?)
2) Make no changes to the serverless.template and deploy the application
3) After deploying the application attempt to redeploy. And again you didn't make any changes to serverless.template?

Then you get the error message "Error creating CloudFormation change set: Parameter values specified for a template which does not require them."?

**Comment by n8allan** [comment] 2018-01-26 20:14
1. yes, Empty... blueprint
2. correct, with a new S3 bucket, but choosing an existing stack.  This is where the error occurs:
"Found existing stack: True
Error creating CloudFormation change set: Parameter values specified for a template which does not require them."
3. No, if you create a new stack and deploy successfully, redeploy works fine.

**Comment by n8allan** [comment] 2018-01-26 20:18
Here's an additional tidbit: if the stack I choose is a stack I've used in deploying another serverless app, it doesn't error.  The stack that causes trouble in my case is an elastic beanstock stack.  Again, if I choose a stack that was already used previously to deploy a serverless application, it works without error.

**Comment by normj** [comment] 2018-04-29 04:30
Closing as this should be fixed with the tooling that was released as part of .NET Core 2.0. Also converting a CloudFormation stack from a beanstalk deployment to something completely different seems like a strange use case because it would tear down all of the beanstalk resources. Why wouldn't you just deploy to a new stack.

**Closed by normj** 2018-04-29 04:30 UTC
Labels: Visual Studio Toolkit
