### ISSUE TITLE
Cognito: UserNotConfirmedException not raised for non-confirmed user at login

### ISSUE THREAD

**Issue by aventurella** [aws/aws-sdk-net#866] opened 2018-02-14 04:14 UTC
A user can sign up, but abandon the Confirmation Step. Upon returning and attempting to login, 
`Amazon.CognitoIdentityProvider.Model.UserNotConfirmedException` is **NOT** thrown instead `Amazon.CognitoIdentityProvider.Model.UserNotFoundException` is thrown. There is no way for the user to get back to a confirmation UI. They would need to create a new account.

**Comment by sstevenkang** [comment] 2018-02-14 17:37
What is this UI you are talking about?  Could you provide a sample code that repros this?

**Comment by aventurella** [comment] 2018-02-14 18:26
There is no UI.

Here's the workflow:

The implied Cognito Workflow (mobile app) is:
- User signs up for a new account that requires verification.
- After clicking submit, show the user a new view with a verification code input field.
- Cognito will send out the verification email / sms with the code
- User checks their email/phone gets the code, enters it, everything is great.


Here's where the issue is (using the user's email as the sign in alias):

- User signs up for a new account that requires verification.
- After clicking submit, show the user a new view with a verification code input field.
- User abandons the verification for any reason
    - App crashes
    - Battery dies
    - User gets distracted and closes the app or for whatever reason they force quit the app
    - etc...

User comes back to the app, and goes to sign in. The error that Cognito reports is `UserNotFoundException`. It does not say `UserNotConfirmedException`. The latter would allow the confirmation view to be presented again. The former we don't know the state of the user's account or if it's truly not found.

The user knows they made an account, so now the user is confused. 

This becomes even more interesting if a pre-signup trigger exists. So when an account is unverified, the email address is not uniquely constrained until it's verified. So I imagine the first response here would be: 

> well just have the user make a new account, it's a bad user experience, but it's the way to work around it. 

While this is true and would work, if a pre-signup trigger is in place that checks email to be sure that only one email is used then the user won't be able to make a new account as the pre-signup trigger enforces that unique email constraint on sign up instead of on verification.

Anyway, it seems that ALL the possibilities become workable if Cognito just raised `UserNotConfirmedException` instead of `UserNotFoundException`. Then the developer decides what works for them, however to handle it.

**Comment by sstevenkang** [comment] 2018-02-14 21:27
This looks like Cognito service is returning an incorrect error message.  I'll try to repro and follow up with the service team.

**Comment by aventurella** [comment] 2018-03-04 13:23
Any news on reproducing this?

**Comment by skodamaAcro** [comment] 2018-07-03 17:37
Hello, I'm having the exact same problem with my app. 
I started to receive complaints from the users that they can't confirm their account if they get out of the app before confirming the account and when they later try to confirm it.

Any progress regarding this problem?

**Comment by annaulkowska** [comment] 2019-08-08 09:55
I’m facing the exact same problem in the Android app as well. Any news about this issue?

**Comment by philohelp** [comment] 2019-08-12 20:54
I have the same problem here. Looking forward for updates.

**Comment by SebSchwartz** [comment] 2019-11-18 13:09
Same probleme here :(

**Comment by prasadkesarkar** [comment] 2019-12-30 07:11
Same problem facing. Any clue ? Please help.

**Comment by pcashdown-tu** [comment] 2020-02-08 19:53
Any update on this?

**Comment by j-petty** [comment] 2020-04-04 07:30
Same problem is still occurring. Results in having to track confirmation status outside of Cognito and use the Post-Confirmation trigger to maintain the status. This is far from ideal, some guidance on this would be appreciated.

**Comment by ashishdhingra** [comment] 2020-11-05 00:56
Duplicate of https://github.com/aws/aws-aspnet-cognito-identity-provider/issues/179

**Closed by ashishdhingra** 2020-11-05 00:56 UTC
Labels: bug, duplicate, module/credentials, service-api
