### ISSUE TITLE
Dynamodb Scan function  not working as expected with nested structure

### ISSUE THREAD

**Issue by SARAVANA1501** [aws/aws-sdk-net#1805] opened 2021-03-01 13:54 UTC
## Description
Dynamodb Scan function  not working as expected with nested structure, I am using asp.net core with dynamodb table, 

## Reproduction Steps
Below step is working, Assume that Root has property of child, child has property1.
```
var child = new Child();
            root.Property1 = 212;
            var conditions = new List<ScanCondition>()
            {
                new ScanCondition("Child", ScanOperator.Equal,
                    child)
            };
            var allDocs = DynamoDbContext.ScanAsync<Root>(conditions).GetRemainingAsync().Result;
```
But Below step not is working.
```
            var conditions = new List<ScanCondition>()
            {
                new ScanCondition("Child.Property1", ScanOperator.Equal,
                    212)
            };
            var allDocs = DynamoDbContext.ScanAsync<Root>(conditions).GetRemainingAsync().Result;
```

### Environment

* SDK Version: 3.5.1
* Package Version: 
* OS Info: OSX Catalina
* Build Environment: Rider
* Targeted .NET Platform:  Dotnet core 3.1

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment] 2021-03-01 17:23
Hi @SARAVANA1501,

Good morning.

Could you please share the complete sample code snippet along with Model classes to reproduce the issue? It would really help to troubleshoot the issue further.

Thanks,
Ashish

**Comment by SARAVANA1501** [comment] 2021-03-16 02:35
Will update the project ASAP

**Comment by ashishdhingra** [comment] 2021-03-16 02:43
> Will update the project ASAP

Hi @SARAVANA1501,

We don't need a source code now. Please check the findings in https://github.com/aws/aws-sdk-net/issues/1805#issuecomment-788125181. The behavior is as per design.

Here is the high level summary:
- The scan on nested property doesn't appear to work in AWS Console. 
- DynamoDB allows to create property names with . (dot) character in the name (e.g. Property.Name).
- Creating an item with property `Property.Name` with value `test` (for example) and executing scan using AWS Console works (this is not a scan for nested property, but for top level property).
- The above points provide reasoning on why `ScanCondition("Child.Property1", ScanOperator.Equal, 212)` does not work. It is looking for property named `Child.Property1` in DynamoDB table (which is allowed as per above DynamoDB behavior)

The .NET SDK behavior is as per the AWS Console. Closing this issue as design.

Thanks,
Ashish

**Closed by ashishdhingra** 2021-03-16 02:43 UTC
Labels: closing-soon, guidance, module/dynamodb, response-requested

**Comment by dtabuenc** [comment] 2022-09-16 00:07
So there's no way to support this in any of the high-level dotnet api? Just because you can or cannot do something in the console is no reason to not support it in the SDKs since it is supported in the actual low-level SDK. There should be a way to specify nested properties for scans and/or filters in the higher-level dot net SDKs
