### ISSUE TITLE
Unity reference in readme

### ISSUE THREAD

**Issue by PlaytonicLtd** [aws/aws-sdk-net#1752] opened 2020-11-27 16:32 UTC
Unity support was removed in commit ba88ecb97889c00dc0e3bfcb01f801cbb17d8946
The readme is still referenced from the main readme: https://github.com/aws/aws-sdk-net#unity-support

It would be useful to have a few lines what it did, why it was removed and what needs to be done now (if anything).

**Comment by ashishdhingra** [comment] 2020-11-27 17:08
Duplicate of https://github.com/aws/aws-sdk-net/issues/1634 which is in progress.

**Closed by ashishdhingra** 2020-11-27 17:08 UTC
Labels: doc-readme, documentation, duplicate, module/unity
