### ISSUE TITLE
ArchiveTransferManager.Upload does not consider archiveDescription parameter 

### ISSUE THREAD

**Issue by giammin** [aws/aws-sdk-net#2462] opened 2022-10-26 12:50 UTC
### Describe the bug

When uploading an archive parameter archiveDescription is not stored

### Expected Behavior

when reatriving inventory, archive list should have the ArchiveDescription specified when uploading

### Current Behavior

Archive Description is an empty string

### Reproduction Steps

i'm currently using the powershell module which internally use ArchiveTransferManager

I verified looking at the code that the Write-GLCArchive command send the description as parameter

 Write-GLCArchive -VaultName testvault -Region eu-central-1 -FilePath "C:\temp\testfile.zip" -Description "test description"

### AWS .NET SDK and/or Package version used

AWS Tools for PowerShell
Version 4.1.184
Copyright 2012-2022 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Amazon Web Services SDK for .NET
Core Runtime Version 3.7.13.18
Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

### Targeted .NET Platform

netstandard2.0

### Operating System and version

windows 11

**Comment by ashishdhingra** [comment] 2022-10-26 16:52
Related PowerShell issue https://github.com/aws/aws-tools-for-powershell/issues/142.

**Comment by ashishdhingra** [comment] 2022-10-27 21:10
Hi @giammin,

Good afternoon.

Unfortunately, the issue is not reproducible using the `ArchiveTransferManager` from AWS .NET SDK directly.
- Created vault and uploaded an archive using the below code (that targets .NET 6):
```C#
using Amazon;
using Amazon.Glacier;
using Amazon.Glacier.Model;
using Amazon.Glacier.Transfer;
using Amazon.Runtime;

ArchiveTransferManager manager;
string archiveId;

//Set the vault name you want to use here.
string vaultName = "testvault";

// Set the file path for the file you want to upload here.
string filePath = @"<<Absolute path to file to be archived>>";

using (manager = new ArchiveTransferManager(RegionEndpoint.USEast2))
{
    try
    {
        // Creates a new Vault
        Console.WriteLine("Create Vault");
        await manager.CreateVaultAsync(vaultName);

        // Uploads the specified file to Glacier.
        Console.WriteLine("Upload a Archive");
        var uploadResult = await manager.UploadAsync(vaultName, "Test Archive Description", filePath);
        archiveId = uploadResult.ArchiveId;
        Console.WriteLine("Upload successful. Archive Id : {0}  Checksum : {1}",
            uploadResult.ArchiveId, uploadResult.Checksum);
    }
    catch (AmazonGlacierException e)
    {
        Console.WriteLine(e.Message);
    }
    catch (AmazonServiceException e)
    {
        Console.WriteLine(e.Message);
    }
}
```
- Using AWS CLI, 
  - Executed `aws glacier initiate-job --vault-name testvault --account-id - --job-parameters '{"Type": "inventory-retrieval"}' `. This returns the output in below format:
```
{
    "location": "/<<acount-id>>/vaults/testvault/jobs/<<job-id>>",
    "jobId": "<<job-id>>"
}
```
  - Using the Job ID returned in above command, kept executing the command `aws glacier describe-job --vault-name testvault --account-id - --job-id <<job-id>>` at regular intervals until it is completed.

  - After the job is completed per above command, executed the command `aws glacier get-job-output --vault-name testvault --account-id - --job-id <<job-id>> testvault_inventory_output.json`
  - Examined the content of __testvault_inventory_output.json__, it had the following content:
```
{"VaultARN":"arn:aws:glacier:us-east-2:<<account-id>>:vaults/testvault","InventoryDate":"2022-10-27T11:56:07Z","ArchiveList":[{"ArchiveId":"<<archive-id>>","ArchiveDescription":"Test Archive Description","CreationDate":"2022-10-26T22:44:28Z","Size":193795881,"SHA256TreeHash":"<<sha>>"}]}
```

So next step would be to investigate the `Write-GLCArchive` issue. This should ideally be investigated as part of https://github.com/aws/aws-tools-for-powershell/issues/142.

Thanks,
Ashish

**Comment by ashishdhingra** [comment] 2022-10-28 00:28
@giammin Closing this issue. I have logged some findings in https://github.com/aws/aws-tools-for-powershell/issues/142#issuecomment-1294262704. It needs investigation.

**Closed by ashishdhingra** 2022-10-28 00:28 UTC
Labels: bug, response-requested, module/sdk-generated
