### ISSUE TITLE
RequesterCharged property of CopyObjectResponse is null 

### ISSUE THREAD

**Issue by AndrewZu1337** [aws/aws-sdk-net#1526] opened 2020-02-12 14:15 UTC
## Expected Behavior

`x-amz-request-charged:requester` in response

## Current Behavior

I enabled the requester pays property for my bucket. 
**(cross-account access to objects enabled for this bucket!)** 
 Then I was trying to copy file from my requester pays bucket to another bucket. But `RequesterCharged` property  in `CopyObjectResponse` was always `null`. And I also used fiddler to find `x-amz-request-charged`, I couldn't find it. 
Could you please tell me how I can check the requester pays is worked for my bucket?

## Your Environment

* AWSSDK.Core version used: 3.3.104.8
* Service assembly and version used: AWSSDK.S3 v 3.3.109.1

## .NET Core Info

* .NET Core version used for development: 2.1

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment] 2020-02-12 22:24
x-amz-request-charged is only added to the response if the requester was actually charged.  When you were checking with the SDK and Fiddler, were you using a different account or your own?  If you are the bucket owner of the requester pays bucket and you made the copy object request, you shouldn't see the request charged header.

Since Fiddler showed that the service also wasn't returning the header, I'm going to close this soon unless you can verify that the issue is in the SDK.  If you need more help with the service, please try the [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=24).

**Comment by andrei-zubkovich** [comment] 2020-02-13 06:58
@klaytaybai , thanks for quick response. 
I have 2 aws accounts . 
First account has bucket with enabled Requester pays, enabled `Cross account functionality` and this bucket has file that I was trying to copy to second bucket. The second bucket is in second account.  
I made Copy request to copy file from first bucket(`on` Requester pays , First account) to second bucket(Second account). 
I excepted to get `x-amz-request-charged:requester` in response, because I set always `RequesterPayer` property in my requests.

**Comment by andrei-zubkovich** [comment] 2020-02-19 15:11
@klaytaybai do you understand my case that I was trying to do?

**Comment by klaytaybai** [comment] 2020-02-20 20:57
Hi @andrei-zubkovich, thanks for reporting this.  You're right.  The CopyObject operation isn't returning the RequesterCharged property (GetObject is working).  I'll work internally to get this resolved.

**Comment by andrei-zubkovich** [comment] 2020-02-21 12:20
Hi @klaytaybai . Thanks for response I'll wait fix. Could you please give me ETA?
Could you please tell me another ways to check `RequesterPays` functionality is working correctly?

**Comment by andrei-zubkovich** [comment] 2020-03-13 10:49
@klaytaybai , are there news?

**Comment by ashishdhingra** [comment] 2021-06-29 22:05
Reproducible using following steps:
- Setup cross account S3 copy using the instructions at [How can I copy S3 objects from another AWS account?]
(https://aws.amazon.com/premiumsupport/knowledge-center/copy-s3-objects-account/)
- Make sure to enable `Requester pays` setting in the source bucket.
- Use the following code to Copy Object:
```C#
using Amazon;
using Amazon.S3;
using Amazon.S3.Model;
using System;
using System.Threading.Tasks;

namespace S3CopyObjectRequesterPaysTest_Issue1526
{
    class Program
    {
        private const string sourceBucket = "<<source-bucket-name>>";
        private const string destinationBucket = "<<destination-bucket-name>>";
        private const string objectKey = "<<source-key>>";
        private const string destObjectKey = "<<destination-key>>";
        // Specify your bucket region (an example region is shown).
        private static readonly RegionEndpoint bucketRegion = RegionEndpoint.USEast2;
        private static IAmazonS3 s3Client;

        public static void Main()
        {
            s3Client = new AmazonS3Client(bucketRegion);
            Console.WriteLine("Copying an object");
            CopyingObjectAsync().Wait();
        }

        private static async Task CopyingObjectAsync()
        {
            try
            {
                CopyObjectRequest request = new CopyObjectRequest
                {
                    SourceBucket = sourceBucket,
                    SourceKey = objectKey,
                    DestinationBucket = destinationBucket,
                    DestinationKey = destObjectKey,
                    CannedACL = S3CannedACL.BucketOwnerFullControl
                };
                CopyObjectResponse response = await s3Client.CopyObjectAsync(request);
            }
            catch (AmazonS3Exception e)
            {
                Console.WriteLine("Error encountered on server. Message:'{0}' when writing an object", e.Message);
            }
            catch (Exception e)
            {
                Console.WriteLine("Unknown encountered on server. Message:'{0}' when writing an object", e.Message);
            }
        }
    }
}
```

**RESULT:**
`CopyObjectResponse.RequestCharged` This is because only the following headers are returned by the S3 service:
- x-amz-id-2
- x-amz-request-id
- Date
- Server
- Content-Type
- Content-Length

<img width="363" alt="Screen Shot 2021-06-29 at 2 51 09 PM" src="https://user-images.githubusercontent.com/67916761/123872705-4ebeb500-d8ea-11eb-939e-f3bb18ae88a9.png">


Notice that there is no header with name `x-amz-request-charged` as mentioned in [CopyObject](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html#API_CopyObject_ResponseSyntax) API reference.

NOTE: .NET SDK `CopyObjectResponseUnmarshaller` has logic to process value for header `x-amz-request-charged`. If present, it is set as value of `CopyObjectResponse.RequestCharged` property.

Need to check with service team on why the `x-amz-request-charged` is not returned when the setting `Requester pays` is enabled in source bucket.

**Comment by ashishdhingra** [comment] 2021-06-29 22:14
V390312875

**Comment by ashishdhingra** [comment] 2021-06-29 23:25
Hi @AndrewZu1337,

Good evening.

Based on analysis in , per service team, `x-amz-request-charged` header is not returned if source account is used to copy objects to destination bucket. Could you please confirm if you used source account to copy object or the destination account? In case you are using the destination account, then it is an existing issue which is being fixed by service team.

Thanks,
Ashish

**Comment by AndrewZu1337** [comment] 2021-06-30 19:02
Hi @ashishdhingra. Yes, I confirm that

**Comment by ashishdhingra** [comment] 2021-06-30 19:03
> Hi @ashishdhingra. Yes, I confirm that

@AndrewZu1337 Did you use source account?

**Comment by AndrewZu1337** [comment] 2021-07-01 03:39
@ashishdhingra , I used destination account to send something to source account. And it didn't work.

**Comment by ashishdhingra** [comment] 2021-07-01 05:43
> @ashishdhingra , I used destination account to send something to source account. And it didn't work.

@AndrewZu1337 Thanks. It's a bug aa per service team and they are working on it for fix. I will keep you posted.

**Comment by AndrewZu1337** [comment] 2021-07-01 07:58
@ashishdhingra  thanks!

**Comment by ashishdhingra** [comment] 2022-01-26 23:58
@AndrewZu1337 Per service team, the source and destination bucket needs to be owned by separate accounts in order to get `x-amz-request-charged` response header. The fix was issued by by service team recently. In case the buckets are owned by the same account, this header doesn't make any sense, hence it is not returned. Please test the scenario using the mentioned guidance and confirm if it works.

**Closed** 2022-01-28 19:06 UTC
Labels: bug, response-requested, service-api, module/s3
