### ISSUE TITLE
Invoking glue job via .net core 3.1 sdk : Internal service error occurred.: InternalServiceException    at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException((short issue description)

### ISSUE THREAD

**Issue by cdpatel** [aws/aws-sdk-net#2117] opened 2022-09-24 08:34 UTC
### Describe the bug

Hi,

We have a lambda that is participating in a step function which invokes various glue jobs during individual executions of the lambda.

This has been working fine for many months in various aws accounts our enterprise has. It suddenly started giving this error today. This part of the system is scheduled to run once every day. We have experienced this error for the first time ever.

_Lambda and Glue support engineers have investigated with us. Invoking via python lambda works fine. Invoking the glue job manually via aws console UI also works. Invoking via .net core 3.1 lambda doesn't work._

AWS case ID has been created for that: 10842873831

`Internal service error occurred.: InternalServiceException
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Registry.Reporting.Lambda.Glue.Job.Invoke(GlueJobState input, ILambdaContext context) in /vsts/agent/_work/7/s/source/stepfunction/lambda/Registry.Reporting.AWS/Registry.Reporting.Lambda.Glue/Job.cs:line 39
   at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)`

Thanks,
Chirag

### Expected Behavior

Invoking glue jobs from .net core 3.1 lambda should work just like it has worked every day in the past. Similarly, the invocation should succeed with .net core 3.1 just like how it succeeds with python as well.

### Current Behavior

Our code snippet which invokes this and has been working in the past.
I have produced a simpler version snippet here.
`
Lazy<IAmazonGlue> GlueClient = new Lazy<IAmazonGlue>(() => new AmazonGlueClient());
var response = await GlueClient.Value.StartJobRunAsync(new StartJobRunRequest
            {
                JobName = input.JobName,
                Arguments = arguments
            });`

Exception:
Internal service error occurred.: InternalServiceException
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Registry.Reporting.Lambda.Glue.Job.Invoke(GlueJobState input, ILambdaContext context) in /vsts/agent/_work/7/s/source/stepfunction/lambda/Registry.Reporting.AWS/Registry.Reporting.Lambda.Glue/Job.cs:line 39
   at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)

### Reproduction Steps

Develop a .net core 3.1 lambda with code similar to the above snippet to start job run.
Invoke a glue job.
Notice the exception coming from the glue job invocation which is actually done by the SDK.

### AWS .NET SDK and/or Package version used

AWSSDK.Glue Version=3.3.15.11
Amazon.Lambda.Core Version=1.0.0
Amazon.Lambda.Tools Version=2.2.0
Amazon.Lambda.Serialization.Json Version=1.4.0

### Targeted .NET Platform

.NET Core 3.1

### Operating System and version

AWS lambda provided managed environment

**Comment by 96malhar** [comment] 2022-09-24 19:35
As stated in the issue, the customer's Glue jobs were invoked successfully prior to this. The latest change to the Glue service were released on 9/22.  

However, this change did not include any breaking changes to the Glue API - https://github.com/aws/aws-sdk-net/commit/34489f9b16eeaebd3900bb29f868292a37de620d#diff-7db7940400d15d21dee2f17e2738e08e14a9bc0d3e5822a1432ede5a79324443

There have not been any material changes to [AWSSDK.Core](https://www.nuget.org/packages/AWSSDK.Core) as well in the past few days - https://github.com/aws/aws-sdk-net/commits/master/sdk/src/Core

Per the internal communication with the Lambda team, there have been no updates to the .NET Core 3.1 Lambda runtime.

**Comment by 96malhar** [comment] 2022-09-26 08:36
Upon internal investigation, it was discovered that this issue was caused due to a regression on AWS Glue service. The change was reverted and the customer has been unblocked.

Resolving this issue as there an no pending action items on .NET SDK team.

**Closed by 96malhar** 2022-09-26 08:36 UTC
Labels: bug, needs-triage
