### ISSUE TITLE
List of ScanConditions with AND operator not working for ScanAsync()

### ISSUE THREAD

**Issue by renansolvimm** [aws/aws-sdk-net#1872] opened 2021-06-15 15:41 UTC
## Description
I would like to report the issue I have when I try to use a list of ScanConditions. They are simply not working in conjunction, only the last scanCondition added to the list is applied. I also tried to use the DynamoDBOperationConfig to force an AND, but the result was the same.

## Reproduction Steps

```
ScanCondition scanCondition1 = new ScanCondition("SK", ScanOperator.BeginsWith, "term1");
ScanCondition scanCondition2 = new ScanCondition("SK", ScanOperator.Contains, "term2");
List<BackOffice> servicePermissions = await  _context.ScanAsync<Table>(new List<ScanCondition> { scanCondition1, scanCondition2 }).GetRemainingAsync();
```

### Environment
* AWSSDK.Core Version: 3.7.0.32
* AWSSDK.DynamoDBv2 Version: 3.7.0.31

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment] 2021-06-17 18:12
Hi @renansolvimm,

Good morning.

Somehow I'm unable to reproduce the issue using `AWSSDK.DynamoDBv2 version 3.7.0.32`. I tweaked the code example at https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBContext.QueryScan.html to the code below:
```C#
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.DataModel;
using Amazon.DynamoDBv2.DocumentModel;
using Amazon.Runtime;
using System;
using System.Collections.Generic;

namespace DynamoDbScan_Issue1872
{
    class Program
    {
        private static AmazonDynamoDBClient client = new AmazonDynamoDBClient();

        static void Main(string[] args)
        {
            try
            {
                DynamoDBContext context = new DynamoDBContext(client);

                // Scan table.
                FindProductsPricedLessThanValue(context, 50);
                Console.WriteLine("To continue, press Enter");
                Console.ReadLine();
            }
            catch (AmazonDynamoDBException e) { Console.WriteLine(e.Message); }
            catch (AmazonServiceException e) { Console.WriteLine(e.Message); }
            catch (Exception e) { Console.WriteLine(e.Message); }
        }

        private static async void FindProductsPricedLessThanValue(DynamoDBContext context, int price)
        {
            var itemsWithWrongPrice =  await context.ScanAsync<Book>(new List<ScanCondition>(){
                                            new ScanCondition("Price", ScanOperator.LessThan, price),
                                            new ScanCondition("ProductCategory", ScanOperator.Equal, "Book")}
                                        ).GetRemainingAsync();
            Console.WriteLine("\nFindProductsPricedLessThanValue: Printing result.....");
            foreach (Book r in itemsWithWrongPrice)
                Console.WriteLine("{0}\t{1}\t{2}\t{3}", r.Id, r.Title, r.Price, r.ISBN);
        }
    }

    [DynamoDBTable("ProductCatalog")]
    public class Book
    {
        [DynamoDBHashKey] //Partition key
        public int Id
        {
            get; set;
        }
        public string Title
        {
            get; set;
        }
        public string ISBN
        {
            get; set;
        }
        public int Price
        {
            get; set;
        }
        public string PageCount
        {
            get; set;
        }
        public string ProductCategory
        {
            get; set;
        }
        public bool InPublication
        {
            get; set;
        }

    }
}
``` 
and inserted the below data to the DynamoDb table `ProductCatalog`:
<img width="1130" alt="Screen Shot 2021-06-17 at 11 07 38 AM" src="https://user-images.githubusercontent.com/67916761/122450771-4070b080-cf5c-11eb-9124-9963cda70883.png">

Executing the above program gave the following result:
```
FindProductsPricedLessThanValue: Printing result.....
2       TestTitle_2     35      TestISBN_2
1       TestTitle_1     40      TestISBN_1
```

Clearly, in the above result, it returned the items satisfying both the Scan conditions.

Please re-validate at your end.

Thanks,
Ashish

**Comment by ashishdhingra** [comment] 2021-06-18 21:18
P48804299

**Comment by renansolvimm** [comment] 2021-06-22 08:43
Thank you for your answer @ashishdhingra!

In my application I needed exactly the "contains" kind of filter. I will keep following the thread.

Regards,
Renan

**Comment by ashishdhingra** [comment] 2021-08-05 18:51
Hi @renansolvimm,

Good afternoon.

I got a response from service team that filter expression supports `contains` operator, please refer https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ExpressionAttributeValues.html. As mentioned earlier, per https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Scan.html, the ScanFilter is a legacy parameter. Recommended technique is to use Filter Expression, example at https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LowLevelDotNetScanning.html.

I tried the following code, it works:
```C#
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.DataModel;
using Amazon.DynamoDBv2.DocumentModel;
using Amazon.DynamoDBv2.Model;
using Amazon.Runtime;
using System;
using System.Collections.Generic;

namespace DynamoDbScan_Issue1872
{
    class Program
    {
        private static AmazonDynamoDBClient client = new AmazonDynamoDBClient();

        static void Main(string[] args)
        {
            try
            {
                DynamoDBContext context = new DynamoDBContext(client);

                FindScan(client);

                Console.WriteLine("To continue, press Enter");
                Console.ReadLine();
            }
            catch (AmazonDynamoDBException e) { Console.WriteLine(e.Message); }
            catch (AmazonServiceException e) { Console.WriteLine(e.Message); }
            catch (Exception e) { Console.WriteLine(e.Message); }
        }

        private static async void FindScan(AmazonDynamoDBClient client)
        {
            Dictionary<string, AttributeValue> lastKeyEvaluated = null;
            do
            {
                var request = new ScanRequest
                {
                    TableName = "ProductCatalog",
                    Limit = 2,
                    ExclusiveStartKey = lastKeyEvaluated,
                    ExpressionAttributeValues = new Dictionary<string, AttributeValue> {
                        { ":startsval", new AttributeValue { S = "Bo" } },
                        { ":containsval", new AttributeValue { S = "o" } }
                    },
                    FilterExpression = "begins_with(ProductCategory, :startsval) and contains(ProductCategory, :containsval)",

                    ProjectionExpression = "Id, Title, Price, ProductCategory"
                };

                var response = await client.ScanAsync(request);

                foreach (Dictionary<string, AttributeValue> item in response.Items)
                {
                    Console.WriteLine("\nScanThreadTableUsePaging - printing.....");
                    PrintItem(item);
                }
                lastKeyEvaluated = response.LastEvaluatedKey;
            } while (lastKeyEvaluated != null && lastKeyEvaluated.Count != 0);

            Console.WriteLine("To continue, press Enter");
            Console.ReadLine();
        }

        private static void PrintItem(Dictionary<string, AttributeValue> attributeList)
        {
            foreach (KeyValuePair<string, AttributeValue> kvp in attributeList)
            {
                string attributeName = kvp.Key;
                AttributeValue value = kvp.Value;

                Console.WriteLine(
                    attributeName + " " +
                    (value.S == null ? "" : "S=[" + value.S + "]") +
                    (value.N == null ? "" : "N=[" + value.N + "]") +
                    (value.SS == null ? "" : "SS=[" + string.Join(",", value.SS.ToArray()) + "]") +
                    (value.NS == null ? "" : "NS=[" + string.Join(",", value.NS.ToArray()) + "]")
                    );
            }
            Console.WriteLine("************************************************");
        }
    }

    [DynamoDBTable("ProductCatalog")]
    public class Book
    {
        [DynamoDBHashKey] //Partition key
        public int Id
        {
            get; set;
        }
        public string Title
        {
            get; set;
        }
        public string ISBN
        {
            get; set;
        }
        public int Price
        {
            get; set;
        }
        public string PageCount
        {
            get; set;
        }
        public string ProductCategory
        {
            get; set;
        }
        public bool InPublication
        {
            get; set;
        }

    }
}
```

You may try creating items using the following item JSON for testing:
```JSON
{
  "Id": {
    "N": "2"
  },
  "InPublication": {
    "BOOL": true
  },
  "ISBN": {
    "S": "TestISBN_2"
  },
  "PageCount": {
    "S": "700"
  },
  "Price": {
    "N": "35"
  },
  "ProductCategory": {
    "S": "Book"
  },
  "Title": {
    "S": "TestTitle_2"
  }
}

{
  "Id": {
    "N": "4"
  },
  "InPublication": {
    "BOOL": true
  },
  "ISBN": {
    "S": "TestISBN_4"
  },
  "PageCount": {
    "S": "700"
  },
  "Price": {
    "N": "50"
  },
  "ProductCategory": {
    "S": "Book"
  },
  "Title": {
    "S": "TestTitle_4"
  }
}

{
  "Id": {
    "N": "1"
  },
  "InPublication": {
    "BOOL": true
  },
  "ISBN": {
    "S": "TestISBN_1"
  },
  "PageCount": {
    "S": "700"
  },
  "Price": {
    "N": "40"
  },
  "ProductCategory": {
    "S": "Book"
  },
  "Title": {
    "S": "TestTitle_1"
  }
}


{
  "Id": {
    "N": "3"
  },
  "InPublication": {
    "BOOL": true
  },
  "ISBN": {
    "S": "TestISBN_3"
  },
  "PageCount": {
    "S": "700"
  },
  "Price": {
    "N": "35"
  },
  "ProductCategory": {
    "S": "Technology"
  },
  "Title": {
    "S": "TestTitle_3"
  }
}
```

Please test at your end and confirm if we could close this issue.

Thanks,
Ashish

**Closed** 2021-08-12 16:51 UTC
Labels: bug, response-requested, service-api, module/dynamodb
