### ISSUE TITLE
SDK Calls Fail on Log4Net Dependency With XUnit and .Net Core

### ISSUE THREAD

**Issue by odyth** [aws/aws-sdk-net#620] opened 2017-04-18 18:57 UTC
What is happening is the `FallbackCredntialsFactory` is trying to load up the credentials from Environment variables.  When the `EnvironmentVariablesAWSCredentials` class executes it's constructor it tries to get a Logger which then throws the exception posted below.

Easiest way to reproduce this issue is make a new .netcore lambda function with a xunit test.  You can use the Amazon provided templates for visual studio 2017.  Then try and execute this code `var sns = new AmazonSimpleNotificationServiceClient()`  you will get an exception

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Method not found: 'Boolean System.Reflection.Assembly.op_Equality(System.Reflection.Assembly, System.Reflection.Assembly)'.
   at log4net.Core.LoggerManager.GetLogger(Assembly repositoryAssembly, Type type)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Amazon.Runtime.Internal.Util.InternalLog4netLogger..ctor(Type declaringType) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\Logger.Log4net.cs:line 147
   at Amazon.Runtime.Internal.Util.Logger..ctor(Type type) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\Logger.cs:line 46
   at Amazon.Runtime.Internal.Util.Logger.GetLogger(Type type) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\Logger.cs:line 111
   at Amazon.Runtime.EnvironmentVariablesAWSCredentials..ctor() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\_bcl+coreclr\EnvironmentVariablesAWSCredentials.cs:line 54
   at Amazon.Runtime.FallbackCredentialsFactory.<>c.<Reset>b__8_1() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\FallbackCredentialsFactory.cs:line 53
   at Amazon.Runtime.FallbackCredentialsFactory.GetCredentials(Boolean fallbackToAnonymous) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\FallbackCredentialsFactory.cs:line 113
```

**Comment by PavelSafronov** [comment] 2017-04-19 18:30
I've tried reproducing this using the template you mentioned but haven't encountered this error yet. Can you provide us with the smallest repro project created from the templates?

**Comment by rlryan** [comment] 2017-04-20 17:26
Having this exact issue... same exception, same environment (VS 2017 .NetCoreApp 1.1 project). Only difference is that this exception is thrown when creating an AmazonDynamoDBClient object. Did not use an AWS template, just create a new .NET Core Class Library, nuget/ref AWSSDK.DynamoDBv2 (3.3.4.6), and the following will throw:

AmazonDynamoDBClient client = new AmazonDynamoDBClient(Amazon.RegionEndpoint.USEast1);

**Comment by PavelSafronov** [comment] 2017-04-20 17:53
The error is coming from log4net, I wonder if you are using a version that's too different from what the SDK expects. What version of log4net are you using? Can you share your project so we can try to reproduce this?

**Comment by odyth** [comment] 2017-04-20 18:23
I'm not using log4net at all, only AWS sdk is using that.  To reproduce this error just make a brand new lambda function project with xunit then drop in this line of code in your lambda function `var sns = new AmazonSimpleNotificationServiceClient()` and add the sns nuget package.  i dont have any other dependencies other than what comes by default in the .netcore lambda template and aws sns.

**Comment by rlryan** [comment] 2017-04-20 20:15
Here is my .csproj:

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.3.4.6" />
  </ItemGroup>

</Project>

And below is the exception... yes, log4net is involved, but it appears to originate from the Amazon.Runtime:


{System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'log4net.Core.LoggerManager' threw an exception. ---> System.MethodAccessException: Attempt by method 'log4net.Core.LoggerManager.RegisterAppDomainEvents()' to access method 'System.AppDomain.add_ProcessExit(System.EventHandler)' failed.
   at log4net.Core.LoggerManager.RegisterAppDomainEvents()
   at log4net.Core.LoggerManager..cctor()
   --- End of inner exception stack trace ---
   at log4net.Core.LoggerManager.GetLogger(Assembly repositoryAssembly, Type type)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Amazon.Runtime.Internal.Util.InternalLog4netLogger..ctor(Type declaringType) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\Logger.Log4net.cs:line 147
   at Amazon.Runtime.Internal.Util.Logger..ctor(Type type) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\Logger.cs:line 46
   at Amazon.Runtime.Internal.Util.Logger.GetLogger(Type type) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\Logger.cs:line 111
   at Amazon.Runtime.AmazonServiceClient..ctor(AWSCredentials credentials, ClientConfig config) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AmazonServiceClient.cs:line 149
   at test2.Class1.<DoDDB>d__1.MoveNext() in C:\temp\test2\test2\Class1.cs:line 19}	System.Reflection.TargetInvocationException

**Comment by rlryan** [comment] 2017-04-20 20:23
Sorry, HERE is the .csproj  ...

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.3.4.6" />
  </ItemGroup>
</Project>
```

**Comment by ddrinka** [comment] 2017-04-28 22:47
Here's a complete repro:
https://github.com/ddrinka/aws-sdk-net-log4net-bug

No need for Lambda, just VS2017 with .Net Core installed.

I'm targeting netcoreapp1.0 rather than 1.1 to show this isn't a regression in .net core.

**Comment by spati2** [comment] 2017-05-08 23:03
Could you tell me what the AWSSDK.Core version number was?

**Comment by odyth** [comment] 2017-05-09 00:49
I was using the following amazon dependanceis

Amazon.Lambda.Core (1.0.0)
Amazon.Lambda.Serialization.Json (1.0.1)
AWSSDK.KeyManagementService (3.3.2.4)
AWSSDK.SimpleNotificationService (3.3.0.11)

**Comment by ddrinka** [comment] 2017-05-09 13:58
![image](https://cloud.githubusercontent.com/assets/1297262/25854420/86030a82-3495-11e7-87f3-d8761990130c.png)

**Comment by ddrinka** [comment] 2017-05-09 14:06
I've updated to the newest release.  Issue not resolved.

![image](https://cloud.githubusercontent.com/assets/1297262/25854750/c1ef0ad6-3496-11e7-971b-bbb486e37b9b.png)

**Comment by spati2** [comment] 2017-05-10 22:38
Hi @ddrinka , how have you setup you credentials info?

**Comment by ddrinka** [comment] 2017-05-10 22:59
The crash occurs before authentication.  The repro I created uses a bogus accessKeyId and secret, and crashes before any authentication error occurs.  When I run the test on net452 instead of netstandard, I get an authentication error, which is what I expect with invalid credentials.

You can of course drop real info into the test if that would be helpful.

**Comment by ydogus** [comment] 2017-05-13 15:44
You can tell AWS Client to not use logging.
I got the same error with S3. I'm not using log4net. And I don't know how to configure log4net for an AWS Client. So I decided to disable it. This way it works:
```
var config = new AmazonS3Config()
{
    DisableLogging = true
};
var amazonS3 = new AmazonS3Client(config);
```

**Comment by ydogus** [comment] 2017-05-13 16:27
Bad news,
When I set `DisableLogging` to `true`, I was able to create an instance of `AmazonS3Client`. But this time I'm stuck on calling `AmazonS3Client.GetObjectAsync`. I got the same exception. Again it's about log4net.

https://github.com/aws/aws-sdk-net/issues/649

**Comment by ddrinka** [comment] 2017-05-15 14:24
@ydogus Thanks for the details on the workaround.

I have updated my repro to include the workaround and show the error persists in GetObjectAsync.  
https://github.com/ddrinka/aws-sdk-net-log4net-bug

**Comment by ddrinka** [comment] 2017-05-15 15:06
@spati2 Can we re-title this issue something along the lines of:
SDK Calls Fail on Log4Net Dependency With XUnit and .Net Core

That'll help folks like @ydogus find this existing issue when they run into the same problem.

**Comment by rlryan** [comment] 2017-05-15 21:38
To workaround this, I installed log4net 2.0.8 to my project from nuget. Seems to get me past the issue and will work for me to continue forward with development, but this is just temporary, I don't want to have to do this for my production code.

Also, this confirms that is likely just a dependency issue on log4net.

**Comment by PavelSafronov** [comment] 2017-05-16 03:37
Looks like this is an issue with log4net being used by a Visual Studio extension, such as [PowerShell Tools for Visual Studio 2017](https://marketplace.visualstudio.com/items?itemName=AdamRDriscoll.PowerShellToolsforVisualStudio2017-18561), though I've still not been able to reproduce this issue. We're looking into this, though not sure when we'll have a fix.

**Comment by ddrinka** [comment] 2017-05-16 14:43
![image](https://cloud.githubusercontent.com/assets/1297262/26111806/c2d81f7a-3a1b-11e7-912c-afb619d760b4.png)
log4net Version 1.02.13.0
```xml
    <Identity Id="PowerShellTools.VS2017" Version="3.0.427" Language="en-US" Publisher="Adam Driscoll" />
    <DisplayName>PowerShell Tools for Visual Studio 2017</DisplayName>
```

**Comment by spati2** [comment] 2017-06-06 21:35
Hi folks, can you try running the test cases using the dotnet CLI. I suspect this is an issue with the visual studio test runner.

**Comment by spati2** [comment] 2017-06-06 22:48
This issue occurs because the log4net.dll used by Powershell Tools for Visual Studio 2017 is of version 2.0.3 which is incompatible with netcore. When running the test through Visual studio, the test adapter assembly is pulling in the reference to the log4net.dll and as the latter is incompatible, you are getting the above error. The issue is not with the AWS DotNet SDK.

**Comment by ddrinka** [comment] 2017-06-07 00:05
I can confirm that the tests run successfully from the CLI.

Here's an issue tracking the root cause @spati2 describes:
https://github.com/Microsoft/vstest/issues/632

**Comment by spati2** [comment] 2017-06-14 21:23
It looks like the vstest team is working on a fix and I see that they have recently pushed a commit that disposes the assemblyresolver. I am still awaiting an official word that the fix is in production. For the time being to work around the error either
1. Uninstall the Powershell Tools for Visual Studio 2017. @PavelSafronov has mentioned in this thread how to locate the extension with the log4net reference.
2. Install log4net 2.0.8. This version supports netcore and should unblock you for the time being.

**Comment by spati2** [comment] 2017-06-15 20:52
The vstest team has deployed a fix https://github.com/Microsoft/vstest/issues/632#issuecomment-308699902 and will be available in the next preview of visual studio. Please reopen this issue if the problem persists.

**Closed by spati2** 2017-06-15 20:52 UTC
Labels: Information Requested, Question
