### ISSUE TITLE
Configuration Manager and Dependency Injection not working as expected.

### ISSUE THREAD

**Issue by CraigChamberlain** [aws/aws-sdk-net#1717] opened 2020-09-23 10:33 UTC
## Description

Only confirmed in the invoke local version of a Lambda function.

In my StartUp file I add the following services as per [AWS Docs](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-netcore.html) + [Unofficial Docs](https://www.stevejgordon.co.uk/credential-loading-and-the-aws-sdk-for-dotnet-deep-dive).

```
     services.AddDefaultAWSOptions(root.GetAWSOptions());
     services.AddAWSService<IAmazonDynamoDB>();
```
If I inspect the configuration it pulls a profile name for example from my appsettings.json
for example:
{
    "AWSConfig": {
        "ServiceURL":  "http://192.168.1.188:8000",
        "LocalMode": false
    },
    "AWS": {
        "Profile": "Craig",
        "Region": "us-east-1"  
    }

}

However, the credentials are not loaded from the listed profile and the client object has an incomplete client.
![image](https://user-images.githubusercontent.com/48378435/94000976-c7a74400-fd8f-11ea-9fae-cabf9611f15c.png)

I have resorted to using environmental variables and loading these into a service manually.

```
               services.AddSingleton<IAmazonDynamoDB>(sp =>
                {
                    var clientConfig = root.GetAWSOptions();
                    var credentials = new BasicAWSCredentials(
                        System.Environment.GetEnvironmentVariable("AWS_ACCESS_KEY_ID"),
                        System.Environment.GetEnvironmentVariable("AWS_SECRET_ACCESS_KEY"));
                    return new AmazonDynamoDBClient(credentials, clientConfig.Region );
                });

```

## Reproduction Steps

Please Clone or Fork this sample repo.
https://github.com/CraigChamberlain/LamdaConfigInvestigation

### Environment
* SDK Version: 
* Package Version:     
    Amazon.Lambda.Core" Version="1.1.0"
    Amazon.Lambda.APIGatewayEvents" Version="2.1.0"
   Amazon.Lambda.Serialization.Json" Version="1.7.0"
    AWSSDK.DynamoDBv2" Version="3.5.0.18" 
   AWSSDK.Extensions.NETCore.Setup" Version="3.3.101" 
    Microsoft.Extensions.Configuration" Version="3.1.8"
    Microsoft.Extensions.Configuration.Json" Version="3.1.8" 
    Microsoft.Extensions.Hosting" Version="3.1.8"
    Newtonsoft.Json" Version="12.0.3"
* OS Info: Debian 10 
* Build Environment  VSCode 
* Targeted .NET Platform:   netcoreapp2.1

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment] 2020-09-23 18:35
Hi @CraigChamberlain, 

Good morning.

I tried to reproduce the issue (using .NET Core 3.1), but credentials are loaded successfully when using the following code in `ConfigureServices`:

```C#
services.AddDefaultAWSOptions(Configuration.GetAWSOptions());
services.AddAWSService<Amazon.DynamoDBv2.IAmazonDynamoDB>();
```

<img width="1078" alt="Screen Shot 2020-09-23 at 11 30 49 AM" src="https://user-images.githubusercontent.com/67916761/94054303-57e58900-fd90-11ea-8511-38c8374d2390.png">

Contents of `.aws/credentials` file:
```
[TestProfile]
aws_access_key_id = AAAA
aws_secret_access_key = BBBB
aws_session_token = CCCC
```

**Package Versions:**
```
AWSSDK.DynamoDBv2 3.3.106.18
AWSSDK.Extensions.NETCore.Setup 3.3.100.1
```

Please check:

- If it was working with the above mentioned package versions and using the code `services.AddDefaultAWSOptions(Configuration.GetAWSOptions());`. I'm not sure if there is a any broken package installation.

- If it works with the default profile (rather than named profile). You would also need to comment/remove profile from `app settings.json`.

Thanks,
Ashish

**Comment by CraigChamberlain** [comment] 2020-09-23 19:35
Hi Ashish,

I've tried with and without the Profile setting in the json and also with the profile named and default.  

I went back to using .net Core 2.1 not 3.1 so I could debug. The other thing that might be different is that this is a local instance of a lambda function.

I'll see if I can make a supper basic example from scratch and if it works then I know my problem is local and if it doesn't I'll post to a repo and share.

**Comment by CraigChamberlain** [comment] 2020-09-23 20:38
So thinking about it.  The local lambda environment is a docker container that will not be able to access my profile in ~/.aws/credentials.  However, it should pull in the keys from environmental variables option 7 if I remove the reference to the missing profile in the appsettings.json.  
![image](https://user-images.githubusercontent.com/48378435/94066841-f4397b00-fde4-11ea-87f6-758c045401fa.png)

**Comment by ashishdhingra** [comment] 2020-09-23 22:42
@CraigChamberlain I'm not sure on how it should behave in docker container environment. Just out of curiosity, how are you passing environment variables to the docker container.

**Comment by CraigChamberlain** [comment] 2020-09-24 08:32
I'm doing it from the launch config. 
```

        {
            "type": "aws-sam",
            "request": "direct-invoke",
            "name": "ConvertDate:HelloWorldFunction (dotnetcore2.1)",
            "invokeTarget": {
                "target": "template",
                "templatePath": "ConvertDate/template.yaml",
                "logicalId": "HelloWorldFunction"
            },
            "lambda": {
                "payload": { "path": "ConvertDate/events/event.json"},
                "environmentVariables": {
                    "AWS_ACCESS_KEY_ID": "XXXXXXXXXXXXXX", 
                    "AWS_SECRET_ACCESS_KEY": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
                }
            }
        },
```

But I could equally do from the template file.

**Comment by CraigChamberlain** [comment] 2020-09-24 08:34
I'm working through some things systematically at the moment to write a few gotchas on my blog.  I'll test my theory about removing the profile reference now.  I'm also looking at the settings I can put in here as I think I can control certain elements about the docker env.  For example network.  I may be able to map certain local files for instance too.

**Comment by CraigChamberlain** [comment] 2020-09-24 12:16
I made a very simple project.
https://github.com/CraigChamberlain/LamdaConfigInvestigation

Code is not pretty and I've put everything in the one file to make it as simple as possible to isolate behaviour.

I would expect that `services.AddDefaultAWSOptions(Configuration.GetAWSOptions());` is not required.  Quote from [here](https://www.stevejgordon.co.uk/getting-started-with-the-aws-sdk-in-net-core-part-1).

    "We can, if you prefer, simplify this code slightly. In earlier versions of the SDK from AWS, the call to AddDefaultAwsOptions was required to ensure settings like the region were loaded correctly. Today, the SDK has behaves differently, and the ClientFactory which is responsible for creating the service clients (the implementation of IAmazonS3 in this case) checks whether the AwsOptions is registered in the DI container. If not, it attempts to create an instance of the options using the GetAWSOptions option, before creating the required SDK client.

    Therefore, it’s possible to remove the call to AddDefaultAWSOptions in ConfigureServices,"

However without this a null value exception is thrown in both .NET 2.1 and .NET 3.1

Also I believed that it would attempt to use environmental variables automatically but it seems not too.

**Comment by ashishdhingra** [comment] 2020-09-24 16:06
Hi @CraigChamberlain,

I'm not sure if it helps, please refer the page https://hub.docker.com/r/lambci/lambda/ which specifies that the environment variables can be passed with `-e` switch, like below:

```
docker run --rm [-d] \
  -e DOCKER_LAMBDA_STAY_OPEN=1 \
  -p 9001:9001 \
  -v <code_dir>:/var/task:ro,delegated \
  [-v <layer_dir>:/opt:ro,delegated] \
  lambci/lambda:<runtime> \
  [<handler>]
```

The page also lists the supported environment variables. 

Thanks,
Ashish

**Comment by CraigChamberlain** [comment] 2020-09-25 08:38
Hi  @ashishdhingra,

Thanks for the link.  The environmental variables are getting into the application but they aren't being picked up by AddDefaultAWSOptions or AddAWSService.

I added a third example to the repo that is just your basic Console app with the minimum features.

It can load the default profile as expected which is great.  However, if I rename the credentials file it doesn't resort to env. variables as I understand it should.

Furthermore AddAWSService<T>(); run without AddDefaultAWSOptions() previously still throws a null value exception so I must have missed instantiating a dependency at some point.

**Comment by ashishdhingra** [comment] 2020-09-25 23:35
Hi @CraigChamberlain,

Good afternoon.

I came across the blog post [A New and Standardized Way to Manage Credentials in the AWS SDKs](https://aws.amazon.com/blogs/security/a-new-and-standardized-way-to-manage-credentials-in-the-aws-sdks/), which specifies that `All the SDKs except the .NET SDK now can automatically look for credentials in the same environment variables: AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY`. I'm not sure if this is still true since it dates back to July 2014.

To test it, added the following profile to my `.aws/credentials` file:
```
[testprofile]
aws_access_key_id = TestKey
aws_secret_access_key = TestSecretKey
``` 

Then using your console application, I was able to use the AWS_PROFILE environment variable to load credentials from different profile than the default profile:

<img width="791" alt="Screen Shot 2020-09-25 at 3 46 40 PM" src="https://user-images.githubusercontent.com/67916761/94322198-a2106b00-ff46-11ea-8984-f1ca8a3b34dd.png">

However, as you pointed out, the credentials are not loaded using AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables. I'm not sure if this is a bug or expected behavior since in AWS SDK for .NET documentation, the page [Configuring AWS Credentials](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html) doesn't specify the support of credentials via environment variables.

As a workaround, you may pass the environment variables to docker container using `-e` flag, but you would need to manually parse it and construct `ImmutableCredentials`, since `Amazon.DynamoDBv2.AmazonDynamoDBClient` doesn't appear to load the credentials from environment variables. 

There is also a blog post [A Guide to Locally Testing Containers with Amazon ECS Local Endpoints and Docker Compose](https://aws.amazon.com/blogs/compute/a-guide-to-locally-testing-containers-with-amazon-ecs-local-endpoints-and-docker-compose/) that might be helpful.

Hope this provides some guidance. Please let me know if you would like developer to have a look at it or if we could close this issue.

Thanks,
Ashish

**Comment by CraigChamberlain** [comment] 2020-09-26 07:56
Many thanks, excellent links.

There is plenty of provision to get the keys into the docker environment through the template file and also in a launch.json file so that is covered.

I actually started out with a workaround loading the credentials into a client a register as a Singleton. So its not holding me up now, I just lost time following various instructions, not all AWS, and wanted to investigate wether I was doing something wrong or the instructions were incorrect.

I agree this might not be a priority to get delevoper time.  It might be more of a documentation issue.  That said I would assume the following is taken from the SDK and it suggests there is a feature to look at environmental variables.

https://gist.github.com/stevejgordon/e6dd8e57af4bc1e01cdc169220c4cbf2#file-environmentvariablesawscredentials-cs

I also plan to look at why AddDefaultAWSOptions is essential, it may be that AddAWSService<IAmazonDynamoDB>() looks for a local variable called Configuration where as I have called my config object root? If its not passed to the method as a param I would be surprised if it was important.

Perhaps I can load the SDK extension source rather than nuget and trace the null value exception?

**Comment by CraigChamberlain** [comment] 2020-09-26 09:11
Might be better to close this as the profile element is well understood. I can look into the environmental variables and the null value exception and make a new specific bug issue out of that.

**Comment by CraigChamberlain** [comment] 2020-09-27 18:42
I found I was missing .AddEnvironmentVariables() in my configuration builder but this doesn't solve the problem.  I'll post over on stackoverflow.

**Comment by ashishdhingra** [comment] 2020-10-02 18:35
@CraigChamberlain Thanks for posting the question on StackOverflow. I have discussed the environment variable issue with developer and they are looking at it (from code, it appears to be fine). I will close this issue based on your suggestion. Request you to post any guidance you receive from community to this issue.

**Closed by ashishdhingra** 2020-10-02 18:35 UTC
Labels: bug, module/credentials
