### ISSUE TITLE
Could not create SSL/TLS secure channel with S3

### ISSUE THREAD

**Issue by craiglink** [aws/aws-sdk-net#86] opened 2014-03-23 14:44 UTC
Over the last couple of days, we've started seeing the following issues communicating with S3. I don't believe anything has changed in our code to cause this.  From research, it seems to often be related to server cert / time issues.  Where using the AWSSDK-NET 20.0.11.0

Anyone else seeing these errors?

Amazon.Runtime.AmazonServiceException: An error occurred while sending the request. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel. at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context) at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar) --- End of inner exception stack trace --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() at Amazon.Runtime.AmazonWebServiceClient.d__3`1.MoveNext() --- End of inner exception stack trace --- at Amazon.Runtime.AmazonWebServiceClient.RetryOrThrow(WebRequestState state, Exception exception) at Amazon.Runtime.AmazonWebServiceClient.d__3`1.MoveNext() --- End of stack trace from previous location where exception was throw

**Comment by Funbit** [comment] 2015-11-16 09:16
The problem is usually related to the SSL certificate revocation issue.
If you have enabled revocation by using:
ServicePointManager.CheckCertificateRevocationList = true;
Then try to disable it and see how it works.

**Comment by gokarnm** [comment] 2016-01-12 23:50
Closing this issue. Feel free to reopen if you are still facing a problem.

**Closed by gokarnm** 2016-01-12 23:50 UTC
Labels: Question

**Comment by sachinpachori** [comment] 2019-05-12 11:34
I am facing the same issue using AWSSDK for .NET version 3.3.0.0
