### ISSUE TITLE
Amazon.SimpleEmail.AmazonSimpleEmailServiceException: Missing '<'

### ISSUE THREAD

**Issue by bmarder** [aws/aws-sdk-net#1432] opened 2019-10-15 14:10 UTC
```
Amazon.SimpleEmail.AmazonSimpleEmailServiceException: Missing '<' ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
```

## Context
Sending emails with SES fails randomly with this exception. The same email can work one time, but fail another.

## Your Environment
`<PackageReference Include="AWSSDK.SimpleEmail" Version="3.3.101.52" />`
Azure App Service
* Targeted .NET platform: netcoreapp2.2

**Comment by klaytaybai** [comment] 2019-10-15 17:56
Do you have more logs/stack traces and sample code you could share with us?--confidential information removed

**Comment by bmarder** [comment] 2019-10-15 21:16
@klaytaybai Sorry no logs or stack traces, but I can add whatever you need me to. The code is nothing out of the ordinary (not using any advanced features/attachments. Happens very rarely.

**Comment by klaytaybai** [comment] 2019-11-18 20:54
I think this is a case that would be best handled by Premium Support if you wish to continue with it.  I'm going to close this out for now because I don't think there is going to be much we are going to be able to do to reproduce this without a lot of effort or more knowledge of the type of AmazonSimpleEmailServiceException.  If others experience this issue, I encourage you to comment here too.

**Closed by klaytaybai** 2019-11-18 20:54 UTC
Labels: response-requested
