### ISSUE TITLE
Cannot set timeout for S3Client (on AmazonS3Config)

### ISSUE THREAD

**Issue by MrM40** [aws/aws-sdk-net#2570] opened 2023-03-15 10:49 UTC
### Describe the bug

Setting the Timeout property on AmazonS3Config doesn't seem to have any effect:
```
this.AWS_S3Config = new AmazonS3Config()
            {
                ServiceURL = "https://" + Config.endpoint,
                Timeout = TimeSpan.FromSeconds(10D),
                MaxErrorRetry = 1
            };
```
At least not on `TransferUtility` and `ListObjectsV2Async`
BUT MaxErrorRetry does have some effect:
Retry=1: Total timeout 1.2s
Retry=2: Total timeout 2.7s 
Retry=3: Total timeout 10s (?)

Did play with `.RetryMode` but didn't change anyting, neither did `.ReadWriteTimeout`

If the application is blocked by firewall, `TransferUtility` and `ListObjectsV2Request` throw the exception with the above specified timeouts:
> An attempt was made to access a socket in a way forbidden by its access permissions.

Found other similar issues in here but they were discarded for different reasons e.g. not using AWS endpoint.

### Expected Behavior

That timeout property worked

### Current Behavior

That timeout property is ignored

### Reproduction Steps

NA

### Additional Information/Context

Did read the page https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/retries-timeouts.html

### AWS .NET SDK and/or Package version used

awssdk.s3.3.7.103.25_netstandard2.0
awssdk.core.3.7.105.17_netstandard2.0

### Targeted .NET Platform

.NET 6

### Operating System and version

Win 10

**Comment by ashishdhingra** [comment] 2023-03-15 17:41
Hi @MrM40,

Good morning.

Could you please share the following:
- Sample code to reproduce the issue.
- Enable verbose logging using below code and share the detailed logs:
```C#
Amazon.AWSConfigs.LoggingConfig.LogResponses = Amazon.ResponseLoggingOption.Always;
Amazon.AWSConfigs.LoggingConfig.LogTo = Amazon.LoggingOptions.SystemDiagnostics;
Amazon.AWSConfigs.AddTraceListener("Amazon", new System.Diagnostics.ConsoleTraceListener());
```
- What is the `ServiceURL` value being set in your application?

Kindly note that:
- We do not support troubleshooting 3rd party solutions that simulate AWS S3.
- In case the application is blocked by firewall, then the network layer (not controlled by SDK) might throw exception immediately.

Thanks,
Ashish

**Comment by MrM40** [comment] 2023-03-15 20:35
Hi Ashish

Since the Timeout is influenced by the property `.MaxErrorRetry` I would claim the issue seem to be related to AWS SDK and not the network layer. 

I've archived my goal by setting the `.MaxErrorRetry` property so I'm "happy" now. But I wasted some time because I had to investigate and do a lot of test-runs. So for other users it would be nice it the presumable bug could be fixed.

I'm afraid I can't provide more details at the moment.

**Comment by ashishdhingra** [comment] 2023-03-17 00:27
There are exceptions to the default timeout values mentioned in https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/retries-timeouts.html.

I tried debugging through the AWS SDK for .NET code using the code below:
```C#
AmazonS3Client _client = new AmazonS3Client(new AmazonS3Config() { Timeout = TimeSpan.FromSeconds(10D), MaxErrorRetry = 1 });
            var _listObjectsV2Response = await _client.ListObjectsV2Async(new ListObjectsV2Request() { BucketName= "testbucket" });
```

The timeout is indeed set at HTTP client level as shown in the below screenshot:
<img width="981" alt="Screen Shot 2023-03-16 at 5 24 14 PM" src="https://user-images.githubusercontent.com/67916761/225781193-f1001e55-3590-4f48-a3e0-c3ad741bbc49.png">

Closing is issue since the Timeout value is set and the issue could not be reproduced.

**Closed by ashishdhingra** 2023-03-17 00:27 UTC
Labels: bug, s3
