### ISSUE TITLE
System.Net.Http.CurlException: Failure when receiving data from the peer when trying to download a file from S3

### ISSUE THREAD

**Issue by flo8** [aws/aws-sdk-net#613] opened 2017-04-09 04:18 UTC
I don't know if this is a .Net Core related bug or a AWS SDK one but I found useful to post it here as well.

We get this error randomly when downloading a lot of files from Amazon S3 using AWSSDK.Core (3.3.8.2) and AWSSDK.S3 (3.3.5.7).

**System.Net.Http.CurlException: Failure when receiving data from the peer
at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)**

Here is the code that seems to produce the error:
```
// Prepare S3 request
GetObjectRequest request = new GetObjectRequest();
request.Key = remoteFile;
request.BucketName = bucketName;

// Download our file from S3
Task<GetObjectResponse> response = client.GetObjectAsync(request);

if (response.Result.ResponseStream != null)
{
    using (MemoryStream memstream = new MemoryStream())
    {
        // Get the stream
        response.Result.ResponseStream.CopyTo(memstream);
        byte[] bytes = memstream.ToArray();
```
More details available in this thread : https://github.com/dotnet/corefx/issues/9357

**Comment by PavelSafronov** [comment] 2017-04-10 16:50
Can you provide some more information about how you are able to encounter this error? How many files are you downloading at any given time? How large are they? How consistently are you seeing this issue? What environment are you running this in? Can you post the contents of your project.json as well?

Does the code that you posted reproduce this exception consistently?

The code is a snippet so I can't tell if you're disposing of the `GetObjectResponse` object or its `ResponseStream`. If you're not already doing this, you should be.

**Comment by flo8** [comment] 2017-04-11 02:00
1/ This function is used by a single thread so files are downloaded one by one, there is no parallel download.

2/ How large files are: It ranges from a few kilobytes to 2-3 MB maximum. 

3/ This happens on a completely random basis for the moment and very rarely. On thousands of file downloads it seems to appear once or twice for the moment. I couldn't establish a pattern and unable to reproduce this exception constantly.

4/ Environment:
Console app with .Net Core 1.1 (netcoreapp1.1) in a standalone application running on Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-70-generic x86_64)
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3

5/ This is a .Net Core 1.1 project, no project.json

6/ Yes I confirm that I dispose everything. Here is what I do at the end of the function:
```
                            // Close our memory stream and fs
                            fs.Dispose();
                            memstream.Dispose();
```

**Comment by epicberry** [comment] 2017-04-24 05:23
I am facing the same error with dotnet core 1.0
When I try to create a bucket using AWS S3 in dotnet core
**In Debug Mode** - Creates the bucket every time successfully
**In Run Mode** - Fails every time with the error
**Failure when receiving data from the peer
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
System.Net.Http**

My Code:
PutBucketRequest newBucket = new PutBucketRequest();
newBucket.BucketName = bucketName;
await client.PutBucketAsync(newBucket);

Please help.

**Comment by PavelSafronov** [comment] 2017-05-02 23:40
@epicberry, it looks like your case is different. Please open a new issue here and provide information about the environment where your code works and where it does not. A complete stack trace would be helpful as well.

**Comment by PavelSafronov** [comment] 2017-05-03 21:19
@flo8, from your code snippet and latest comment it's not clear what `fs` is. Can you post the complete code sample? Are you also disposing of `response.Result` or `response.Result.ResponseStream`?

**Comment by flo8** [comment] 2017-05-04 02:58
@PavelSafronov please find the complete code below

```
// Download and unzip a file on S3
        public bool DownloadAndUnzipFile(string bucketName, string remoteFile, string localFile, out double fileSizeInKb)
        {
            fileSizeInKb = 0;
            int nbRetries = 0;
            string log = string.Empty;
            const int msBeforeRetry = 2000;

            // This block can fail so we will retry 5 times before giving up
            while (nbRetries++ <= 5)
            {
                try
                {
                    // First, make sure our local files do not already exist, if they do, remove existing ones
                    if (File.Exists(localFile))
                        File.Delete(localFile);

                    // Craft our request
                    GetObjectRequest request = new GetObjectRequest();
                    request.Key = remoteFile;
                    request.BucketName = bucketName;

                    // Download our file
                    Task<GetObjectResponse> response = client.GetObjectAsync(request);

                    if (response.Result.ResponseStream != null)
                    {
                        using (MemoryStream memstream = new MemoryStream())
                        {
                            // Get the stream
                            response.Result.ResponseStream.CopyTo(memstream);
                            byte[] bytes = memstream.ToArray();

                            // Decompress it
                            byte[] uncompressed = GZipUtil.Decompress(bytes);

                            // Set our fileSize
                            fileSizeInKb = (uncompressed.Length / 1024);

                            // Write it to file
                            FileStream fs = new FileStream(localFile, FileMode.Create);
                            fs.Write(uncompressed, 0, uncompressed.Length);

                            // Close our memory stream and fs
                            fs.Dispose();
                            memstream.Dispose();

                            // Success, we can leave
                            return true;
                        }
                    }
                }
                catch (Exception e)
                {
                    // We couldn't download the file, sometimes it can be due to a temporary (network error), so we'll wait before retrying
                    Thread.Sleep(msBeforeRetry);
                }
            }

            // If we got here, it means we couldn't get our file
            return false;
        }
```

**Comment by PavelSafronov** [comment] 2017-05-04 19:06
You're not disposing of the GetObjectResponse (and are not safely disposing of the FileStream, though that's unrelated). Here's a slight rewrite of your code that disposes of the required resources:
```
// Download our file
using(GetObjectResponse response = client.GetObjectAsync(request).Result)
{
    if (response.ResponseStream != null)
    {
        using (MemoryStream memstream = new MemoryStream())
        {
            // Get the stream
            response.ResponseStream.CopyTo(memstream);
            byte[] bytes = memstream.ToArray();

            // Decompress it
            byte[] uncompressed = GZipUtil.Decompress(bytes);

            // Set our fileSize
            fileSizeInKb = (uncompressed.Length / 1024);

            // Write it to file
            using(FileStream fs = new FileStream(localFile, FileMode.Create))
            {
                fs.Write(uncompressed, 0, uncompressed.Length);
            }

            // Success, we can leave
            return true;
        }
    }
}
```

That being said, it's still not clear from the provided stack trace, code, and the linked corefx issue if this is being caused by an issue with .NET Core or the SDK.

Can you provide the full stack trace? Where does the error usually occur, at the point when you get the first response (`response.Result`), or when you're reading the data from S3 (`ResponseStream.CopyTo`)?

**Comment by KiarashS** [comment] 2017-05-06 04:13
Also i have this problem in Linux with a Local Web Server.

**Comment by PavelSafronov** [comment] 2017-05-08 17:02
@KiarashS, do you mean that you're also receiving CurlException? It's not year clear what is causing this specific issue, and you have not provided any more additional information, including stack trace and code. Can you open a separate issue with all the information that the issue template requests?

**Comment by KiarashS** [comment] 2017-05-09 14:57
@PavelSafronov No, My problem is not CurlException.

**Comment by gokarnm** [comment] 2017-05-15 21:55
@flo8, the SDK automatically retries [IOException](https://github.com/aws/aws-sdk-net/blob/cfa2b60d98bda61249e320f7c849790e9f8e4f00/sdk/src/Core/Amazon.Runtime/Pipeline/RetryHandler/DefaultRetryPolicy.cs#L217) and other errors which are intermittent in nature, and are due to internet weather. The `GetObjectAsync` API is a bit different w.r.t. retries, it hands the response stream directly back to the user code. If an exception is thrown when you work with the response stream, the SDK does not retry it, the user code will need to retry in this case.

@KiarashS, are you getting this error for `GetObjectAsync` API? If not, could you open a new issue for it?

Closing this issues, feel free to reopen.

**Closed by gokarnm** 2017-05-15 21:55 UTC
Labels: Question
