### ISSUE TITLE
Issue with EnableTerminationProtection in DescribeStacks when no StackName are provided

### ISSUE THREAD

**Issue by Pomdap** [aws/aws-sdk-net#805] opened 2017-11-28 16:38 UTC
When DescribeStacks is called without filter on the StackName, the property EnableTerminationProtection from the Stack model is filled with an invalid value (False).

## Expected Behavior
The EnableTerminationProtection property should be filled with the real value.

## Current Behavior
EnableTerminationProtection is filled with the value "False" wheter the Stack is protected or not.

## Steps to Reproduce (for bugs)
- Create a stack
- Try to make a call to DescribeStacks using the StackName in the parameters
- Try to make a call to DescribeStacks without any filter

The result for the same stack is not the same in both cases.

I have attached a console application sample [EnableTerminationProtectionIssue.zip](https://github.com/aws/aws-sdk-net/files/1510764/EnableTerminationProtectionIssue.zip).
Launch it as follows :

`EnableTerminationProtectionIssue.exe <accesskey> <secretkey> <region name> <stackname>`

## Context
When I try to display the result for a list of stacks, the result is not accurate.

## Your Environment
* AWSSDK.Core version used:  3.3.20
* AWSSDK.CloudFormation version used:  3.3.9
* Operating System and version: Windows 10 Entreprise
* Visual Studio version: 2015
* Targeted .NET platform: net461

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by sstevenkang** [comment] 2017-11-28 18:11
Thanks for detailed report.  This seems to be a service side issue. I forwarded the information to CloudFormation team.

**Comment by sstevenkang** [comment] 2017-11-28 18:31
It looks like CloudFormation service is not returning `EnableTerminationProtection` flag when making DescribeStacks without filter.  We passed the information to the service team.  I'll keep the ticket open until we hear back from them.

**Comment by sstevenkang** [comment] 2017-12-04 18:25
Hi, I had a chat with the service team.  This behavior seems to be as designed.  It appears that the documentation doesn't have any information about this so we'll update that.  CloudFormation team is aware of this inconsistency and they are actively working on this.

Since there's no actionable item on our side, I'll close this.

**Closed by sstevenkang** 2017-12-04 18:25 UTC
Labels: Service Issue
