### ISSUE TITLE
Unable to add instance for EBS volume with a snapshot

### ISSUE THREAD

**Issue by gopaldogra** [aws/aws-sdk-net#515] opened 2016-12-20 13:04 UTC
When I am trying to add an EBS device based BlockDeviceMapping, with a snapshot id, the instance launch is failing with error: 

**the encrypted flag cannot be specified since device /dev/xvda has a snapshot specified**

The issue is: 

Acc to,  AWS Api documentation: 

**Supplying both a snapshot ID and an encryption value as arguments for block-device mapping results in an error.**

Now currently, in EbsBlockDevice class, by default the Encrypted Property is being set as false, and not Null. But aws api expects it to be null for the ebs device, when snapshot id is given. So both snapshot id and encryption value are getting sent, and hence, instance launch is failing.

**Comment by steveataws** [comment] 2016-12-20 16:34
Thanks for letting us know, we'll take a look and get a fix out asap.

**Comment by gopaldogra** [comment] 2016-12-28 10:48
It is happening, when I take blockdevice mapping from AMI using DescribeImages call.

**Comment by gopaldogra** [comment] 2016-12-28 11:40
And only On-Demand Instance launch is failing, spot instance launch is working.

**Comment by gopaldogra** [comment] 2016-12-28 14:25
Update: The issue is with Launch Configuration BlockDeviceMapping. BlockDeviceMappings from AMI are not coming properly in LaunchConfiguration's BlockDeviceMappings.

**Comment by PavelSafronov** [comment] 2016-12-29 18:52
Which version of the .NET SDK are you currently using?

**Comment by gopaldogra** [comment] 2016-12-30 07:00
I am using nuget packages. 

AWSSDK.AutoScaling - 3.3.0.3
AWSSDK.EC2 - 3.3.2.1

Scenario: Autoscaling group launchconfiguration contains an ami which is having ebs volume with snapshot specified. Then if you take all BlockDeviceMappings from Launch Configuration's BlockDeviceMappings(including the one's inherited from AMI) and try to launch ondemand ec2 instance, it is failing with error:

**the encrypted flag cannot be specified since device /dev/xvda has a snapshot specified**

In AmazonAutoScalingClient, I am calling DescribeLaunchConfigurations method to find the BlockDeviceMappings from Launch Configuration. 

Code to convert Amazon.AutoScaling.Model.BlockDeviceMapping to Amazon.EC2.Model.BlockDeviceMapping:

var lc = describeLaunchConfigurationResponse.LaunchConfigurations.FirstOrDefault();
foreach (var blockDeviceMapping in lc.BlockDeviceMappings)
{
    var mapping = new Amazon.EC2.Model.BlockDeviceMapping()
    {
        DeviceName = blockDeviceMapping.DeviceName,
        NoDevice = blockDeviceMapping.NoDevice ? blockDeviceMapping.DeviceName : null,
        VirtualName = blockDeviceMapping.VirtualName,
        Ebs = blockDeviceMapping.Ebs == null ? null : new Amazon.EC2.Model.EbsBlockDevice()
        {
            DeleteOnTermination = blockDeviceMapping.Ebs.DeleteOnTermination,
            SnapshotId = blockDeviceMapping.Ebs.SnapshotId,
            VolumeSize = blockDeviceMapping.Ebs.VolumeSize,
            VolumeType = blockDeviceMapping.Ebs.VolumeType
        }
    };
    if (blockDeviceMapping.Ebs != null)
    {
        if (string.IsNullOrEmpty(blockDeviceMapping.Ebs.SnapshotId))
        {
            mapping.Ebs.Encrypted = blockDeviceMapping.Ebs.Encrypted;
        }
        if (blockDeviceMapping.Ebs.VolumeType == "io1")
            mapping.Ebs.Iops = blockDeviceMapping.Ebs.Iops;
    }
    launchConfigurationResponse.BlockDeviceMappings.Add(mapping);
}

**Comment by PavelSafronov** [comment] 2016-12-30 15:59
Since you are constructing the BlockDeviceMapping and populating it here, you can simply add a check if the `blockDeviceMapping.Ebs.SnapshotId` is set (this can be checked with `!string.IsNullOrEmpty(blockDeviceMapping.Ebs.SnapshotId)`), in which case the `Encrypted` property should not be set by you at all.

This code sample does not show how the mappings are finally used. If they are being inserted into a `RunInstancesRequest`, then the SDK should be unsetting the `Encrypted` flag for you automatically, in [this piece of code](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/EC2/Custom/Internal/AmazonEC2PreMarshallHandler.cs#L94). What operation is are the mappings passed into?

**Comment by gopaldogra** [comment] 2016-12-31 02:56
I am already doing it, but for EBS volumes inherited from AMI, the SnapshotId itself comes as null. So this logic does not work. So In my request snapshotid goes as null and Encrypted flag as false. But in aws api/ aws sdk somewhere in code, snapshotid is getting picked up and hence the error comes.

I am directly passing the mappings to RunInstancesRequest. 

PS: For purely LaunchConfiguration related EBS volumes, SnapshotId comes.

**Comment by PavelSafronov** [comment] 2017-01-04 00:50
I've been unable to reproduce this issue locally. Can you capture the request wire-log (for instance, using [Fiddler](http://www.telerik.com/fiddler)) and post it here?

**Comment by PavelSafronov** [comment] 2017-01-05 19:26
Thanks for that. I was finally able to construct a matching request (code below) that reproduces this issue. Looking into this.

```
using (var ec2 = new AmazonEC2Client())
{
    var request = new RunInstancesRequest
    {
        ImageId = "ami-b73b63a0",
        InstanceType = InstanceType.M3Medium,
        DisableApiTermination = false,
        MaxCount = 1,
        MinCount = 1,
        SubnetId = "subnet-666e302f",
        BlockDeviceMappings = new List<BlockDeviceMapping>
        {
            new BlockDeviceMapping
            {
                DeviceName = "/dev/xvda",
                Ebs = new EbsBlockDevice
                {
                    DeleteOnTermination = true,
                    Encrypted = false,
                    SnapshotId = null,
                    VolumeSize = 8,
                    VolumeType = VolumeType.Gp2
                }
            }
        },
        EbsOptimized = false,
    };
    ec2.RunInstances(request);
}
```

**Comment by PavelSafronov** [comment] 2017-01-05 19:59
Trying to launch this instance through the console, I can see that the device "/dev/xvda" is already configured, and its Encrypted status cannot be modified, as shown in the below screenshot:
![image](https://cloud.githubusercontent.com/assets/1359724/21695108/3ea8f34a-d33d-11e6-8d57-3f822eebab16.png)

Before attempting to run an instance, you need to verify if a BlockDeviceMapping you are trying to configure already exists on the image's existing BlockDeviceMappings **and** it has a SnapshotId set, in which case the Encrypted flag on the RunInstancesRequest should not be touched.

**Comment by gopaldogra** [comment] 2017-01-07 09:03
Yes. I understood this hack and I am able to run instance. But it will be better if, DescribeLaunchConfigurations method returns SnapshotId for such BlockDeviceMappings, so that this hack is not required.

**Comment by PavelSafronov** [comment] 2017-01-09 18:42
Good point. I'm contacting the service team about this.

**Comment by PavelSafronov** [comment] 2017-01-17 18:38
The root cause of this issue is a software bug in Auto Scaling Console that causes the EBS snapshot ID to not be set properly when creating Launch Configuration. Hence when calling *DescribeLaunchConfigurations*, the snapshot ID is not returned in the response. Auto Scaling team is taking an immediate action item to fix this issue.

**Comment by PavelSafronov** [comment] 2017-03-14 22:50
The bug in the Auto Scaling Console has been fixed. Resolving.

**Closed** 2017-03-14 23:26 UTC
Labels: Question
