### ISSUE TITLE
S3 : Error when try to access object

### ISSUE THREAD

**Issue by shaangidwani** [aws/aws-sdk-net#2467] opened 2022-10-31 17:26 UTC
### Describe the bug

We are uploaded one file using AWS SDK for JavaScript v2.727.1 with key “156-50191-55215f17-0718-4713-b0d4-3bcb8b401d71/Enterprise/Documents/156/Directories/kyoScan-‎10‎.‎31‎.‎2022-‎0‎.‎07‎.‎44_685_202210311112484.pdf” and its successfully uploaded but when we try to fetch the file information using S3FileInfo its gives the error below :

 

Target resource path [156-50191-55215f17-0718-4713-b0d4-3bcb8b401d71/Enterprise/Documents/156/Directories/kyoScan-‎10‎.‎31‎.‎2022-‎0‎.‎07‎.‎44_685_202210311112484.pdf] has bidirectional characters, which are not supportedby System.Uri and thus cannot be handled by the .NET SDK.

Currently we our Portal is using framework 4.6.1 and using AWSSDK.S3, Version=3.3.0.0

 

We try to check solution and found one solution that framework 4.7.2 but we are not able to upgrade our framework due to some reason.

### Expected Behavior

It should work as its uploaded successfully.

### Current Behavior

Not able to access file as its gives error.

### Reproduction Steps

Upload file using Unicode characters and try to access using .net aws sdk.

### Possible Solution

It should work like its working on windows instead of access file from windows server physical location.

### AWS .NET SDK and/or Package version used

AWSSDK.S3, Version=3.3.0.0

### Targeted .NET Platform

.net framework 4.6.1

### Operating System and version

Windows server / windows 10

**Comment by ashishdhingra** [comment] 2022-10-31 18:56
@shaangidwani Could you please confirm the exact AWSSDK.S3 package version used (not the assembly version)? Also, have you tried any other S3 API(s), like using `AmazonS3Client` directly or `TransferUtility`?

**Comment by shaangidwani** [comment] 2022-11-01 06:24
Exact AWSSDK.S3 package version used (not the assembly version)?
**Shankar : We are using AWSSDK.S3 3.7.0**
Have you tried any other S3 API(s), like using AmazonS3Client directly or TransferUtility?
Shankar: Yes, we are using AmazonS3Client  and TransferUtility
When you say file having unicode characters, could you please the sample name which could help us in reproduction (may be create a test file with unicode character in name, zip it and attach it to the GitHub issue)?
Shankar : Attached file for your ref.
[kyoScan-‎10‎.‎31‎.‎2022-‎0‎.‎07‎.‎44_685.pdf](https://github.com/aws/aws-sdk-net/files/9907420/kyoScan-.10.31.2022-.0.07.44_685.pdf)
File name : kyoScan-‎10‎.‎31‎.‎2022-‎0‎.‎07‎.‎44_685
Sample code fir reproduction.:
Shankar : Here is the code :
S3DirectoryInfo di = new S3DirectoryInfo(s3Client, S3BucketName, Key);

When we try with windows space its working fine its gives the issue when files are on the AWS and when we try to fetch / download at that time its gives the error.

**Comment by shaangidwani** [comment] 2022-11-02 06:05
We are stuck at this position and as we are on production environment and huge number of files having this issue as we migrated all clients data on S3 space and now client is not able to open those files having bidirectional characters.

I don't have any date of resolution until we got any date from Github SDK team as discussed with AWS S3 helpdesk.

Kindly provide date of fixed or temporary other way to fix this so that we can  communicate same with our clients.

**Comment by ashishdhingra** [comment] 2022-11-02 18:55
Hi @shaangidwani,

Good morning.

Somehow, the issue is not reproducible using the file you shared.
- Manually created the folder structure and uploaded the file using AWS Console (didn't use AWS SDK for JS).
- Using the below code (used `AWSSDK.S3 3.7.101.7` package, targeting `.NET Framework 4.6.1`):
```C#
using Amazon;
using Amazon.S3;
using Amazon.S3.IO;

namespace S3FileInfoTest_Issue2467
{
    internal class Program
    {
        private static string bucketName = "<<your-bucketname>>";
        private static string key = "156-50191-55215f17-0718-4713-b0d4-3bcb8b401d71/Enterprise/Documents/156/Directories/kyoScan-.10.31.2022-.0.07.44_685.pdf"; // or "kyoScan-.10.31.2022-.0.07.44_685🚠.pdf"
        private static string localPath = @"D:\kyoScan-.10.31.2022-.0.07.44_685.pdf"; // or "kyoScan-.10.31.2022-.0.07.44_685🚠.pdf"

        static void Main(string[] args)
        {
            AmazonS3Client amazonS3Client = new AmazonS3Client(RegionEndpoint.USEast2);
            S3FileInfo s3FileInfo = new S3FileInfo(amazonS3Client, bucketName, key);
            s3FileInfo.CopyToLocal(localPath);
        }
    }
}
```

The file is copied successfully at the specified local path.

I also tested with key `156-50191-55215f17-0718-4713-b0d4-3bcb8b401d71/Enterprise/Documents/156/Directories/kyoScan-.10.31.2022-.0.07.44_685🚠.pdf` containing `🚠` unicode character for `U+1F6A0`. It also works fine.

Thanks,
Ashish

**Comment by shaangidwani** [comment] 2022-11-03 07:47
May be github editor replace the characters but key has the Unicode characters "\u200e"

Let me reattached file and screenshots which shows the Unicode characters "\u200e"

<img width="791" alt="image" src="https://user-images.githubusercontent.com/26000152/199669136-1140f231-bd62-4bbc-999f-1aaebf99913c.png">
[kyoScan-‎10‎.‎31‎.‎2022-‎0‎.‎07‎.‎44_685.pdf](https://github.com/aws/aws-sdk-net/files/9926391/kyoScan-.10.31.2022-.0.07.44_685.pdf)

**Comment by ashishdhingra** [comment] 2022-11-04 17:13
@shaangidwani Discussed the issue with the team. The issue lies with the underlying .NET Framework 4.6.1. Glad to hear that the workaround to trim off the non-printable characters and subsequent validation in JS SDK logic for these characters, works for you. Please confirm if we could close the issue.

**Closed** 2022-11-07 05:51 UTC
Labels: bug, response-requested, module/s3

**Comment by kenjiuno** [comment] 2024-02-28 04:30
I came here from a web link.

And about the thrown exception:

```
Unhandled Exception: Amazon.Runtime.AmazonClientException: Target resource path [A?B] has bidirectional characters, which are not supportedby System.Uri and thus cannot be handled by the .NET SDK.
   at Amazon.Runtime.AmazonServiceClient.ComposeUrl(IRequest iRequest)
   at ConsoleApp103.Program.Main(String[] args)
```

Make sure that this exception is thrown from AWS SDK method: `AmazonServiceClient.ComposeUrl`, not from BCL.
So any attempts to do workarounds against .NET Framework 4.7.2 will be immune.

As a workaround, there is a chance to try older version of: `AWSSDK.Core < 3.7.0` (e.g. `3.5.3.9`)

This is the place where check occurs:

https://github.com/aws/aws-sdk-net/blob/22c8103f6265f995803dfdf344ba11bae24c8ce7/sdk/src/Core/Amazon.Runtime/AmazonServiceClient.cs#L568-L580

It says that it needs to switch the TargetFramework to `.NET Core 3.1` or later.

And then, about the banned bidi control characters:

https://github.com/aws/aws-sdk-net/blob/22c8103f6265f995803dfdf344ba11bae24c8ce7/sdk/src/Core/Amazon.Util/AWSSDKUtils.cs#L1400-L1416

This is the list we need to care about:

Unicode Character | Name
:-:|:-:
`'\u200E'` | LRM
`'\u200F'` | RLM
`'\u202A'` | LRE
`'\u202B'` | RLE
`'\u202C'` | PDF
`'\u202D'` | LRO
`'\u202E'` | RLO
