### ISSUE TITLE
When publishing a Lambda Function from a Node.js project, Dead Letter Queue is Required

### ISSUE THREAD

**Issue by ddrinka** [aws/aws-sdk-net#949] opened 2018-05-10 15:18 UTC
Moving from https://github.com/aws/aws-vsts-tools/issues/77.

I would not like to utilize a Dead Letter Queue.  When publishing a new Lambda Function from a Node.js project, if I don't select a Dead Letter Queue destination (and add permission to publish to that queue), creating the function fails with "ARNs must start with 'arn'".

![image](https://user-images.githubusercontent.com/1297262/39877331-50612c6c-543b-11e8-82ec-4350726f380a.png)
![image](https://user-images.githubusercontent.com/1297262/39877374-6ce342ee-543b-11e8-822a-5cf16a8af6a0.png)
![image](https://user-images.githubusercontent.com/1297262/39877411-84bced16-543b-11e8-9207-fd2b6f3f8d0a.png)

**Comment by ddrinka** [comment] 2018-05-10 15:19
@steveataws

**Comment by steveataws** [comment] 2018-05-11 16:12
Thanks for the clarifying screen shots, we'll take a look.

**Comment by wildest** [comment] 2018-05-23 16:30
Any update on this?
The POST request seems to be pushing this through, instead of just leaving it null.
"DeadLetterConfig":{"TargetArn":""},"

**Comment by 7therunner** [comment] 2018-05-23 16:34
This has happened to me twice. If i recall well, in both situations the case was with a new Lambda function. What I did was creating a dummy DLQ, publish the Lambda, then go at the console, remove the DLQ from the Lambda, and after that you can re-deploy the code without using a DLQ.

**Comment by steveataws** [comment] 2018-05-23 18:54
We're taking a look.

**Comment by normj** [comment] 2018-05-23 20:05
I have reproduced the problem and checked in a fix. We will work on getting the fixed released out to you.

**Comment by steveataws** [comment] 2018-05-25 15:52
Resolving issue as fix now available for both VS2017 and VS2015 users.

**Closed by steveataws** 2018-05-25 15:52 UTC
Labels: Bug, Visual Studio Toolkit

**Comment by cdichter** [comment] 2019-05-01 17:21
Even now, I will get "error uploading lambda function" several times in a row, then it succeeds.

What should we be looking at?

**Comment by klaytaybai** [comment] 2019-05-02 21:59
@cdichter, is your error the same--ARNs must start with 'arn'?

**Comment by cdichter** [comment] 2019-05-02 23:46
Whether you are on the lamba console v or the AWS deployment tool in visual
studio, you would see it as a timeout or thaty it was called.  It is really
a timeout

Summarizing, there are at least the following problems with the code for
updating AWS Lambda Functions:

1. Reliability problems in Lambda CLI console. The file upload used in "aws
lambda update-function-code" and by the web gui ("Lambda Management
Console") is not reliable for files above about 20 MB.  It virtually always
fails at 60 MB or above. The workaround is to upload to s3 and then update
from there.

2. Inconsistencies in Lambda CLI. For example:  "aws lambda
update-function-code" worn't take s3 url syntax
("s3://bucket/path_to_my_file") for the zipfile. "aws s3 cp" and other
commands accept this syntax.
