### ISSUE TITLE
Not able to add aws toolkit to visual studio 2017

### ISSUE THREAD

**Issue by nishidi** [aws/aws-sdk-net#956] opened 2018-05-16 11:48 UTC
I have installed the vsix aws toolkit from here https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.AWSToolkitforVisualStudio2017#overview

When tried to install from visual studio extension, I get an error saying **extension/package.json not found inside zip.**

Need help to install aws toolkit with visual studio in windows.
## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by normj** [comment] 2018-05-16 17:26
Can you tell us the Visual Studio version number by going to Help - About? It should be something like 15.X.X.

**Comment by nishidi** [comment] 2018-05-17 04:28
Thanks Norm.
Here are the details.
![vstudio](https://user-images.githubusercontent.com/34380992/40156696-bf7f2b26-59b8-11e8-8883-9e88afa046e4.png)

**Comment by normj** [comment] 2018-05-17 04:41
Sorry but that is the about box for Visual Studio Code, not Visual Studio 2017.

**Comment by WillPhoenixLiu** [comment] 2018-05-18 07:51
I can't install the toolkit too. My VS2017 version number is 15.7.1.
Below is the part of the log.

5/18/2018 5:49:26 PM - Signature Details...
5/18/2018 5:49:26 PM - 	Extension is signed with a valid signature.
5/18/2018 5:49:26 PM - 
5/18/2018 5:49:26 PM - Searching for applicable products...
5/18/2018 5:49:31 PM - Found installed product - Microsoft Visual Studio Ultimate 2013
5/18/2018 5:49:31 PM - Found installed product - Microsoft Visual Studio Premium 2013 
5/18/2018 5:49:31 PM - Found installed product - Microsoft Visual Studio Professional 2013
5/18/2018 5:49:31 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
5/18/2018 5:49:31 PM - Found installed product - Microsoft Visual Studio Enterprise 2015
5/18/2018 5:49:31 PM - Found installed product - Microsoft Visual Studio Professional 2015
5/18/2018 5:49:31 PM - Found installed product - Microsoft Visual Studio Community 2015
5/18/2018 5:49:31 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
5/18/2018 5:49:31 PM - Found installed product - Global Location
5/18/2018 5:49:31 PM - Found installed product - ssms
5/18/2018 5:49:31 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by steveataws** [comment] 2018-05-18 15:26
If you have VS2017 v15.7.1 installed then I would have expected it to at least show up in the probing that the installer is doing - all I see in your log is editions from 2013 through 2015, which is odd.

The installer (vsixinstaller.exe) is part of Visual Studio itself and is owned by Microsoft. A vsix package (which is what you download from the marketplace) is nothing more than a zip file of the artifacts to be installed. I have a similar setup to yours (with 2013 - 2017 versions) and scanning those installers shows there are multiple copies of the executable. For me these paths are:

C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE

My guess, and I stress this is a guess, based on the log trace that you supplied is that the vsixinstaller.exe for VS2015 is getting invoked, and not the one for VS2017. The vsix file we publish to the gallery installs only into VS2017 - therefore if an earlier vsixinstaller.exe runs it likely won't find the later versions of Visual Studio that correspond with our minimum install version. Why an earlier version runs, I don't know.

If you downloaded the vsix package and ran it outside Visual Studio then I'd recommend instead you try installing from within the IDE - if the wrong installer executable is being picked up outside the IDE, this may fix it. From within VS2017, select the Extensions and Updates option on the Tools menu and in the resulting dialog select the 'online' node and search for AWS. This will cause our extension to be listed, and you can then start the install from within Visual Studio.

If you need the toolkit for VS2013 and/or VS2015 too then those versions can be obtained from our [Windows installer](https://sdk-for-net.amazonwebservices.com/latest/AWSToolsAndSDKForNet.msi). This image does not contain the toolkit for VS2017 - that edition is only released to the Visual Studio gallery.

**Comment by WillPhoenixLiu** [comment] 2018-05-22 01:10
Hi steveataws, thank you very much. I disabled the AV software and restart several times. Finally, I installed it successfully.

**Comment by steveataws** [comment] 2018-05-22 15:39
Ok, good to know you are up and running whatever the cause was. Resolving the issue as I don't think there's anything else to do here.

**Closed by steveataws** 2018-05-22 15:39 UTC
Labels: Question, Visual Studio Toolkit

**Comment by mostafafallah** [comment] 2018-07-06 09:12
Hi
I have problem for installing AWS Toolkit
Can you help me ? 
[VSIXInstaller_bcb8ce2a-0531-47e8-8733-8ebe37e058ea.log](https://github.com/aws/aws-sdk-net/files/2169768/VSIXInstaller_bcb8ce2a-0531-47e8-8733-8ebe37e058ea.log)

**Comment by klaytaybai** [comment] 2018-10-05 23:05
@mostafafallah, sorry we didn't see this earlier.  It looks like a dependency download failed.  Have you tried reinstalling since you had the problem?  I'm guessing it could have just been a connectivity issue

**Comment by mostafafallah** [comment] 2018-10-15 08:19
Thanks @klaytaybai 
Yes, It is fixed now
Thanks a lot
