### ISSUE TITLE
RetryPolicy does not retry on TimeoutException

### ISSUE THREAD

**Issue by pworkpop** [aws/aws-sdk-net#1904] opened 2021-08-20 05:06 UTC
## Description
.NET 5 introduced changes to `HttpClient` for timed out requests by returning a wrapped `TimeoutException` - see the relevant changes in this PR [HttpClient throws TimeoutException wrapped by TaskCancellationException when request times out](https://github.com/dotnet/runtime/pull/2281)
The wrapped exception is being unwrapped by `HttpWebRequestMessage` https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Pipeline/HttpHandler/_netstandard/HttpRequestMessageFactory.cs#L566
This means a `TimeoutException` travels up the pipeline to the `RetryHandler` but it is not currently handled by the `RetryPolicy` and thus requests that timeout are not retried.

Expected behaviour is `TimeoutExceptions` to be handled by the `RetryPolicy`.

## Reproduction Steps
```
System.TimeoutException Void MoveNext()    at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at SsmOptionsConfigurator`1.GetAndApplyParametersAsync(TOptions options) // our code calling SSM GetParameters
```

As a temporary solution we have introduced a `TimeoutHandler` that is included in the pipeline after `RetryHandler` to wrap the `TimeoutException` back into an `OperationCancelledException` until this issue is resolved.

### Environment

* SDK Version: 3.3.100 (issue still exists in master)
* Package Version: 3.3.100
* OS Info: Dockerized Alpine 3.12
* Build Environment: Docker
* Targeted .NET Platform:  5

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

Add `TimeoutException` to the `RetryPolicy.IsTransientError`
https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Pipeline/RetryHandler/RetryPolicy.cs#L345
```
if (exception is OperationCanceledException || e is TimeoutException)
```

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment] 2021-08-31 23:47
@pworkpop Somehow, I'm unable to reproduce the issue. Followed the below steps:
- Using Postman, created a Mock server to configure GET URL that returns `408 Request Timeout` error code. It created URL something like `https://d3255f17-7588-4fbf-bc32-1925d7184c3a.mock.pstmn.io/`
- Created a simple .NET Core console application targeting .NET 5.0 (notice that it uses the URL generated by Mock server):
```C#
using Amazon.S3;
using System;

namespace TestConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            ListBuckets();
            Console.ReadLine();
        }

        private static void ListBuckets()
        {
            using (var amazonS3Client = new AmazonS3Client(new AmazonS3Config() { ServiceURL = "https://d3255f17-7588-4fbf-bc32-1925d7184c3a.mock.pstmn.io" })) 
            {
                var listBucketsResponse = amazonS3Client.ListBucketsAsync().Result;
                foreach (var bucket in listBucketsResponse.Buckets)
                {
                    Console.WriteLine($"{bucket.BucketName}");
                }
            }
        }
    }
}
```

Upon executing the application, it did retry default 5 times before giving error. Stepped through the code and found that the `408` HTTP timeout error is handled at the line https://github.com/aws/aws-sdk-net/blob/d8f73f937ef6ceb54782c7ce2e50bc4db7629860/sdk/src/Core/Amazon.Runtime/Pipeline/RetryHandler/DefaultRetryPolicy.cs#L191 via call to [IsServiceTimeoutError(exception)](https://github.com/aws/aws-sdk-net/blob/d8f73f937ef6ceb54782c7ce2e50bc4db7629860/sdk/src/Core/Amazon.Runtime/Pipeline/RetryHandler/RetryPolicy.cs#L386).

Output of `dotnet --version` is `5.0.400`. Could you please confirm the .NET 5 version?

Thanks,
Ashish

**Comment by lostincomputer** [comment] 2021-09-01 00:37
In my opinion, classify, timeout as a transient error is subjective.

The server could be taking too long to response because it is overloaded. Retrying will add even more load to the server(s) which is counterproductive.

Think about it this way, if your computer is slow because it's busy doing something, should you add even more load to it or leave it alone?

**Comment by pworkpop** [comment] 2021-09-01 00:40
@ashishdhingra This case is when request times out due to configured timeout waiting for remote party to respond.
@lostincomputer Timeout can be caused by network issues in between so retrying is still a valuable option + AWS endpoints are load balanced so next try will hopefully reach a better responding end.

**Comment by ashishdhingra** [comment] 2021-09-01 18:57
> @ashishdhingra This case is when request times out due to configured timeout waiting for remote party to respond. Remote url should take longer than the configured timeout to respond.
> @lostincomputer Timeout can be caused by network issues in between so retrying is still a valuable option + AWS endpoints are load balanced so next try will hopefully reach a better responding end.
> Timeouts were handled by the retry policy before the change in HttpClient in .NET 5 that introduced a TimeoutException as internal exception to the OperationCancelledException.

@pworkpop I tried to reproduce the issue by developing a simple WebAPI as below (which loops infinitely for Get and Post operations):
```C#
using Microsoft.AspNetCore.Mvc;
using System;

namespace WebApplication2.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class TestController : ControllerBase
    {
        [HttpGet]
        public string Get()
        {
            var rng = new Random();
            bool loop = true;
            while(loop)
            {
                System.Threading.Thread.Sleep(5000);
            }
            return "Testing";
        }

        [HttpPost]
        public string Post()
        {
            var rng = new Random();
            bool loop = true;
            while (loop)
            {
                System.Threading.Thread.Sleep(5000);
            }
            return "Posted";
        }
    }
}
```
and using the below sample app (targeting `net5.0`):
```C#
using Amazon.EC2;
using System;

namespace TestConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            DoOperation();
            Console.ReadLine();
        }

        private static void DoOperation()
        {
            using (var amazonEC2Client = new AmazonEC2Client(new AmazonEC2Config() { ServiceURL = "https://localhost:44352/test" })) 
            {
                var describeImagesResponse = amazonEC2Client.DescribeImagesAsync().Result;
                foreach (var image in describeImagesResponse.Images)
                {
                    Console.WriteLine($"{image.ImageId}");
                }
            }
        }
    }
}

```
The request failed with `OperationCanceledException` where InnerException is of type `System.TimeoutException`. This is handled successfully by [IsTransientError](https://github.com/aws/aws-sdk-net/blob/d8f73f937ef6ceb54782c7ce2e50bc4db7629860/sdk/src/Core/Amazon.Runtime/Pipeline/RetryHandler/RetryPolicy.cs#L266) via call to [ExceptionUtils.IsInnerException<IOException>(exception)](https://github.com/aws/aws-sdk-net/blob/d8f73f937ef6ceb54782c7ce2e50bc4db7629860/sdk/src/Core/Amazon.Runtime/Internal/Util/ExceptionUtils.cs#L47) when the inner exception of type `IOException` is encountered and thereafter retried. As mentioned earlier, the output of `dotnet --version` is `5.0.400`.

Please share the following to further investigate the issue:
- .NET 5 version.
- Sample code for consistent repro (where TimeoutException is not handled for retry)
- Steps for reproduction (including setup steps)

Thanks,
Ashish

**Comment by pworkpop** [comment] 2021-09-06 02:50
Hi @ashishdhingra,
I am able to reproduce this with the following test case where `TimeoutException` is not retried:
```
    public class TimeoutTest
    {
        [Fact]
        public async Task TimeoutRaisesTimeoutException()
        {
            // Arrange
            AWSConfigs.LoggingConfig.LogTo = LoggingOptions.Console;

            using var client = new AmazonSimpleSystemsManagementClient(
                new BasicAWSCredentials("test", "test"),
                new AmazonSimpleSystemsManagementConfig
            {
                ServiceURL = "http://240.0.0.0/",
                Timeout = TimeSpan.FromSeconds(1)
            });

            // Assert
            await Assert.ThrowsAsync<TimeoutException>(() =>
                client.GetParameterAsync(new GetParameterRequest
                {
                    Name = "test-param",
                    WithDecryption = false
                }));
        }
    }
```

**Comment by shirlik** [comment] 2021-09-06 06:55
Hi @ashishdhingra  , this is the configuration we tested :

  "AWSS3Config": {
    "MaxErrorRetry": 3,
    "Timeout": 200
  }
and like @pworkpop mentioned we get Exception BUT without retry attempts ,when can we expect fix?

**Comment by pworkpop** [comment] 2021-09-07 20:18
Please use http://240.0.0.0/ to reproduce issue. This is an unreachable IP to simulate NAT/packet loss/network issue between client and AWS API. This is needed for reproduction only as obviously we don't use ServiceUrl in production. Otherwise you need a firewall setup to drop packets to reproduce.

**Comment by ashishdhingra** [comment] 2021-09-07 20:46
> @ashishdhingra Please use http://240.0.0.0/ to reproduce issue. This is an unreachable IP to simulate NAT/packet loss/network issue between client and AWS API. This is needed for reproduction only as obviously we don't use ServiceUrl in production. Otherwise you need a firewall setup to drop packets to reproduce. Setting timeout to 1 second is to not wait for 60s for this test.

@pworkpop Using `http://240.0.0.0/` appears to retry for me on `Windows 10`:
```
EnvironmentVariableInternalConfiguration 1|2021-09-07T13:27:21.427Z|INFO|The environment variable AWS_ENABLE_ENDPOINT_DISCOVERY was not set with a value.
EnvironmentVariableInternalConfiguration 2|2021-09-07T13:27:21.447Z|INFO|The environment variable AWS_MAX_ATTEMPTS was not set with a value.
EnvironmentVariableInternalConfiguration 3|2021-09-07T13:27:21.447Z|INFO|The environment variable AWS_RETRY_MODE was not set with a value.
EnvironmentVariableInternalConfiguration 4|2021-09-07T13:27:21.448Z|INFO|The environment variable AWS_EC2_METADATA_SERVICE_ENDPOINT was not set with a value.
EnvironmentVariableInternalConfiguration 5|2021-09-07T13:27:21.448Z|INFO|The environment variable ...
...
AWSSDKUtils 12|2021-09-07T13:27:21.605Z|INFO|Process started
ProcessAWSCredentials 13|2021-09-07T13:27:25.389Z|INFO|Process ends with exitcode - 0
RegionFinder 14|2021-09-07T13:27:25.457Z|INFO|Unable to find exact matched region in endpoint 240.0.0.0
RegionFinder 15|2021-09-07T13:27:25.526Z|INFO|Unable to find fuzzy matched region in endpoint 240.0.0.0
AmazonSimpleSystemsManagementClient 16|2021-09-07T13:27:25.765Z|ERROR|An exception of type HttpRequestException was handled in ErrorHandler. --> System.Net.Http.HttpRequestException: A socket operation was attempted to an unreachable network. (240.0.0.0:80)
 ---> System.Net.Sockets.SocketException (10051): A socket operation was attempted to an unreachable network.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
AmazonSimpleSystemsManagementClient 17|2021-09-07T13:27:25.828Z|INFO|HttpRequestException making request GetParameterRequest to http://240.0.0.0/. Attempting retry 1 of 4.
AmazonSimpleSystemsManagementClient 18|2021-09-07T13:27:26.262Z|ERROR|An exception of type HttpRequestException was handled in ErrorHandler. --> System.Net.Http.HttpRequestException: A socket operation was attempted to an unreachable network. (240.0.0.0:80)
...
...
AmazonSimpleSystemsManagementClient 19|2021-09-07T13:27:26.272Z|INFO|HttpRequestException making request GetParameterRequest to http://240.0.0.0/. Attempting retry 2 of 4.
AmazonSimpleSystemsManagementClient 20|2021-09-07T13:27:27.901Z|ERROR|An exception of type HttpRequestException was handled in ErrorHandler. --> System.Net.Http.HttpRequestException: A socket operation was attempted to an unreachable network. (240.0.0.0:80)
...
...
AmazonSimpleSystemsManagementClient 21|2021-09-07T13:27:27.911Z|INFO|HttpRequestException making request GetParameterRequest to http://240.0.0.0/. Attempting retry 3 of 4.
AmazonSimpleSystemsManagementClient 22|2021-09-07T13:27:34.330Z|ERROR|An exception of type HttpRequestException was handled in ErrorHandler. --> System.Net.Http.HttpRequestException: A socket operation was attempted to an unreachable network. (240.0.0.0:80)
...
...
AmazonSimpleSystemsManagementClient 23|2021-09-07T13:27:34.339Z|INFO|HttpRequestException making request GetParameterRequest to http://240.0.0.0/. Attempting retry 4 of 4.
AmazonSimpleSystemsManagementClient 24|2021-09-07T13:27:59.965Z|ERROR|An exception of type HttpRequestException was handled in ErrorHandler. --> System.Net.Http.HttpRequestException: A socket operation was attempted to an unreachable network. (240.0.0.0:80)
...
...
AmazonSimpleSystemsManagementClient 25|2021-09-07T13:27:59.969Z|ERROR|HttpRequestException making request GetParameterRequest to http://240.0.0.0/. Attempt 5. --> System.Net.Http.HttpRequestException: A socket operation was attempted to an unreachable network. (240.0.0.0:80)
 ---> System.Net.Sockets.SocketException (10051): A socket operation was attempted to an unreachable network.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
```

However, on Mac (Catalina, 10.15.7) with same `dotnet --version` as `5.0.400` appears to reproduce the issue:
```
UserCrypto 1|2021-09-07T13:40:23.266Z|INFO|UserCrypto is not supported.  This may be due to use of a non-Windows operating system or Windows Nano Server, or the current user account may not have its profile loaded. Unable to load shared library 'Crypt32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libCrypt32.dll, 1): image not found
EnvironmentVariableInternalConfiguration 2|2021-09-07T13:40:23.441Z|INFO|The environment variable AWS_ENABLE_ENDPOINT_DISCOVERY was not set with a value.
EnvironmentVariableInternalConfiguration 3|2021-09-07T13:40:23.441Z|INFO|The environment variable AWS_MAX_ATTEMPTS was not set with a value.
EnvironmentVariableInternalConfiguration 4|2021-09-07T13:40:23.442Z|INFO|The environment variable AWS_RETRY_MODE was not set with a value.
EnvironmentVariableInternalConfiguration 5|2021-09-07T13:40:23.442Z|INFO|The environment variable AWS_EC2_METADATA_SERVICE_ENDPOINT was not set with a value.
EnvironmentVariableInternalConfiguration 6|2021-09-07T13:40:23.443Z|INFO|The environment variable AWS_EC2_METADATA_SERVICE_ENDPOINT_MODE was not set with a value.
ProfileInternalConfiguration 7|2021-09-07T13:40:23.445Z|INFO|There is no endpoint_discovery_enabled set in the profile named 'default' in store Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain
ProfileInternalConfiguration 8|2021-09-07T13:40:23.445Z|INFO|There is no retry_mode set in the profile named 'default' in store Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain
ProfileInternalConfiguration 9|2021-09-07T13:40:23.445Z|INFO|There is no max_attempts set in the profile named 'default' in store Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain
ProfileInternalConfiguration 10|2021-09-07T13:40:23.445Z|INFO|There is no ec2_metadata_service_endpoint set in the profile named 'default' in store Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain
ProfileInternalConfiguration 11|2021-09-07T13:40:23.445Z|INFO|There is no ec2_metadata_service_endpoint_mode set in the profile named 'default' in store Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain
AWSSDKUtils 12|2021-09-07T13:40:23.529Z|INFO|Starting a process with the following ProcessInfo: UseShellExecute - False RedirectStandardError - True, RedirectStandardOutput - True, CreateNoWindow - True
AWSSDKUtils 13|2021-09-07T13:40:23.545Z|INFO|Process started
ProcessAWSCredentials 14|2021-09-07T13:40:28.320Z|INFO|Process ends with exitcode - 0
RegionFinder 15|2021-09-07T13:40:28.410Z|INFO|Unable to find exact matched region in endpoint 240.0.0.0
RegionFinder 16|2021-09-07T13:40:28.515Z|INFO|Unable to find fuzzy matched region in endpoint 240.0.0.0
AmazonSimpleSystemsManagementClient 17|2021-09-07T13:40:29.646Z|ERROR|An exception of type TimeoutException was handled in ErrorHandler. --> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
AmazonSimpleSystemsManagementClient 18|2021-09-07T13:40:29.688Z|ERROR|TimeoutException making request GetParameterRequest to http://240.0.0.0/. Attempt 1. --> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
```

So there appears to be different behavior on Windows Vs Mac.

**Comment by pworkpop** [comment] 2021-09-07 22:21
@ashishdhingra happy that you're able to reproduce this - possibly same on linux - we use Alpine for our ECS tasks.

**Comment by ashishdhingra** [comment] 2021-09-16 16:05
Fixed in [AWSSDK.Core 3.7.3.6](https://www.nuget.org/packages/AWSSDK.Core/3.7.3.6)

**Closed by ashishdhingra** 2021-09-16 16:05 UTC
Labels: bug, module/sdk-core, A, queued
