### ISSUE TITLE
AWSPowerShell—New/Update-CfnStack Cannot Handle Nulls Parameter Values from Get-CfnStack

### ISSUE THREAD

**Issue by bgshacklett** [aws/aws-sdk-net#611] opened 2017-04-07 04:41 UTC
# Summary
Calling `Get-CfnStack` and piping to `Select-Object -ExpandProperty Parameters` will return a collection of Parameter objects which may have null values for the ParameterValue property. If this collection is passed in to the `Parameter` parameter on `New-CfnStack` or `Update-CfnStack` an error will be thrown:

Example:
```
Update-CFNStack : Invalid input for parameter key InternalRecordName. Need to
specify either usePreviousValue as true or a value for the parameter
At line:1 char:1
+ Update-CFNStack -Region us-east-2 -StackName bgs-test-windows2012r2 - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Amazon.PowerShe...eCFNStackCm
   dlet:UpdateCFNStackCmdlet) [Update-CFNStack], InvalidOperationException
    + FullyQualifiedErrorId : Amazon.CloudFormation.AmazonCloudFormationExcept
   ion,Amazon.PowerShell.Cmdlets.CFN.UpdateCFNStackCmdlet
```

# Steps to Reproduce
1. Launch a new stack in CloudFormation. Ensure that some of the parameters are empty.
2. Retrieve the parameter configuration for the stack:
`$params = Get-CfnStack -Region $region -StackName $stackName | Select-Object -ExpandProperty Parameters`
3. Attempt to update the stack:
`Update-CfnStack -Region $region -StackName $stackName -TemplateBody $templateBody -Parameter $params`

## Expected Behavior
The stack should be updated with the new template contents

## Actual Behavior
The `Update-CFNStack` command will complain about any parameters in the `$params` collection which are null.

# Additional Information
If the parameters in the `$params` collection are set to an empty string (`$params[$badParamIndex] = ''`) the stack update will succeed.

I see two possible solutions:
1. Return an empty string for empty parameters instead of null in the `ParameterValue` property of the `[Amazon.CloudFormation.Model.Parameter]` returned from the `Get-CfnStack` command.
2. Allow the `New-CfnStack` and `Update-CfnStack` commands to cast null values in `[Parameter]` objects to an empty or unset value of whatever type is expected.

I'm inclined toward recommending option 1, since the `New-CfnStack` and `Update-CfnStack` commands are currently able to handle an empty string as the parameter value.

**Comment by steveataws** [comment] 2017-04-07 16:43
Thanks for the detailed write up.

I've marked this as feature request for now, since as a team we need to discuss where this change should potentially be made. Given that the cmdlets use the underlying AWS SDK for .NET to make all calls to service apis, I'm fairly sure this could be reproduced with just an SDK app making the calls, so perhaps this is something we might want to fix there. Or as you suggest, we could update the cmdlets to trim out null parameter values (provided this doesn't cause side effects such as the service then deleting the parameter as it wasn't present in the input set -- we'll need to check docs etc).

Anyway, we'll discuss and come up with a plan and then update the issue with details.

**Comment by bgshacklett** [comment] 2017-04-07 20:18
Thanks for the quick response! I'll leave it in your capable hands.

**Comment by vellozzi** [comment] 2017-05-04 17:18
This feature request has been added to our backlog.

**Closed by vellozzi** 2017-05-04 17:18 UTC
Labels: Feature Request
