### ISSUE TITLE
Misleading error when bucket is empty

### ISSUE THREAD

**Issue by gkasa** [aws/aws-sdk-net#299] opened 2016-01-21 15:47 UTC
When executing a `client.ListObjects` against an empty bucket I got an exception with an `Access denied` message. After I put an object in the bucket - without changing anything else whatsoever - the error didn't appear anymore.

**Comment by PavelSafronov** [comment] 2016-01-21 18:03
That is strange behavior. I tried reproducing this issue with the below code and was unable to encounter the error. Can you try reproducing your error with a similar stand-alone bit of code?

```
var creds = new StoredProfileAWSCredentials("test-creds");
var region = RegionEndpoint.USWest2;
using(var client = new AmazonS3Client(creds, region))
{
	var bucketName = "test-299-bucket-" + DateTime.Now.ToFileTime();
	client.PutBucket(bucketName);
	try
	{
		client.ListObjects(bucketName);
		Console.WriteLine("Expected exception, none caught!");
	}
	catch(Exception e)
	{
		Console.WriteLine("Exception! {0}", e.Message);
	}

	var key = "test.txt";
	client.PutObject(new PutObjectRequest
	{
		BucketName = bucketName,
		Key = key,
		ContentBody = "test"
	});
	client.ListObjects(bucketName);

	client.DeleteObject(bucketName, key);
	client.DeleteBucket(bucketName);
}
```

**Comment by PavelSafronov** [comment] 2016-01-21 18:33
Also, are you using an IAM user, temporary credentials, or have an IAM policy configured that may be impacting you?

**Comment by gentian-kasa** [comment] 2016-01-22 11:43
The credentials are of a customer I'm working with, so I don't have much info regarding them. The code you used is similar to the one I used, with the only exception being the region. I don't know if this is relevant.

**Comment by PavelSafronov** [comment] 2016-01-22 20:26
This sounds like a permission issue with the S3 service itself. Please post this question to the [S3 Forum](https://forums.aws.amazon.com/forum.jspa?forumID=24), they should be able to help you track down the issue. It would also be helpful if you can contact your customer and get the policy document for the credentials you are using, as it's likely this is an issue caused by an incorrect policy  configuration.

**Comment by gentian-kasa** [comment] 2016-01-23 23:48
I will. Thank you

**Comment by gokarnm** [comment] 2016-01-26 23:35
Closing this issue, please reopen if this turn out to be an SDK issue.

**Closed by gokarnm** 2016-01-26 23:35 UTC
Labels: Question
