### ISSUE TITLE
HashSet duplicate key exception when setting up region endpoints

### ISSUE THREAD

**Issue by kewal-sarode** [aws/aws-sdk-net#2097] opened 2022-09-05 11:35 UTC
### Describe the bug

After upgrading AWSSDK.Core to 3.7.12.11 and all other packages specific to AWS services to compatible versions with AWSSDK.Core, we've begun seeing the following exception 

```
Exception=System.ArgumentException: An item with the same key has already been added. Key: System.Collections.Generic.HashSet`1[System.String]\
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)\
   at Amazon.Internal.RegionEndpointV3.ServiceMap.Add(String serviceName, Endpoint endpoint, HashSet`1 variants)\
   at Amazon.Internal.RegionEndpointV3.AddVariantEndpointsToServiceMap(JsonData mergedEndpoint, String regionName, String serviceName, Dictionary`2 mergedVariants)\
   at Amazon.Internal.RegionEndpointV3.AddServiceToMap(JsonData service, String serviceName)\
   at Amazon.Internal.RegionEndpointV3.ParseAllServices()\
   at Amazon.Internal.RegionEndpointV3.GetEndpointForService(String serviceName, HashSet`1 variants)\
   at Amazon.Runtime.ClientConfig.set_RegionEndpoint(RegionEndpoint value)
```
Let me know if you need any additional details.

### Expected Behavior

We should not get above exception.

### Current Behavior

```
Exception=System.ArgumentException: An item with the same key has already been added. Key: System.Collections.Generic.HashSet`1[System.String]\
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)\
   at Amazon.Internal.RegionEndpointV3.ServiceMap.Add(String serviceName, Endpoint endpoint, HashSet`1 variants)\
   at Amazon.Internal.RegionEndpointV3.AddVariantEndpointsToServiceMap(JsonData mergedEndpoint, String regionName, String serviceName, Dictionary`2 mergedVariants)\
   at Amazon.Internal.RegionEndpointV3.AddServiceToMap(JsonData service, String serviceName)\
   at Amazon.Internal.RegionEndpointV3.ParseAllServices()\
   at Amazon.Internal.RegionEndpointV3.GetEndpointForService(String serviceName, HashSet`1 variants)\
   at Amazon.Runtime.ClientConfig.set_RegionEndpoint(RegionEndpoint value)\
   at Dome9.Amazon.EC2.AwsEc2Wrapper.CreateAwsConfig(CloudRegion region)\
   at Dome9.Amazon.AwsBaseWrapper`3.CreateClientAsync(CloudRegion region)\
   at Dome9.Amazon.AwsBaseWrapper`3.InvokeAwsRequest[TResult](Func`2 func, CloudRegion region, Int32 retriesAllowed, List`1 excludedErrorCodes)\
   at Dome9.Amazon.EC2.AwsEc2Wrapper.DescribeSecurityGroupsAsync(CloudRegion region, List`1 securityGroupIds)
```

### Reproduction Steps

N/A

### AWS .NET SDK and/or Package version used

AWSSDK.Core 3.7.12.11
and compatible packages for all other services (AWSSDK.EC2 3.7.78.3, WSSDK.S3 3.7.9.28 etc)

### Targeted .NET Platform

.NET 6, .NET Standard 2.0

### Operating System and version

AmazonLinux (AWS Lambda)

**Comment by kewal-sarode** [comment] 2022-09-05 12:42
Steps to reproduce is given in below link
https://github.com/aws/aws-sdk-net/issues/1939#issuecomment-983044534

**Comment by ashishdhingra** [comment] 2022-09-06 15:57
Duplicate of https://github.com/aws/aws-sdk-net/issues/1939. Please follow up on the the other issue which is prioritized and being worked upon by the team.

**Closed by ashishdhingra** 2022-09-06 15:57 UTC
Labels: bug, needs-triage, module/sdk-core
