### ISSUE TITLE
ListContacts turns out to be 403 error

### ISSUE THREAD

**Issue by sandycs-protoss** [aws/aws-sdk-net#2096] opened 2022-09-05 04:17 UTC
### Describe the bug

All the funciton in SimpleEmailV2 runs Ok except ListContacts.
When I tried ListContacts, I got the response that the request signature does not match. 
However I've tried getcontact/getcontactlist/updatecontactlist and all of them worked perfect.
So I think the id and the key are both OK to use.

About the permissions associated with the id/key, I'm pretty sure if I could do "GetContact", I would definately use ListContacts.

Further more, I could easily use the ListContacts API on aws console with the same id/key.

### Expected Behavior

client.ListContacts should return the Contacts list as the document said.

### Current Behavior

"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."

I've checked and confirm the secret access key is right.

### Reproduction Steps

1. AmazonSimpleEmailServiceV2Client sesv2 = new AmazonSimpleEmailServiceV2Client(awsAccessKeyId, awsSecretAccessKey, RegionEndpoint.USEast1);
2.ListContactsRequest listContactsRequest = new ListContactsRequest();
listContactsRequest.PageSize = 50;
listContactsRequest.ContactListName = "Calceus_Customers";
3.ListContactsResponse listContactsResponse =  sesv2.ListContacts(listContactsRequest);

*I've tried to save the id/key in the aws profile and it still got the same error. 

### AWS .NET SDK and/or Package version used

AWSSDK.SimpleEmailV2 3.7.123

### Targeted .NET Platform

.Net Framework 4.7.2

### Operating System and version

Windows 10

**Comment by sandycs-protoss** [comment] 2022-09-06 02:05
This bug was also occured in Java SDK.

**Comment by ashishdhingra** [comment] 2022-09-06 22:12
Duplicate of https://github.com/aws/aws-sdk-net/issues/1793.

**Comment by ashishdhingra** [comment] 2022-09-06 22:30
This is a cross SDK service issue tracked via https://github.com/aws/aws-sdk/issues/307. Closing this to avoid duplication. The other issue #1793 could remain open.

**Closed by ashishdhingra** 2022-09-06 22:30 UTC
Labels: bug, duplicate, module/sdk-generated
