### ISSUE TITLE
simpleemailv2 not exposing Source

### ISSUE THREAD

**Issue by rogerfar** [aws/aws-sdk-net#1711] opened 2020-09-16 20:34 UTC
Currently in the simpleemailv2 the Source property on SendEmailRequest is not available.

Original:
https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SimpleEmailV2/TSendEmailRequest.html

v2:
https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SimpleEmailV2/TSendEmailRequest.html

Currently there is no way to specify the from name in an email request with v2.

**Comment by ashishdhingra** [comment] 2020-09-18 16:15
Hi @rogerfar,

Good morning.

If you look at the code for [SendEmailRequest](https://github.com/aws/aws-sdk-net/blob/de74d6ab1334cfbd3452a70fbdba8317d5e9f2e6/sdk/src/Services/SimpleEmailV2/Generated/Model/SendEmailRequest.cs#L56), there is a property named [FromEmailAddress](https://github.com/aws/aws-sdk-net/blob/de74d6ab1334cfbd3452a70fbdba8317d5e9f2e6/sdk/src/Services/SimpleEmailV2/Generated/Model/SendEmailRequest.cs#L201). Could you please share your environment information in the following format if this is still an issue in the latest AWS .NET SDK along with the code snippet?



## Expected Behavior



## Current Behavior






## Possible Solution



## Steps to Reproduce (for bugs)





## Context



## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

Thanks,
Ashish

**Comment by rogerfar** [comment] 2020-09-18 16:48
Hello Ashish,

That is correct, but where do I specify the **name**? Before you could set the `source` property to: `My Name <name@domain.com>`, in v2 there is no option to specify the name.

**Comment by ashishdhingra** [comment] 2020-09-18 17:30
@rogerfar Could you please confirm if using the same format in FromEmailAddress property works? If not, we might need to seek inputs from SES V2 support to provide input since this property is limited by the Service API.

Thanks,
Ashish

**Comment by rogerfar** [comment] 2020-09-24 22:21
Yes this seems to be the case.

When I set the same format in the `FromEmailAddress` field it will accept the `My Name <name@domain.com>` format.

This is not clear from documentation though.

The v2 docs state for `FromEmailAddress`:

> Gets and sets the property FromEmailAddress.The email address that you want to use as the "From" address for the email. The address that you specify has to be verified.

The v1 docs state for `Source`:
> The email address that is sending the email. This email address must be either individually verified with Amazon SES, or from a domain that has been verified with Amazon SES. For information about verifying identities, see the Amazon SES Developer Guide.If you are sending on behalf of another user and have been permitted to do so by a sending authorization policy, then you must also specify the SourceArn parameter. For more information about sending authorization, see the Amazon SES Developer Guide.Amazon SES does not support the SMTPUTF8 extension, as described in RFC6531. For this reason, the local part of a source email address (the part of the email address that precedes the @ sign) may only contain 7-bit ASCII characters. If the domain part of an address (the part after the @ sign) contains non-ASCII characters, they must be encoded using Punycode, as described in RFC3492. The sender name (also known as the friendly name) may contain non-ASCII characters. These characters must be encoded using MIME encoded-word syntax, as described in RFC 2047. MIME encoded-word syntax uses the following form: =?charset?encoding?encoded-text?=.


The latter explicitly mentions the "friend name" part of the email can be added, but does it not present in the v2 documentation.

**Comment by ashishdhingra** [comment] 2020-09-24 22:27
@rogerfar Thanks for confirming the issue. I will close this issue. Please use the "Provide Feedback" link on the bottom of the documentation page to submit your feedback to add such a note in the new documentation.

**Closed by ashishdhingra** 2020-09-24 22:27 UTC
Labels: guidance, module/sdk-core, response-requested
