### ISSUE TITLE
Cannot query DynamoDB table with partition key only using QueryAsync

### ISSUE THREAD

**Issue by lorisleitner** [aws/aws-sdk-net#1898] opened 2021-08-10 17:53 UTC
## Description
I'm trying to query a DynamoDB table using the .NET SDK. I'm using `DynamoDBContext.QueryAsync<>`.
The data model looks like this:
```C#
[DynamoDBTable("prices")]
public class Price
{
    [DynamoDBHashKey("id")]
    public String Id { get; set; }

    [DynamoDBProperty("symbol")]
    public string Symbol { get; set; }

    [DynamoDBProperty("expdate")]
    public long ExpDate { get; set; }
}
```
Note that there isn't a sort key defined as the table does not have one.

When trying to query the table like this, I'm getting an `InvalidOperationException`
`q = db.QueryAsync<Price>("ID");`

`System.InvalidOperationException: 'Must have one range key or a GSI index defined for the table prices'`

Trying to query the table using `FromQueryAsync` will work:
```C#
var query = new QueryOperationConfig()
{
    KeyExpression = new Expression()
    {
        ExpressionStatement = "id = :id",
        ExpressionAttributeValues = new Dictionary<string, DynamoDBEntry>()
        {
            {":id", "ID" }
        }
    },
};

var q = db.FromQueryAsync<Price>(query);
...
```

I expect `QueryAsync` to work the same as `FromQueryAsync`.

## Reproduction Steps
See above

### Logs
StackTrace
```
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.ComposeQueryFilterHelper(DynamoDBFlatConfig currentConfig, Document hashKey, IEnumerable`1 conditions, ItemStorageConfig storageConfig, List`1& indexNames)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.ComposeQueryFilter(DynamoDBFlatConfig currentConfig, Object hashKeyValue, IEnumerable`1 conditions, ItemStorageConfig storageConfig, List`1& indexNames)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.ConvertQueryByValue[T](Object hashKeyValue, IEnumerable`1 conditions, DynamoDBOperationConfig operationConfig, ItemStorageConfig storageConfig)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.QueryAsync[T](Object hashKeyValue, DynamoDBOperationConfig operationConfig)
   at ccctest.Program.<Main>d__0.MoveNext() in C:\Users\loris\source\repos\ccctest\ccctest\Program.cs:line 44
```

### Environment

* SDK Version: 3.7.0.50
* Package Version: 3.7.0.50
* OS Info: Windows 10 
* Build Environment: Visual Studio
* Targeted .NET Platform: .NET Core 3.1 

## Resolution
I hope this is a real bug and not a misuse by me.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment] 2021-08-10 23:50
Reproducible using the following code:
```C#
using Amazon;
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.DataModel;
using Amazon.DynamoDBv2.DocumentModel;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace DynamoDBQuery_Issue1898
{
    class Program
    {
        static void Main(string[] args)
        {
            RegionEndpoint regionEndpoint = RegionEndpoint.USEast1;
            AmazonDynamoDBClient amazonDynamoDBClient = new AmazonDynamoDBClient(regionEndpoint);
            DynamoDBContext dynamoDBContext = new DynamoDBContext(amazonDynamoDBClient);

            List<Price> prices = ExecuteQueryAsync(dynamoDBContext, "121").Result;
            //List<Price> prices = ExecuteFromQueryAsync(dynamoDBContext, "121").Result;

            foreach (var price in prices) Console.WriteLine(price);
        }

        private static async Task<List<Price>> ExecuteQueryAsync(DynamoDBContext dynamoDBContext, string id)
        {
            var query = dynamoDBContext.QueryAsync<Price>(id);

            var prices = new List<Price>();

            do
            {
                List<Price> nextSet = await query.GetNextSetAsync();
                prices.AddRange(nextSet);
            } while (!query.IsDone);

            return prices;
        }

        private static async Task<List<Price>> ExecuteFromQueryAsync(DynamoDBContext dynamoDBContext, string id)
        {
            var query = new QueryOperationConfig()
            {
                KeyExpression = new Expression()
                {
                    ExpressionStatement = "id = :id",
                    ExpressionAttributeValues = new Dictionary<string, DynamoDBEntry>()
                    {
                        {":id", id }
                    }
                }
            };


            var fromQueryResult = dynamoDBContext.FromQueryAsync<Price>(query);

            var prices = new List<Price>();

            do
            {
                List<Price> nextSet = await fromQueryResult.GetNextSetAsync();
                prices.AddRange(nextSet);
            } while (!fromQueryResult.IsDone);

            return prices;
        }
    }

    [DynamoDBTable("prices")]
    public class Price
    {
        [DynamoDBHashKey("id")]
        public String Id { get; set; }

        [DynamoDBProperty("symbol")]
        public string Symbol { get; set; }

        [DynamoDBProperty("expdate")]
        public long ExpDate { get; set; }

        public override string ToString()
        {
            return $"[Price] Id: {Id}, Symbol: {Symbol}, ExpDate: {ExpDate}";
        }
    }
}
```

**Comment by MDanialSaleem** [comment] 2021-12-09 17:48
According to the [docs](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DotNetDynamoDBContext.html#w20aac17c17c21c35c31) this is expected behavior and not a bug. 

> If your table has a simple primary key (partition key), you can't use the Query method. Instead, you can use the Load method and provide the partition key to retrieve the item.

**Comment by guilhermecaixeta** [comment] 2022-09-13 19:09
And is it possible to query/load a table without pass the sort key? Because I tried in many ways and always return some error. Like 

```
 "message": "Unable to convert range key value for property Timestamp",
    "stack_trace": [
      "at Amazon.DynamoDBv2.DataModel.DynamoDBContext.MakeKey(Object hashKey, Object rangeKey, ItemStorageConfig storageConfig, DynamoDBFlatConfig flatConfig) in D:\\JenkinsWorkspaces\\trebuchet-stage-release\\AWSDotNetPublic\\sdk\\src\\Services\\DynamoDBv2\\Custom\\DataModel\\ContextInternal.cs:line 971",
```

**Comment by BryanCrotaz** [comment] 2023-05-21 13:32
> According to the [docs](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DotNetDynamoDBContext.html#w20aac17c17c21c35c31) this is expected behavior and not a bug.
> 
> > If your table has a simple primary key (partition key), you can't use the Query method. Instead, you can use the Load method and provide the partition key to retrieve the item.

Load doesn't work either. It doesn't provide a KeyCondition so the call fails.

**Comment by bhoradc** [comment] 2024-10-04 17:19
Closing this issue as it is not a bug, but rather an expected behavior as previously discussed in the [comment](https://github.com/aws/aws-sdk-net/issues/1898#issuecomment-990081352).

**Closed by bhoradc** 2024-10-04 17:19 UTC
Labels: bug, dynamodb, p2, queued, low-effort
