### ISSUE TITLE
DynamoDB dynamodb:DescribeTable Error when using OverrideTableName

### ISSUE THREAD

**Issue by ayongbannayan** [aws/aws-sdk-net#1421] opened 2019-10-07 18:01 UTC
I'm using the object persistent model, the name of the DynamoDB table is also dynamic.  My queries  currently function however when using X-Ray I'm noticing an exception that is occurring after the query.

In my object I am not using the DynamoDBTable attribute because the table name is dynamic. I'm using the DynamoDBOperationConfig and setting the OverrideTableName property.

When excuting QueryAsync<T> the query returns results but X-Ray shows the following

![Screen Shot 2019-10-07 at 1 44 25 PM](https://user-images.githubusercontent.com/49486285/66335759-aee91880-e909-11e9-8769-cccc2f8d4271.png)

The error that is occurring is ...not authorized to perform: dynamodb:DescribeTable on resource: arn:aws:dynamodb:ca-central-1:xxxxxxxxx:table/T where T is the name of the object and not the table.
```
using (DynamoDBContext context = new DynamoDBContext(AmazonDynamoDB))
{
    DynamoDBOperationConfig config = new DynamoDBOperationConfig
    {
        OverrideTableName = “TableName”,
        IndexName = “IndexName”
    };

    AsyncSearch<ObjectType> query = context.QueryAsync<ObjectType>(“HashKey”, config);
    IEnumerable<ObjectType> objects = await query.GetRemainingAsync();
}
```
I'm not sure how to handle this exception. I've tried to set the DynamoDBTable however the error simply changes to the name I provide instead of the objects Name. Not sure what else I'm missing.

Regards
Artin

**Comment by klaytaybai** [comment] 2019-10-08 18:07
Hi @Artin-ST, thanks for reporting this.  I think it is root caused by a known bug.  I'll look into this more soon and add more details as I go along.

**Comment by harshghorpade** [comment] 2020-09-05 06:46
Hello, any update on this bug ? I can still reproduce this exact same issue with AWSSDK.DynamoDBv2 version 3.3.105.26 on .NET Core 3.1 Project.

**Comment by AdalbertKhoolsaat** [comment] 2020-09-15 16:13
Hey there, in the exact same manner as the OP I found out that I suffer from this bug as well.
At the company I work for we are considering using X-Ray (as part of CloudWatch ServiceLens), and we found this bug with the very first project we started monitoring (Using v3.3.105.34 on .NET Core 3.1).

Considering that the OPM is used quite generally around here , this issue is definitely pretty widespread.

**Comment by ashishdhingra** [comment] 2021-03-11 21:26
Breaking change as per https://github.com/aws/aws-sdk-net/issues/1218#issuecomment-660391518

**Comment by ashishdhingra** [comment] 2021-03-11 21:28
Also refer https://github.com/aws/aws-sdk-net/issues/1448 and validate the scenario if this issue is fixed in next major release.

**Comment by Kralizek** [comment] 2022-03-14 10:11
@ashishdhingra Both this one and #1448 are closed now. Could you please reopen one of them to make sure the error is tracked?

**Comment by ashovlin** [comment] 2024-08-14 20:35
In our next major version of the SDK (development underway now, see #3209), we've separated the hierarchy between `DynamoDBContextConfig` and `DynamoDBOperationConfig`. You will no longer be able to pass an _operation-level_ config in to the _context-level_ constructor, where `OverrideTableName` is not honored.

```csharp
var dynamoDbOperationConfig = new DynamoDBOperationConfig
{
    OverrideTableName = _tableName            
};

var context = new DynamoDBContext(_client, dynamoDbOperationConfig);  // no longer possible in V4   
```

We didn't want to take a single override table name as an input to the context object, since one can reuse a context object with multiple tables. If you do want to override table names on an application-level, you can use the `TableAlias` or `TypeMapping` collections on `AWSConfigsDynamoDB.Context`.

We'll close this once V4 packages ship with this change. This addresses #1218 which we de-duped into this one.

---

Revisiting this issue and #1448 which was also de-duped here. These appear to be both be overriding the table name via a `DynamoDBOperationConfig` on a query. This is working as expected when I attempt to reproduce with AWSSDK.DynamoDBv2 3.7.400.5. Let us know if you're still seeing an issue on V3.

```csharp
var config = new DynamoDBOperationConfig
{
    OverrideTableName = “TableName”,
};

var query = context.QueryAsync<ObjectType>(“HashKey”, config);
```

**Comment by bhoradc** [comment] 2024-09-13 16:48
Hello @ayongbannayan, 

These changes are available in .NET 4 Preview. Kindly track this [issue](https://github.com/aws/aws-sdk-net/issues/3362) for when this change would go GA. 

Will go ahead and close this out. Thank you. 

Regards, 
Chaitanya

**Closed by bhoradc** 2024-09-13 16:48 UTC
Labels: bug, breaking-change, dynamodb, p2, queued
