### ISSUE TITLE
Amazon.Runtime.AmazonClientException: 'No RegionEndpoint or ServiceURL configured'

### ISSUE THREAD

**Issue by Cular** [aws/aws-sdk-net#1299] opened 2019-05-23 15:41 UTC
Case №1
## Expected Behavior
RegisteredAccounts.json file contains info about region after configuring via [AWS Explorer Tool](https://aws.amazon.com/ru/visualstudio/). There is no info about region (in RegisteredAccounts, but MiscSettings.json contains **lastselectedregion** ) for now. Or sdk get region info from another files.
path: 
```
C:\Users\%userprofile%\AppData\Local\AWSToolkit\RegisteredAccounts.json
```

## Current Behavior
When call **default** constructor for AmazonLamdaClient: Amazon.Runtime.AmazonClientException: 'No RegionEndpoint or ServiceURL configured'

## Steps to Reproduce
1. Create Console app for net core. (2.2 in my case)
1. Setup [AWS Explorer toolkit](https://aws.amazon.com/ru/visualstudio/)
2. Add new account profile with your credentials from AWS.Console with **default** profile name.
3. Check file for encrypted credentials with **default** profile name.
```
C:\Users\%userprofile%\AppData\Local\AWSToolkit\RegisteredAccounts.json 
```
4. Run code:
``` c#
    class Program
    {
        static void Main(string[] args)
        {
            using (var client = new AmazonLambdaClient())
            {
                InvokeRequest request = new InvokeRequest
                {
                    FunctionName = "myfunction",
                    InvocationType = InvocationType.RequestResponse,
                    Payload = "",
                    LogType = LogType.Tail
                };

                var response = client.InvokeAsync(request).GetAwaiter().GetResult();

                Console.WriteLine(JsonConvert.SerializeObject(response));
            }
        }
    }
```
![image](https://user-images.githubusercontent.com/26927442/58262508-15b6cc80-7d83-11e9-83e9-5e1c95b4dfdd.png)

Case №2 (When you rename or delete RegisteredAccounts.json file.)
## Expected Behavior
Credentials and configs reads from files and **used both** of them for default:
```
C:\Users\%userprofile%\.aws\credentials
C:\Users\%userprofile%\.aws\config
```

## Current Behavior
When call **default** constructor for AmazonLamdaClient.: Amazon.Runtime.AmazonClientException: 'No RegionEndpoint or ServiceURL configured'
After some digging found next:
![image](https://user-images.githubusercontent.com/26927442/58264699-f457df80-7d86-11e9-9582-1b72a48a0067.png)
Assuming problem in IniFile.cs
```c#
public bool TryGetSection(Regex sectionNameRegex, out string sectionName,
            out Dictionary<string, string> properties) 
```

## Possible Solution
WorkAround: Add to credentials file **region** param and save it.
```
C:\Users\%userprofile%\.aws\credentials
```
```
[default]
aws_access_key_id = <your_access_key>
aws_secret_access_key = <your_secret_key>
region = <your_region>
```

## Context
It happens only on local env. For cloud all works according to binded instances and roles(permissions) on creating steps.

## Your Environment

* AWSSDK.Core version used: master branch, tag 3.3.516.0
* Targeted .NET platform: .Net Core 2.2

## .NET Core Info

* .NET Core version used for development: 2.2
* Output of `dotnet --info`: 
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.102
 Commit:    96ff75a873

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.102\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  1.1.13 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009497 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.601 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

P.S. Assuming that I have missed something important and all my efforts is monkey business.

**Comment by linjmeyer** [comment] 2019-07-01 13:53
I'm seeing the same thing with our dev teams.  Devs on Mac and our production servers on EC2/Linux are able to create DynamoDB and Secrets Manager Clients using ~/.aws/ and environment variable configs but the same code on Windows results in `No RegionEndpoint or ServiceURL configured`.  We have double checked the default region is set, deleted the config and recreated using `aws configure.`

As a workaround we can create the clients by passing in the RegionEndpoint to the client's constructor we need but we'd rather not "hard code" this value.

**Comment by sage-peterwilson** [comment] 2019-08-22 14:14
Seems this sort of thing happens if you're trying to `Mock<>` the AWS class in unit tests, which makes CI builds/tests fail. For local test runs adding a region to the `~/.aws/credentials` file seems to resolve it, but it shouldn't need that IMO.

**Comment by plittlewood-rpt** [comment] 2020-01-20 16:26
Just run into the same problem here. Adding the region manually to the credentials file as suggested above resolved the problem. Bit of a pain having to add it manually though

**Comment by ashishdhingra** [comment] 2020-10-07 17:34
Hi @Cular,

Good morning.

I was going through the issue backlog and came across this one. This is a known issue where region is not read from `.aws/config` file, but instead read from `.aws/credentials` file. The issue is being tracked as part of https://github.com/aws/aws-extensions-for-dotnet-cli/issues/117. Hence, closing this issue as duplicate. 

Thanks,
Ashish

**Closed by ashishdhingra** 2020-10-07 17:34 UTC
Labels: bug, duplicate, module/sdk-core
