### ISSUE TITLE
Add Transaction for DynamoDB using Document Interfaces or Object Persistence Interface

### ISSUE THREAD

**Issue by hanslai** [aws/aws-sdk-net#1471] opened 2019-12-01 14:20 UTC
#25 has been 6 years.
There are really little document on .net or .net core.
And seems impossible to do it in Document Interfaces or Object Persistence Interface.

**Comment by klaytaybai** [comment] 2019-12-02 20:34
Thanks for voicing your interest.  I'm going to close this out as a duplicate of https://github.com/aws/aws-sdk-net/issues/1453.  If you have any more comments to add about your use case or how you would prefer the implementation to look like, please comment there.

**Closed by klaytaybai** 2019-12-02 20:35 UTC
Labels: duplicate

**Comment by dtabuenc** [comment] 2022-04-18 06:17
How hard can this possibly be? Transaction support is already in the low level library, I would assume the high level libraries are just handling type serialization and such... so how hard is it to add the transactional version of the batching methods?

**Comment by dtabuenc** [comment] 2022-04-22 03:55
For anyone looking for a workaround, you can combine the low-level api with high-level api serialization by doing something like:

```cs 
    var dynamoDbClient = new AmazonDynamoDBClient();
    var dynamoDbContext = new DynamoDBContext(dynamoDbClient);
    var item1 = new MySampleItem();
    var item2 = new MySampleItem();
    await dynamoDbClient.TransactWriteItemsAsync(new TransactWriteItemsRequest()
    {
      TransactItems = new List<TransactWriteItem>
      {
        new TransactWriteItem()
        {
          Put = new Put()
          {
            Item = dynamoDbContext.ToDocument(item1).ToAttributeMap(),
            Ta
            TableName = dynamoDbContext.GetTargetTable<MySampleItem>().TableName
          },
        },
        new TransactWriteItem()
        {
          Put = new Put()
          {
            Item = dynamoDbContext.ToDocument(item2).ToAttributeMap(),
            TableName = dynamoDbContext.GetTargetTable<MySampleItem>().TableName
          }
        },
      }
    });
```
