### ISSUE TITLE
Can't save simple DynamoDB item

### ISSUE THREAD

**Issue by rsparkyc** [aws/aws-sdk-net#106] opened 2014-05-24 04:01 UTC
I have a table called Category with 3 fields:

| Field Name | Type | Notes |
| --- | --- | --- |
| Name | String | The primary hash key |
| Description | String |  |
| PictureIds | String | will ultimately be a comma separated list of ids since I want to preserve order |

I am trying to create an initial record in the table with just a Name field populated.  The request data that I captured in fiddler is as follows:

``` json
{"TableName":"Category","Key":{"Name":{"S":"Test"}},"AttributeUpdates":{"Description":{"Action":"DELETE"},"PictureIds":{"Action":"DELETE"}},"ReturnValues":"NONE"}
```

No objects are being saved when I scan the table for all records, and nothing shows up in the AWS DynamoDB console.

**Comment by PavelSafronov** [comment] 2017-04-28 18:35
**Bug**: DynamoDBContext is used to Save an object where only the key attributes are set and all the other attributes are null AND the item does not exist in the target Table, the item creation will not happen.

**Workaround**: Include non-key data in the object.

**Service behavior**: According to the [DynamoDB documentation](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValueUpdate.html), this behavior of UpdateItem is by design. Relevant bit:
> If no item with the specified Key is found:
>  DELETE - Nothing happens; there is no attribute to delete.

**Decision**: We've looked into the relevant SDK code and the DynamoDB service protocol and haven't been able to come up with a simple, reliable fix for this issue. Considering that this is a very infrequently-encountered issue with a simple work-around, we are going to close this issue as **Won't Fix**.

**Follow-up**: if you feel that this bug should be fixed, please reply to this issue with your use-case and how this bug is impacting you, and we will reconsider this decision.

**Closed by PavelSafronov** 2017-04-28 18:35 UTC
Labels: Bug, Won't Fix

**Comment by leninator** [comment] 2019-03-14 12:29
Hello,

I have just run into this bug myself, and believe it should be fixed. As its taken me a while to figure out the underlying cause and is extremely confusing behaviour.

Consider the following poco data class...

```
    [DynamoDBTable("Users")]
    public class User
    {
        [DynamoDBHashKey]
        public string Id { get; set; }
        
        public List<Orders> Order { get; set; }
    }
```
I save an intitial copy of this by using code akin to the following.

```
        public CreateUserCommandHandler(IDynamoDBContext context)
        {
            _context = context;
        }

        public async Task HandleAsync(CreateUserCommand command)
        {
            ...

            var user = new User
            {
                Id = command.UserId
            };

            await _context.SaveAsync(user);

           ...
        }
```

Given the above code where there's a method called "SaveAsync" with data I fully expect the data to be saved. Especially when no errors are returned or exceptions occur. However behind the scenes the following request data is issued.

```
{"AttributeUpdates":{"Orders":{"Action":"DELETE"}},"Key":{"Id":{"S":"NewUser"}},"ReturnValues":"NONE","TableName":"Users"}
```

Despite SaveAsync succeeding a delete action is sent without ever creating the new object. I can't see how this is a 'won't fix' issue when this is surely a fairly common scenario where an initial resource is created and then additional parts are added later on. I understand the workaround, and by simply initialising the 'Orders' collection in the default constructor to be an empty list, save works correctly. However its extremely confusing behaviour where SaveAsync can effectively fail completely silently as far as the application is concerned. I've given it data to save, no errors have occured. I should be safe to assume that the data is stored, if it hasn't been then as far as i'm concerned the SaveAsync method has failed.

If I've asked for a method to save data and it hasn't saved i'd consider this exceptional behaviour, and even if this functionality is not fixed, i'd at least expect some sort of exception or response back from the saveAsync method explaining why.

Even further confusion is compounded by running a local instance of DynamoDb. When running the above code locally, the record is created successfully when running a local DynamoDb database with no changes other than to a local DDB instance over a remote one. Therefore there is a difference in behaviour between what amazon provides for testing and what it actually provides in the cloud.
