### ISSUE TITLE
S3: Empty Content-Encoding header

### ISSUE THREAD

**Issue by sanketsawkar** [aws/aws-sdk-net#559] opened 2017-02-18 09:28 UTC
Uploading files to S3 using PutObjectRequest or TransferUtility results in an empty Content-Encoding header being set although I am not setting one explicitly. This is being observed across file types.

![empty-content-encoding](https://cloud.githubusercontent.com/assets/16939223/23092132/4b67a0de-f5ea-11e6-98b2-be27661baae4.png)

**Comment by PavelSafronov** [comment] 2017-02-20 22:56
Thanks for reporting this. Looks like it is a service-side behavior caused by the .NET SDK [uploading a file in chunks](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html#d0e3680). I'm contacting the S3 team to find out if the Content-Encoding header should be left out if it's empty.

**Comment by sanketsawkar** [comment] 2017-02-22 04:56
Thanks for picking this up. Looking forward to the solution/next steps.

**Comment by nxnfufunezn** [comment] 2017-03-09 20:55
Any update on this?

**Comment by PavelSafronov** [comment] 2017-03-09 22:37
Nothing to report yet, sorry.

**Comment by ffpaul** [comment] 2017-03-14 21:56
Also seeing this issue.  Results in CloudFront not gzipping content because the header is set.  The [single chunk version of the link above](http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html) doesn't mention the Content-Encoding header ..  

I can subsequently go into S3 and remove the empty Content-Encoding header and CloudFront gzips the content properly.

Perhaps in single-chunk mode it can be done without that Content-Encoding header?

**Comment by sanketsawkar** [comment] 2017-03-15 04:25
Yeah, this issue gets compounded when you have a CDN that's delivering the last mile. Because compression has been enabled at the CDN (in our case), I end up seeing two Content-Encoding headers in the response, one with gzip and the other empty and the eventual output in the browser is junk.

The only way to get around it for me was to actually save the file as gzip compressed and explicitly set the content-encoding: gzip. This issue is forcing workarounds that may not be scalable. SDK implementations for other platforms/languages don't seem to have this issue.

**Comment by ffpaul** [comment] 2017-03-15 22:05
The main problem with supplying the content only in gzip format is that any browser that is not set to use compression won't be able to retrieve it.  While the majority of browsers do to the point where this is likely a non-issue, it's not the most desirable workaround.

It's working for me for now, I'm hoping the aws sdk developers will implement a fix for this soon.  :)

**Comment by samfromlv** [comment] 2017-04-10 15:01
Trying to use S3 with Azure CDN with compression enabled. Due this issue CDN caches gziped images and sends duplicate Content-Encoding headers to client, one is empty and another is gzip. As result images are not displayed on the webpage.

Please fix it.

**Comment by gokarnm** [comment] 2017-04-24 17:16
Closing, this was fixed in [AWSSDK.Core 3.3.13](https://www.nuget.org/packages/AWSSDK.Core/3.3.13).

**Closed by gokarnm** 2017-04-24 17:16 UTC
Labels: Question, Service Issue
