### ISSUE TITLE
DynamoDBContext.SaveAsync can't handle Nullable<DateTime> if NULL

### ISSUE THREAD

**Issue by dguisinger** [aws/aws-sdk-net#629] opened 2017-04-25 04:32 UTC
When using SaveAsync to save an object with a DateTime? nullable field set to null, SaveAsync completes without throwing an exception, but no data ends up in DynamoDB.

## Expected Behavior
With a nullable field, it should get insert the field as NULL into the database, just like what works with strings and json structures.

Alternatively, an exception would be nice instead of failing silently

## Context
I was trying to insert new records into DynamoDB and spent several hours trying to figure out what on earth was going on since I was getting no errors and no data in the database.

## Your Environment

* AWSSDK.Core version used: 3.3.10.3
* Service assembly and version used: DynamoDBv2  3.3.4.4
* Operating System and version:  Windows Server 2016
* Visual Studio version:  2017 CE
* Targeted .NET platform:  .NET Core 1.1

## .NET Core Info

* .NET Core version used for development: 1.1
* .NET Core version installed in the environment where application runs: 1.1
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj:

**Comment by PavelSafronov** [comment] 2017-04-25 20:11
>With a nullable field, it should get insert the field as NULL into the database, just like what works with strings and json structures.

This is not correct. Null strings or classes are **not** stored as DynamoDB NULL, they are converted to DynamoDB's [DELETE Action](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LegacyConditionalParameters.AttributeUpdates.html), thus removing their attribute values from the item in question.

Overall, DynamoDBContext only stores nulls as DynamoDB NULL values in the following two cases. In all other cases DynamoDBContext converts null to a DELETE Action.
1. If storing `Dictionary<string,T>` and the value of a given key-value-pair is null
2. If storing `List<T>` and an entry is null


If you need to explicitly set a particular attribute to DynamoDB NULL, you can use the low-level client or the Document API. The Document API is easier: first you convert your object instance to a Document by using `DynamoDBContext.ToDocument<T>`, set the required attributes equal to `DynamoDBNull.Null`, then save the resultant Document to the correct table, like this:
```
var poco = new Issue629POCO();

var table = context.GetTargetTable<Issue629POCO>();
var document = context.ToDocument(poco1);
document["NullableDateTime"] = DynamoDBNull.Null;
await table.UpdateItemAsync(document);
```

**Comment by dguisinger** [comment] 2017-04-25 20:30
Sorry, I didn't mean physically storing 'NULL' in the database, yes, deleting the property is inline with what I expected.  I need to work on my termonology. 

I meant that if I have a class:
`
class SomeEntity {
    string id { get; set; }
    string someText { get; set; }
    DateTime? somethingHappenedOnThisDate { get; set; }
}
`

If I set somethingHappenedOnThisDate = null, I still fully expect an entity to save into the database when I call SaveAsync() if the index fields are valid, and delete the somethingHappenedOnThisDate property (or in my mental image, it is saved/retrieved as null).     If I set a string property to null, it will still save (minus the particular NULL properties).  Since the date is getting converted to a string, and the string can be stored as null, I don't see that this behavior of failing to save and failing to throw an error is intentional behavior.

The absolute wrong behavior is to fail silently let the code think the item was saved to the database, which it is doing right now...

**Comment by PavelSafronov** [comment] 2017-04-25 21:29
Sorry, still not fully following.

Below is a code sample which populates a nullable DateTime, saves it, nulls it out, saves that, loads the item and logs the value of the nullable DateTime. In my local testing I was able to confirm that the correct attribute is deleted from DynamoDB by the second SaveAsync call and the nullable DateTime is set to null. Can you modify the below sample to reproduce the issue you are seeing?

Class description:
```
public class Issue629POCO
{
    public int Id { get; set; }
    public DateTime? NullableDateTime { get; set; }
}
```

Test code:
```
using (var client = new Amazon.DynamoDBv2.AmazonDynamoDBClient(creds, RegionEndpoint.USEast1))
using (var context = new Amazon.DynamoDBv2.DataModel.DynamoDBContext(client, new DynamoDBContextConfig { ConsistentRead = true }))
{
    var poco = new Issue629POCO
    {
        Id = 1,
        NullableDateTime = DateTime.Now,
    };
    Console.WriteLine($"poco.NullableDateTime = {poco.NullableDateTime}");
    await context.SaveAsync(poco);
    var loaded = await context.LoadAsync(poco);
    Debug.Assert(loaded.NullableDateTime.HasValue);
    Console.WriteLine($"loaded.NullableDateTime = {loaded.NullableDateTime}");

    poco.NullableDateTime = null;
    Console.WriteLine($"poco.NullableDateTime = {poco.NullableDateTime}");
    await context.SaveAsync(poco);
    loaded = await context.LoadAsync(poco);
    Debug.Assert(!loaded.NullableDateTime.HasValue);
    Console.WriteLine($"loaded.NullableDateTime = {loaded.NullableDateTime}");
}
```

**Comment by dguisinger** [comment] 2017-04-25 22:04
Alright, this will reproduce it for me.  Your code works, but as soon as I try the insert with a null value instead of inserting it with a date, it fails on loading a replacement and it never inserted a record.

```
[DynamoDBTable("tblName")]
    public class Issue629POCO
    {
        [DynamoDBProperty]
        public string id { get; set; }
        [DynamoDBProperty]
        public DateTime? NullableDateTime { get; set; }
    }

var poco = new Issue629POCO
            {
                id = Guid.NewGuid().ToString(),
                NullableDateTime = null// DateTime.Now,
            };

            Console.WriteLine($"poco.NullableDateTime = {poco.NullableDateTime}");
            await _context.SaveAsync(poco);
            var loaded = await _context.LoadAsync(poco);
            Debug.Assert(!loaded.NullableDateTime.HasValue);
            Console.WriteLine($"loaded.NullableDateTime = {loaded.NullableDateTime}");
```

**Comment by PavelSafronov** [comment] 2017-04-25 23:56
OK, I think I've got the repro case nailed down and it appears to be a DynamoDB issue. Below is the code that reproduces the bug using the low-level client. The bug (item not written to DynamoDB) appears to happen if the item contains only the key and DELETE directives. Uncommenting the commented-out line in the code sample (this introduces an arbitrary piece of data) results in everything working as expected.

I'm going to contact the DynamoDB team with this information. In the meantime, you can get your SaveAsync calls to succeed if there is non-key data present on your POCOs.

```
var keyAttributeValue = new AttributeValue { S = DateTime.Now.ToFileTimeUtc().ToString() };
var key = new Dictionary<string, AttributeValue> { { "Id", keyAttributeValue } };
await client.UpdateItemAsync(new UpdateItemRequest
{
    TableName = tableName,
    Key = key,
    AttributeUpdates = new Dictionary<string, AttributeValueUpdate>
    {
        { "Data", new AttributeValueUpdate { Action = AttributeAction.DELETE } },
        // Uncomment below line to make the UpdateItem succeed
        //{ "OtherData", new AttributeValueUpdate { Value = new AttributeValue { NULL = true } } }
    },
});

var response = await client.GetItemAsync(new GetItemRequest
{
    TableName = tableName,
    ConsistentRead = true,
    Key = key,
});
Debug.Assert(response.Item.Count != 0);
```

**Comment by dguisinger** [comment] 2017-04-26 00:38
That makes sense when you explain it that way, my initial tests were passing "" for several other properties on the object just to make sure my web service was getting called and the call was going to DynamoDB.  I'm guessing those are treated as null and deleted as well?   Normally my code would be passing real data in, but I spun my wheels for a few hours trying to figure out why the code was executing, returning no error, and leaving nothing in the database.

I just used the same example, added a string property and set it to "Hello World".  The example worked, data was saved.  I then changed it to "", so it was an id, an empty string, and a null date; and it failed to insert.

**Comment by PavelSafronov** [comment] 2017-04-28 18:34
**Bug**: DynamoDBContext is used to Save an object where only the key attributes are set and all the other attributes are null AND the item does not exist in the target Table, the item creation will not happen.

**Workaround**: Include non-key data in the object.

**Service behavior**: According to the [DynamoDB documentation](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValueUpdate.html), this behavior of UpdateItem is by design. Relevant bit:
> If no item with the specified Key is found:
>  DELETE - Nothing happens; there is no attribute to delete.

**Decision**: We've looked into the relevant SDK code and the DynamoDB service protocol and haven't been able to come up with a simple, reliable fix for this issue. Considering that this is a very infrequently-encountered issue with a simple work-around, we are going to close this issue as **Won't Fix**.

**Follow-up**: if you feel that this bug should be fixed, please reply to this issue with your use-case and how this bug is impacting you, and we will reconsider this decision.

**Closed by PavelSafronov** 2017-04-28 18:34 UTC
Labels: Question, Won't Fix
