### ISSUE TITLE
S3 bucket with “Requester pays” enabled still gets data transfer costs

### ISSUE THREAD

**Issue by orbengigi** [aws/aws-sdk-net#1529] opened 2020-02-17 09:34 UTC
I'm trying to configure cross account access to S3 bucket with "Requester Pays" enabled.
I've configured a Request payer property as enabled in the bucket properties in the first account.
I gave another account access to AmazonS3ReadOnlyAccess with a role to external account. In my dotnet application I used the role to authenticate, and created a GetObjectRequest with the RequestPayer parameter :

`GetObjectRequest getObjectRequest = new GetObjectRequest { BucketName = "bucketName", Key = "fileName", RequestPayer = RequestPayer.Requester };
var response = await client.GetObjectAsync(getObjectRequest);`

In fiddler I see the request has the expected header of: x-amz-request-payer: requester,
but in the response I don't see the x-amz-request-charged header, also in the response object I get null value for the RequestCharged  property.

Also tried removing the RequestPayer property from the request, which by your documentation should result in 403 error, but the request got no error and was able to get the objects from S3.

## Expected Behavior
Response should include x-amz-request-charged header, and response object should include RequestCharged  value.

Accessing a Requester Pays Buckets without the RequestPayer property should result in 403 error.

## Your Environment
"AWSSDK.S3" Version="3.3.108.4"
## .NET Core Info
netcoreapp3.1

**Comment by klaytaybai** [comment] 2020-02-20 18:53
Appears to be a duplicate of https://github.com/aws/aws-sdk-net/issues/1526

**Closed by klaytaybai** 2020-02-20 18:53 UTC
Labels: duplicate
