### ISSUE TITLE
AssumeRole request when using a role in profile config does not specify AuthenticationToken when triggered from another service client

### ISSUE THREAD

**Issue by scanham** [aws/aws-sdk-net#681] opened 2017-06-25 22:37 UTC
I'm attempting to use the AmazonSQSClient. If I specify a role in my /.aws/config file for a profile and try to use that profile I get the exception Amazon.SecurityToken.AmazonSecurityTokenServiceException(Request is missing Authentication Token) when the SDK attempts to call AssumeRole before calling SQS.

Based on the exception, it looks like my security token is not being attached to the AssumeRole request. If I use an account that does have access to the resource and does not requires the role to be assumed I am able to interact with SQS as expected.

## Expected Behavior
I expect the underlying AssumeRole request to succeed so that my application can call SQS with valid temporary credentials.

## Current Behavior
The below exception is thrown instead:
```csharp
Unhandled Exception: Amazon.Runtime.AmazonClientException: Error calling AssumeRole for role <MY-ROLE-ARN> ---> Amazon.SecurityToken.AmazonSecurityTokenServiceException: Request is missing Authentication Token ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponse()
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller)
   at Amazon.SecurityToken.AmazonSecurityTokenServiceClient.Amazon.Runtime.SharedInterfaces.ICoreAmazonSTS.CredentialsFromAssumeRoleAuthentication(String roleArn, String roleSessionName, AssumeRoleAWSCredentialsOptions options)
   --- End of inner exception stack trace ---
   at Amazon.SecurityToken.AmazonSecurityTokenServiceClient.Amazon.Runtime.SharedInterfaces.ICoreAmazonSTS.CredentialsFromAssumeRoleAuthentication(String roleArn, String roleSessionName, AssumeRoleAWSCredentialsOptions options)
   at Amazon.Runtime.AssumeRoleAWSCredentials.GenerateNewCredentials()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.RefreshingAWSCredentials.<GetCredentialsAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at aws_test.Program.<MainAsync>d__3.MoveNext() in /Users/scott/Code/sqs-bug/Program.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at aws_test.Program.Main(String[] args) in /Users/scott/Code/sqs-bug/Program.cs:line 19
```

## Steps to Reproduce (for bugs)
Sample program demonstrating the issue. The first block works, when I call AssumeRole and use the response create a client. The second block in which i just use the AWSOptions class to generate a client does not work.

The sample was written as a console app on a mac for simplicity. I first discovered this problem while developing a .NET Core MVC application in Visual Studio 2017 on Windows 10. 

```csharp
using System;
using System.Threading;
using System.Threading.Tasks;
using Amazon;
using Amazon.SQS;
using Amazon.SQS.Model;
using Amazon.SecurityToken;
using Amazon.SecurityToken.Model;
using Amazon.Extensions.NETCore.Setup;

namespace aws_test
{
    class Program
    {
        public static string _queueUrl = "<MY-QUEUE-URL>";
        public static string _roleArn = "<MY-ROLE-ARN>";
        public static void Main(string[] args)
        {
            MainAsync(args).GetAwaiter().GetResult();

            Console.ReadKey();
        }
        
        public static async Task MainAsync(string[] args)
        {
            //THIS WORKS.
            var options = new AWSOptions() 
            {
                Profile = "default",
                Region = RegionEndpoint.USEast1
            }; 
            
            var manualResponse = await ManualAssume(options);
            Console.WriteLine(manualResponse.Messages.Count);

            //THIS DOES NOT WORK
            options = new AWSOptions() 
            {
                Profile = "sqs-dev",
                Region = RegionEndpoint.USEast1
            }; 

            var autoResponse = await AutomaticAssume(options);
            Console.WriteLine(autoResponse.Messages.Count);
        }


        public static async Task<ReceiveMessageResponse> ManualAssume(AWSOptions options) 
        {
            var stsClient = options.CreateServiceClient<IAmazonSecurityTokenService>();
            var assumedRoleResponse = await stsClient.AssumeRoleAsync(new AssumeRoleRequest() { 
                RoleArn = _roleArn, 
                RoleSessionName = "test" 
            });
            
            var sqsClient = new AmazonSQSClient(assumedRoleResponse.Credentials.AccessKeyId, assumedRoleResponse.Credentials.SecretAccessKey, assumedRoleResponse.Credentials.SessionToken, RegionEndpoint.USEast1);
            
            return await sqsClient.ReceiveMessageAsync(_queueUrl);
        }

        public static Task<ReceiveMessageResponse> AutomaticAssume(AWSOptions options)
        {
            var sqsClient = options.CreateServiceClient<IAmazonSQS>();

            return sqsClient.ReceiveMessageAsync(_queueUrl);
        }
    }
}
```

My ~/.aws/credentials :
```
[default]
aws_access_key_id = <MY-ACCESS-KEY>
aws_secret_access_key = <MY-SECRET-KEY>
aws_session_token = <MY-SESSION-TOKEN>
```

My ~/.aws/config :
```
[default]
region = us-east-1

[profile sqs-dev]
source_profile = default
role_arn = <MY-ROLE-ARN>
```

Block from my appsettings.Development.json file when I did this in MVC originally:
```json
"AWS": {
    "Profile": "sqs-dev",
    "Region": "us-east-1"
  }
```

## Context
I would like to be able to use the designed approach for credentials and authentication when developing. This is not a problem for me in production as I run this application on an EC2 Instance and it works as expected there by assigning the role to the instance

## Your Environment
* AWSSDK.Core version used: 3.3.14.2
* Service assembly and version used: 
AWSSDK.SQS 3.3.2.4
AWSSDK.Securitytoken 3.3.2
AWSSDK.Extensions.NETCore.Setup 3.3.1
* Operating System and version: macOS 10.12.1
* Visual Studio version: Code 
* Targeted .NET platform: netcoreapp1.1

## .NET Core Info
* .NET Core version used for development:  1.1
* .NET Core version installed in the environment where application runs:  1.1
* Output of `dotnet --info`: 
```bash
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```
* Contents of project.json/project.csproj: 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="3.3.14.2"/>
    <PackageReference Include="AWSSDK.SQS" Version="3.3.2.4"/>
    <PackageReference Include="AWSSDK.Securitytoken" Version="3.3.2"/>
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.1"/>
  </ItemGroup>
</Project>
```
[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by vellozzi** [comment] 2017-06-26 23:18
Thanks for the clear write up.  It helped a lot.
The problem is that the SDK only allows you to use a basic profile as the source for an assume role profile.
This was an oversight in the initial design of the assume role credentials code.  We should also allow session profiles.
This will be fixed and released as soon as we're able to do it.

**Comment by scanham** [comment] 2017-06-27 05:41
Great! Thanks. There is one more thing I thought I should mention that I noticed while experimenting with workarounds/auth stuff. It may be related, or it may deserve it's own issue:

With the same credentials/config files as above the following code behaves differently on Windows vs Mac when using the `CredentialProfileStoreChain` object:

```csharp
var credentialStore = new CredentialProfileStoreChain();
AWSCredentials awsCredentials = null;
if (credentialStore.TryGetAWSCredentials("sqs-dev", out awsCredentials))
{
    var creds = awsCredentials.GetCredentials();
}
```

On Mac, the same exception is thrown as above. On Windows the `creds` variable has the same access id/secret key as the default profile but the session token is an empty string. If I try to load the default profile in either enviornment the session token is not empty.

If I take the `role-arn` line out of the config file. Windows behaves the same and returns an object with an empty session token. Strangely though on Mac the `TryGetAWSCredentials` returns `false`.

**Comment by vellozzi** [comment] 2017-06-27 16:54
Do you have a default profile in your .NET SDK credentials store at C:\Users\user\AppData\Local\AWSToolkit\RegisteredAccounts.json ?  If so, it's picking that one up because on windows it checks the .NET SDK credentials store first.

**Comment by scanham** [comment] 2017-06-27 18:04
Ahhh.. duh. That makes sense, my bad!

I cleared that out and now it's back to just the original issue when attempting to assume the role.

By the way - are there plans to allow entering a token along with the key/secret when using the vs2017 toolkit?

**Comment by vellozzi** [comment] 2017-06-27 18:13
We plan on doing it at some point but it's not scheduled yet.  You're not the first to ask for it so we know we need it.

**Closed** 2017-07-11 16:42 UTC
Labels: Question
