### ISSUE TITLE
Amazon AppSync - Higher Level Library/Amplify Support

### ISSUE THREAD

**Issue by yoni536** [aws/aws-sdk-net#1776] opened 2021-01-15 16:56 UTC
issue for a higher level library / **Amplify** Framework port for interfacing with Amazon **AppSync**.
This is the preferred service for doing offline data synchronization and cross-device data management.
**support for .net and unity**

**Comment by yoni536** [comment] 2021-04-16 16:32
@AppSync

**Comment by yoni536** [comment] 2021-04-16 16:34
any updates?

@AppSync  @Amplify

**Comment by normj** [comment] 2021-08-21 22:40
Closing as a duplicate of this issue
https://github.com/aws/dotnet/issues/20

**Closed by normj** 2021-08-21 22:40 UTC
Labels: feature-request, needs-triage, module/sdk-custom
