### ISSUE TITLE
DynamoDB TransactionCanceledException does not provide any information on cancellation reasons

### ISSUE THREAD

**Issue by ghost** [aws/aws-sdk-net#1292] opened 2019-05-14 07:29 UTC
## Expected Behavior
I expect the TransactionCanceledException to be able to give an indication of why the transaction was cancelled or for a work around to be available to get this information.

## Current Behavior
There is nothing on the exception or inner exception to figure out what could be wrong. An attempt to read the response body of the inner HttpErrorResponseException also fails as the stream is already disposed.

## Possible Solution
Provide the CancellationReasons as is available in the Java client SDK.

I have seen this note in the docs:

> If using Java, DynamoDB lists the cancellation reasons on the CancellationReasons property. This property is not set for other languages. Transaction cancellation reasons are ordered in the order of requested items, if an item has no error it will have NONE code and Null message.

There seems to be no information whatsoever on how to handle this in .net. I hope there is currently a work around for this that someone can point me out to.

**Comment by klaytaybai** [comment] 2019-05-14 23:05
@thulani-chivandikwa, thanks for the feature request.  A solution is currently high in our queue of pending work.

**Comment by richjrader** [comment] 2019-08-30 17:17
+1

**Comment by kosmakoff** [comment] 2020-02-07 13:33
Bump!

Exception says: `Transaction cancelled, please refer cancellation reasons for specific reasons [ConditionalCheckFailed]`

While there is no Cancellation reasons field/property whatsoever, ErrorCode property contains the name of exception class, namely `TransactionCanceledException`, which doesn't even match any error in documentation, and the only way I can learn about the exception nature is to parse the message text. Very safe 😠 What's even more annoying, I'll have to monitor each update to SDK so that my code don't suddenly blow up when the error message changes.

ErrorCode property must contain whatever there is in square brackets in the exception's message, at least it is one of error codes I see in [official documentation](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TransactWriteItems.html#API_TransactWriteItems_Errors).

Please, make this issue critical priority.

**Comment by chivandikwa** [comment] 2020-02-17 07:25
I am original reporter of this issue, now using this as my single github account in case someone needs more information.

**Comment by winzig** [comment] 2020-05-08 01:03
@normj Since @klaytaybai isn't on the team any more, has this fallen off the radar? What's the status? I've been banging my head on this for a few hours now with still no clear way to figure out what the underlying errors are currently. Is there a recommended debugging workaround?

**Comment by tgoorden** [comment] 2021-02-02 11:25
Let me just join the queue of people that ended up here after hopelessly looking for the promised "cancellation reasons".

**Comment by jehrenzweig** [comment] 2021-02-25 15:34
Just ran into this problem myself.  This issue has been open for almost two years now.

**Comment by ashishdhingra** [comment] 2021-02-26 22:15
Hi @jehrenzweig @tgoorden @winzig @chivandikwa.

Good afternoon.

Based on the high level look at the code https://github.com/aws/aws-sdk-net/blob/133eddb00a3fbd2ab395e01c3d84ac9fe1ff38b2/sdk/src/Services/DynamoDBv2/Generated/Model/Internal/MarshallTransformations/TransactionCanceledExceptionUnmarshaller.cs#L39, the `CancellationReasons` for `TransactionCanceledException` should be populated. Could you please try updating to latest version of SDK and confirm if this is still an issue?

Thanks,
Ashish

**Comment by jehrenzweig** [comment] 2021-03-01 20:53
@ashishdhingra PROGRESS!  I do see the `CancellationReasons` property being populated.  However -- and it's possible this is specific to my particular use case -- one of the two items in the array doesn't have any useful info in it.  For example, the `Code` property is "None", the `Item` property is empty (`Count` = 0), and the `Message` is null.

**Comment by ashishdhingra** [comment] 2021-03-02 20:12
Just for reference, could be easily confirmed that `CancellationReasons` property is populated using the following code:
```C#
using System;
using System.Collections.Generic;
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.DataModel;
using Amazon.DynamoDBv2.Model;
using Amazon.Runtime;

namespace DynamoDb_Issue1292
{
    class Program
    {
        private static AmazonDynamoDBClient client = new AmazonDynamoDBClient();

        static void Main(string[] args)
        {
            try
            {
                DynamoDBContext context = new DynamoDBContext(client);

                var transactWriteItemsRequest = new TransactWriteItemsRequest()
                {
                    TransactItems = new List<TransactWriteItem>() {
                        new TransactWriteItem(){
                            Put = new Put(){
                                TableName = "Root",
                                Item = new Dictionary<string, AttributeValue>{
                                            { "Id", new AttributeValue() { S = "Id1" } },
                                            {"Attribute1", new AttributeValue{ S = "testattributevalue" } }
                                }
                            }
                        },
                        new TransactWriteItem(){
                            Update = new Update(){
                                TableName = "Root",
                                Key = new Dictionary<string, AttributeValue>{
                                            { "Id", new AttributeValue() { S = "Id4" } }
                                },
                                UpdateExpression = "SET Attribute1 = testattributevalue4"
                            }
                        }
                    }
                };
                TransactWriteItemsResponse transactWriteItemsResponse = client.TransactWriteItemsAsync(transactWriteItemsRequest).GetAwaiter().GetResult();

                Console.WriteLine("To continue, press Enter");
                Console.ReadLine();
            }
            catch (AmazonDynamoDBException e) { Console.WriteLine(e.Message); }
            catch (AmazonServiceException e) { Console.WriteLine(e.Message); }
            catch (Exception e) { Console.WriteLine(e.Message); }
        }
    }

    [DynamoDBTable("Root")]
    public class Root
    {
        [DynamoDBHashKey] //Partition key
        public string Id
        {
            get; set;
        }

        public string Attribute1
        {
            get; set;
        }
    }
}
```

**Comment by ashishdhingra** [comment] 2021-03-02 20:30
> @ashishdhingra PROGRESS! I do see the `CancellationReasons` property being populated, which is awesome!
> 
> However, one of the two items in my `CancellationReasons` array doesn't have any useful info in it. For example, the `Code` property value is "_None_", the `Item` property value is empty (`Count` = 0), and the `Message` value is _null_. Kinda weird. FWIW all I did to reproduce this behavior was create a transaction with two `Put` items, one of which specifies a key attribute that doesn't exists in the DynamoDB table.
> 
> UPDATE 1: I just confirmed that the `CancellationReasons` property will contain as many items as the number of items that were added to the transaction. If a given transaction item did not produce any errors, it will add an empty, useless item to the `CancellationReasons` property. Is this behavior intentional?
> 
> UPDATE 2: I think I realize what's going on. The empty `CancellationReasons` array items are present to help developers identify what happened when each transaction item was processed. However, figuring that out isn't terribly straightforward right now -- you need to lookup the contents of the original transaction item to figure out the table name associated with any issues/errors/warnings reported by the `CancellationReasons` property.
> 
> Is there any way a `TableName` property could be added to the [CancellationReason](https://github.com/aws/aws-sdk-net/blob/633b4fe2288186e0da57ce3805c692121667e0ed/sdk/src/Services/DynamoDBv2/Generated/Model/CancellationReason.cs#L37) class, so that the info in the `CancellationReasons` property is more self-descriptive? That's absolutely a feature request and not something that should keep this issue open.

Hi @jehrenzweig,

Let me check the same. The [CancellationReason](https://github.com/aws/aws-sdk-net/blob/633b4fe2288186e0da57ce3805c692121667e0ed/sdk/src/Services/DynamoDBv2/Generated/Model/CancellationReason.cs#L37) class should be modeled as per information returned from service. If the service doesn't return the required data, then this feature might not be possible. As per my understanding, the [TransactionCanceledExceptionUnmarshaller](https://github.com/aws/aws-sdk-net/blob/133eddb00a3fbd2ab395e01c3d84ac9fe1ff38b2/sdk/src/Services/DynamoDBv2/Generated/Model/Internal/MarshallTransformations/TransactionCanceledExceptionUnmarshaller.cs#L39) deserializes the information returned by service.

Thanks,
Ashish

**Comment by ashishdhingra** [comment] 2021-03-03 19:39
Hi @jehrenzweig,

Good morning.

I stepped through the code and figured out that for the above example, following response is returned from the service when `TransactionCanceledException` scenario occurs for above example:

```JSON
{
   "__type": "com.amazonaws.dynamodb.v20120810#TransactionCanceledException",
   "CancellationReasons": [
      {
         "Code": "None"
      },
      {
         "Code": "ValidationError",
         "Message": "The provided expression refers to an attribute that does not exist in the item"
      }
   ],
   "Message": "Transaction cancelled, please refer cancellation reasons for specific reasons [None, ValidationError]"
}
```

The [TransactionCanceledExceptionUnmarshaller](https://github.com/aws/aws-sdk-net/blob/133eddb00a3fbd2ab395e01c3d84ac9fe1ff38b2/sdk/src/Services/DynamoDBv2/Generated/Model/Internal/MarshallTransformations/TransactionCanceledExceptionUnmarshaller.cs#L39) just deserializes the above JSON returned by service and populates the `CancellationReason` list. As you could see that the response does not contain the other details like TableName, Item, etc. Since the unmarshaller is generic and should not assume anything, it would not be possible to add TableName property to the `CancellationReason` class. 

Hope this provides good information. Closing this issue since the original issue appears to be resolved in the latest version (as also confirmed by you).

Thanks,
Ashish

**Closed by ashishdhingra** 2021-03-03 19:39 UTC
Labels: feature-request, module/dynamodb

**Comment by sakopov** [comment] 2021-04-13 17:06
Does each item in `CancellationReasons` correspond to an item submitted in the original request to DynamoDB? If so, how do we correlate the two? To give an example, If I submit a TransactionWriteItems request containing 2 transactions where 1 fails with ConditionCheckFailed, the `CancellationReasons` collection returns reason `None` for one and `ConditionCheckFailed` for the other and nothing is returned in the `Item` property for either one. So I'm not sure how I can correlate cancellation reasons to the original request aside from comparing positions of items in the `CancellationReasons` collection and the original request. This, however, seems very dodgy and prone to error since there is nothing saying (AFAIK) that these will always be in the same order.
