### ISSUE TITLE
Polly prefixes a period to the filename on speech synthesis tasks

### ISSUE THREAD

**Issue by mariox2098** [aws/aws-sdk-net#1880] opened 2021-07-07 18:15 UTC
## The Question
I'm using the AWS Polly client to start a synthesis task with `StartSpeechSynthesisTaskAsync`. Whenever it runs, it prefixes a period to the file name. So if the the TaskId is like `1234-5678`, the final file name ends up being `.1234-5678.mp3`. I'm also including an `OutputS3KeyPrefix` in the request, which I thought was causing the issue but the period is still there even when I removed it. 
Am I just misunderstanding how this should work or is this a bug?

### Environment
* SDK Version: AWSSDK.Polly 3.7.1.8, 
* Targeted .NET Platform:  Net Core 3.1
---

This is a :question: general question

**Comment by mariox2098** [comment] 2021-07-07 18:49
Actually I was mistaken, only when I include the `OutputS3KeyPrefix` does it prepends the period

**Comment by ashishdhingra** [comment] 2021-07-07 18:49
Hi @mariox2098,

Thanks for posting guidance question. Somehow I'm unable to reproduce the issue.
**Code:**
```C#
using Amazon.Polly;
using Amazon.Polly.Model;

namespace Polly_Issue1880
{
    class Program
    {
        static void Main(string[] args)
        {
            var client = new AmazonPollyClient();
            var response = client.StartSpeechSynthesisTaskAsync(new StartSpeechSynthesisTaskRequest()
            {
                OutputFormat = OutputFormat.Mp3,
                Text = "Hello World",
                TextType = TextType.Text,
                VoiceId = new VoiceId("Joanna"),
                OutputS3BucketName = "testbucket-issue1880"
            }).Result;
        }
    }
}
```
This created task in Amazon Polly dashboard:
<img width="1948" alt="Screen Shot 2021-07-07 at 11 44 45 AM" src="https://user-images.githubusercontent.com/67916761/124812703-ceff9e80-df18-11eb-8d3f-81617ea00921.png">
Checked the S3 bucket, it had the file named `230bce87-470b-4c9c-bdac-5d81cf0831ff.mp3` (based on TaskId):
<img width="1725" alt="Screen Shot 2021-07-07 at 11 46 33 AM" src="https://user-images.githubusercontent.com/67916761/124812851-ffdfd380-df18-11eb-940a-2e3404624697.png">

Changed the above code to include `OutputS3KeyPrefix`:
```C#
using Amazon.Polly;
using Amazon.Polly.Model;

namespace Polly_Issue1880
{
    class Program
    {
        static void Main(string[] args)
        {
            var client = new AmazonPollyClient();
            var response = client.StartSpeechSynthesisTaskAsync(new StartSpeechSynthesisTaskRequest()
            {
                OutputFormat = OutputFormat.Mp3,
                Text = "Hello World",
                TextType = TextType.Text,
                VoiceId = new VoiceId("Joanna"),
                OutputS3BucketName = "testbucket-issue1880",
                OutputS3KeyPrefix = "testprefix"
            }).Result;
        }
    }
}
```
Executing it created the output file named `testprefix.7a5ce61a-1f34-4cf8-803f-8d9f495c7936.mp3` in the S3 bucket.

Thanks,
Ashish

**Comment by mariox2098** [comment] 2021-07-07 19:01
I see my problem now. The prefix I was using something like `/some/folder/someId-` but I didn't know the service added period afterwards when you specify a prefix. So I ended up with `/some/folder/someId-.taskId.mp3`. Is this documented anywhere?

**Comment by ashishdhingra** [comment] 2021-07-07 19:50
> I see my problem now. The prefix I was using something like `/some/folder/someId-` but I didn't know the service added period afterwards when you specify a prefix. So I ended up with `/some/folder/someId-.taskId.mp3`. Is this documented anywhere?

@mariox2098 I do not see it documented ar [StartSpeechSynthesisTask](https://docs.aws.amazon.com/polly/latest/dg/API_StartSpeechSynthesisTask.html) service API reference page. If required, feel free to submit feedback using `Provide feedback` link at the bottom of the page for this specific API operation, it should be taken care by service team. Closing this ticket.

**Closed by ashishdhingra** 2021-07-07 19:50 UTC
Labels: guidance, module/sdk-generated, response-requested, service-api
