### ISSUE TITLE
DynamoDB OverrideTableName doesn't work

### ISSUE THREAD

**Issue by vickyrathee** [aws/aws-sdk-net#1448] opened 2019-11-07 05:41 UTC
I am using `Table1` to override using `DynamoDBOperationConfig.OverrideTableName` but the SDK doesn't override the tableName and throwing error with class name `Documents `. So the override request not honored and getting error.

**Error : Requested resource not found: Table: Documents not found**

My requirement is to change the table name dynamically on business logic to insert documents in different tables. So I can't use the `[DynamoDBTable("Table1")]`

```
async Task Main()
{
	var document = new Documents {doc_id = "abc", name = "test", created = DateTime.UtcNow};
	
	string tableName = "Table1";
	var dynamo = new DynamoDbService(tableName);
	await dynamo.InsertDocumentAsync<Documents>(document);
	
}

public class DynamoDbService
{
	private static readonly string awsAccessKey = "access key here";
	private static readonly string awsSecretKey = "secret here";
	
	private static DynamoDBOperationConfig _operationConfig;

	private static BasicAWSCredentials awsCredentials = new BasicAWSCredentials(awsAccessKey, awsSecretKey);
	private static AmazonDynamoDBClient client = new AmazonDynamoDBClient(awsCredentials, RegionEndpoint.USEast1);
	private static DynamoDBContext context = new DynamoDBContext(client);

	public DynamoDbService(string tableName)
	{
		_operationConfig = new DynamoDBOperationConfig()
		{
			OverrideTableName = tableName
		};
	}
	
	public async Task InsertDocumentAsync<T>(T document)
	{
		await context.SaveAsync<T>(document);
	}

	public async Task<List<T>> GetDocumentsAsync<T>(string id, int limit = 10)
	{
		QueryFilter filter = new QueryFilter();
		filter.AddCondition("doc_id", QueryOperator.Equal, id);
		QueryOperationConfig queryConfig = new QueryOperationConfig
		{
			Filter = filter,
			Limit = limit,
			BackwardSearch = true
		};
		var documents = await context.FromQueryAsync<T>(queryConfig, _operationConfig).GetNextSetAsync();
		return documents;
	}
}

public class Documents
{
	public string doc_id { get; set; }
	public string name {get; set;}
	public DateTime created {get; set;}
}

```

![image](https://user-images.githubusercontent.com/6106479/68362871-ca388500-014e-11ea-9c21-a1d2fe7a12f3.png)

**Comment by klaytaybai** [comment] 2019-11-07 23:06
Hi @vickyrathee, thanks for the time to provide the feedback on this.  It is a known problem.  You can see another report from https://github.com/aws/aws-sdk-net/issues/1218.  We're looking for other approaches to fix this problem that wouldn't cause a breaking change for any customers depending on the flawed behavior.

**Comment by vickyrathee** [comment] 2019-11-08 04:44
@klaytaybai Thanks. But that's 9 month old issue if you are aware.. I think many `DynamoDBv2` versions released after that. Any timeline when we can expect a fix?

**Comment by klaytaybai** [comment] 2019-11-08 18:24
Unless we can find a way to solve this without causing breaking changes, we have to wait until a major version based on our policy of not making breaking changes except for major versions.

**Comment by jameswoodley** [comment] 2020-07-03 11:49
So how are we supposed to use this? I need to use a table name override and can't right now. I think surely you should be focussing on those of us who want to use it as intended than those who are using a flawed version? 

If you have to bump to a major version then please do, but otherwise this functionality is unusable?

**Comment by ashishdhingra** [comment] 2021-03-11 21:27
Refer https://github.com/aws/aws-sdk-net/issues/1218#issuecomment-660391518, this is a breaking change. Duplicate of https://github.com/aws/aws-sdk-net/issues/1421. Closing this one.

**Closed by ashishdhingra** 2021-03-11 21:27 UTC
Labels: breaking-change, bug, duplicate, module/dynamodb
