### ISSUE TITLE
PutObjectAsync is calling a synchronous operation

### ISSUE THREAD

**Issue by dsarfati** [aws/aws-sdk-net#1452] opened 2019-11-13 18:09 UTC
## Expected Behavior

We just upgraded to asp.net core 3 and are seeing a new exception when trying to upload an image to S3 that we did not see when running in the .net core 2.X environment.

## Current Behavior

When calling `PutObjectAsync` on the `AmazonS3Client` we get an `InvalidOperationException` (included below)

## Steps to Reproduce (for bugs)

```c#
public async Task<string> SaveImage(Stream stream, long streamLength)
{
            try
            {
                var imageId = Guid.NewGuid().ToString();

                var filename = GetFileName(imageId);

                var putObjRequest = new PutObjectRequest()
                {
                    BucketName = _bucketName,
                    Key = filename,
                    InputStream = stream,
                };

                putObjRequest.Headers.ContentLength = streamLength;

                await _amazonS3Client.PutObjectAsync(putObjRequest);

                return imageId;
            }
            catch
            {
                return null;
            }
}
```

```
"   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)\r\n   at Amazon.Runtime.Internal.Util.WrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)\r\n   at Amazon.Runtime.Internal.Util.PartialReadOnlyWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)\r\n   at Amazon.Runtime.Internal.Util.WrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)\r\n   at Amazon.Runtime.Internal.Util.HashStream.Read(Byte[] buffer, Int32 offset, Int32 count)\r\n   at Amazon.Runtime.Internal.Util.ChunkedUploadWrapperStream.FillInputBuffer()\r\n   at Amazon.Runtime.Internal.Util.ChunkedUploadWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)\r\n   at Amazon.Runtime.Internal.Util.WrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)\r\n   at System.IO.Stream.<>c.<BeginReadInternal>b__43_0(Object <p0>)\r\n   at System.Threading.Tasks.Task`1.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.IO.Stream.<CopyToAsyncInternal>d__30.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()\r\n   at System.Net.Http.StreamToStreamCopy.<<CopyAsync>g__DisposeSourceAsync|0_0>d.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()\r\n   at System.Net.Http.HttpContent.<CopyToAsyncCore>d__49.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()\r\n   at System.Net.Http.HttpConnection.<SendRequestContentAsync>d__58.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()\r\n   at System.Net.Http.HttpConnection.<SendRequestContentWithExpect100ContinueAsync>d__59.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()\r\n   at System.Net.Http.HttpConnection.<SendAsyncCore>d__53.MoveNext()"
```

## Your Environment

* AWSSDK.Core version used: AWSSDK.S3 (3.3.104.42) AWSSDK.Core (>= 3.3.103.54 < 3.4)
* Service assembly and version used: 
* Operating System and version: Windows and Linux
* Visual Studio version: VSCode
* Targeted .NET platform: .net core 3

## .NET Core Info

* .NET Core version used for development: 3
* .NET Core version installed in the environment where application runs: 3
* Output of `dotnet --info`: 
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment] 2019-11-13 22:28
Hi @dsarfati, what is the type of the stream you are passing to SaveImage?

**Comment by dsarfati** [comment] 2019-11-13 22:42
@klaytaybai Here is the API controller that is calling `SaveImage`, we are simply pulling the body from the request

```c#
[HttpPost("{rewardId:guid}/image")]
public async Task<IActionResult> UpdateRewardImage(Guid rewardId)
{
     var file = Request.Body;
     var streamLength = Request.ContentLength;
     var imageId = await _rewardImageService.SaveImage(file, streamLength.Value);
     ...
}
```

**Comment by broadbear** [comment] 2019-12-15 22:00
We ran into this, too. To fix it I had to copy the request body stream into a MemoryStream (actually a RecyclableMemoryStream).

**Comment by KarlKl** [comment] 2020-01-14 07:51
We also ran into this problem but with the `UploadAsync` method of the `TransferUtility`. :(
@broadbear: We do not want to copy our Stream into the memory, because we want to stream our file upload directly to S3. So we allowed sync stream with the `AllowSynchronousIO` Kestrel option. But this should not be a permanent solution...

**Comment by oliverjanik** [comment] 2020-10-28 06:50
Any update here?

**Comment by ashishdhingra** [comment] 2020-11-04 22:16
Hi @dsarfati,

Good afternoon.

I was trying to reproduce the issue using the below code:

```C#
using System;
using System.IO;
using System.Threading.Tasks;
using Amazon.S3;
using Amazon.S3.Model;

namespace S3StreamTest
{
    class Program
    {
        private static string _bucketName = "testbucket-1452";
        private static AmazonS3Client _amazonS3Client = new AmazonS3Client();
        private static string imageFilePath = "<fullfilepath>/<filename>.png";

        static void Main(string[] args)
        {
            Stream stream = new FileStream(imageFilePath, FileMode.Open);
            SaveImage(new NonSeekableStream(stream), stream.Length, "TestImage.png").GetAwaiter().GetResult();
        }

        public static async Task<string> SaveImage(Stream stream, long streamLength, string fileName)
        {
            try
            {
                var imageId = Guid.NewGuid().ToString();

                var putObjRequest = new PutObjectRequest()
                {
                    BucketName = _bucketName,
                    Key = fileName,
                    InputStream = stream,
                };

                putObjRequest.Headers.ContentLength = streamLength;

                await _amazonS3Client.PutObjectAsync(putObjRequest);

                return imageId;
            }
            catch
            {
                return null;
            }
        }
    }

    public class NonSeekableStream : Stream
    {
        Stream m_stream;
        public NonSeekableStream(Stream baseStream)
        {
            m_stream = baseStream;
        }
        public override bool CanRead
        {
            get { return m_stream.CanRead; }
        }

        public override bool CanSeek
        {
            get { return false; }
        }

        public override bool CanWrite
        {
            get { return m_stream.CanWrite; }
        }

        public override void Flush()
        {
            m_stream.Flush();
        }

        public override long Length
        {
            get { throw new NotSupportedException(); }
        }

        public override long Position
        {
            get
            {
                return m_stream.Position;
            }
            set
            {
                throw new NotSupportedException();
            }
        }

        public override int Read(byte[] buffer, int offset, int count)
        {
            return m_stream.Read(buffer, offset, count);
        }

        public override long Seek(long offset, SeekOrigin origin)
        {
            throw new NotImplementedException();
        }

        public override void SetLength(long value)
        {
            throw new NotSupportedException();
        }

        public override void Write(byte[] buffer, int offset, int count)
        {
            m_stream.Write(buffer, offset, count);
        }
    }
}
```

However, the above code works fine without any issues (class `NonSeekableStream` is used to mimic non-seekable stream). Would it be possible for you to share sample code solution, descriptive error message and full error stack trace for us to troubleshoot the issue?

Thanks,
Ashish

**Comment by dsarfati** [comment] 2020-11-05 19:36
Here is the code that we use to call the `SaveImage` method I posted at the start of the thread. This is simply a method in our ASP.NET controller.

```c#
    [ApiController]
    [Route("api/v{version:apiVersion}/rewards")]
    [V1]
    public class RewardsController : ControllerBase {

        [HttpPost("{rewardId:guid}/cover-image")]
        public async Task<IActionResult> AddCoverImage(Guid rewardId)
        {
            var file = Request.Body;
            var streamLength = Request.ContentLength;

            if (file == null || streamLength == null)
            {
                return BadRequest();
            }

            var syncIOFeature = HttpContext.Features.Get<IHttpBodyControlFeature>();

            if (syncIOFeature != null)
            {
                //This is should not be here, but is required for the AWS SDK to work correctly
                syncIOFeature.AllowSynchronousIO = true;
            }

            var imageId = await _rewardImageService.SaveImage(file, streamLength.Value);

            try
            {
                var rewardGrain = _clusterClient.GetGrain<IRewardGrain>(rewardId);
                await rewardGrain.SetCoverImage(Guid.Parse(imageId));
                return Accepted();
            }
            catch (InvalidOperationException)
            {
                return Forbid();
            }
        }
}
```

You'll notice that we were forced to include ` syncIOFeature.AllowSynchronousIO = true;` for it to work.

**Comment by ashishdhingra** [comment] 2020-11-05 20:04
Hi @dsarfati,

Thanks for the code snippet. Could you also please share the exact error message (which is not included in the 1st comment above) along with stack trace? Going through some articles/forums online, there is a reported error `System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.`, which has a workaround similar to what you have implemented or use asynchronous operations.

The Microsoft documentation [Request and response operations in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/request-response?view=aspnetcore-3.1) details about reading from `Request.Body`.

There is also an [[Announcement] AllowSynchronousIO disabled in all servers](https://github.com/dotnet/aspnetcore/issues/7644) in ASP.NET Core repository for the same.

Since this happens within the ASP.NET Core environment, this doesn't appear to be a bug in AWS .NET SDK, rather limitation/feature of .NET Core environment. Hope this helps.

Thanks,
Ashish

**Comment by oliverjanik** [comment] 2020-11-08 00:07
What exactly are you saying here @ashishdhingra? With all due respect, I don't want a workaround. I want an SDK that follows modern conventions of the environment it's *deliberately* built for.

PutObjectAsync should not use any Sync IO, in other words it should not use `Stream.Read` it should use `Stream.ReadAsync`.

> Since this happens within the ASP.NET Core environment, this doesn't appear to be a bug in AWS .NET SDK, rather limitation/feature of .NET Core environment. Hope this helps.

Really? You're not going to a point a finger at a primary environment your SDK is supposed to run within?

I suggest you reconsider.

**Comment by ashishdhingra** [comment] 2020-11-08 00:49
@oliverjanik Thanks for your suggestion. My initial understanding was that synchronous operations were disabled in Kestrel Server which caused existing functionality to break, not sure if there was another similar issue reported. I understand `PutObjectAsync` should not use synchronous I/O. I would need to discuss the issue with developer to get more insight.

**Comment by ashishdhingra** [comment] 2020-11-12 00:40
Duplicate of https://github.com/aws/aws-sdk-net/issues/1534

**Comment by ashishdhingra** [comment] 2020-11-12 00:41
Hi @oliverjanik, @dsarfati,

Looks like this bug is duplicate of https://github.com/aws/aws-sdk-net/issues/1534. Please review and confirm if we could close this issue since the other bug is already tracked and prioritized.

Thanks,
Ashish

**Comment by ashishdhingra** [comment] 2020-11-12 16:58
Closing this as duplicate of https://github.com/aws/aws-sdk-net/issues/1534.

**Closed by ashishdhingra** 2020-11-12 16:58 UTC
Labels: bug, confusing-error, duplicate, module/s3, response-requested
