### ISSUE TITLE
AdminSetUserPassword: method not found

### ISSUE THREAD

**Issue by Forkosigan** [aws/aws-sdk-net#1320] opened 2019-06-20 21:03 UTC
I use VS2017 and use Nuget package manager. Last version of AWSSDK.core is 3.3.102.7.
My project is Net.Core 2.2
I try to find method AdminSetUserPassword in AmazonCognitoIdentityProviderClient but it is not exists

## Expected Behavior
method AdminSetUserPassword exists in class method AmazonCognitoIdentityProviderClient
## Current Behavior
method AdminSetUserPassword do not exists in class method AmazonCognitoIdentityProviderClient

## Your Environment

* AWSSDK.Core version used: 3.3.102.7
* Service assembly and version used: 
* Operating System and version: Windows 10
* Visual Studio version:  2017
* Targeted .NET platform: Net.Core 2.2

## .NET Core Info

* .NET Core version used for development: Net.Core 2.2
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`:  

Version:   2.2.202
Commit:    8a7ff6789d

???? ??????????:
OS Name:     Windows
OS Version:  10.0.17134
OS Platform: Windows
RID:         win10-x64
Base Path:   C:\Program Files\dotnet\sdk\2.2.202\

ost (useful for support):
 Version: 2.2.3
 Commit:  6b8ad509b6

NET Core SDKs installed:
 1.1.13 [C:\Program Files\dotnet\sdk]
 2.1.202 [C:\Program Files\dotnet\sdk]
 2.1.505 [C:\Program Files\dotnet\sdk]
 2.2.105 [C:\Program Files\dotnet\sdk]
 2.2.202 [C:\Program Files\dotnet\sdk]

NET Core runtimes installed:
 Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
 Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
 Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
 Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
 Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
 Microsoft.NETCore.App 1.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
 Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
 Microsoft.NETCore.App 1.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
 Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
 Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
 Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

o install additional .NET Core runtimes or SDKs:
 https://aka.ms/dotnet-download
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment] 2019-06-21 21:02
Thanks.  I think this should be in there, so I'm considering it a bug.  I'll let the others know and look into why we didn't already have it in there.

**Comment by assyadh** [comment] 2019-06-24 20:48
Hi,

I am unable to reproduce the issue. I pulled down the latest AWSSDK.CognitoIdentityProvider with a project targeting the netstandard and I have no issue calling AdminSetUserPassword()

I see you are mentioning AWSSDK.Core v3.3.102.7.

The  AdminSetUserPassword was made available in AmazonCognitoIdentityProviderClient starting AWSSDK.CognitoIdentityProvider v3.3.102.0.

Can you make sure you are targeting the latest version of the AWSSDK.CognitoIdentityProvider package?

**Comment by klaytaybai** [comment] 2019-06-24 21:00
I can't reproduce it anymore either on any of the recent releases, but I was able to when you opened the issue.  I'm not sure why that would be.  I say we close this out.  Let us know if you are still having issues for some reason.

**Closed by klaytaybai** 2019-06-24 21:00 UTC
Labels: bug

**Comment by klaytaybai** [comment] 2019-06-24 21:18
Also note that if you are using Nuget 3.x or later, Amazon.AspNetCore.Identity.Cognito's default AWSSDK.CognitoIdentityProvider package will be too old to include this method.
