### ISSUE TITLE
DynamoDB Stream - How to Deserialize DynamoDb stream JSON back to my original object? - Serializing and the Deserialising AttributeMap, List of Objects is Lost

### ISSUE THREAD

**Issue by coultonluke** [aws/aws-sdk-net#1980] opened 2022-02-21 12:19 UTC
## The Question

I have data in DynamoDB. I know the shape of it is a certain object, because it put it in there. The object in this case is `ObjectWithListObjects`. It contains a list of objects with a couple of properties on it:

    public class ObjectWithListObjects
    {
        public List<Translation> BrandFamilyTranslation { get; set; }
    }
 
    public class Translation
    {
        public string LanguageCode { get; set; }
        public string Value { get; set; }
    }

I'm subscribing a lambda to the DynamoDB stream. My lambda handler has a `DynamoDBEvent` property defined so that I can access the `NewImage` data of the stream.

It makes sense to me that I should be able to get from the DynamoDB stream object `NewImage` property back to my own object `ObjectWithListsObjects` again in my lambda, because I know the shape of the data that I put in. I figure that the .NET library is able to do essentially the same thing when using the object model, take the data from DynamoDB and turn it into an object so I wanted to do the same with the stream data.

I wrote a helper that looked promising at first but now I've found that the List (`L`) data is being lost, `Document.FromAttributeMap` interprets the list as an `AlwaysSendList` with the data in there...

![image](https://user-images.githubusercontent.com/16463338/154952682-93e64164-f90d-4a51-9b4f-71697ab4c0f2.png)

And then the `AnySendList` is then unable to be processed by the `dynamoDbContext.FromDocument<T>` call and is instead seen as a `DynamoDBNull` which can't be converted to my `List<Translation>`

![image](https://user-images.githubusercontent.com/16463338/154953163-17ee0657-d6bb-4f39-bf74-2811f62bded1.png)

I've created an NUnit test to show the issue in full from creating the object as an Attribute Map (`Dictionary<string,AttributeValue>`) which is the same shape as the `NewImage` property received in the DynamoDB stream, then I serialize it and then attempt to return it back to the object shape using `Document.FromAttributeMap` and then `context.FromDocument<T>` from the DynamoDB library.

     [Fact]
    public void WhyDoesntThisWork()
    {
        AmazonDynamoDBConfig clientConfig = new() { RegionEndpoint = RegionEndpoint.EUWest1 };
        DynamoDBContext dynamoDbContext = new(new AmazonDynamoDBClient(clientConfig));
 
        var initialAttributeMap = new Dictionary<string, AttributeValue>
        {
            {
                "BrandFamilyTranslation", new AttributeValue
                {
                    IsLSet = true,
                    L = new List<AttributeValue>
                    {
                        new AttributeValue
                        {
                            IsMSet = true,
                            M = new Dictionary<string, AttributeValue>
                            {
                                {"LanguageCode", new AttributeValue("en-GB")},
                                {"Value", new AttributeValue("Cookmaster 100")}
                            }
                        }
                    }
                }
            }
        };
 
        var serialised = JsonSerializer.Serialize(initialAttributeMap);
        var attsFromJson = JsonSerializer.Deserialize<Dictionary<string, AttributeValue>>(serialised);
        var dynamoDocument = Document.FromAttributeMap(attsFromJson);
        var mappedObject = dynamoDbContext.FromDocument<ObjectWithListObjects>(dynamoDocument);

        Assert.Single(mappedObject.BrandFamilyTranslation);
        Assert.Equal("Cookmaster 100", mappedObject.BrandFamilyTranslation.ElementAtOrDefault(0)?.Value);
        Assert.Equal("en-GB", mappedObject.BrandFamilyTranslation.ElementAtOrDefault(0)?.LanguageCode);
    } 

    public class ObjectWithListObjects
    {
        public List<Translation> BrandFamilyTranslation { get; set; }
    }
 
    public class Translation
    {
        public string LanguageCode { get; set; }
        public string Value { get; set; }
    }

In this example I have created the object using the object initializer, but I have also tried to create it by deserializing from the exact JSON that is received by my lambda function and that does the same thing. I'm happy to share the exact JSON if this would help.

If I'm completely going off off-piste here using the code I have written, is there an SDK supported way to convert the DynamoDB stream `NewImage` or `OldImage` straight to an object again because I know the shape that I put it in as?

### Environment

* SDK Version: AWSSDK.DynamoDBv2 
* Package Version: 3.7.0 
* OS Info: Windows 10 
* Build Environment: Rider 
* Targeted .NET Platform: net6.0

---

This is a :question: general question

**Comment by ashishdhingra** [comment] 2022-02-21 19:59
Hi @coultonluke,

Good morning.

Thanks for posting guidance question. I think you are affected by the issue https://github.com/aws/aws-sdk-net/issues/1887. I'm not sure if there is any workaround that could be suggested at this stage. Could you please thumbs up on the related issue so that there is enough votes for getting traction on it, closing this issue?

Thanks,
Ashish

**Comment by coultonluke** [comment] 2022-02-21 20:18
Yes it looks like the same issue. The example I've given is a List and their example is a Map, but looks like they both result in a `DynamoDBNull`.

How does the object model convert the DynamoDB result correctly if this doesn't work...?

Thanks again

**Comment by ashishdhingra** [comment] 2022-02-21 21:09
Changing this issue to bug. You may get more details about object model in https://github.com/aws/aws-sdk-net/blob/5b90d56a50322bfafc537b575232bd17cf9cfc0b/sdk/src/Services/DynamoDBv2/Custom/DataModel/Context.cs#L433.

Thanks,
Ashish

**Comment by ashishdhingra** [comment] 2022-02-21 21:11
Possible duplicate of https://github.com/aws/aws-sdk-net/issues/1887, but keeping it open for tracking purposes.

**Comment by ashishdhingra** [comment] 2022-04-19 16:59
@coultonluke PR https://github.com/aws/aws-sdk-net/pull/1983 is released in [AWSSDK.DynamoDBv2 (3.7.3.24)](https://www.nuget.org/packages/AWSSDK.DynamoDBv2/3.7.3.24). For now, you may manually update dependency to `AWSSDK.DynamoDBv2` in your Lambda project to new version. We would version bump the https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.DynamoDBEvents/Amazon.Lambda.DynamoDBEvents.csproj to include the reference to the new version and prepare it for release.

**Comment by ashishdhingra** [comment] 2022-05-03 03:05
[Amazon.Lambda.DynamoDBEvents version 2.1.1](https://www.nuget.org/packages/Amazon.Lambda.DynamoDBEvents/2.1.1) is released with the fix.

**Closed by ashishdhingra** 2022-05-03 03:05 UTC
Labels: bug, module/dynamodb, A, queued
