### ISSUE TITLE
Get-S3Bucket : Invalid URI: The format of the URI could not be determined.

### ISSUE THREAD

**Issue by KristofKuli** [aws/aws-sdk-net#3206] opened 2024-02-29 12:21 UTC
### Describe the bug

We are using Azure Devops pipeline to issue the above mentioned command, which currently throws the following error message:
Get-S3Bucket : Invalid URI: The format of the URI could not be determined.
We are using self-hosted agents, which are using Blueprint images from Microsoft. The command worked fine with AWSPowershell version 4.1.368, then the version has been updated in the Blueprint image, first to 4.1.487 and then to 4.1.518 and since we receive the mentioned error. The command is called during a custom Powershell script execution and it is connecting to an internal S3 instance. We are behind proxy, but in the script the target endpoint is added to the no_proxy environment variable, so the traffic should not go through the proxy.
Could you please help us investigate this problem?

### Expected Behavior

The Get-S3Bucket should list the buckets.

### Current Behavior

Currently we receive the following errors for different versions:
4.1.525 -- Invalid URI
4.1.518 -- Invalid URI
4.1.487 -- Bad Gateway
4.1.368 -- Bad Gateway

```
Get-S3Bucket : Error making request with Error Code BadGateway and Http Status Code BadGateway. No further error information was returned by the service.
At C:\a\1\au_module\scripts\Invoke-SCS3Upload.ps1:55 char:9
+         Get-S3Bucket -EndpointUrl $endpoint -Verbose
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Amazon.PowerShell.C…3.GetS3BucketCmdlet:GetS3BucketCmdlet) [Get-S3Bucket], InvalidOperationException
+ FullyQualifiedErrorId : Amazon.S3.AmazonS3Exception,Amazon.PowerShell.Cmdlets.S3.GetS3BucketCmdlet
##[error]PowerShell exited with code '1'.
```

```
Get-S3Bucket : Invalid URI: The format of the URI could not be determined.
At C:\a\1\au_module\scripts\Invoke-SCS3Upload.ps1:55 char:9
+         Get-S3Bucket -EndpointUrl $endpoint -Verbose
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Amazon.PowerShell.C…3.GetS3BucketCmdlet:GetS3BucketCmdlet) [Get-S3Bucket], InvalidOperationException
+ FullyQualifiedErrorId : System.UriFormatException,Amazon.PowerShell.Cmdlets.S3.GetS3BucketCmdlet
##[error]PowerShell exited with code '1'.
```

### Reproduction Steps

Since the endpoint is an internal site, therefore I can't provide reproduction steps.

### AWS .NET SDK and/or Package version used

AWSPowershell
4.1.525
4.1.518
4.1.487
4.1.368

### Targeted .NET Platform

.NET Framework 4.8.1

### Operating System and version

Windows Server 2022

**Comment by dscpinheiro** [comment] 2024-02-29 12:24
Could this be related to https://github.com/aws/aws-sdk-net/issues/3198? We added support for `http_proxy` a while ago, but `no_proxy` was missing (this was fixed in version `4.1.525` of the `AWSPowershell` modules).

**Comment by KristofKuli** [comment] 2024-02-29 12:30
Hi Daniel,

Yes, we have checked this issue yesterday, but even with 4.1.525, we are getting this "Invalid URI" error and from that message it's hard to decide, where the issue is coming from exactly. In the "Current Behavior" section I have specified the versions being tried and the respective error messages.

**Comment by dscpinheiro** [comment] 2024-02-29 13:01
I'm not sure if you can share it, but what does your `no_proxy` look like? I know we're not ignoring it anymore, but from the [PR](https://github.com/aws/aws-sdk-net/pull/3200):
> The full implementation of no_proxy would involve DNS resolution to IP address and CIDR matching. That is a much larger scope to integrate into the SDK and for the SDK's use cases unlikely to be needed. This implementation does host name matching with wildcard support matching the Java and Kotlin SDK's implementation.

**Comment by KristofKuli** [comment] 2024-03-01 10:39
$noProxyComma

**Comment by afroz429** [comment] 2024-03-07 16:53
Please enable logging to see if it helps. PowerShell logging can be enabled with below commands.

```
    Add-AWSLoggingListener -Name "AWS Logs" -LogFilePath "C:\Logs\ps-logs.txt" # or any path
    Set-AWSResponseLogging Always
    Enable-AWSMetricsLogging
```

**Comment by KristofKuli** [comment] 2024-03-14 09:53
Hi @afroz429,

We have enabled the logging, but it doesn't provide any extra information.
`Amazon Error: 1 : UriFormatException making request ListBucketsRequest to [https://example.target.company.com/.](https://example.target.company.com/) Attempt 1., System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)`

**Comment by KristofKuli** [comment] 2024-03-20 09:44
Hi All,

Is there anything else, which can be tried? Do you see anything in the source code of AWSPowershell, which could cause this issue?

**Comment by KristofKuli** [comment] 2024-03-21 07:29
Hi,

I have checked the URL with the command you have provided, but it doesn't display any error, it list the details of the URL properly. This issue was reported by one of our customer, who came across with this problem. For testing purpose, I have created an S3 Bucket and currently testing the connection from the Azure Devops pipeline. I am receiving Service Unavailable, when it tries to connect, hence I assume the command in not recognizing the no_proxy env var. I am pasting the task configuration below:
```
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $Env:no_proxy="https://example.target.company.com"
      
      cd $(System.DefaultWorkingDirectory)
      
      Add-AWSLoggingListener -Name "AWS Logs" -LogFilePath "ps-logs.txt"
      
      Set-AWSResponseLogging Always
      
      Enable-AWSMetricsLogging
      
      Install-Module -Name AWSPowerShell -RequiredVersion 4.1.525 -Force
      
      Get-Package -Name AWSPowershell
      
      Set-AWSCredential -AccessKey $(accessKey) -SecretKey $(sharedSecret)
      
      Get-S3Bucket -EndpointUrl https://example.target.company.com
```

The error I receive is the following:
```
`Get-S3Bucket : Error making request with Error Code ServiceUnavailable and Http Status Code ServiceUnavailable. No 
further error information was returned by the service.
At C:\a\_temp\d03dbdf9-edcd-4ba4-a685-1df89a5b0f50.ps1:13 char:1
+ Get-S3Bucket -EndpointUrl https://example.target.company.com/
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Amazon.PowerShe...tS3BucketCmdlet:GetS3BucketCmdlet) [Get-S3Bucket],  
   InvalidOperationException
    + FullyQualifiedErrorId : Amazon.S3.AmazonS3Exception,Amazon.PowerShell.Cmdlets.S3.GetS3BucketCmdlet
 
##[error]PowerShell exited with code '1'.`
```

**Comment by KristofKuli** [comment] 2024-03-22 13:48
Update:
I have installed the latest AWSPowershell version (4.1.542) locally and found this strange behavior:

1. If I use the default proxy settings on my workstation, then the Get-S3Bucket command fails with 503 Service Unavailable. The target is an internal site, hence the connection should not use the proxy. By default the no_proxy contains the domain of the target, but despite that I receive the above mentioned error.
2. If I include the target URL, then the connection still not working.
3. If I delete the value of https_proxy and http_proxy env vars and I use the default version of no_proxy value from point 1, then the connection works.
4. If I unset everything, so http_proxy, https_proxy and no_proxy is empty, then the connection is working.

In pipeline:
The same steps have been tried and the only thing to make it work, is to unset everything. So it seems, the no_proxy is getting recognized only, then the http_proxy and https_proxy variables have been unset.

**Comment by KristofKuli** [comment] 2024-04-02 08:31
Hi,
has anyone reviewed my previous comment and was able to reproduce the issue? I am trying to figure out, whether there's a bug in AWSPowershell module or I am messing up something.

**Comment by dscpinheiro** [comment] 2024-04-02 11:17
Nobody in our team was able to reproduce the problem (we also confirmed the latest version of PowerShell recognizes all of `http_proxy`, `https_proxy`, and `no_proxy`).

We created an internal backlog item to (optionally) turn off checking for those environment variables but it hasn’t been prioritized yet (FYI: For the error you described this is the only report we received, so we believe it’s unfortunately an issue with your setup - especially the _internal S3 instance_ part).

**Comment by kellertk** [comment] 2024-04-16 20:47
Hi folks, we're only able to assist you in troubleshooting the use of the .NET SDK with S3 proper, not an internal service that is emulating S3. Since we haven't been able to reproduce this issue, I will be closing it. 

If I'm not correct and you are talking to the actual S3 service, please let me know and I'll reopen this.

**Closed by kellertk** 2024-04-16 20:47 UTC
Labels: bug, s3, p2, queued
