### ISSUE TITLE
Forgot Password flow doesn't working

### ISSUE THREAD

**Issue by fredericof** [aws/aws-sdk-net#1702] opened 2020-09-11 00:43 UTC
I'm currently developing the forgot password flow. Starting by calling ForgotPassword method that sends to my email a confirmation code, but when I set confirmation code at the ConfirmForgotPassword method, it throws ExpiredCodeException. Another weird thing I realized is that Account Status of User does not changes to "Enabled / RESET_REQUIRED".

**Comment by ashishdhingra** [comment] 2020-09-11 16:15
Hi @fredericof,

Good morning.

Thanks for reporting the bug. I'm assuming you are using Cognito extension for ASP.NET. In that case, it would be better if we could transfer this issue to https://github.com/aws/aws-aspnet-cognito-identity-provider repository. Also, request you to share the sample code (with sensitive information removed) to troubleshoot the issue. 

Thanks,
Ashish

**Comment by fredericof** [comment] 2020-09-11 18:06
Hi @ashishdhingra 
Yeap! I'm using Cognito extension for .Net. I will transfer that issue to the specific repository. 

Thanks for the answer,
Frederico

**Comment by ashishdhingra** [comment] 2020-09-14 20:21
Closing as duplicate of https://github.com/aws/aws-aspnet-cognito-identity-provider/issues/171

**Closed by ashishdhingra** 2020-09-14 20:21 UTC
Labels: bug, duplicate, module/credentials, needs-triage
