### ISSUE TITLE
Can't save a returned stream

### ISSUE THREAD

**Issue by btecu** [aws/aws-sdk-net#1592] opened 2020-04-29 16:03 UTC
This seems like a major inconsistency:

```
// Retrieve document Stream
var obj = await S3Client.GetObjectAsync(bucketName, key);

// Save it to a different client
var transfer = new TransferUtilityUploadRequest {
	InputStream = stream,
	BucketName = otherBucketName,
	Key = key
};

await new TransferUtility(OtherS3Client).UploadAsync(transfer);
```

**NotSupportedException: HashStream does not support seeking**

This does not work because `GetObjectAsync` returns a `HashStream` which does not have `length` but on the other hand, `UploadAsync` expects a stream that `CanSeek`.

**Comment by renaudcalmont** [comment] 2021-03-19 07:29
Duplicate of #1200 that was labelled "won't fix"

However I agree that's a super annoying inconsistency. The upload could quite easily take the stream length as a parameter (with fallback on the current method) and let the caller manage the way to provide this information.

**Comment by normj** [comment] 2022-02-14 08:27
Content-Length being required is a design of S3 not the SDK. I'm closing this because from the SDKs point of view we can't change S3's requirement.

**Closed by normj** 2022-02-14 08:27 UTC
Labels: feature-request, module/s3, needs-review
