### ISSUE TITLE
AmazonS3Client.GetObjectMetadataAsync() throw exception for filename with space character

### ISSUE THREAD

**Issue by akivamu** [aws/aws-sdk-net#1894] opened 2021-08-06 05:12 UTC
## Description
I have a s3 filename with space in it: `has space.txt`.
The url shown in AWS console in entry "Object URL" is `https://bucket.s3.amazonaws.com/has+space.txt`.
When calling `AmazonS3Client.GetObjectMetadataAsync()`, passing the request with prop `Key = "has+space.txt"`, it throws exception:
```
Amazon.S3.AmazonS3Exception: Error making request with Error Code NotFound and Http Status Code NotFound. No further error information was returned by the service. ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
```

So there are 2 issues here:
1. `AmazonS3Uri()` doesn't decode `+` to ` ` (space) in key.
2. `AmazonS3Client.GetObjectMetadataAsync()` doesn't accept the key parsed by `AmazonS3Uri()` if there's space in filename.

I can manually scan and replace `+` to ` ` (space), but shouldn't be, right? Because the `GetObjectMetadataRequest` should accept the result `Key` from `AmazonS3Uri`.

## Reproduction Steps
Using this testcase, bucket name is just an example.
```
// The file name is 'has space.txt'
// This URL is copied from AWS console in entry "Object URL"
var url = "https://bucket.s3.amazonaws.com/has+space.txt";

// Use AmazonS3Uri() to parse URL
var s3Uri = new AmazonS3Uri(url);

// Build the request
var req= new GetObjectMetadataRequest()
{
    BucketName = s3Uri.Bucket,
    Key = s3Uri.Key, // value here is `has+space.txt`. If manually set to `has space.txt`, the request below is success.
};

// And client
var s3Client = new AmazonS3Client(awsKeyId, awsKeySecret, RegionEndpoint.GetBySystemName(awsRegion));

// Do request and got exception
var res = await s3Client.GetObjectMetadataAsync(req); // throw exception
```

### Environment

* SDK Version: AWSSDK.S3:3.7.1.20
* Package Version: AWSSDK.S3:3.7.1.20
* OS Info: Windows 10
* Build Environment Visual Studio 2019
* Targeted .NET Platform:  net5.0

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment] 2021-08-06 16:23
Issue reproducible using the code provided by customer. Upload the object to S3 which has space character in file name. AWS S3 Console will show the uploaded object with key name having space (as expected), use `Copy URL` from S3 console to use the URL in the code above. Manually changing `+` to space character resolves the issue.

**Question:** should `AmazonS3Uri` automatically decode `+` and other escaped characters (also known as percent-encoded octets) that don't have a reserved purpose (refer .NET [Uri Class](https://docs.microsoft.com/en-us/dotnet/api/system.uri?view=net-5.0))?

**Comment by ashishdhingra** [comment] 2021-08-06 22:27
`AmazonS3Uri` class uses `System.Uri` class. Here is some behavior of `System.Uri` class:
```C#
using System;

namespace UriTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var urlWithPlus = "https://somebucket.s3.us-east-2.amazonaws.com/C8624825821_S3+Log";
            var urlWithSpace = "https://somebucket.s3.us-east-2.amazonaws.com/C8624825821_S3 Log";
            var urlwithEncodedSpace = "https://somebucket.s3.us-east-2.amazonaws.com/C8624825821_S3%2BLog";

            Uri uriWithPlus = new Uri(urlWithPlus);
            Uri uriWithSpace = new Uri(urlWithSpace);
            Uri uriWithEncodedSpace = new Uri(urlwithEncodedSpace);

            Console.WriteLine($"URL with Plus LocalPath: {uriWithPlus.LocalPath}");
            Console.WriteLine($"URL with Space LocalPath: {uriWithSpace.LocalPath}");
            Console.WriteLine($"URL with Encoded Space LocalPath: {uriWithEncodedSpace.LocalPath}");
        }
    }
}
```
This produces the output:
```
URL with Plus LocalPath: /C8624825821_S3+Log
URL with Space LocalPath: /C8624825821_S3 Log
URL with Encoded Space LocalPath: /C8624825821_S3+Log
```
Per [System.Uri](https://docs.microsoft.com/en-us/dotnet/api/system.uri?view=netcore-3.1) documentation, `Escaped characters (also known as percent-encoded octets) that don't have a reserved purpose are decoded (also known as being unescaped). These unreserved characters include uppercase and lowercase letters (%41-%5A and %61-%7A), decimal digits (%30-%39), hyphen (%2D), period (%2E), underscore (%5F), and tilde (%7E)`.

Amazon S3 buckets allows space and `+` characters in object key. Hence, if object key is like `C8624825821_S3+Log`, then changing `+` to space would be incorrect and may result in unintended side-effects (imagine there are 2 objects named `C8624825821_S3+Log` and `C8624825821_S3 Log`. Changing `+` to space character and using this new key to delete operation would result in incorrect object being deleted).

**Comment by akivamu** [comment] 2021-08-13 03:02
Hi @ashishdhingra 

So is it planned to fix?

**Comment by ashishdhingra** [comment] 2021-08-20 20:25
@akivamu Based on our analysis, we could not change the existing behavior of `AmazonS3Uri` since that would be a breaking change for existing users. What we might possibly be able to do is to provide an overloaded constructor for `AmazonS3Uri` which accepts boolean parameter `shouldDecode`. If the value for this parameter is `true`, then we can attempt to decode the URL (e.g. changing "+" to space). The default value `false` would retain the existing behavior. Please advise if this is an acceptable solution for your use case.

**Comment by akivamu** [comment] 2021-08-23 03:42
Thanks @ashishdhingra that solution should work to me.

**Comment by ashishdhingra** [comment] 2021-11-05 03:59
Fixed in [AWSSDK.S3 (3.7.4.0)](https://www.nuget.org/packages/AWSSDK.S3/3.7.4)

**Closed** 2021-11-05 03:59 UTC
Labels: bug, module/s3, B
