### ISSUE TITLE
Amazon.Imagebuilder.Model.ImageVersion.DateCreated is a string

### ISSUE THREAD

**Issue by ryanwilliams83** [aws/aws-sdk-net#1916] opened 2021-09-21 07:14 UTC
## Describe the Feature
Change Amazon.Imagebuilder.Model.ImageVersion.DateCreated into a DateTime

## Additional Context
I am trying to create a Lambda function to erase old Image Versions then subsequently erase any orphaned AMI's and their EBS snapshots.
Perhaps you should consider integrating EC2 LifeCycle manager with Image Builder to allow old AMI's to be cleaned up.

### Environment
* [] :wave: I may be able to implement this feature request
* [X] :warning: This feature might incur a breaking change  

---

This is a :rocket: Feature Request

**Comment by ashishdhingra** [comment] 2021-09-21 16:24
Hi @ryanwilliams83,

Good morning.

Thanks for submitting the feature request. Upon examining further, looks like the [Imagebuilder](https://github.com/aws/aws-sdk-net/tree/master/sdk/src/Services/Imagebuilder) code is auto-generated from [service model](https://github.com/aws/aws-sdk-net/blob/master/generator/ServiceModels/imagebuilder/imagebuilder-2019-12-02.api.json). The [ImageVersion](https://github.com/aws/aws-sdk-net/blob/b89c12964f8c9c2ccd45676ad4de69594ed68e55/generator/ServiceModels/imagebuilder/imagebuilder-2019-12-02.api.json#L2101) `dateCreated` property is modeled with [DateTime](https://github.com/aws/aws-sdk-net/blob/b89c12964f8c9c2ccd45676ad4de69594ed68e55/generator/ServiceModels/imagebuilder/imagebuilder-2019-12-02.api.json#L1465) shape which is of type `string`. Hence in the the auto-generated model class, it is of type string.

Also, if you refer the [EC2 Image Builder API Reference](https://docs.aws.amazon.com/imagebuilder/latest/APIReference/Welcome.html), in [ImageVersion](https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_ImageVersion.html) data type, the `dateCreated` property is of type `string`. I might be able to contact service team for their inputs, however, since any service specific change impacts many customers, I do not see this change getting prioritized.

Since this is not a bug in SDK as it relies on service models and also not a feasible feature request, closing this issue as designed.

Thanks,
Ashish

**Closed by ashishdhingra** 2021-09-21 16:24 UTC
Labels: feature-request, needs-triage, module/sdk-generated
