### ISSUE TITLE
DeleteBucketAsync throws UriFormatException when used with default S3 region

### ISSUE THREAD

**Issue by danielmarbach** [aws/aws-sdk-net#1583] opened 2020-04-22 11:59 UTC
## Expected Behavior

It should work by passing the location to the delete bucket request

## Current Behavior

```
            if (await s3.DoesS3BucketExistAsync(bucketName))
            {
                var response = await s3.GetBucketLocationAsync(bucketName);
                var deleteRequest = new DeleteBucketRequest
                {
                    BucketName = bucketName,
                    BucketRegion = response.Location,
                };

                await s3.DeleteBucketAsync(deleteRequest).ConfigureAwait(false);

            }
```

works for most regions but `us-east-1`.

The service returns `new S3Region("")` this hen is tried to be translated by the RegionEndpoint resolver into a service URL and throws

```
System.UriFormatException : Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Amazon.Runtime.ClientConfig.GetUrl(RegionEndpoint regionEndpoint, String regionEndpointServiceName, Boolean useHttp, Boolean useDualStack)
   at Amazon.Runtime.Internal.EndpointResolver.DetermineEndpoint(IClientConfig config, IRequest request)
   at Amazon.S3.Internal.AmazonS3PostMarshallHandler.ProcessRequestHandlers(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3PostMarshallHandler.PreInvoke(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3PostMarshallHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Marshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3PreMarshallHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.<>n__0[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
```

the reason being the service map has no entry for region `""`

## Possible Solution

Change the code to

```
            if (await s3.DoesS3BucketExistAsync(bucketName))
            {
                var response = await s3.GetBucketLocationAsync(bucketName);
                S3Region region;
                switch (response.Location)
                {
                    case "":
                    {
                        region = new S3Region("us-east-1");
                        break;
                    }
                    case "EU":
                    {
                        region = S3Region.EUW1;
                        break;
                    }
                    default:
                        region = response.Location;
                        break;
                }

                var deleteRequest = new DeleteBucketRequest
                {
                    BucketName = bucketName,
                    BucketRegion = region,
                };

                await s3.DeleteBucketAsync(deleteRequest).ConfigureAwait(false);
            }
```
## Steps to Reproduce (for bugs)

Execute the snippet with an existing bucket in us-east-1

## Your Environment

* AWSSDK.Core version used:  latest
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.1.804 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by ashishdhingra** [comment] 2020-07-23 20:30
Hi @danielmarbach,

Thanks for reporting the issue. Using the latest .NET SDK version, I was able to validate that _s3Client.GetBucketLocationAsync(bucketName)_ for **us-east-1** region returns a blank location. Due to this the subsequent _DeleteBucketRequest()_ call, as specified in the code snippet shared by you, fails.

However, I noticed that if we create a DeleteBucketRequest without specifying the BucketRegion, the delete operation is successful. Also note that bucket names are unique in time and space.

```C#
var deleteRequest = new DeleteBucketRequest
{
    BucketName = bucketName
};
```

Please advise if there is a specific need to use bucket location while creating DeleteBucketRequest.

Thanks,
Ashish

**Comment by danielmarbach** [comment] 2020-07-24 11:34
Thanks for looking into this. I don't really understand your question. The whole reason why I opened this case is the first snippet and the non intuitive behaviour of the SDK. For any bucket that resides outside the default region the location needs to be specified. Hence I wrote the code to first query the location and then pass the location to the deletion request since this occurred to me as the most appropriate "generic" way of deleting a bucket. Unfortunately the default empty region is not mapped and bombs with the mentioned exception. I would consider this as an area of improvement for the SDK. If you disagree with my reasoning feel free to close

**Comment by ashishdhingra** [comment] 2020-07-24 17:25
Hi @danielmarbach,

Thanks for your reply. I will try to reproduce the issue with additional scenarios and get back to you on this.

Regards,
Ashish

**Comment by normj** [comment] 2020-07-24 19:20
Hi @danielmarbach 

This goes back to legacy behavior when S3 was launched us-east-1 the concept of regions didn't exist. The get bucket location returns back inconsistent values for us-east-1 and eu-west-1 compared to the rest of the AWS regions.

I agree the SDK should be handling this inconsistency and your first code snippet should work. Looks like the bug is the DeleteBucketRequestMarshaller which is not compensating for us-east-1 and eu-west-1.

https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/Model/Internal/MarshallTransformations/DeleteBucketRequestMarshaller.cs#L45

We will get this fixed so your original code will work and you want have to do your workaround code.

**Comment by SrutiG** [comment] 2020-08-05 18:36
We have released a possible fix for this issue in AWSSDK.S3 v3.3.111.37

Please let us know if you are still having problems using this version

**Comment by rbrus** [comment] 2020-08-11 03:50
I believe that I created my S3 bucket on USEast1, when I query for its location the value is empty. AWSSDK.S3 - Version: 3.3.112.1.

**Comment by ashishdhingra** [comment] 2020-11-13 21:14
Hi @rbrus,

Per my discussion with developer, `us-east-1` is one of the legacy code regions and that always returns empty string for bucket location. The fix implemented was for the delete bucket operation.

Thanks,
Ashish

**Closed by ashishdhingra** 2020-11-13 21:14 UTC
Labels: bug, module/s3
