### ISSUE TITLE
DeleteChannelAsync does not return anything

### ISSUE THREAD

**Issue by evan-winata** [aws/aws-sdk-net#1011] opened 2018-07-25 05:25 UTC
Whenever I call await DeleteChannelAsync(...), the code hangs on that line, not returning anything.

## Expected Behavior
The DeleteChannelAsync(...) should return DeleteChannelResponse object.

## Current Behavior
I tried to run:
var deleteChannelResponse = await DeleteChannelAsync(new DeleteChannelRequest() {ChannelId = channelId}),
The code stucks there, not returning anything nor going to the next line.

## Steps to Reproduce (for bugs)
Try the following code (change channelId variable with existing channel id):
var deleteChannelResponse = await DeleteChannelAsync(new DeleteChannelRequest() {ChannelId = channelId}),

## Context
I'm trying to delete both Channel and input attached to it. Before the input can be deleted, the channel needs to be deleted first, therefore detaching the input from the channel. If I'm calling normal DeleteChannel and DeleteInput directly after that, AWS throws an exception saying that the input is still busy (because it's still attached to the channel). By using async channel deletion, it seems it will be possible to delete the input safely after the channel is deleted properly.

## Your Environment
* AWSSDK.Core version used: 3.3.24.3
* Service assembly and version used: 
* Operating System and version: Windows 10 Pro
* Visual Studio version: VS 2017
* Targeted .NET platform: 4.6.1

**Comment by gokarnm** [comment] 2018-07-27 16:32
Hi @evan-winata , I'm unable to replicate the issue using similar environment. Could you provide more information?

- Are you seeing the same behavior every time?
- Is this request being executed under load?
- Could you describe the application e.g. is this a Lambda function, a web application?

**Comment by evan-winata** [comment] 2018-07-30 00:40
Hi @gokarnm , yes I'm seeing the same behavior everytime. It is executed under almost no load at all. I called the method from a web API. Every time I debug, the code just hangs on the delete async line, not returning anything.

**Comment by klaytaybai** [comment] 2019-11-18 21:31
Closing due to age and inability to reproduce.  Please reopen if this is still an issue.

**Closed by klaytaybai** 2019-11-18 21:31 UTC
Labels: investigating
