### ISSUE TITLE
Using aws cmdlets with s3 compatible storage has a 15 second delay before communicating with the endpointurl

### ISSUE THREAD

**Issue by nocentino** [aws/aws-sdk-net#3030] opened 2023-08-17 21:38 UTC
### Describe the bug

Using `Get-S3Object ` and conjunction with the `-endpointurl` parameter the cmdlet attempts to retrieve instance metadata. Since this execution is not on an EC2 instance there is a delay which the attempt to get instance metadata times out. This is approximately 15 seconds. Once it times out the connection to s3 compatible storage works fine.  If you specify a -Region parameter with any value the cmdlet works properly, in a timely fashion. 

### Expected Behavior

When using the `endpointurl` parameter I would expect the ability to disable the instance metadata check. 

### Current Behavior

There is a 15 second delay due to connection retry attempts on retrieving instance metadata 

### Reproduction Steps

`Get-S3Object -BucketName sql-dumps -SecretKey $SecretKey -AccessKey $AccessKey -endpointurl https://PRIVATEENDPOINTURL
`

### Possible Solution

Allow a `-Region` parameter value of None to be set to bypass the instance metadata check

### AWS .NET SDK and/or Package version used

AWSPowerShell 4.1.348

### Targeted .NET Platform

.NET Core 

### Operating System and version

Windows Server 2016

**Comment by nocentino** [comment] 2023-08-17 21:41
Apologies, wrong repo. Opened on proper repo at https://github.com/aws/aws-tools-for-powershell/issues/330

**Comment by ashishdhingra** [comment] 2023-08-18 15:56
Duplicate of https://github.com/aws/aws-tools-for-powershell/issues/330

**Closed by ashishdhingra** 2023-08-18 15:56 UTC
Labels: bug, needs-triage
