### ISSUE TITLE
Delay in loading the credentials

### ISSUE THREAD

**Issue by dumitrascuSorin** [aws/aws-sdk-net#2080] opened 2022-07-28 12:14 UTC
### Describe the bug

Hi,

I'm using the AWSSDK.Core in a .NET 6 project and I noticed that in a production hosting environment there is a considerable delay (around 16 seconds) from the moment the AWS credentials are found until the controller action method is actually executed.
The credentials are stored in a shared credentials file, but I'm using a custom name and location.
Registering the AWS Services with a scoped lifetime in the DI container makes things even worse, as this delay can be noticed for each request.

Please see the attached logs and the sample project for more details.

### Expected Behavior

When using a shared credentials file, I wouldn't expect any considerable delay between the moment the credentials are found and the action method being executed.
When running the referenced sample project locally on IIS Express I do not encounter this bug.
Please see the following logs from my local machine: 
[28-07-2022 13:35:13.586 +02:00  INF]  Request starting HTTP/1.1 GET http://localhost:21956/WeatherForecast - -
[28-07-2022 13:35:13.595 +02:00  INF]  Executing endpoint 'AWS.SES.NET6.Controllers.WeatherForecastController.Get (AWS.SES.NET6)'
[28-07-2022 13:35:13.606 +02:00  INF]  Route matched with {action = "Get", controller = "WeatherForecast"}. Executing controller action with signature System.Collections.Generic.IEnumerable`1[AWS.SES.NET6.WeatherForecast] Get() on controller AWS.SES.NET6.Controllers.WeatherForecastController (AWS.SES.NET6).
[28-07-2022 **13:35:13.649** +02:00  INF]  Found AWS credentials for the profile test-profile
[28-07-2022 **13:35:13.792** +02:00  INF]  Executing ObjectResult, writing value of type 'AWS.SES.NET6.WeatherForecast[]'.
[28-07-2022 13:35:13.804 +02:00  INF]  Executed action AWS.SES.NET6.Controllers.WeatherForecastController.Get (AWS.SES.NET6) in 193.8871ms
[28-07-2022 13:35:13.807 +02:00  INF]  Executed endpoint 'AWS.SES.NET6.Controllers.WeatherForecastController.Get (AWS.SES.NET6)'
[28-07-2022 13:35:13.808 +02:00  INF]  Request finished HTTP/1.1 GET http://localhost:21956/WeatherForecast - - - 200 - application/json;+charset=utf-8 **221.5434ms**

### Current Behavior

When deploying the app in production environment, there is a consistent delay each time a request is sent.
Please see the following logs from the staging environment:
[28-07-2022 07:05:21.802 -04:00  INF]  Request starting HTTP/1.1 GET http://localhost:89/weatherforecast - -
[28-07-2022 07:05:21.803 -04:00  INF]  Executing endpoint 'AWS.SES.NET6.Controllers.WeatherForecastController.Get (AWS.SES.NET6)'
[28-07-2022 07:05:21.804 -04:00  INF]  Route matched with {action = "Get", controller = "WeatherForecast"}. Executing controller action with signature System.Collections.Generic.IEnumerable`1[AWS.SES.NET6.WeatherForecast] Get() on controller AWS.SES.NET6.Controllers.WeatherForecastController (AWS.SES.NET6).
[28-07-2022 **07:05:21.80**5 -04:00  INF]  Found AWS credentials for the profile test-profile
[28-07-2022 **07:05:37.574** -04:00  INF]  Executing ObjectResult, writing value of type 'AWS.SES.NET6.WeatherForecast[]'.
[28-07-2022 07:05:37.575 -04:00  INF]  Executed action AWS.SES.NET6.Controllers.WeatherForecastController.Get (AWS.SES.NET6) in 15771.0262ms
[28-07-2022 07:05:37.575 -04:00  INF]  Executed endpoint 'AWS.SES.NET6.Controllers.WeatherForecastController.Get (AWS.SES.NET6)'
[28-07-2022 07:05:37.576 -04:00  INF]  Request finished HTTP/1.1 GET http://localhost:89/weatherforecast - - - 200 - application/json;+charset=utf-8 **15773.1153m**s

### Reproduction Steps

I put up together a sample project which can be cloned from this repo
[https://github.com/dumitrascuSorin/AwsCredentialsSample](https://github.com/dumitrascuSorin/AwsCredentialsSample)

### AWS .NET SDK and/or Package version used

AWSSDK.Core 3.7.12.14
AWSSDK.Extensions.NETCore.Setup 3.7.2
AWSSDK.SimpleEmail 3.7.0.185

### Targeted .NET Platform

.NET 6

### Operating System and version

**Local machine**: 
Windows 10 Enterprise 
Version 21H2 
OS build 19044.1826

**Staging environment**
Windows Server 2019 Standard
VErsion 1809
OS Build 17763.3165

**Comment by dumitrascuSorin** [comment] 2022-07-29 07:24
FYI, I just downgraded the AWSSDK.Extensions.NETCore.Setup package to version 3.7.0 from 3.7.2 and the delay is no longer there

**Comment by ashishdhingra** [comment] 2022-07-29 19:50
> FYI, I just downgraded the AWSSDK.Extensions.NETCore.Setup package to version 3.7.0 from 3.7.2 and the delay is no longer there

Could be related to https://github.com/aws/aws-sdk-net/issues/2000. @dumitrascuSorin Could we close this issue as duplicate of https://github.com/aws/aws-sdk-net/issues/2000?

**Comment by dumitrascuSorin** [comment] 2022-07-31 17:05
Sure, this can be closed as a duplicate of issue 2000

**Closed** 2022-07-31 17:06 UTC
Labels: bug, module/credentials, perf
