### ISSUE TITLE
WriteGetObjectResponseAsync throws AmazonClientException: ChunkedUploadWrapperStream was initialized without a SigV4 or SigV4a signing result

### ISSUE THREAD

**Issue by chrischappell-rgare** [aws/aws-sdk-net#2519] opened 2023-01-13 18:08 UTC
### Describe the bug

When an S3 Object Lambda calls AmazonS3Client.WriteGetObjectResponseAsync with the request body having a response stream retrieved using GetObjectAsync an exception is thrown.

This does not happen when the WriteGetObjectResponseRequest.Body is a MemoryStream or it is a stream retrieved using an HttpClient with the InputS3Url.

### Expected Behavior

WriteGetObjectResponseAsync should succeed.

### Current Behavior

AmazonClientException is thrown.

Amazon.Runtime.AmazonClientException: ChunkedUploadWrapperStream was initialized without a SigV4 or SigV4a signing result.\n   at Amazon.Runtime.Internal.Util.ChunkedUploadWrapperStream..ctor(Stream stream, Int32 wrappedStreamBufferSize, AWSSigningResultBase headerSigningResult)\n   at Amazon.Runtime.Internal.HttpHandler`1.GetInputStream(IRequestContext requestContext, Stream originalStream, IRequest wrappedRequest)\n   at Amazon.Runtime.Internal.HttpHandler`1.WriteContentToRequestBody(TRequestContent requestContent, IHttpRequest`1 httpRequest, IRequestContext requestContext)\n   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.RedirectHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)\n 

### Reproduction Steps

```
public class Functions
{
    public async Task Convert(S3ObjectLambdaEvent olapEvent, ILambdaContext context)
    {
		using var s3 = new AmazonS3Client();
		var bucket = "bucket-name";
		var uri = new Uri(olapEvent.UserRequest.Url);
		var key = string.Concat(uri.Segments[1..]);

		using var response = await s3.GetObjectAsync(bucket, key);
		var request = new WriteGetObjectResponseRequest
		{
			StatusCode = (int)response.HttpStatusCode,
			RequestRoute = olapEvent.GetObjectContext.OutputRoute,
			RequestToken = olapEvent.GetObjectContext.OutputToken,
			Body = response.ResponseStream
		};

		await s3.WriteGetObjectResponseAsync(request);
    }
}
```

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.101.48
AWSSDK.Core 3.7.103.10

### Targeted .NET Platform

.NET 6

### Operating System and version

AmazonLinux

**Comment by ashishdhingra** [comment] 2023-01-13 22:42
Reproducible using the test code below (Values for `RequestRoute` and `RequestToken` are dummy values for reproduction, refer [Writing Lambda functions for S3 Object Lambda access points](https://docs.aws.amazon.com/AmazonS3/latest/userguide/olap-writing-lambda.html) or customer's code on how to get actual values):
```C#
using Amazon.S3.Model;
using Amazon.S3;

using var s3 = new AmazonS3Client();
var bucket = "bucket-name";
var key = "samplefile.zip";

using var response = await s3.GetObjectAsync(bucket, key);
var request = new WriteGetObjectResponseRequest
{
    StatusCode = (int)response.HttpStatusCode,
    RequestRoute = "testroute",
    RequestToken = "testtoken",
    Body = response.ResponseStream
};

var writeGetObjectResponse = await s3.WriteGetObjectResponseAsync(request);
Console.WriteLine(writeGetObjectResponse.HttpStatusCode);
```

**Code Flow:**
While using the above code where we use the `ResponseStream` directly,
- `request.UseChunkEncoding` is `false` at [S3Signer.Sign()](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Internal/Auth/S3Signer.cs#L82), hence `request.AWS4SignerResult` is not set.
- In [HttpHandler.GetInputStream()](https://github.com/aws/aws-sdk-net/blob/13331e34867205d9705679d2fb197c754423fd7f/sdk/src/Core/Amazon.Runtime/Pipeline/HttpHandler/HttpHandler.cs#L540), the stream resolves to `ChunkedUploadWrapperStream` due to `isTransferEncodingHeaderChunked` resolving to `true`.
- Due to above evaluation, exception is thrown at [ChunkedUploadWrapperStream::ctor()](https://github.com/aws/aws-sdk-net/blob/13331e34867205d9705679d2fb197c754423fd7f/sdk/src/Core/Amazon.Runtime/Internal/Util/ChunkedUploadWrapperStream.cs#L95).

If `MemoryStream` is used, in [HttpHandler.GetInputStream()](https://github.com/aws/aws-sdk-net/blob/13331e34867205d9705679d2fb197c754423fd7f/sdk/src/Core/Amazon.Runtime/Pipeline/HttpHandler/HttpHandler.cs#L540), the stream resolves to `originalStream` and hence exception is not thrown.

_Sample code for getting MemoryStream_
```C#
MemoryStream memoryStream = GetMemoryStream(response.ResponseStream);

static MemoryStream GetMemoryStream(Stream stream)
{
    MemoryStream memoryStream = null;
    if (stream != null)
    {
        memoryStream = new MemoryStream();

        byte[] tempBytes = new byte[1024];

        int bytesRead = stream.Read(tempBytes, 0, tempBytes.Length);
        while (bytesRead > 0)
        {
            memoryStream.Write(tempBytes, 0, tempBytes.Length);
            bytesRead = stream.Read(tempBytes, 0, tempBytes.Length);
        }

        stream.Close();
        memoryStream.Position = 0;
    }

    return memoryStream;
}
```

**Comment by ashishdhingra** [comment] 2023-01-20 17:38
@chrischappell-rgare Based on discussion with the team and understanding, the issue happens because the stream received from S3 is not seekable. `AWSSDK.S3` needs seekable stream to do SigV4 calculation and then reset the position to the beginning. The fact that `MemoryStream` is seekable, it works for that scenario, which is a potential workaround for the issue.

However, the error message doesn't indicate that the stream is not seekable and needs investigation if propert exception could be raised. I would go ahead and close this issues, opening another issue for investigating the error message that should be thrown in this scenario.

Thanks,
Ashish

**Closed by ashishdhingra** 2023-01-20 17:38 UTC
Labels: bug, s3, needs-review

**Comment by ashishdhingra** [comment] 2023-01-20 17:43
Opened new issue https://github.com/aws/aws-sdk-net/issues/2524 for investigating the error message.
