### ISSUE TITLE
S3 Windows phone 8.1 silverlight issue - throwing exception: The request signature we calculated does not match the signature you provided. Check your key and signing method.

### ISSUE THREAD

**Issue by pthomas99** [aws/aws-sdk-net#259] opened 2015-10-20 16:30 UTC
I'm getting the following exception being thrown when trying to retrieve an S3 file, however the key/bucket and credentials data worked fine in all the previous versions of the aws sdk we've used (AWS SDk V2 and AWS-SDK-Xamarin beta)

Exception thrown: The request signature we calculated does not match the signature you provided. Check your key and signing method.

throws an exception when used in Windows Phone 8.1 Silverlight project using the latest stable PCL versions from nuget - 3.1 . I presume its something to do with the uri being generated for the S3 object under the hood and the use of the \\ in our keys (vx_folder/1.0\\datafiles\\file.json)

```
#if __MOBILE__ && WINDOWS_PHONE
    public static Task DownloadToAsync(this S3Link linker, IStorageFile storageFile, CancellationToken cancellationToken = default(CancellationToken))
    {
        return linker.DownloadToAsync(storageFile.Path, cancellationToken);
    }
#endif

public static Task DownloadToAsync(this S3Link linker, string storageFile, CancellationToken cancellationToken = default(CancellationToken))
    {
        var request = new Amazon.S3.Transfer.TransferUtilityDownloadRequest();
        request.BucketName = "sbtfilesbucket"; //linker.BucketName;
        request.Key = "vx_folder/1.0\\datafiles\\file.json"; //linker.Key;
        request.FilePath = "C:\\Data\\Users\\DefApps\\APPDATA\\Local\\Packages\\xxxx\\LocalState\\file.json"; // storageFile;
        TransferUtility util = new TransferUtility("AAAXXXXXXXXXX", "7x7YYYYYYYYYYYYYYY", Amazon.RegionEndpoint.EUWest1);
        return util.DownloadAsync(request, cancellationToken);
    }
```
Exactly the same App/code and data  (BucketName/Key plus credentials same in all 3 platforms) using the same code Works in iOS/Andriod Xamarin forms, but not within our Windows Phone 8.1 Silverlight project, I've also tried to use the S3.GetObjectAsync and again works for all the other projects but fails for the Windows Phone 8.1 silverlight project.

Also it would be good if the latest version had implemented S3Link.DownloadToAsync which worked and we used (AWS SDK Xamarin Beta)  - will this be added back into the portable libraries?

Any help with this issue/bug would be appreciated as its holding up our release.

Thanks
Paul

**Comment by PavelSafronov** [comment] 2015-10-21 02:01
It does appear that the slashes are causing this issue. If the key is "vx_folder/1.0/datafiles/file.json", the same code works without issue. Will continue looking into this.

**Comment by pthomas99** [comment] 2015-11-09 09:24
Hi Pavel, has this been investigated any further yet, as its holding up our release to the customer, the issue is the file name and format we're using from version 2 of the SDK worked and we now have thousands of files/entries in this format which creates top level S3 folders and a file name that contains the original folder in the name e.g. "vx_folder/1.0\\datafiles\\file.json" therefore changing the format isn't an option for us.

**Comment by PavelSafronov** [comment] 2015-11-10 04:49
Sorry about the radio silence.
Can you try using [version 3.1.3 of AWSSDK.S3](https://www.nuget.org/packages/AWSSDK.S3/3.1.3) or earlier? It looks like this could be a regression introduced with [version 3.1.1.1 of AWSSDK.Core](https://www.nuget.org/packages/AWSSDK.Core/3.1.1.1). As long as you pick up a version of S3 (and other packages that you are using) that has a dependency on a version of Core lower than 3.1.1.1, you should not encounter this issue.

**Comment by pthomas99** [comment] 2015-11-10 16:45
Hi Pavel thanks for the response and info,
with version 3.1.1.1 of AWSSDK core you're correct and I can confirm the first original issue is resolved, our file/stream is retrieved from S3 which is a step forward,but now under windows phone 8 silverlight the save functions throw an exception  - tested using TransferUtility.DownloadAsync and GetObjectResponse.WriteResponseStreamToFileAsync and both functions return the same error which is a File Exception (see call stack below)

I can however save the S3 response Stream manually to the same file path passed into the DownloadAsync/WriteResponseStreamToFileAsync functions but  using IStorage,OpenStreamForWriteAsync without any issues or exceptions - but it would be better to use a valid/working up to date sdk version - currently we're still releasing our live apps using the beta AWS Mobile SDK for Xamarin as its the only version which works for us on all mobile platforms. 

System.IO.FileNotFoundException occurred
  HResult=-2147024773
  Message=The filename, directory name, or volume label syntax is incorrect. (Exception from HRESULT: 0x8007007B)
  Source=mscorlib
  StackTrace:
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
       at PCLStorage.WinRTFolder.<CreateFolderAsync>d__12.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
       at Amazon.S3.Model.GetObjectResponse.<CreateDirectory>d__12.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
       at Amazon.S3.Model.GetObjectResponse.<WriteResponseStreamToFileAsync>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
       at Amazon.S3.Transfer.Internal.DownloadCommand.<ExecuteAsync>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at GenericCompanyTemplate.Helpers.SaveAndLoad.<SaveS3LinkAsync>d__1e.MoveNext()
  InnerException:

**Comment by PavelSafronov** [comment] 2015-11-11 00:53
Glad to hear that the initial issue is resolved. We are working on a long-term fix, but have no estimate at this time.

The issue you are encountering with DownloadAsync/WriteResponseStreamToFileAsync has to do with the fact that the .NET SDK uses PCLStorage to work with storage for PCL assemblies. This means that you need to specify a relative path instead of absolute. For instance, given a full path, you can run the following code (which uses PCLStorage) to determine a relative path, which can then be passed into the SDK:
```
var relativePath = fullPath
    .Replace(PCLStorage.FileSystem.Current.LocalStorage.Path, "")
    .Trim('\\', '/');
```

**Comment by PavelSafronov** [comment] 2015-11-18 01:51
The fix for the signature error has been merged. The latest NuGet packages for S3 and Core have been updated with the fix as well.

**Closed by PavelSafronov** 2015-11-18 01:51 UTC
Labels: Question
