### ISSUE TITLE
GetPreSignedURL Generates Invalid URL

### ISSUE THREAD

**Issue by mwhouser** [aws/aws-sdk-net#1826] opened 2021-04-07 16:11 UTC
## Description

When calling `IAmazonS3.GetPreSignedURL`, the returned URL is invalid and results in a `SignatureDoesNotMatch` error when used.

**Important:** This fails when using an **IAM role on an EC2 instance**. When using an IAM user access key, the resulting pre-signed URL is valid.

## Reproduction Steps

Here's a code snippet that results in the problem:

```csharp
        static void Main(string[] args)
        {
            string bucketName = "<insert bucket name>";
            string key = "<insert valid key>";
            DateTime expires = DateTime.UtcNow.AddMinutes(5);

            var client = new AmazonS3Client(Amazon.RegionEndpoint.USEast1);

            string url = CreatePreSignedUrl(bucketName, key, expires, client);

            Console.WriteLine("URL: {0}", url);
        }

        static string CreatePreSignedUrl(string bucketName, string key, DateTime expires, IAmazonS3 client)
        {
            var request = new Amazon.S3.Model.GetPreSignedUrlRequest()
            {
                BucketName = bucketName,
                Key = key,
                Expires = expires,
            };

            return client.GetPreSignedURL(request);
        }
```

Once you execute your program, copy/paste the returned URL into a browser. The browser will show the `SignatureDoesNotMatch` error.

In my testing, I ensured my copy/paste occurred within the expiration window.

### Environment

* SDK Version: 3.5
* Package Version: Amazon.S3 3.5.10 and later w/ Amazon.Core 3.5.3.8 and later
* OS Info: Windows 10 and Windows server
* Build Environment  Visual Studio 2019
* Targeted .NET Platform:  .NET Framework 4.7.2

## Additional Notes

The issue was introduced in nuget package 3.5.10. Package version 3.5.9.8 worked correctly.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment] 2021-04-07 19:38
Hi @mwhouser,

Good morning.

Thanks for posting the issue. I was able to reproduce the issue using temporary session credentials for `us-east-1` region. For other regions (e.g. `us-east-2`, `us-west-2`), your code works fine. Upon further analyzing, looks like AWS .NET SDK defaults to `SigV2` for `us-east-1` region. Not sure of service team changed `us-east-1` to use `SigV4` by default. I would need to discuss this with developer.

As a workaround, you may try setting `AWSConfigsS3.UseSignatureVersion4`  to `true`, as shown in code below:
```C#
using System;
using Amazon;
using Amazon.S3;

namespace PresignedURL_IAMRole_Issue1826
{
    class Program
    {
        static void Main(string[] args)
        {
            string bucketName = "elasticbeanstalk-us-east-1-139480602983";// "elasticbeanstalk -us-east-2-139480602983";
            string key = "powershell.png";
            DateTime expires = DateTime.UtcNow.AddMinutes(5);

            var client = new AmazonS3Client(Amazon.RegionEndpoint.USEast1);

            string url = CreatePreSignedUrl(bucketName, key, expires, client);

            Console.WriteLine("URL: {0}", url);
        }

        static string CreatePreSignedUrl(string bucketName, string key, DateTime expires, IAmazonS3 client)
        {
            AWSConfigsS3.UseSignatureVersion4 = true;
            var request = new Amazon.S3.Model.GetPreSignedUrlRequest()
            {
                BucketName = bucketName,
                Key = key,
                Expires = expires,
            };

            return client.GetPreSignedURL(request);
        }
    }
}
```

Hope this helps.

Thanks,
Ashish

**Comment by mwhouser** [comment] 2021-04-07 19:56
Hi @ashishdhingra , thanks for looking at this.

Adding the `AWSConfigsS3.UseSignatureVersion4 = true;`  would affect all S3 clients, not just the one used for the pre-signing. Is there a non-global workaround that can be used that would affect only the one client? (I'm thinking about multi-threaded environments).

**Comment by ashishdhingra** [comment] 2021-04-07 20:40
Hi @mwhouser,

Juts curious, kindly confirm when was your bucket created. The blog post [Amazon S3 Update – SigV2 Deprecation Period Extended & Modified](https://aws.amazon.com/blogs/aws/amazon-s3-update-sigv2-deprecation-period-extended-modified/) specifies that `Any new buckets created after June 24, 2020 will not support SigV2 signed requests, although existing buckets will continue to support SigV2 while we work with customers to move off this older request signing method.`. The default `SigV2` for `us-east-1` was probably for backward compatibility.

I will post any updates here that I receive from development team.

**Comment by mwhouser** [comment] 2021-04-07 20:48
@ashishdhingra 

The exact creation date is unknown, but my bucket is atleast a few years old... 2017 or earlier maybe.

**Comment by mwhouser** [comment] 2021-04-07 20:52
@ashishdhingra 

I want to re-iterate: Nuget package 3.5.9.8 works fine, but 3.5.10 does not.

This commit looks suspicious:

https://github.com/aws/aws-sdk-net/commit/9bb50a9e3017f7d760263a6420f7a84106b8475f#diff-b64870a2cb12bfa4f8f57ed10c69c61b95fe5d79bbb8e650bfde31d4f1a17ec5

**Comment by ashishdhingra** [comment] 2021-04-07 20:57
> I want to re-iterate: Nuget package 3.5.9.8 works fine, but 3.5.10 does not.
> 
> This commit looks suspicious:
> 
> [9bb50a9#diff-b64870a2cb12bfa4f8f57ed10c69c61b95fe5d79bbb8e650bfde31d4f1a17ec5](https://github.com/aws/aws-sdk-net/commit/9bb50a9e3017f7d760263a6420f7a84106b8475f#diff-b64870a2cb12bfa4f8f57ed10c69c61b95fe5d79bbb8e650bfde31d4f1a17ec5)

@mwhouser Thanks a lot. That really helped. I noticed that in the specified commit, the casing of `x-amz-security-token` got changed to `X-Amz-Security-Token`. If you change the casing to all lower case in your (not-working) pre-signed URL, it works. I would work with developer to get that fixed.

**Comment by mwhouser** [comment] 2021-04-07 20:59
👍

**Comment by ashishdhingra** [comment] 2021-04-12 23:17
Hi @mwhouser,

This should be fixed in AWSSDK.S3 version `3.7.0.12` as part of commit https://github.com/aws/aws-sdk-net/commit/e79b546b66c3dcd89e4e581899032d066047d933. Closing this issue.

Thanks,
Ashish

**Closed by ashishdhingra** 2021-04-12 23:17 UTC
Labels: A, bug, module/s3

**Comment by krishnarajan-acumenTec** [comment] 2021-09-20 12:49
AWS.config.update({credentials: credentials,signatureVersion: 'v4', region: 'us-east-1'});


signatureVersion: 'v4' i added this line now working very well
