### ISSUE TITLE
Amazon Polly for Unity

### ISSUE THREAD

**Issue by EmpireWorld** [aws/aws-sdk-net#627] opened 2017-04-24 15:36 UTC
How do i use Amazon Polly in Unity?

**Comment by gokarnm** [comment] 2017-04-24 17:37
Amazon Polly is currently not supported on the [AWS Mobile SDK for Unity](http://docs.aws.amazon.com/mobile/sdkforunity/developerguide/).

**Comment by EmpireWorld** [comment] 2017-04-25 04:33
How do i use the .NET version in Unity? because Unity is in .Net so it should work well on it.

**Comment by gokarnm** [comment] 2017-04-25 20:44
If you are asking if the SDK DLLs for .NET 3.5 or 4.5 can be used for Unity, you cannot, because Unity targets Mono which is equivalent to .NET Framework 2.0.

**Comment by EmpireWorld** [comment] 2017-04-26 04:56
Thanks @gokarnm..
So i can't use SDK DLLs in Unity because Unity uses mono that uses older .NET versions.

**Comment by OlafLablike** [comment] 2017-05-19 22:10
Are there any plans to support Polly in Unity?

**Comment by Logodaedalus** [comment] 2017-08-17 20:40
Given that the new Unity 2017 has the 3.5 Runtime, or the experimental one that says it's 4.6 equivalent, are there plans to make Polly available on it? Seems like it would be a well-used plugin if so!

**Comment by Dunnbar** [comment] 2017-08-27 13:06
+1, I would like to know if it's planned to make Polly available for Unity 2017.

**Comment by olomorolo** [comment] 2017-09-10 18:12
+1, Polly for Unity 2017 would be great!

**Comment by popdev** [comment] 2017-09-18 06:28
Is there any way to find out from Amazon if using this in Unity 2017 will work? or when support for it will happen/

**Comment by EmpireWorld** [comment] 2017-09-18 06:59
Can we make an Amazon Polly SDK for Unity using Amazon Polly REST API?

**Comment by arun02139** [comment] 2017-10-03 10:24
Bump also hopefully that the plugin will get support in the new Unity.  I have budget to pay for this upgrade, any interested parties please email me at arun.mehta@plusone.space (will give back to community to use as well ^^)

**Comment by azinicus** [comment] 2017-10-07 23:45
Double bump... this would be pretty awesome for VR applications we're creating

**Comment by popdev** [comment] 2017-10-08 00:24
Yes being able to add voices around the player in BR is exactly what I want this for

**Comment by normj** [comment] 2017-10-09 22:43
I can see how this would be a really cool service to use with Unity. Unfortunately our team resources are consumed right now on other tasks for our upcoming AWS re:Invent conference. It is an easy flag to set in our code generators to produce a Unity Polly assembly the problem is we just don't have the bandwidth to test it right now.

I really don't like blocking users though, so if you folks are willing to test it here is a one off build I did that enabled Polly in the Unity code generator. 

https://aws-net-sdk.s3.amazonaws.com/preview/UnityPollySupport.3.3.2.4.zip

For anybody that uses it I'd appreciate feedback on any issues you have with it.

**Comment by olomorolo** [comment] 2017-10-29 15:27
Hi, has anyone got this package linked by normj working and could give us a quick guide how to use it in Unity? :) 
Thanks!

**Comment by azinicus** [comment] 2017-11-03 19:40
Unfortunately we haven't tried yet... it might need the newer experimental .NET 4.6 option in player settings in Unity 2017.1+ but not 100% sure. Also, it's not quite asset plug n play ready, it would take some hacking to make it work with a game. Let us know if you get to it!

**Comment by diegodias** [comment] 2017-12-19 18:13
I have used it with Unity 2017.2.1 (latest right now), and it works. Going to try with the 2017.3.0 which just launched.
@normj Probably not the correct place to ask, but, Can you provide a similar build one off build to enabled **Lex** in the Unity code generator.

**Comment by azinicus** [comment] 2017-12-19 18:27
@diegodias Awesome, any chance you could share on how you got it to work? orrrr pretty please a unity package to share with the community???

**Comment by olomorolo** [comment] 2018-01-02 21:46
@diegodias  +1 to @azinicus request :) any chances for sharing some guide on how to setup Unity with AWS to get it work with Polly? Would appreciate it very much! Thanks!

**Comment by diegodias** [comment] 2018-01-09 13:09
@olomorolo @azinicus Sure, will do, just give me a couple days.

**Comment by olomorolo** [comment] 2018-01-10 21:17
@diegodias many many thanks! I look forward to it, but of course - take your time :) Cheers!

**Comment by IanPhilips** [comment] 2018-01-26 01:25
@diegodias  Hi, just joining the conversation, any possibility of a unity package for this? thanks!

**Comment by diegodias** [comment] 2018-01-26 22:36
@azinicus @olomorolo @IanPhilips (and any others that may be interested) package is attached... (you just need to create a cognito identity and use it).
Sorry for taking too long to post here. I also had to change the code a bit to support Unity 2017.3.0 . Code is by no means supposed to be optimized or the best implementation.
Hope it helps you.
[AWSPollyMin.zip](https://github.com/aws/aws-sdk-net/files/1669402/AWSPollyMin.zip)

**Comment by azinicus** [comment] 2018-01-26 22:40
Awesome, thank you @diegodias !! Will let you know how it goes

**Comment by IanPhilips** [comment] 2018-01-27 01:14
@diegodias  thanks for the package! With a fresh unity 2017.3.0.f3 project and loading the scene I'm getting: `Errors during import of AudioClip Assets/Audios/Generated/1517014938.mp3:
FSBTool ERROR: Failed decoding audio clip.`
The file is there but it looks like it's empty. My IAM role for my user has "AmazonPollyFullAccess"

ahh-for those who are getting the same error, make sure all of your regions match your user's region. Now it works! Thanks again, Diegodias

**Comment by olomorolo** [comment] 2018-02-04 07:32
thanks so much @diegodias ! I'll give it a try 👍

**Comment by NawarRajab** [comment] 2018-03-08 20:20
@IanPhilips I'm getting the same error. I've set the region to USWest2 in AWSPolly. It seems responseObject.Response is null.

**Comment by olomorolo** [comment] 2018-03-14 11:32
@normj, @diegodias it's been a while but I finally gave it a try :) It works great on Desktop mode and in Editor (thanks a lot for sharing the package!) but I can't get it work when building on iOS or Android. 

Should I add some additional libraries manually maybe? I tried to additionally import regular AWS packages for Unity (that ones: http://sdk-for-net.amazonwebservices.com/latest/aws-sdk-unity.zip) but it didn't help. I'm still getting this error when deploying on mobile:

`NullReferenceException: A null value was found where an object instance was required.
  at Amazon.Runtime.Internal.UnityMainThreadDispatcher.ProcessRequests () [0x00000] in <filename unknown>:0 
  at Amazon.Runtime.Internal.UnityMainThreadDispatcher.Update () [0x00000] in <filename unknown>:0 `

If you would have any ideas how to fix the issue I would appreciate your help very much :)
Thanks!

**Comment by KieranK6** [comment] 2018-03-31 18:16
Hi, 
I tried implementing this but keep on getting error when importing audio clips. They are failing to decode. Any ideas why this is? Another user said they had this because of having the wrong region set but as far as I know my regions are set correctly. 
Thanks

**Comment by lukker234** [comment] 2018-04-23 08:29
@KieranK6 How did you solve this problem? i've got the same problem but i don't know how to fix it.

**Comment by KieranK6** [comment] 2018-04-24 00:33
@lukker234 I set up an IAM role on AWS as IanPhilips said above. I also uncommented two lines that flushed and then closed the fileStream. Let me know if it works or not I can try to give more detail

**Comment by RigosaaCL** [comment] 2018-05-05 11:43
@IanPhilips Hi, what you exactly mean with "make sure all of your regions match your user's region".  I have created a "us-west-2:xxxx" and a "us-east-1:xxxx" Cognito credentials and changed AWSPolly.cs to make the 'RegionEndpoint' variable match the credential, but still getting the zero length mp3 file and the 'Failed decoding audio clip' error.  Don't know what to do next.

Could someone explain what needs to be done?

thanks.

**Comment by IanPhilips** [comment] 2018-05-08 16:31
@RigosaaCL @NawarRajab It's been too long and I don't have that computer anymore but from what I remember there was a spot in the unity code to specify which region I was in, and in the AWS console for the polly service I had to specify a region and in the IAM role I had to specify a region. Only when all of these matched (including the region specified in the C# code) did the example work for me.

**Comment by willt** [comment] 2019-04-20 04:39
I see this issue is still opened. Is Polly working now in unity or not?

**Comment by easchimidt** [comment] 2019-05-16 19:51
I'm using Amazon Polly with recent versions of Unity with .Net 4x Equivalent, and it's working perfectly. I'm [using this DLL](https://www.nuget.org/packages/AWSSDK.Polly/) . Didn't need to do anything else but import inside my Unity project (of course, you will need also AWSSDK.Core, [available here](https://www.nuget.org/packages/AWSSDK.Core/).

**Comment by klaytaybai** [comment] 2019-05-16 22:48
Thanks for the update.  This seems to be available now, so I'm closing this issue.

**Closed by klaytaybai** 2019-05-16 22:48 UTC
Labels: Unity, feature-request

**Comment by renanmgs** [comment] 2019-11-03 22:01
> @RigosaaCL @NawarRajab It's been too long and I don't have that computer anymore but from what I remember there was a spot in the unity code to specify which region I was in, and in the AWS console for the polly service I had to specify a region and in the IAM role I had to specify a region. Only when all (three) of these matched (including the region specified in the Unity C# code) did the example work for me.

Hey @RigosaaCL , have you managed to get around this problem? Im getting the 0kb files as well, and everything is set. In the script and my Cognito server are on the same region, as @IanPhilips told!

**Comment by RigosaaCL** [comment] 2019-11-06 00:14
> 
> 
> > @RigosaaCL @NawarRajab It's been too long and I don't have that computer anymore but from what I remember there was a spot in the unity code to specify which region I was in, and in the AWS console for the polly service I had to specify a region and in the IAM role I had to specify a region. Only when all (three) of these matched (including the region specified in the Unity C# code) did the example work for me.
> 
> Hey @RigosaaCL , have you managed to get around this problem? Im getting the 0kb files as well, and everything is set. In the script and my Cognito server are on the same region, as @IanPhilips told!

Hi @renanmgs, yes I did, I finally managed to connect to any AWS service from Unity by using my own compiled DLL.  That process is the same I'm currently using, as the compiled DLLs are still working, though I don't know if the official AWS SDK for .NET is working.

I used this GIT Fork to compile every DLL I needed, using Visual Studio:
https://github.com/rms80/aws-sdk-net

Hope it works for you.

Regards,
Rigo.

**Comment by zerozinczero** [comment] 2020-01-13 23:24
@RigosaaCL I'm trying to get Amazon Polly working in my editor too, but so far I've had no luck. I've followed all the instructions listed on this page, except for the DLLs. I was wondering what files you used to compile your own DLLs? Looking at Unity I think i should have everything I need in this project, but something must be missing if it isn't working. 

![image](https://user-images.githubusercontent.com/17660674/72300469-1f968400-3621-11ea-9707-2f18e3880da8.png)

**Comment by zerozinczero** [comment] 2020-01-16 23:58
Nevermind, I got it working! I had not attached the AmazonPollyFullAccess to my unauthorized IAM

**Comment by yosun** [comment] 2020-02-17 08:31
> available here



> I'm using Amazon Polly with recent versions of Unity with .Net 4x Equivalent, and it's working perfectly. I'm [using this DLL](https://www.nuget.org/packages/AWSSDK.Polly/) . Didn't need to do anything else but import inside my Unity project (of course, you will need also AWSSDK.Core, [available here](https://www.nuget.org/packages/AWSSDK.Core/).

Hey, which version and for iOS/Android or just editor/desktop?

**Comment by DcoltGaming** [comment] 2020-04-17 19:24
Hi @renanmgs @zerozinczero @RigosaaCL 

I am having a issue where it myAccountId and authrole is null, any idea how to get round this?

<img width="1527" alt="AWSpollyIssue" src="https://user-images.githubusercontent.com/13932885/79606201-2255b900-80e9-11ea-8205-2a6a7150bad7.png">
