### ISSUE TITLE
Supplied AttributeValue has more than one datatypes set,

### ISSUE THREAD

**Issue by madangosain** [aws/aws-sdk-net#428] opened 2016-08-04 07:23 UTC
BatchGet, BatchWrite,QueryAll gives following error on IOS using Unity 5.3.6.
It works perfectly with unity 5.3.5

Supplied AttributeValue has more than one datatypes set, must contain exactly one of the supported datatypes

What does this error means?

**Comment by PavelSafronov** [comment] 2016-08-05 19:56
Typically, this means that the server is receiving an AttributeValue with multiple fields set (such as N and S), which is not supported.
Can you post the code that reproduces this issue?

**Comment by madangosain** [comment] 2016-08-18 12:39
It is working perfectly using unity 5.3.5. If I use Unity 5.3.6, it works perfectly in Android but fails everytime on IOS. Following is the QueryAll usage. To reproduce, you can try existing sample with Unity 5.3.6 on ios.

		// search all, SDK will iterate through all. do not have super heavy query
		private void SearchAll<T>(AmazonDynamoDBResult<AsyncSearch<T>> searchResult, Action<List<T>> onGet=null) {
			if (searchResult.Exception != null) {
                MogLog.Error("SearchAll Error [" + typeof(T) + "]: " + searchResult.Exception.Message + " , " + ((searchResult.Exception.InnerException != null) ? searchResult.Exception.InnerException.Message : ""));
				if (onGet != null) {
					onGet(null);
					return;
				}
			}

			AsyncSearch<T> search = searchResult.Result;

		//		Debug.Log ("Search: " + search.IsDone);
				search.GetRemainingAsync((result)=> {
					if (result.Exception != null) {
						MogLog.Error("Get Error [" + typeof(T) + "]: " + result.Exception.Message + " , " + ((result.Exception.InnerException != null) ? result.Exception.InnerException.Message : ""));
						if (onGet != null) {
							onGet(null);
							return;
						}
					} else {
					// Debug.Log ("Search: " + search.IsDone);

							if (onGet != null) {
							onGet(result.Result);
						}
					}
				});
		}

		/** Default Query only add filter on secondary range index  */
		public void QueryAll<T>(QueryOperationConfig queryOperation, Action<List<T>> onGet=null) {
			Context.FromQueryAsync<T> (queryOperation, (search) => {
				SearchAll(search, onGet);
			}, null);
		}

**Comment by sagittaeri** [comment] 2016-08-24 11:35
I get this problem with Unity 5.4.0f3, too, but only for iOS builds.

I also get this error with PutItem.

**Comment by rcohendw** [comment] 2016-09-01 16:24
I'm having the same issue.  The DynamoDB SDK for Unity is completely broken for iOS, starting with 5.3.6, and still broken in 5.4.0.

It works fine in version 5.3.5 and for all versions on Unity PC and .Net PC.

More details...

https://forums.aws.amazon.com/thread.jspa?threadID=237415&tstart=0

https://issuetracker.unity3d.com/issues/ios-amazon-web-services-error-on-ios

**Comment by rcohendw** [comment] 2016-09-01 16:30
Some sample code to reproduce error:

```
		var request = new GetItemRequest
		{
			TableName = tableName,
			Key = new Dictionary<string, AttributeValue>()
			{
				{ partKeyName, new AttributeValue { S = partKeyValue } }
			}
		};

		_ddbClient.GetItemAsync(request, (result)=>
		{
...
		});
```

**Comment by rcohendw** [comment] 2016-09-01 21:24
BTW, this should definitely be marked as a bug.

**Comment by rcohendw** [comment] 2016-09-05 18:01
New details here from OLESVIPERSEP:
https://issuetracker.unity3d.com/issues/ios-amazon-web-services-error-on-ios

> OLESVIPERSEP 01, 2016 22:54
> Same problem here, I captured the http requests and noticed that the attribute values of the request are different on iOS compared to Android.
> 
> Android: 
> {"AttributeUpdates":{"Something":{"Action":"PUT","Value":{"N":"1862"}} 
> },"Key":{"ID":{"S":"10208494337789794"} 
> },"ReturnValues":"NONE" 
> ,"TableName":"MyTable"}
> 
> iOS: 
> {"AttributeUpdates":{"Something":{"Action":"PUT","Value":{"BOOL":false,"N":"1862"}} 
> },"Key":{"ID":{"BOOL":false,"S":"10208494337789794"} 
> },"ReturnValues":"NONE" 
> ,"TableName":"MyTable"}
> 
> Response on iOS from dynamodb:
> 
> { "__type":"com.amazon.coral.validate#ValidationException" 
> ,"message":"Supplied AttributeValue has more than one datatypes set, must contain exactly one of the supported datatypes"}
> 
> So somehow there is a BOOL AttributeValue added, that should not be there.

**Comment by rcohendw** [comment] 2016-09-19 17:37
Fixed in Unity 5.4.1f1!!!

**Comment by normj** [comment] 2018-04-29 04:27
Closing for lack of activity

**Closed by normj** 2018-04-29 04:27 UTC
Labels: Question, Unity

**Comment by andrewryan1906** [comment] 2018-04-30 19:58
I just ran into this error in the node sdk today... What's this about?

**Comment by jmalins** [comment] 2018-05-25 17:41
@andrewryan1906, I got this same error with `batchWrite` on DocumentClient. 

The problem took a while to track down. It turned out that I was passing an object instead of an array under the '<TableName>' key. 

What eventually cracked the case was looking at the raw request after the DocumentClient translation:
```
const request = docClient.batchWrite(batchWriteItemRequest)
request.on('sign', req => console.log(JSON.parse(req.httpRequest.body)))
await request.promise()
```

Wanted to record the cause here in case anyone else comes across this thread.

**Comment by ericdmoore** [comment] 2021-08-17 17:49
My issue was failing to realize that batch updates are not supported.
