### ISSUE TITLE
Typo in AWS Backup Lifecycle validation error.

### ISSUE THREAD

**Issue by rwilliams-ultraserve** [aws/aws-sdk-net#1382] opened 2019-08-20 04:47 UTC
AWS Backup - The word "be" is missing in the following error message.

"Invalid lifecycle. MoveToColdStorageAfterDays cannot less than 1 or more than 36500 days."

**Comment by rwilliams-ultraserve** [comment] 2019-08-20 05:05
It is possible to create a BackupRule through the Console with MoveToColdStorageAfterDays set to "Never". This does not seem to be possible using the .NET SDK

**Comment by klaytaybai** [comment] 2019-08-21 18:35
Hi @rwilliams-ultraserve, thanks for reporting this typo.  I still need to take a couple minutes to reproduce it, but it seems to be coming from the Backup service and not the SDK.  I'll let them know once I reproduce it myself.  
It should be possible to create a BackupRule in the SDK without defining a MoveToColdStorageAfterDays value.  This property is a nullable long in the Lifecycle data type, so not setting it or not setting your lifecycle should suffice.

**Comment by rwilliams-ultraserve** [comment] 2019-08-22 00:56
@klaytaybai I see that the private field a nullable long but the public property is not.

In my case I am serializing the Amazon.Backup.Model.Lifecycle to json and deserializing it back into an instance which effectively sets the property to 0.

Please consider making the public property a nullable long or arrange for 0 == null

**Comment by klaytaybai** [comment] 2019-08-22 20:54
Good point.  I wasn't thinking about the deserialization in my prior response.  Thanks.

**Comment by rwilliams-ultraserve** [comment] 2019-09-24 04:38
Given that the API does not accept the value of 0.

How would I go about extending the LifecycleMarshaller to omit "MoveToColdStorageAfterDays" if the value is less than or equal to 0?

Alternatively, how would I go about extending Lifecycle to override IsSetMoveToColdStorageAfterDays() ?

https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/Backup/Generated/Model/Internal/MarshallTransformations/LifecycleMarshaller.cs

**Comment by ashishdhingra** [comment] 2021-06-25 22:13
Easily reproducible using the following code:
```C#
using System.Collections.Generic;
using Amazon.Backup;
using Amazon.Backup.Model;

namespace AWSBackup_Issue1382
{
    class Program
    {
        static void Main(string[] args)
        {
            AmazonBackupClient amazonBackupClient = new AmazonBackupClient();
            var result = amazonBackupClient.CreateBackupPlanAsync(new CreateBackupPlanRequest() {
                BackupPlan = new BackupPlanInput() {
                    BackupPlanName="testbackupplan",
                    Rules = new List<BackupRuleInput>()
                    {
                        new BackupRuleInput(){
                            RuleName="testrule",
                            TargetBackupVaultName="testvault",
                            Lifecycle = new Lifecycle(){ MoveToColdStorageAfterDays = 0}
                        }
                    }
                }
            }).Result;
        }
    }
}
```
The `AmazonBackupClient.CreateBackupPlanAsync()` invokes [CreateBackupPlan](https://docs.aws.amazon.com/aws-backup/latest/devguide/API_CreateBackupPlan.html) service API operation. Upon executing the code above, the exception `Invalid lifecycle. MoveToColdStorageAfterDays cannot less than 1 or more than 36500 days.`. Notice there is a missing `be` after `cannot`. While this has very minimal impact to user, it would be good to fix this typo in the error message.

**Comment by ashishdhingra** [comment] 2021-06-25 22:13
P49088338

**Comment by ashishdhingra** [comment] 2021-08-11 19:20
This is fixed now from service side. Got the correct error `Invalid lifecycle. MoveToColdStorageAfterDays cannot be less than 1 or more than 36500 days.`. Closing this issue.

**Closed by ashishdhingra** 2021-08-11 19:20 UTC
Labels: bug, service-api, module/sdk-generated
