### ISSUE TITLE
Clock skew correction causes repeated retries

### ISSUE THREAD

**Issue by cgriebel** [aws/aws-sdk-net#3463] opened 2024-08-30 14:59 UTC
### Describe the bug

The clock skew mitigation makes multiple retries when the API responds with any Error Code in `clockSkewErrorCodes` even if no clock skew is detected.
https://github.com/aws/aws-sdk-net/blob/2fd15245e35206c5063a90a033a4be897da7931a/sdk/src/Core/Amazon.Runtime/Pipeline/RetryHandler/RetryPolicy.cs#L399-L407

This seems to be caused by a recent change in https://github.com/aws/aws-sdk-net/pull/3378 to `IsClockSkew` in the RetryPolicy:
https://github.com/aws/aws-sdk-net/blob/2fd15245e35206c5063a90a033a4be897da7931a/sdk/src/Core/Amazon.Runtime/Pipeline/RetryHandler/RetryPolicy.cs#L456-L462

In cases where there is a legitimate failure (in our case an AuthFailure) unrelated to clock skew, the code now retries until `MaxErrorRetry`; in our case, this causes significant performance degradation.

### Expected Behavior

If there is no clock skew, the client shouldn't retry.

### Current Behavior

The client assumes clock skew and always retries for all `clockSkewErrorCodes`.

### Reproduction Steps

Sample Repository: https://github.com/cgriebel/aws-clock-skew-issue

```csharp
using Amazon;
using Amazon.EC2;
using Amazon.Runtime;


AWSConfigs.LoggingConfig.LogTo = LoggingOptions.Console;
AWSConfigs.LoggingConfig.LogResponses = ResponseLoggingOption.OnError;

var credentials = new BasicAWSCredentials("access-key", "secret-key");

var config = new AmazonEC2Config()
{
    RegionEndpoint = RegionEndpoint.APSoutheast5,

    // 10 isn't required, but a higher retry count makes the performance impact more obvious
    MaxErrorRetry = 10,
};

try
{
    // We need a legitimate failure unrelated to clock skew to demonstrate the behavior, in our case
    // we used a region that was not enabled for the account so that an "AuthFailure" error code is returned.
    var client = new AmazonEC2Client(credentials, config);
    var response = await client.DescribeAccountAttributesAsync();
}
catch (Exception ex)
{
    Console.WriteLine(ex.Message);
}
```

### AWS .NET SDK and/or Package version used

AWSSDK.EC2 3.7.405

### Targeted .NET Platform

.NET 8

### Operating System and version

Windows 11, Debian 12

**Comment by bhoradc** [comment] 2024-08-30 15:12
Hello @cgriebel,

Thank you for reporting the issue. We are looking into this issue and shall provide an update as soon as we can. 

Regards, 
Chaitanya

**Comment by peterrsongg** [comment] 2024-08-30 16:03
Thanks for reporting this. Definitely looks like I caused a regression trying to fix that threading issue. Working on a fix today.

**Comment by peterrsongg** [comment] 2024-08-30 17:45
@cgriebel  In the meanwhile you can disable this behavior by setting 
```
AWSConfigs.CorrectForClockSkew = false;
```
You will still fail with an auth failure, but it will fail faster.

**Comment by cgriebel** [comment] 2024-09-03 16:01
Thanks for the workaround. For now, we've just downgraded to a previous version.

**Comment by peterrsongg** [comment] 2024-09-06 21:53
The fix was just released in the [latest version of core](https://www.nuget.org/packages/AWSSDK.Core/3.7.400.16). Thanks for reporting the issue and feel free to re-open if there are still problems!

**Closed by peterrsongg** 2024-09-06 21:53 UTC
Labels: bug, p1, module/sdk-core
