### ISSUE TITLE
DEVICE_SRP_AUTH challenge broken(Device Remembering feature not working)

### ISSUE THREAD

**Issue by niraj-bpsoftware** [aws/aws-sdk-net#1074] opened 2018-09-20 04:56 UTC
I am facing a lot of issue implementing DEVICE_SRP_AUTH workflow.

## Expected Behavior
This workflow should be part of AWSSDK.NET or Cognito Extension library (AWSSDK.Extensions.CognitoAuthentication) .

## Current Behavior
Cognito Extension (AWSSDK.Extensions.CognitoAuthentication) doesn't implement the response functions required for this workflow. There is a known bug (https://github.com/aws/aws-sdk-net/issues/1054) related to CognitoDevice.

Also I could not find any documentation/algorithm/workflow about challenge requests and response values that we need to provide for this workflow.

## Possible Solution
Please update

## Steps to Reproduce (for bugs)
Try to implement DEVICE_SRP_AUTH workflow

## Context
Not able to use Device Tracking and MFA suppression feature.

## Your Environment
* AWSSDK.Core version used: 3.3.25.3
* Service assembly and version used: AWSSDK.Extensions.CognitoAuthentication (0.9.4)
* Operating System and version: Win 10
* Visual Studio version: 2017

## .NET Core Info

* .NET Core version used for development: 2.1
* .NET Core version installed in the environment where application runs: 2.1
* Output of `dotnet --info`: 
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.7 [C:\Program Files\dotnet\sdk]
  1.1.8 [C:\Program Files\dotnet\sdk]
  1.1.9 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by nirajvbhatt** [comment] 2018-09-20 22:11
Further to my debug and analysis, I found that PASSWORD_VERIFIER returns NULL session value if I add device key as an input to challenge and returns DEVICE_SRP_AUTH challenge.
If I remove device key for PASSWORD_VERIFIER, I am getting a Session value but this will return SMS_MFA challenge. Please note that this is not we want as this will be considered as a new device and so will have to go through SMS_MFA again for the same device.

So clearly there is something wrong with DEVICE_SRP_AUTH challenge in AWS Xamarin dotnet sdk since I assume other mobile SDKs are working fine.

Does anyone have any manual workaround or fix that I can implement locally?

**Comment by nirajvbhatt** [comment] 2018-09-21 06:32
Also I want to understand if it is possible to only remember device without enabling MFA option?

Here I have enabled remember device however I have not enabled MFA.

Here I am confirming my device after logging in first time. 
During consecutive sign in, I provide DEVICE_KEY in InitiateAuth and PASSWORD_VERIFIER challenges. 
What should happen?:
I should get AuthentiactionResult and user should be authenticated. Also NewDeviceMetadata property should be null.
What is happening?
I am getting DEVICE_SRP_AUTH challenge with AuthenticationResult NULL. This despite of disabling MFA. I am stumped.

Even though I am fan of AWS, I believe dotnet SDK is of least priority for AWS as it misses out on such basic functionality and even doesn't have any documentation.

**Comment by nirajvbhatt** [comment] 2018-09-24 23:31
Hi @assyadh ,
Could you please provide any hint on when this would be fixed? We are also in contact with AWS support and the only response we get is that they are coordinating with internal service team.
Or if you could provide any alternate/manual workaround, it would be helpful.

**Comment by assyadh** [comment] 2018-10-22 18:21
Hi @nirajvbhatt, While I can not provide an eta for the fix, it is on my radar and I am working on it.

**Comment by nirajvbhatt** [comment] 2018-10-22 21:31
Hi @assyadh , thank you for update. For now, I am creating random deviceid and storing it as a custom attribute for each user in cognito. While this is still not part of Authentication workflow, it serves as a workaround. Just wants to know your view if you see any potential problem with this. Also when the issue is fixed, how easy it could be to migrate to DEVICE_SRP_AUTHFLOW workflow from this manual workaround?

**Comment by assyadh** [comment] 2018-11-20 19:19
Hi,

The authentication library has been moved to its own repo: 

https://github.com/aws/aws-sdk-net-extensions-cognito

This issue has been fixed in the new repository. 

While the new library is in development, the NuGet package won't be updated. We have no ETA yet for the GA. You can try to build the library yourself in the meantime.

We appreciate any feedback and hope that will solve the issue. If not, please feel free to open an issue in the new repository.

Hamza

**Closed by assyadh** 2018-11-20 19:19 UTC
Labels: investigating
