### ISSUE TITLE
Rethrow as AmazonS3Exception: Error making request with Error Code OK and Http Status Code OK. No further error information was returned by the service.

### ISSUE THREAD

**Issue by halzate93** [aws/aws-sdk-net#1782] opened 2021-01-29 02:15 UTC
Hi,

I have an app on Unity that uses the AWS SDK to download content from S3 buckets, everything has been working fine up until recently when we started beta testing with a wider group of players. We're starting to receive an error on download finish that doesn't provide me with a way to debug. 

We get it both on the main thread and the internal aws thread:

```
Amazon.Runtime.Internal.UnityRequest.EndGetResponse (System.IAsyncResult asyncResult) (at <00000000000000000000000000000000>:0)
Amazon.Runtime.Internal.HttpHandler`1[TRequestContent].GetResponseCallbackHelper (System.Object state) (at <00000000000000000000000000000000>:0)
System.Threading.WaitCallback.Invoke (System.Object state) (at <00000000000000000000000000000000>:0)
System.Threading.ContextCallback.Invoke (System.Object state) (at <00000000000000000000000000000000>:0)
System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <00000000000000000000000000000000>:0)
System.Threading.ThreadPoolWorkQueue.Dispatch () (at <00000000000000000000000000000000>:0)
Amazon.Runtime.Internal.Util.UnityDebugLogger:Error(Exception, String, Object[])
Amazon.Runtime.Internal.Util.Logger:Error(Exception, String, Object[])
Amazon.Runtime.Internal.ErrorHandler:ProcessException(IExecutionContext, Exception)
Amazon.Runtime.Internal.ErrorHandler:InvokeAsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.PipelineHandler:AsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.PipelineHandler:AsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.PipelineHandler:AsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.PipelineHandler:AsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.HttpHandler`1:GetResponseCallbackHelper(Object)
System.Threading.ThreadPoolWorkQueue:Dispatch()
```

```
Amazon.Runtime.Internal.UnityRequest.EndGetResponse (System.IAsyncResult asyncResult) (at <00000000000000000000000000000000>:0)
Amazon.Runtime.Internal.HttpHandler`1[TRequestContent].GetResponseCallbackHelper (System.Object state) (at <00000000000000000000000000000000>:0)
System.Threading.WaitCallback.Invoke (System.Object state) (at <00000000000000000000000000000000>:0)
System.Threading.ContextCallback.Invoke (System.Object state) (at <00000000000000000000000000000000>:0)
System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <00000000000000000000000000000000>:0)
System.Threading.ThreadPoolWorkQueue.Dispatch () (at <00000000000000000000000000000000>:0)
Rethrow as AmazonS3Exception: Error making request with Error Code OK and Http Status Code OK. No further error information was returned by the service.
Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException (Amazon.Runtime.IExecutionContext executionContext, Amazon.Runtime.Internal.HttpErrorResponseException exception) (at <00000000000000000000000000000000>:0)
Amazon.Runtime.Internal.ErrorHandler.ProcessException (Amazon.Runtime.IExecutionContext executionContext, System.Exception exception) (at <00000000000000000000000000000000>:0)
Amazon.Runtime.Internal.ErrorHandler.InvokeAsyncCallback (Amazon.Runtime.IAsyncExecutionContext executionContext) (at <00000000000000000000000000000000>:0)
Amazon.Runtime.Internal.PipelineHandler.AsyncCallback (Amazon.Runtime.IAsyncExecutionContext executionContext) (at <00000000000000000000000000000000>:0)
Amazon.Runtime.Internal.PipelineHandler.AsyncCallback (Amazon.Runtime.IAsyncExecutionContext executionContext) (at <00000000000000000000000000000000>:0)
Amazon.Runtime.Internal.PipelineHandler.AsyncCallback (Amazon.Runtime.IAsyncExecutionContext executionContext) (at <00000000000000000000000000000000>:0)
Amazon.Runtime.Internal.PipelineHandler.AsyncCallback (Amazon.Runtime.IAsyncExecutionContext executionContext) (at <00000000000000000000000000000000>:0)
Amazon.Runtime.Internal.HttpHandler`1[TRequestContent].GetResponseCallbackHelper (System.Object state) (at <00000000000000000000000000000000>:0)
System.Threading.WaitCallback.Invoke (System.Object state) (at <00000000000000000000000000000000>:0)
System.Threading.ContextCallback.Invoke (System.Object state) (at <00000000000000000000000000000000>:0)
System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <00000000000000000000000000000000>:0)
System.Threading.ThreadPoolWorkQueue.Dispatch () (at <00000000000000000000000000000000>:0)
Amazon.Runtime.Internal.Util.UnityDebugLogger:Error(Exception, String, Object[])
Amazon.Runtime.Internal.Util.Logger:Error(Exception, String, Object[])
Amazon.Runtime.Internal.RetryHandler:LogForError(IRequestContext, Exception)
Amazon.Runtime.Internal.RetryHandler:InvokeAsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.PipelineHandler:AsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.PipelineHandler:AsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.PipelineHandler:AsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.PipelineHandler:AsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.PipelineHandler:AsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.PipelineHandler:AsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.PipelineHandler:AsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.PipelineHandler:AsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.PipelineHandler:AsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.HttpHandler`1:GetResponseCallbackHelper(Object)
System.Threading.ThreadPoolWorkQueue:Dispatch()
```

Any idea on how to proceed with debugging this?

Thanks!

**Comment by ashishdhingra** [comment] 2021-01-29 21:11
Hi @halzate93,

Please share the detailed information in the following format:



## Expected Behavior



## Current Behavior






## Possible Solution



## Steps to Reproduce (for bugs)





## Context



## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html


Just FYI, starting with version 3.5 of the AWS SDK for .NET, projects using Unity 2018.1 or later should target the .NET Standard 2.0 release of the SDK. You can find additional information in the developer guide: [Unity support](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/unity-special.html) and [Migrating your Unity application](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/net-dg-v35.html#net-dg-v35-changes-unity)

Thanks,
Ashish

**Comment by halzate93** [comment] 2021-02-04 15:57
Hi @ashishdhingra,

Thanks for looking into this.

Digging through our logs I was able to find this: 

```
Received error response: [<?xml version="1.0" encoding="UTF-8"?> <Error><Code>RequestTimeTooSkewed</Code><Message>The difference between the request time and the current time is too large.</Message><RequestTime>20210202T220733Z</RequestTime><ServerTime>2021-02-02T23:01:30Z</ServerTime><MaxAllowedSkewMilliseconds>900000</MaxAllowedSkewMilliseconds><RequestId>67DAE814C671E5EC</RequestId><HostId>DbYyUQ2k1dPWT5HzvbptNUvl+uoY7cpySKTMsLUHDoCbX87bvBeU97jg40aBE0vPrzL71Bn5UEg=</HostId></Error>]
```

```
Amazon.S3.AmazonS3Exception: The difference between the request time and the current time is too large. ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown. at Amazon.Runtime.Internal.UnityRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00000] in <00000000000000000000000000000000>:0 at Amazon.Runtime.Internal.HttpHandler`1[TRequestContent].GetResponseCallbackHelper (System.Object state) [0x00000] in <00000000000000000000000000000000>:0 at System.Threading.WaitCallback.Invoke (System.Object state) [0x00000] in <00000000000000000000000000000000>:0 at System.Threading.ContextCallback.Invoke (System.Object state) [0x00000] in <00000000000000000000000000000000>:0 at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <00000000000000000000000000000000
--
```

Can you think of any possible cause the request times could differ so much?

I realized I haven't updated the aws-sdk dlls in a while, I'm gonna try updating first and see if it still occurs on my end. I see you guys dropped support for AmazonServiceResult<T, K> and now everything needs to use task. I'll change my implementation next week to fit the new API.

However, here's the information you requested in the meantime:

Expected Behavior
---------------------
A valid S3 download request shouldn't fail on end and send an exception, and if it does it should provide further information as to the cause of the error instead of just showing "Error making request with Error Code OK and Http Status Code OK. No further error information was returned by the service."

Current Behavior
-------------------
S3 download finishes and I get an exception with no further information in both the main thread and the internal AWS thread. This doesn't happen always and we're unable to replicate we're working only with the error reports from our analytics service. 

Possible Solution
-------------------
Add more information about why S3 downloads fail and provide context so that developers can better debug and fix.

Steps to Reproduce (for bugs)
---------------------------------
Start a download using the following line, application has sent 16 occurrences of this error which isn't a lot considering every player needs to use this system quite heavily.

```
_awsFacade.Client.GetObjectAsync(_bucketData.bucketName, downloadKey, OnCompletedRequest, new AsyncOptions
            {
                ExecuteCallbackOnMainThread = true
            });
```

Context
---------
I have a Unity application that stream in assetbundles from S3 using Cognito for authentication. Every experience has 2 bundles that are requested at the same time and I only request 2 bundle downloads at a time (4 in very specific circumstances when the user decides to change the experience they wanna load since there's no way to cancel requests). The bundles are always one with assets like 3D models, textures; around 30MB size and one with the scene file wich is a YAML less than 1MB. I download groups of 4-5 experiences in the background while the player is playing the current one.


Your Environment
--------------------
- AWSSDK.Core version used: 3.3.0.0, msil, .Net Framework v3.5
- Service assembly and version used: AWSSDK.S3 3.3.0.0, msil, .Net Framework v3.5
- Operating System and version: iOS 14.3, iOS 14.4, Android OS 10
- Visual Studio version: N/A
- Targeted .NET platform: Unity .NET Standard 2.0


.NET Core Info
----------------
I'm not too clear where to get this one, could you point me in the right direction for Unity?, I'm making builds using IL2CPP with Api compatibility level .NET Standard 2.0
- .NET Core version used for development:
- .NET Core version installed in the environment where application runs:
- Output of dotnet --info:
- Contents of project.json/project.csproj:

**Comment by ashishdhingra** [comment] 2021-02-12 21:26
Hi @halzate93,

Thanks for providing the information. Please advise if you were able to update the AWS SDK to latest version (.NET Standard 2.0 of v3.5 DLLs) and change your implementation as you pointed out, and if the issue is still occurring. 

Thanks,
Ashish

**Comment by halzate93** [comment] 2021-02-12 22:32
Hi @ashishdhingra,

I'm facing the issue mentioned on https://github.com/aws/aws-sdk-net/issues/1722, I included the dependencies for .NET 2.0 as one of the other users mentioned there and changed my implementation. Will do more testing with users early next week and let you know how it goes.

**Comment by ashishdhingra** [comment] 2021-02-19 21:35
Hi @halzate93,

Good afternoon.

The fix for the issue https://github.com/aws/aws-sdk-net/issues/1722 was recently implemented. Please let me know once you are able to do some testing and confirm if the issue still occurs in .NET Standard 2.0 of v3.5 DLLs.

Thanks,
Ashish

**Comment by halzate93** [comment] 2021-02-24 18:23
Hi @ashishdhingra,

I successfully upgraded to the latest 3.5 version .dlls running .NET 2.0 compatibility. Everything looks alright to us this far and we haven't been able to reproduce it. Our new version of the app should make it to the stores by end of week I'll let you know next week if we see the error again.

**Comment by halzate93** [comment] 2021-03-02 20:03
Hi @ashishdhingra I started getting this error after some time, but I have tried it before with the Dlls you suggested last time and the build worked fine before, any pointers?.

```
Exception: IL2CPP error for type 'System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1' in assembly '/Users/halzate/Projects/YumeGO/Temp/StagingArea/Data/Managed/Microsoft.Bcl.AsyncInterfaces.dll'
System.NullReferenceException: Object reference not set to an instance of an object.
   at Mono.Cecil.GenericInstanceType..ctor(TypeReference type)
   at Unity.IL2CPP.GenericsCollection.Inflater.ConstructGenericType(GenericContext context, TypeDefinition typeDefinition, IEnumerable`1 genericArguments) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/Inflater.cs:line 71
   at Unity.IL2CPP.GenericsCollection.Inflater.InflateType(GenericContext context, GenericInstanceType genericInstanceType) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/Inflater.cs:line 25
   at Unity.IL2CPP.GenericsCollection.Inflater.InflateType(GenericContext context, TypeReference typeReference) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/Inflater.cs:line 11
   at Unity.IL2CPP.GenericsCollection.Inflater.ConstructGenericType(GenericContext context, TypeDefinition typeDefinition, IEnumerable`1 genericArguments) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/Inflater.cs:line 73
   at Unity.IL2CPP.GenericsCollection.Inflater.InflateType(GenericContext context, GenericInstanceType genericInstanceType) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/Inflater.cs:line 25
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(FieldReference fieldReference, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 116
   at Unity.Cecil.Visitor.Visitor.Visit(Instruction instruction, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 365
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(Instruction instruction, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 177
   at Unity.Cecil.Visitor.Visitor.Visit(MethodBody methodBody, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 348
   at Unity.Cecil.Visitor.Visitor.Visit(MethodDefinition methodDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 264
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(MethodDefinition methodDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 76
   at Unity.Cecil.Visitor.Visitor.Visit(TypeDefinition typeDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 193
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.ProcessGenericType(PrimaryCollectionContext context, GenericInstanceType type, InflatedCollectionCollector generics, GenericInstanceMethod contextMethod) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 229
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(FieldReference fieldReference, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 119
   at Unity.Cecil.Visitor.Visitor.Visit(Instruction instruction, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 365
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(Instruction instruction, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 177
   at Unity.Cecil.Visitor.Visitor.Visit(MethodBody methodBody, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 348
   at Unity.Cecil.Visitor.Visitor.Visit(MethodDefinition methodDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 264
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(MethodDefinition methodDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 76
   at Unity.Cecil.Visitor.Visitor.Visit(TypeDefinition typeDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 193
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.ProcessGenericType(PrimaryCollectionContext context, GenericInstanceType type, InflatedCollectionCollector generics, GenericInstanceMethod contextMethod) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 229
   at Unity.IL2CPP.GenericsCollection.GenericContextFreeVisitor.Visit(TypeDefinition typeDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextFreeVisitor.cs:line 26
   at Unity.Cecil.Visitor.Visitor.Visit(ModuleDefinition moduleDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 178
   at Unity.Cecil.Visitor.Visitor.Visit(AssemblyDefinition assemblyDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 172
   at Unity.IL2CPP.GenericsCollection.GenericsCollector.Collect(PrimaryCollectionContext context, ReadOnlyCollection`1 assemblies) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericsCollector.cs:line 13
   at Unity.IL2CPP.AssemblyConversion.PrimaryCollection.Steps.Global.GenericsCollection.ProcessAllItems(GlobalPrimaryCollectionContext context, ReadOnlyCollection`1 items) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/AssemblyConversion/PrimaryCollection/Steps.Global/GenericsCollection.cs:line 32
   at Unity.IL2CPP.AssemblyConversion.Steps.Base.GlobalScheduledStepFunc`3.WorkerWrapper(WorkItemData`3 workerData) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/AssemblyConversion/Steps.Base/GlobalScheduledStepFunc.cs:line 41
   at Unity.IL2CPP.Contexts.Scheduling.PhaseWorkScheduler`1.WorkerLoop(Object data) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/Contexts.Scheduling/PhaseWorkScheduler.cs:line 247
UnityEditorInternal.Runner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:129)
UnityEditorInternal.Runner.RunManagedProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1[T] setupStartInfo) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:65)
UnityEditorInternal.IL2CPPBuilder.RunIl2CppWithArguments (System.Collections.Generic.List`1[T] arguments, System.Action`1[T] setupStartInfo, System.String generatedCppOutputDirectory) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:793)
UnityEditorInternal.IL2CPPBuilder.ConvertPlayerDlltoCpp (UnityEditor.Il2Cpp.Il2CppBuildPipelineData data, System.String outputDirectory, System.Boolean platformSupportsManagedDebugging) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:765)
UnityEditorInternal.IL2CPPBuilder.Run () (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:598)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String tempFolder, System.String stagingAreaData, UnityEditorInternal.IIl2CppPlatformProvider platformProvider, System.Action`1[T] modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:269)
UnityEditor.iOS.PostProcessiPhonePlayer.CrossCompileManagedDlls (UnityEditor.iOS.PostProcessiPhonePlayer+BuildSettings bs, UnityEditor.iOS.PostProcessiPhonePlayer+ProjectPaths paths, UnityEditor.AssemblyReferenceChecker checker, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport buildReport) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:908)
UnityEditor.iOS.PostProcessiPhonePlayer.PostProcess (UnityEditor.iOS.PostProcessiPhonePlayer+BuildSettings bs, UnityEditor.iOS.PostProcessiPhonePlayer+ProjectPaths paths, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport buildReport) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:718)
UnityEditor.iOS.PostProcessiPhonePlayer.PostProcess (UnityEditor.iOS.PostProcessorSettings postProcessorSettings, UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:663)
UnityEditor.iOS.iOSBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/ExtensionModule.cs:45)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.iOS.iOSBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/ExtensionModule.cs:49)
UnityEditor.Modules.DefaultBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at /Users/bokken/buildslave/unity/build/Editor/Mono/Modules/DefaultBuildPostprocessor.cs:29)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:337)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)

```

**Comment by ashishdhingra** [comment] 2021-03-05 21:22
https://github.com/aws/aws-sdk-net/issues/1810

**Comment by halzate93** [comment] 2021-03-08 21:55
An update on this, I created an empty repro project just with the SDK and some test code and everything seems to work fine. I also removed AWS SDK from my project and the build works.

So it seems to be an interaction of the SDK with our project specifically, let me know if you guys have any pointers on your end as to how to debug it.

**Comment by ashishdhingra** [comment] 2021-03-26 20:16
Closing this in favor of #1810

**Closed by ashishdhingra** 2021-03-26 20:16 UTC
Labels: bug, module/s3, module/unity
