### ISSUE TITLE
Out parameters are not being retrieved in amazon redshift for a stored procedure

### ISSUE THREAD

**Issue by APTest22** [aws/aws-sdk-net#2485] opened 2022-11-15 06:36 UTC
### Describe the bug

HI, I am unable to retrieve the Out Parameters of a Stored Procedure in Amazon Redshift , I am only able to retrieve the IN parameters , even INOUT parameters which are accepted when creating the stored procedure later are shown as IN parameters during retrieving them , the Out parameters are taken during the creation of the stored procedure but later not able to retrieve them . below is the following SQL Query I am using to retrieve the Stored Procedure parameters .

" select proc.routine_name as procedure_name,args.parameter_name,args.parameter_mode,args.data_type from information_schema.routines proc left join information_schema.parameters args on proc.specific_schema = args.specific_schema and proc.specific_name = args.specific_name where proc.routine_schema not in ('pg_catalog', 'information_schema') and proc.routine_type = 'PROCEDURE' and proc.specific_name='{0}' order by procedure_name, args.ordinal_position"

Please help me find a solution for this.
Thanks, and Regards

### Expected Behavior

To retrieve Out parameters and In parameters and INOUT parameters

### Current Behavior

only retrieving IN parameters

### Reproduction Steps

Reproduction Steps
Create a stored procedure on Amazon Redshift with IN parameters , INOUT parameters , Out parameters .
after successful creation use the following SQL Query to retrieve the parameters of the stored procedure.
"select proc.routine_name as procedure_name,args.parameter_name,args.parameter_mode,args.data_type from information_schema.routines proc left join information_schema.parameters args on proc.specific_schema = args.specific_schema and proc.specific_name = args.specific_name where proc.routine_schema not in ('pg_catalog', 'information_schema') and proc.routine_type = 'PROCEDURE' and proc.specific_name='{0}' order by procedure_name, args.ordinal_position"
As you can observe the IN parameters are being displayed , the INOUT parameters are also being displayed as IN Parameters , and no Out parameters are being displayed.

### AWS .NET SDK and/or Package version used

AWSRedshiftDataService

### Targeted .NET Platform

.NET Framework 4.8

### Operating System and version

windows 10

**Comment by APTest22** [comment] 2022-11-15 06:40
Even the same behavior is seen on AWS CLI , it would be very helpful if I get a SQL query to retrieve all the parameters of a stored procedure. Currently I am using this query to retrieve the parameters but the OUT and INOUT are not being shown , only the IN parameters are retrieving .      "select proc.routine_name as procedure_name,args.parameter_name,args.parameter_mode,args.data_type from information_schema.routines proc left join information_schema.parameters args on proc.specific_schema = args.specific_schema and proc.specific_name = args.specific_name where proc.routine_schema not in ('pg_catalog', 'information_schema') and proc.routine_type = 'PROCEDURE' and proc.specific_name='{0}' order by procedure_name, args.ordinal_position"

**Comment by ashishdhingra** [comment] 2022-11-15 17:12
Hi @APTest22,

Good morning.

Thanks for opening the issue. I believe there is a similar issue reported earlier https://github.com/aws/aws-sdk-net/issues/2450 which was closed for staleness. As you reported, the same behavior is seen in AWS CLI, so at high level this doesn't appear to be SDK issue. As mentioned in the https://github.com/aws/aws-sdk-net/issues/2450#issuecomment-1277852925, the SDK for `RedshiftDataAPIService` is autogenerated and the behavior is controlled by the service. Could you please let me know the following:

- Share the sample code which uses AWS SDK for .NET for executing the RedShift query.
- What is the output in RedShift QueryEditor in AWS Console? This is just to figure out if it works correctly in AWS Console.
- Could you also compare and share the output of executing the same query using AWS CLI?

Thanks,
Ashish

**Comment by ashishdhingra** [comment] 2022-11-16 01:14
@APTest22 Upon reviewing further, you want to retrieve details of stored procedure and it's parameters, is this correct? Although I have not tested it, it appears that you need to use [PG_PROC_INFO](https://docs.aws.amazon.com/redshift/latest/dg/r_PG_PROC_INFO.html) system view. Please check.

**Comment by APTest22** [comment] 2022-11-16 04:31
hi @ashishdhingra  As this SQL query retrieves all the parameters in other SQL supported databases , not retrieving the OUT parameters and INOUT parameters in Redshift . please find the attached image of AWS CLI showing the same  , and as system view PG_PROC_INFO is very difficult to implement with very less documentation and gives a problem with duplicate procedures . please help me out with some other suggestions Thanks, and Regards.

` "select proc.routine_name as procedure_name,args.parameter_name,args.parameter_mode,args.data_type from information_schema.routines proc left join information_schema.parameters args on proc.specific_schema = args.specific_schema and proc.specific_name = args.specific_name where proc.routine_schema not in ('pg_catalog', 'information_schema') and proc.routine_type = 'PROCEDURE' and proc.specific_name='{0}' order by procedure_name, args.ordinal_position"
<img width="610" alt="awsissue1" src="https://user-images.githubusercontent.com/112923327/202084127-daae0421-9a59-409c-aa02-b0de3ed23514.PNG">
<img width="654" alt="awsissue2" src="https://user-images.githubusercontent.com/112923327/202084134-a7509310-5247-4fac-9367-25ec243b6042.PNG">
`

**Comment by ashishdhingra** [comment] 2022-11-21 22:44
@APTest22 Your screenshot from AWS Console supports the consistent behavior of AWS SDK for .NET (and AWS CLI or other SDKs). This is also supplemented by the the comment https://github.com/aws/aws-sdk-net/issues/2450#issuecomment-1277852925, the SDK for RedshiftDataAPIService is autogenerated and the behavior is controlled by the service. The workaround to use [PG_PROC_INFO](https://docs.aws.amazon.com/redshift/latest/dg/r_PG_PROC_INFO.html) system view is based on the documentation where `proargmodes` column is an array with the modes of the procedure arguments, encoded as 'i' for IN arguments, 'o' for OUT arguments, and 'b' for INOUT arguments. You might want to write some SQL like query which uses sub-queries and/or INNER/OUTER JOIN(s) to get the desired behavior.

The issue is not related to the bug in AWS SDK for .NET (or AWS CLI), but more related to the schema in Amazon Redshift and using that schema to get the desired output. Hence, closing this issue.

**Closed by ashishdhingra** 2022-11-21 22:44 UTC
Labels: guidance, module/sdk-generated
