### ISSUE TITLE
IAmazonS3.GetObjectAsync tries to log and fails because of missing deps log4net.

### ISSUE THREAD

**Issue by ydogus** [aws/aws-sdk-net#649] opened 2017-05-13 16:24 UTC
## Expected Behavior
It should not throw current exception.

## Current Behavior
It throws `MethodAccessException`:
> MethodAccessException: Attempt by method log4net.Core.LoggerManager.RegisterAppDomainEvents()' to access method 'System.AppDomain.add_ProcessExit(System.EventHandler)' failed.

## Steps to Reproduce (for bugs)
I have 3 reproduces.
### First Repro
```
new AmazonS3Client();
```
### After a small fix
I tried to set `DisableLogging` property to `true`. By doing this, I was able to create a `AmazonS3Client` instance. But this time I got this Exception when calling `AmazonS3Client.GetObjectAsync` method:
```
var config = new AmazonS3Config() { DisableLogging = true };
var amazonS3 = new AmazonS3Client(config);
amazonS3.GetObjectAsync("bucketName", "key").Wait();
```
### Tried also this one
```
AWSConfigs.LoggingConfig.LogTo = LoggingOptions.None;
new AmazonS3Client();
```

## Version Info
Using:
- .NET Standard 1.3
- xunit 2.2.0
- AWSSDK.S3 3.3.6.1

**Comment by PavelSafronov** [comment] 2017-05-16 03:24
Duplicate of #620, closing.

**Closed by PavelSafronov** 2017-05-16 03:24 UTC
