### ISSUE TITLE
S3 : sharing violation & stream mismatch exceptions

### ISSUE THREAD

**Issue by mzekrallah** [aws/aws-sdk-net#523] opened 2017-01-04 19:17 UTC
I'm getting an intermittent issue from Amazon S3 SDK in Xamarin ios and android .. The issue is that files failing to download/upload for some users some of the time.. Again it happens sometimes and sometimes it just works with no problems .. Tracing it back to two issues that appear in our error reporting library and I don't know if they related to each other or totally unique .. I post them here : 

**The first issue :** 

`System.IO.IOExceptionSharing violation on path /var/mobile/Containers/Data/Application/DFF51261-1BE8-4C07-A2AA-AADA786BC35B/Documents/con_7137_4002_636191415419672182_342/bu1rcggc.joy0ea5x11r.lre.JPG
`

**Stack Trace :** 

```
System.IO.FileStream.FileStream(string path, FileMode mode, FileAccess access, FileShare share, int bufferSize, bool anonymous, FileOptions options)
System.IO.FileStream.FileStream(string path, FileMode mode, FileAccess access, FileShare share)
System.IO.File.OpenRead(string path)
PCLStorage.FileSystemFile.<OpenAsync>d__0.MoveNext()
Amazon.S3.Transfer.Internal.DownloadCommand.<ByteRangeRemainingForDownloadAsync>d__13.MoveNext()
Amazon.S3.Transfer.Internal.DownloadCommand.<ExecuteAsync>d__11.MoveNext()
Cura.iOS.Core.AmazonS3Helper.DownloadAsync()
Cura.iOS.Core.ChatViewController.DownloadFromS3()


```

**The second issue :** 

`Amazon.S3.Model.StreamSizeMismatchExceptionThe total bytes read 498280 from response stream is not equal to the Content-Length 1223729 for the object con_7137_4002_636191415419672182_342/bu1rcggc.joy0ea5x11r.lre.JPG in bucket XYZ. Request ID = 1D5532E7C2F71769 , AmzId2 = brarxw/GsSbHr0cTiSf+jkwOCfPeAl+/lV56oA/Hi3/45FGxwsLONDT4xYYOEdtBmjOfDi/W/3k=.
`

**Stack Trace** 

```
Amazon.S3.Model.GetObjectResponse.ValidateWrittenStreamSize(long bytesWritten)
Amazon.S3.Model.GetObjectResponse.<WriteResponseStreamToFileAsync>d__101.MoveNext()
Amazon.S3.Transfer.Internal.DownloadCommand.<ExecuteAsync>d__11.MoveNext()
Cura.iOS.Core.AmazonS3Helper.DownloadAsync()
Cura.iOS.Core.ChatViewController.DownloadFromS3()

```

Environment information :

**AWWSDK.S3 Version 3.1.6.1**

=== Xamarin Studio Community ===

Version 6.1.3 (build 19)
Installation UUID: 0b4d0196-d3f2-45db-8dab-cd95bf14c07c
Runtime:
	Mono 4.6.2 (mono-4.6.0-branch/ac9e222) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 406020016

=== NuGet ===

Version: 3.4.3.0

=== Xamarin.Profiler ===

Not Installed

=== Apple Developer Tools ===

Xcode 8.2.1 (11766.1)
Build 8C1002

=== Xamarin.iOS ===

Version: 10.3.1.7 (Xamarin Studio Community)
Hash: 8b53676
Branch: cycle8-xi
Build date: 2016-12-18 12:23:27-0500

=== Xamarin.Android ===

Version: 7.0.2.42 (Xamarin Studio Community)
Android SDK: /Users/mzekrallah/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.2    (API level 17)
		4.3    (API level 18)
		4.4    (API level 19)
		4.4.87 (API level 20)
		5.0    (API level 21)
		5.1    (API level 22)
		6.0    (API level 23)
		7.0    (API level 24)

SDK Tools Version: 25.2.4
SDK Platform Tools Version: 25.0.3
SDK Build Tools Version: 25.0.2

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Android Player ===

Not Installed

=== Xamarin.Mac ===

Not Installed

=== Xamarin Inspector ===

Version: 1.0.0.0
Hash: 1f3067d
Branch: master
Build date: 11/15/2016 11:13:59 PM

=== Build Information ===

Release ID: 601030019
Git revision: 7fabf9293c2d7b638e28a07f798d21799da1f886
Build date: 2016-12-21 07:08:35-05
Xamarin addins: efbae0e683a0060d2230e91e70c1598abc054845
Build lane: monodevelop-lion-cycle8

=== Operating System ===

Mac OS X 10.12.2
Darwin mzekrallah-mbp.zte.com.cn 16.3.0 Darwin Kernel Version 16.3.0
    Thu Nov 17 20:23:58 PST 2016
    root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Xamarin Inspector 1.0.0.0

**Comment by gokarnm** [comment] 2017-01-04 22:34
Hi Mohammad, you said these errors were reported from your customers. Have you been able to replicate these issues locally?

A [quick search](http://stackoverflow.com/search?q=IOException+sharing+violation) for "IOException Sharing violation" indicates that this error can be thrown when the same file is opened again before it was closed by another operation. Is it possible that the file is being opened multiple times simultaneously for download? Given your stack trace, is it possible for users to initiate the download operation twice in quick succession, that might cause this issue.

The StreamSizeMismatchException is trickier to root cause, it may be internet weather but in that case you probably would have seen a different exception. If you have an AWS Support subscription, you can open a support ticket with the Request ID and AmzId2 for further investigation. My suggestion would be to try to replicate this error, and to catch StreamSizeMismatchException and retry the download when this error occurs.

**Comment by mzekrallah** [comment] 2017-01-05 08:04
Hi @gokarnm .. thank you for your feedback .. actually the files get downloaded automatically when you open a chat room (it's like WhatsApp) .. it is not initiated by users .. just opening the screen will automatically start downloading received photos .. the same code is working fine for 1 year now but some people in some conditions are reporting that photos do not get downloaded and I see the exceptions I sent in Xamarin Insights (Error reporting tool) ..  I'm leaning more towards something wrong in the AWS SDK handling it in certain scenarios because stream mismatch seems like something in the low-level aws sdk itself rather than an issue in my code asking for download .. Anyway I will try the support thing but I'm still thinking there is a certain issue in the SDK itself we need to detect .. Appreciate any other opinions as well ..

**Comment by sstevenkang** [comment] 2017-03-16 17:46
Closing this due to inactivity, feel free to reopen this if there's an update or more information we can work with.

**Closed by sstevenkang** 2017-03-16 17:46 UTC
