### ISSUE TITLE
AWSXRayRecorder is full framework only.  Need .NET Core.

### ISSUE THREAD

**Issue by adamhathcock** [aws/aws-sdk-net#500] opened 2016-12-02 08:48 UTC
I don't know where to go for this but it is full framework only.

I could probably port the usage to .NET Core but I don't know where the source is.

**Comment by adamhathcock** [comment] 2016-12-02 08:49
https://www.nuget.org/packages/AWSXRayRecorder/1.0.1-beta

When being installed the target is just `net45`

**Comment by PavelSafronov** [comment] 2016-12-02 23:38
At the moment the AWSXRayRecorder is only supported on net45. We are looking to porting this functionality to .NET Core, but cannot give an ETA.
Keeping this issue open and will update it with any progress.

**Comment by adamhathcock** [comment] 2016-12-03 00:16
Is the code open source?  Is all that is needed is to hook into Asp.Net Core middleware instead of a http handler of whatever the System.Web version was called?

I'm interested in helping.

**Comment by PavelSafronov** [comment] 2016-12-06 18:57
The source for AWSXRayRecorder is not open source at this moment, and I cannot provide an ETA of when (if ever) it will be.

**Comment by adamhathcock** [comment] 2016-12-07 09:06
That's disappointing.  I was hoping the X-Ray protocol would be open so we could embed the implementation in various applications.

**Comment by PavelSafronov** [comment] 2016-12-07 20:25
We are definitely interested in making it as easy as possible for members of the AWS community to implement X-Ray integration in whichever language and framework is best suited to your needs. To that end we are working on documenting the protocol, which should be available in the next few weeks, and will eventually publish the source for the current .NET version to GitHub.

**Comment by adamhathcock** [comment] 2016-12-07 22:23
Great!  Thank you.

**Comment by Caldas** [comment] 2016-12-15 12:51
@PavelSafronov I was looking for AWSXRayRecorder github page, but as I read above I will not found it.

But we are starting using at [VTEX](vtex.com) and one of the problems I found was that library stuck when working in a test environment without XRay service running. I believe in some point the `TracingMessageHandler` handler it lock waiting for service response (sorry I don't know)

Since there isn't a public project I hope you can pass my message forwarder ..

PS: Sorry use reply as "email"

**Comment by PavelSafronov** [comment] 2016-12-15 19:46
@Caldas , please post your question to the [AWX X-Ray forum](https://forums.aws.amazon.com/forum.jspa?forumID=241) and the team should be able to help you out.

**Comment by yishengl** [comment] 2016-12-15 19:54
@Caldas There is no blocking logic in `TracingMessageHandler`. It doesn't acquire any locks or waiting for any external components. Actually, there is no direct connection between XRayRecorder and XRay service. The communication is through a daemon on the host using UDP package. 

As @PavelSafronov stated, AWS X-Ray Forum is the better place to ask any XRay related questions. Can you post your question there and elaborate more about what you did and what's the problem you see? I would like to help you figure out what went wrong.

**Comment by sstevenkang** [comment] 2017-02-03 18:42
Closing this as the discussion seems to be taking place in the forums.  Feel free to reopen if I missed anything.

**Comment by ollnixon** [comment] 2017-04-24 15:13
@sstevenkang: I would suggest that this issue needs to be re-opened. It was originally opened due to lack of .NET Core support which, as far as I can tell, hasn't been implemented.

cc @adamhathcock

**Comment by adamhathcock** [comment] 2017-04-24 17:56
I agree this should be reopened as it was high jacked by an irrelevant question then closed.

**Comment by PavelSafronov** [comment] 2017-04-25 20:28
You are correct, reopening.

**Comment by PavelSafronov** [comment] 2017-04-25 21:43
The [X-Ray Segment documentation](http://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html) provides the documentation around the X-Ray protocol.
We're still working on adding .NET Core support and open-sourcing the AWSXRayRecorder code.

**Comment by adamhathcock** [comment] 2017-04-26 06:16
Would it be helpful to attempt to implement this on ASP.NET Core or is the release close-ish?

**Comment by PavelSafronov** [comment] 2017-04-26 15:39
Sorry, I can't say anything schedule-wise, it's against Amazon policy to provide any estimates on future releases.

**Comment by adamhathcock** [comment] 2017-04-27 14:43
Reimplementing the full protocol is not something I'm looking to do.  I will help with porting to .NET Core and ASP.NET Core once the current code is open sourced however.

**Comment by coreycoto** [comment] 2017-06-06 00:33
@PavelSafronov any updates on when the AWSXRayRecorder will be open sourced?

**Comment by PavelSafronov** [comment] 2017-06-06 01:23
Sorry, it's against Amazon policy to discuss launch dates, so I cannot provide any sort of ETA.

**Comment by auriou** [comment] 2017-06-19 07:05
Hello, I am also waiting, to implement it in lambda .net functions through api gateway with core dotnet, thanks.

Another small problem about cloudformation to configure x-ray on a lambda : 

TracingConfig : {Mode: "Active"}  # does not exist in your documentation, but it's ok with cloudformation?
`
# LAMBDA EXECUTION HANDLER ASP.NET
    LambdaApi:
        Type: 'AWS::Lambda::Function'
        Properties:
            FunctionName: TestApiRest-Lambda
            TracingConfig: {Mode: Active } # ACTIVE X-RAY
            Handler: 'TestAWSServerless::TestAWSServerless.LambdaEntryPoint::FunctionHandlerAsync'
            MemorySize: 256  
            Role: {'Fn::GetAtt': [LambdaRole, Arn]}
            Runtime: dotnetcore1.0
            Timeout: 30`

AWS Lambda Function TracingConfig
http://docs.aws.amazon.com/fr_fr/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-tracingconfig.html


Here, There is no reference at propertie TracingConfig
AWS::Lambda::Function
http://docs.aws.amazon.com/fr_fr/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html


And the template cloudformation : "serverless.template", into visual studio 2017 Reports error for TraceConfig, but publish into AWS works well

**Comment by flynnCoolblue** [comment] 2017-08-06 09:24
bump for xray with .net core

**Comment by erick-thompson** [comment] 2017-08-29 22:33
Any progress on this? It is been quiet for a while

**Comment by eric-davis** [comment] 2017-11-16 17:28
bump for xray with .NET Core!!!

**Comment by normj** [comment] 2017-11-16 19:19
Progress is being made to get .NET Core support. Out of curiosity what type of environments are you planning to use X-Ray in? Beanstalk, Lambda, other?

**Comment by rnowosielski** [comment] 2017-11-16 19:33
I am planning to use it in an Lambda

**Comment by Caldas** [comment] 2017-11-16 19:42
I Will be using on ECS/Beanstalk

Em 16 de nov de 2017 5:19 PM, "Norm Johanson" <notifications@github.com>
escreveu:

**Comment by ljacobsson** [comment] 2017-11-16 23:04
Lambda

**Comment by AbbTek** [comment] 2017-11-17 00:29
Lambda

**Comment by kyngvesson** [comment] 2017-11-17 06:56
Lambda

**Comment by timker** [comment] 2017-11-18 20:51
ec2 docker .net core 2.0

**Comment by maynardflies** [comment] 2017-11-20 21:12
EC2 Docker Beanstalk

**Comment by eric-davis** [comment] 2017-11-21 16:08
EC2 Docker .NET Core 2.0

**Comment by tsibelman** [comment] 2017-11-27 13:30
Doing Lambdas just now, and it an absolute must-have for production debugging.
Any chance we getting it at ReInvent  :)  ?

**Comment by dls314** [comment] 2017-11-27 17:54
ECS Docker .NET Core 2

**Comment by tsibelman** [comment] 2017-11-27 20:37
@PavelSafronov @normj I checked the [license](https://www.nuget.org/packages/AWSXRayRecorder.Handlers.AwsSdk/) you use for AWSXRayRecorder it looks like you explicitly allow to make a derivative work based on it. 

Let me quite it
"Subject to the terms and conditions of this License, each Contributor hereby grants to You a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare Derivative Works of, publicly display, publicly perform, sublicense, and distribute the Work and such Derivative Works in Source or Object form."

So as I understand it nothing is stopping me or anyone else to jus dissamble your dll and just prepare a version for .net core.

**Comment by normj** [comment] 2017-11-30 17:06
Yesterday I did my .NET Core session at our AWS re:Invent conference. In my session, .NET Core 2.0 Lambda support was officially pre announced and it is coming soon. To help prove it was coming soon, we actually demoed running an ASP.NET Core application with Razor pages using our upcoming .NET Core 2.0 runtime from the us-west-2 region.

We also demoed upcoming .NET Core 2.0 X-Ray support as well. That will probably come out around the same time as .NET Core 2.0 Lambda support. .NET Core 1.0 didn't have some of the API we needed to port the existing .NET Framework version to .NET Core. There has also been a lot of work done to make it easier to use X-Ray for .NET in the upcoming version.

The session will be posted online soon and I'll post a link for those that wanted to see that demo.

@tsibelman Yes you could disassemble the assembly and make your own .NET Core but you want have to wait much longer for our official support.

**Comment by eric-davis** [comment] 2017-11-30 17:10
Hey Norm - I was in your session. It was great! Thank you. Really excited about what is coming. I just hope "soon" actually is just that. ;-)

**Comment by normj** [comment] 2017-11-30 17:14
@eric-davis Thanks! Glad you liked it.

**Comment by tsibelman** [comment] 2017-11-30 17:40
Great news @normj let's make .net great again :)

**Comment by normj** [comment] 2017-12-01 01:09
My session is online if anybody wants to see the .NET Core 2.0 Lambda demo with X-Ray support. The Lambda part starts about 13 minutes into the talk. There is also some cool ECS Fargate support we talked about after the Lambda section.

https://www.youtube.com/watch?v=IfF1E2RJ6Do

**Comment by ljacobsson** [comment] 2018-01-19 12:03
Thanks for dotnet core 2.0 support! Is xray support still to be expected soon or should I stop popping in here every morning for a while? :-)

**Comment by normj** [comment] 2018-01-19 17:12
@ljacobsson We should have .NET Core 2.0 X-Ray support out soon. My focus right now is actually helping the X-Ray team finish up some final details.

**Comment by normj** [comment] 2018-02-05 20:13
AWS X-Ray support for .NET Core 2.0 is out today. Checkout the new AWS X-Ray .NET [GitHub](https://github.com/aws/aws-xray-sdk-dotnet) repository which has a lot of the information on how to use it. There is also a new version of the AWS Toolkit for Visual Studio that allows you to enable X-Ray in Beanstalk and Lambda environments.

Closing this issue as the support has been released. For issues with the new .NET X-Ray SDK open an issue on the new [.NET X-Ray GitHub repository.](https://github.com/aws/aws-xray-sdk-dotnet)

**Closed by normj** 2018-02-05 20:13 UTC
Labels: .NET Core, Feature Request

**Comment by eric-davis** [comment] 2018-02-06 00:57
Woohoo! Thanks for the update!
