### ISSUE TITLE
The environment variable AWS_ENABLE_ENDPOINT_DISCOVERY was not set with a boolean value.

### ISSUE THREAD

**Issue by paulmattinglybv** [aws/aws-sdk-net#1876] opened 2021-07-02 12:40 UTC
## Description
After using the SDK with no problems for a long time, today I am getting two exceptions when trying to perform a basic Dynamo DB query

## Reproduction Steps
Create a DynamoDBv2 client which uses credentials from the `.credentials` file. Call `QueryAsync` with a request object

![image](https://user-images.githubusercontent.com/50362859/124275270-2a591780-db3a-11eb-9b0c-2ce6c68dc74e.png)

### Environment

AWSSDK.DynamoDBv2 3.3.105.6
AWSSDK.Core 3.3.104.32
Windows 10, Visual Studio 16.10.2
Targeting .NET Framework 4.7.2

Stack traces

System.InvalidOperationException
  HResult=0x80131509
  Message=The environment variable AWS_ENABLE_ENDPOINT_DISCOVERY was not set with a boolean value.
  Source=AWSSDK.Core
  StackTrace:
   at Amazon.Runtime.EnvironmentVariableAWSEndpointDiscoveryEnabled..ctor() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\EndpointDiscoveryEnabled.cs:line 46

System.InvalidOperationException
  HResult=0x80131509
  Message=There is no endpoint_discovery_enabled set in the profile named 'default' in store Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain
  Source=AWSSDK.Core
  StackTrace:
   at Amazon.Runtime.ProfileAWSEndpointDiscoveryEnabled.Setup(ICredentialProfileSource source, String profileName) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\EndpointDiscoveryEnabled.cs:line 111

The AWS CLI is working fine and the AWS ToolKit extension for Visual Studio is also working.

The classes mentioned in the stack trace seem to be marked as obsolete? I have found very little information when Googling the name of the environment variable. I have never had to use environment variables in the past.

Any help much appreciated. Thanks

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment] 2021-07-02 14:52
Hi @paulmattinglybv,

Good morning.

Could you please try using the latest version of `AWSSDK.DynamoDBv2` and check if it resolves the issue? These basic operations should not give any error. Also share the list of environment variables defined for the environment, and how the credentials and region are configured.

Thanks,
Ashish

**Comment by paulmattinglybv** [comment] 2021-07-02 15:41
There are no AWS environment variables configured and I am using the `%USERPROFILE%\.aws\credentials` file for access key storage. The region is configured in the `config` file and is also configured for each pair in the `credentials` file. It is also passed into the client as a parameter when setting up.

I can get round the issue by adding `endpoint_discovery_enabled=false` into the credentials file. The exception regarding the environment variables is still thrown. I am sure that will disappear if I were to add the environment variable.

Upgrading to the latest of `AWSSDK.DynamoDBv2` and `AWSSDK.Core` also fixes the issue.

Thanks
Paul

**Comment by ashishdhingra** [comment] 2021-07-02 15:46
> There are no AWS environment variables configured and I am using the `%USERPROFILE%\.aws\credentials` file for access key storage. The region is configured in the `config` file and is also configured for each pair in the `credentials` file. It is also passed into the client as a parameter when setting up.
> 
> I can get round the issue by adding `endpoint_discovery_enabled=false` into the credentials file. The exception regarding the environment variables is still thrown. I am sure that will disappear if I were to add the environment variable.
> 
> Upgrading to the latest of `AWSSDK.DynamoDBv2` and `AWSSDK.Core` also fixes the issue.
> 
> Thanks
> Paul

@paulmattinglybv Thanks for your reply. Since you confirmed that this issue is not seen in the latest version, hence, closing the same.

**Closed by ashishdhingra** 2021-07-02 15:46 UTC
Labels: guidance, module/dynamodb, response-requested
