### ISSUE TITLE
[Feature request] Add a way to check if optional fields in responses are set.

### ISSUE THREAD

**Issue by hsuantio** [aws/aws-sdk-net#1331] opened 2019-07-01 11:28 UTC
EC2 launch template created using Powershell fails to launch EC2 instance due to gp2 EBS disk IOPS value is set to default value of 0. Error message: ````"The parameter iops is not supported for gp2 volumes"````

## Expected Behavior

1. When launching an EC2 instance from a launch template, if EBS disk volume type is gp2, specified IOPS value should not be used as specified [here.](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_LaunchTemplateEbsBlockDeviceRequest.html) Otherwise, it should be possible to set ````Amazon.EC2.Model.LaunchTemplateEbsBlockDeviceRequest.Iops```` value to null.
2. If ````Amazon.EC2.Model.LaunchTemplateEbsBlockDeviceRequest.Iops```` value is null, it should return the same value retrieved using other SDKs. 

## Current Behavior
1. The ````New-EC2LaunchTemplateVersion```` cmdlet accepts either or both ````-LaunchTemplateData```` or/and ````-SourceTemplateData```` parameters for launch template data. Focusing only on ````-LaunchTemplateData```` parameter:
a. The cmdlet's ````LaunchTemplateData```` parameter accepts ````Amazon.EC2.Model.RequestLaunchTemplateData```` object class.
b. ````Amazon.EC2.Model.RequestLaunchTemplateData```` object class has an EBS disk mapping property which is a list of ````Amazon.EC2.Model.LaunchTemplateBlockDeviceMappingRequest```` object class.
c.  ````Amazon.EC2.Model.LaunchTemplateBlockDeviceMappingRequest```` object class has a Ebs disk property which is an ````Amazon.EC2.Model.LaunchTemplateEbsBlockDeviceRequest```` object class.
d. ````Amazon.EC2.Model.LaunchTemplateEbsBlockDeviceRequest```` object class' ````Iops```` property is an integer data type.

By default, when ````Amazon.EC2.Model.LaunchTemplateEbsBlockDeviceRequest```` object is created, the Iops property is set as 0 as shown below:
```
$ebs_disk = New-Object Amazon.EC2.Model.LaunchTemplateEbsBlockDeviceRequest
$ebs_disk
DeleteOnTermination : False
Encrypted           : False
Iops                : 0
KmsKeyId            :
SnapshotId          :
VolumeSize          : 0
VolumeType          :
```
Nullify the Iops property has no effect:
```
$ebs_disk.iops = $null                                                    
$ebs_disk                                                                                                                                  
DeleteOnTermination : False                                                 
Encrypted           : False                                                 
Iops                : 0                                                     
KmsKeyId            :                                                       
SnapshotId          :                                                       
VolumeSize          : 0                                                     
VolumeType          :     
```

Available methods:
```
$ebs_disk.iops | Get-Member
   TypeName: System.Int32

Name        MemberType Definition
----        ---------- ----------
CompareTo   Method     int CompareTo(System.Object value), int CompareTo(int value), int IComparable.CompareTo(System.Object obj), int IComparable[int].CompareTo(int other)
Equals      Method     bool Equals(System.Object obj), bool Equals(int obj), bool IEquatable[int].Equals(int other)
GetHashCode Method     int GetHashCode()
GetType     Method     type GetType()
GetTypeCode Method     System.TypeCode GetTypeCode(), System.TypeCode IConvertible.GetTypeCode()
ToBoolean   Method     bool IConvertible.ToBoolean(System.IFormatProvider provider)
ToByte      Method     byte IConvertible.ToByte(System.IFormatProvider provider)
ToChar      Method     char IConvertible.ToChar(System.IFormatProvider provider)
ToDateTime  Method     datetime IConvertible.ToDateTime(System.IFormatProvider provider)
ToDecimal   Method     decimal IConvertible.ToDecimal(System.IFormatProvider provider)
ToDouble    Method     double IConvertible.ToDouble(System.IFormatProvider provider)
ToInt16     Method     int16 IConvertible.ToInt16(System.IFormatProvider provider)
ToInt32     Method     int IConvertible.ToInt32(System.IFormatProvider provider)
ToInt64     Method     long IConvertible.ToInt64(System.IFormatProvider provider)
ToSByte     Method     sbyte IConvertible.ToSByte(System.IFormatProvider provider)
ToSingle    Method     float IConvertible.ToSingle(System.IFormatProvider provider)
ToString    Method     string ToString(), string ToString(string format), string ToString(System.IFormatProvider provider), string ToString(string format, System.IFormatProvider provider), string IFormattable.ToString(string format, Sys... ToType      Method     System.Object IConvertible.ToType(type conversionType, System.IFormatProvider provider)
ToUInt16    Method     uint16 IConvertible.ToUInt16(System.IFormatProvider provider)
ToUInt32    Method     uint32 IConvertible.ToUInt32(System.IFormatProvider provider)
ToUInt64    Method     uint64 IConvertible.ToUInt64(System.IFormatProvider provider)
```               
Failure to nullify the IOPS property when ````VolumeType```` is ````gp2```` renders the launch template unusable as launching EC2 instances using GUI or any other method failed with this error: ````"The parameter iops is not supported for gp2 volumes"````

2. If ````Amazon.EC2.Model.LaunchTemplateEbsBlockDeviceRequest.Iops```` is null:
a. Powershell returns 0.
b. Other SDKs, such as Python returns the correct value of null.

## Steps to Reproduce (Powershell)
1. Issue 1
````
#Create LaunchTemplateEbsBlockDeviceRequest: https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/EC2/TLaunchTemplateEbsBlockDeviceRequest.html
$LaunchTemplateEbsBlockDeviceRequest = New-Object -TypeName Amazon.EC2.Model.LaunchTemplateEbsBlockDeviceRequest
$LaunchTemplateEbsBlockDeviceRequest.DeleteOnTermination = $true
$LaunchTemplateEbsBlockDeviceRequest.Iops = $null
$LaunchTemplateEbsBlockDeviceRequest.SnapshotId = "snap-0aaa4145f66e70c33" #AMI ami-0bbdf9279190cdd33 root device snapshot ID
$LaunchTemplateEbsBlockDeviceRequest.VolumeSize = 30
$LaunchTemplateEbsBlockDeviceRequest.VolumeType = "gp2" 

#Create LaunchTemplateBlockDeviceMappingRequest: https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/EC2/TLaunchTemplateBlockDeviceMappingRequest.html
$LaunchTemplateBlockDeviceMappingRequest = New-Object -TypeName Amazon.EC2.Model.LaunchTemplateBlockDeviceMappingRequest
$LaunchTemplateBlockDeviceMappingRequest.Ebs = $LaunchTemplateEbsBlockDeviceRequest
$LaunchTemplateBlockDeviceMappingRequest.DeviceName = "/dev/sda1"

#Create RequestLaunchTemplateData: https://docs.aws.amazon.com/sdkfornet/v3/apidocs/index.html?page=EC2/TEC2RequestLaunchTemplateData.html&tocid=Amazon_EC2_Model_RequestLaunchTemplateData
$RequestLaunchTemplateData = New-Object -TypeName Amazon.EC2.Model.RequestLaunchTemplateData
$RequestLaunchTemplateData.BlockDeviceMappings = $LaunchTemplateBlockDeviceMappingRequest
$RequestLaunchTemplateData.ImageId = "ami-0bbdf9279190cdd33"

#Create EC2 launch template
New-EC2LaunchTemplate -LaunchTemplateData $RequestLaunchTemplateData -LaunchTemplateName "TestIssue1"

#Create LaunchTemplateSpecification: https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/EC2/TLaunchTemplateSpecification.html
$LaunchTemplateSpec = New-Object -TypeName Amazon.EC2.Model.LaunchTemplateSpecification
$LaunchTemplateSpec.LaunchTemplateName = "TestIssue1"
$LaunchTemplateSpec.Version = 1

#Launch new EC2 instance from created launch template
New-EC2Instance -LaunchTemplate $LaunchTemplateSpec -SubnetId subnet-0924382f5e3e147df

# Exception caught
<# New-EC2Instance : The parameter iops is not supported for gp2 volumes.
At line:1 char:1
+ New-EC2Instance -LaunchTemplate $LaunchTemplateSpec -SubnetId subnet- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Amazon.PowerShe...2InstanceCmdlet:NewEC2InstanceCmdlet) [New-EC2Instance], InvalidOperationException
    + FullyQualifiedErrorId : Amazon.EC2.AmazonEC2Exception,Amazon.PowerShell.Cmdlets.EC2.NewEC2InstanceCmdlet #>
````

2. Issue 2
a. Create a new version of TestIssue1 launch template using GUI or other SDKs other than .NET/Powershell. Set the gp2 EBS disk from 0 to null.
b. Retrieve the value using Powershell:
````
((Get-EC2TemplateVersion -LaunchTemplateName "TestIssue1").LaunchTemplateData.BlockDeviceMappings | Where-Object {$_.DeviceName -Match "/dev/sda1"}).Ebs

DeleteOnTermination : True                   
Encrypted           : False                  
Iops                : 0                      
KmsKeyId            :                        
SnapshotId          : snap-0a1194e6c78114ead 
VolumeSize          : 30                     
VolumeType          : gp2                    
                                             
DeleteOnTermination : True                   
Encrypted           : False                  
Iops                : 0                      
KmsKeyId            :                        
SnapshotId          : snap-0aaa4145f66e70c33 
VolumeSize          : 30                     
VolumeType          : gp2                    
````
Retrieving the same object using AWS CLI:
````
aws ec2 describe-launch-template-versions --launch-template-name "TestIssue1"   
{                                                                                 
    "LaunchTemplateVersions": [                                                   
        {                                                                         
            "LaunchTemplateId": "lt-0a0270f2a4d8a9793",                           
            "LaunchTemplateName": "TestIssue1",                                   
            "VersionNumber": 2,                                                   
            "CreateTime": "2019-07-01T11:15:20.000Z",                             
            "CreatedBy": "arn:aws:iam::752879605274:user/apiuser",                
            "DefaultVersion": false,                                              
            "LaunchTemplateData": {                                               
                "BlockDeviceMappings": [                                          
                    {                                                             
                        "DeviceName": "/dev/sda1",                                
                        "Ebs": {                                                  
                            "DeleteOnTermination": true,                          
                            "SnapshotId": "snap-0a1194e6c78114ead",               
                            "VolumeSize": 30,                                     
                            "VolumeType": "gp2"                                   
                        }                                                         
                    }                                                             
                ],                                                                
                "ImageId": "ami-0bbdf9279190cdd33"                                
            }                                                                     
        },                                                                        
        {                                                                         
            "LaunchTemplateId": "lt-0a0270f2a4d8a9793",                           
            "LaunchTemplateName": "TestIssue1",                                   
            "VersionNumber": 1,                                                   
            "CreateTime": "2019-07-01T10:48:08.000Z",                             
            "CreatedBy": "arn:aws:iam::752879605274:user/apiuser",                
            "DefaultVersion": true,                                               
            "LaunchTemplateData": {                                               
                "BlockDeviceMappings": [                                          
                    {                                                             
                        "DeviceName": "/dev/sda1",                                
                        "Ebs": {                                                  
                            "DeleteOnTermination": true,                          
                            "Iops": 0,                                            
                            "SnapshotId": "snap-0aaa4145f66e70c33",               
                            "VolumeSize": 30,                                     
                            "VolumeType": "gp2"                                   
                        }                                                         
                    }                                                             
                ],                                                                
                "ImageId": "ami-0bbdf9279190cdd33"                                
            }                                                                     
        }                                                                         
    ]                                                                             
}                                                                                 
````
Notice the same object IOPS value returned from Powershell is different from AWS CLI.

## Context
Unable to implement launch template/versions automation using Powershell. Workaround is to use other SDKs however this is not practical given the automation is based on Powershell.

## Your Environment

* AWSPowershell used: 3.3.522.0
* Service assembly and version used: .NET 4.7.2
* Operating System and version: Windows 10 (10.0.17763)
* Visual Studio version: 2017
* Targeted .NET platform: .NET 4.7.2

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by matteo-prosperi** [comment] 2019-07-03 17:37
Hello,
thanks for the detailed description of the issue. This is related to how service inputs and outputs are modeled in the AWS SDK for .NET, not an issue with the AWSPowerShell module itself.

***Ramblings about internal modeling of the `Iops` property***
Both service inputs (like `LaunchTemplateEbsBlockDeviceRequest`) and outputs (like `LaunchTemplateEbsBlockDevice` returned by `Get-EC2TemplateVersion`) have, internally, all nullable fields.
If you look [here](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/EC2/Generated/Model/LaunchTemplateEbsBlockDeviceRequest.cs) `_iops` is `int?` (nullable). The value is made available to the user through the public property `Iops` which is `int` (not nullable) and the default value (`0`) is returned in case the field is not set.
A method named `IsSetIops()` allows to check if the `Iops` property is set or not (whether `_iops` is `null` or not), but unfortunately the method is `internal`.
The same is true for `LaunchTemplateEbsBlockDevice`.

When the request is serialized to be sent to the EC2 service, the `IsSetIops()` method is called (see [here](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/EC2/Generated/Model/Internal/MarshallTransformations/CreateLaunchTemplateRequestMarshaller.cs)) to verify if the `Iops` field should be sent to the service or not. If `Iops` is not set, the parameter is not sent to the service. This is working as designed: if you don't assign a value to the `Iops` property, the `_iops` value will be `null` and the property will not be sent to the service.

The reasoning behind this modeling is to avoid exposing users to unnecessary nullable properties which are more cumbersome to use.

For `LaunchTemplateEbsBlockDevice` this is more of a problem, because you are receiving this object back from the service and you don't have a way (because `IsSetIops()` is `internal`) to distinguish if `Iops` is `null` or `0`.

***Workaround for Issue 1***
The issue is caused by PowerShell treating
```
$LaunchTemplateEbsBlockDeviceRequest.Iops = $null
```
as if it were
```
$LaunchTemplateEbsBlockDeviceRequest.Iops = 0
```
which results in you setting the value to 0. If you remove this line and just do the following
```
$LaunchTemplateEbsBlockDeviceRequest = New-Object -TypeName Amazon.EC2.Model.LaunchTemplateEbsBlockDeviceRequest
$LaunchTemplateEbsBlockDeviceRequest.DeleteOnTermination = $true
$LaunchTemplateEbsBlockDeviceRequest.SnapshotId = "snap-0aaa4145f66e70c33" #AMI ami-0bbdf9279190cdd33 root device snapshot ID
$LaunchTemplateEbsBlockDeviceRequest.VolumeSize = 30
$LaunchTemplateEbsBlockDeviceRequest.VolumeType = "gp2" 
```
the issue should be solved. Even if printing the object will still show `Iops` being `0`, the property will actually be considered unset and not set to the service.
You can double-check that the property is unset by checking the non-public `IsSetIops` method:
```
($LaunchTemplateEbsBlockDeviceRequest.GetType().GetMethods('NonPublic,Instance') | Where-Object Name -eq IsSetIops).Invoke($LaunchTemplateEbsBlockDeviceRequest, @())
```

***Workaround for Issue 2***
The `Get-EC2TemplateVersion` cmdlet ([`DescribeLaunchTemplateVersions`](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/EC2/MEC2DescribeLaunchTemplateVersionsDescribeLaunchTemplateVersionsRequest.html) operation) returns a [`LaunchTemplateEbsBlockDevice`](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/EC2/TLaunchTemplateEbsBlockDevice.html) where `Iops` can be either an integer or unset. If it is unset, the `Iops` property will still show 0.
In case you really need to check if `Iops` is set, you can again use
```
$var = ((Get-EC2TemplateVersion -LaunchTemplateName "TestIssue1").LaunchTemplateData.BlockDeviceMappings | Where-Object {$_.DeviceName -Match "/dev/sda1"}).Ebs
($var.GetType().GetMethods('NonPublic,Instance') | Where-Object Name -eq IsSetIops).Invoke($var, @())
```

We will need to discuss what is a user-friendly approach to make this information available.

***Disclaimer***
My workarounds show you how to use the internal `IsSetIops` method. Please consider that internal methods may change without warning in future versions of the SDKs.

**Comment by hsuantio** [comment] 2019-07-04 01:29
Thank you for the explanation in great details, there's always something new to learn every day. Workaround1 works perfectly to launch an EC2 instance from a launch template created using Powershell. Workaround2 provides us a way to determine whether the IOPS value is set or not.

We are now back to the issue we have encountered that led to the original post when creating subsequent versions of a launch template using Powershell. Details are as follows:
````
$LaunchTemplateName = "TestIssue2"
#Create LaunchTemplateEbsBlockDeviceRequest: https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/EC2/TLaunchTemplateEbsBlockDeviceRequest.html
$LaunchTemplateEbsBlockDeviceRequest = New-Object -TypeName Amazon.EC2.Model.LaunchTemplateEbsBlockDeviceRequest
$LaunchTemplateEbsBlockDeviceRequest.DeleteOnTermination = $true
$LaunchTemplateEbsBlockDeviceRequest.SnapshotId = "snap-0a1194e6c78114ead" #AMI ami-0bbdf9279190cdd33 root device snapshot ID
$LaunchTemplateEbsBlockDeviceRequest.VolumeSize = 30
$LaunchTemplateEbsBlockDeviceRequest.VolumeType = "gp2" 

#Create LaunchTemplateBlockDeviceMappingRequest: https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/EC2/TLaunchTemplateBlockDeviceMappingRequest.html
$LaunchTemplateBlockDeviceMappingRequest = New-Object -TypeName Amazon.EC2.Model.LaunchTemplateBlockDeviceMappingRequest
$LaunchTemplateBlockDeviceMappingRequest.Ebs = $LaunchTemplateEbsBlockDeviceRequest
$LaunchTemplateBlockDeviceMappingRequest.DeviceName = "/dev/sda1"

#Create RequestLaunchTemplateData: https://docs.aws.amazon.com/sdkfornet/v3/apidocs/index.html?page=EC2/TEC2RequestLaunchTemplateData.html&tocid=Amazon_EC2_Model_RequestLaunchTemplateData
$RequestLaunchTemplateData = New-Object -TypeName Amazon.EC2.Model.RequestLaunchTemplateData
$RequestLaunchTemplateData.BlockDeviceMappings = $LaunchTemplateBlockDeviceMappingRequest
$RequestLaunchTemplateData.ImageId = "ami-0bbdf9279190cdd33"

#Create EC2 launch template
New-EC2LaunchTemplate -LaunchTemplateData $RequestLaunchTemplateData -LaunchTemplateName $LaunchTemplateName

#Check if v1 launch template __iops is set using IsSetIops() method 
$IsSetIopsValue = ((Get-EC2TemplateVersion -LaunchTemplateName $LaunchTemplateName -Version 1).LaunchTemplateData.BlockDeviceMappings | Where-Object {$_.DeviceName -Match "/dev/sda1"}).Ebs
Write-Host "Is v1 IOPS value set: $(($IsSetIopsValue.GetType().GetMethods('NonPublic,Instance') | Where-Object Name -eq IsSetIops).Invoke($IsSetIopsValue, @()))"
#Returns false, all good.

#Create LaunchTemplateSpecification: https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/EC2/TLaunchTemplateSpecification.html
$LaunchTemplateSpec = New-Object -TypeName Amazon.EC2.Model.LaunchTemplateSpecification
$LaunchTemplateSpec.LaunchTemplateName = $LaunchTemplateName
$LaunchTemplateSpec.Version = 1

#Launch new EC2 instance from created launch template
New-EC2Instance -LaunchTemplate $LaunchTemplateSpec -SubnetId subnet-0924382f5e3e147df
#Instance launched successfully.

#Create new launch template version from original TestIssue2 as-is. This is launch template version 2.
New-EC2LaunchTemplateVersion -SourceTemplateData (Get-EC2TemplateVersion -LaunchTemplateName $LaunchTemplateName -Version 1).LaunchTemplateData -LaunchTemplateName $LaunchTemplateName

#Check if v2 launch template __iops is set using IsSetIops() method
$IsSetIopsValue = ((Get-EC2TemplateVersion -LaunchTemplateName $LaunchTemplateName -Version 2).LaunchTemplateData.BlockDeviceMappings | Where-Object {$_.DeviceName -Match "/dev/sda1"}).Ebs
Write-Host "Is v2 IOPS value set: $(($IsSetIopsValue.GetType().GetMethods('NonPublic,Instance') | Where-Object Name -eq IsSetIops).Invoke($IsSetIopsValue, @()))"
#Returns true, the value is now set for some reason.

#Let's see if I can apply a workaround
$LatestLaunchTemplateData = (Get-EC2TemplateVersion -LaunchTemplateName $LaunchTemplateName -Version (Get-EC2TemplateVersion -LaunchTemplateName $LaunchTemplateName | Sort-Object VersionNumber -Descending | Select-Object -First 1).VersionNumber).LaunchTemplateData
$LaunchTemplateEbsBlockDevice = New-Object -TypeName Amazon.EC2.Model.LaunchTemplateEbsBlockDevice 
$LaunchTemplateEbsBlockDevice.DeleteOnTermination = $LatestLaunchTemplateData.BlockDeviceMappings.Ebs.DeleteOnTermination
$LaunchTemplateEbsBlockDevice.SnapshotId = $LatestLaunchTemplateData.BlockDeviceMappings.Ebs.SnapshotId
$LaunchTemplateEbsBlockDevice.VolumeSize = $LatestLaunchTemplateData.BlockDeviceMappings.Ebs.VolumeSize
$LaunchTemplateEbsBlockDevice.VolumeType = $LatestLaunchTemplateData.BlockDeviceMappings.Ebs.VolumeType

#The new template data EBS IOPS should not be set now
$ModifiedTemplateData = $LatestLaunchTemplateData
$ModifiedTemplateData.BlockDeviceMappings[0].Ebs = $LaunchTemplateEbsBlockDevice
Write-Host "Is ModifiedTemplateData IOPS value set: $(($ModifiedTemplateData.BlockDeviceMappings.Ebs.GetType().GetMethods('NonPublic,Instance') | Where-Object Name -eq IsSetIops).Invoke($ModifiedTemplateData.BlockDeviceMappings.Ebs, @()))"
#Returns false, new LaunchTemplateEbsBlockDevice IOPS looks good.

#So we now have a LaunchTemplateData which IOPS value is unset. Let's create a new launch template version using this one as v3.
New-EC2LaunchTemplateVersion -SourceTemplateData $ModifiedTemplateData -LaunchTemplateName $LaunchTemplateName

$IsSetIopsValue = ((Get-EC2TemplateVersion -LaunchTemplateName $LaunchTemplateName -Version 3).LaunchTemplateData.BlockDeviceMappings | Where-Object {$_.DeviceName -Match "/dev/sda1"}).Ebs
Write-Host "Is v3 IOPS value set: $(($IsSetIopsValue.GetType().GetMethods('NonPublic,Instance') | Where-Object Name -eq IsSetIops).Invoke($IsSetIopsValue, @()))"
#For some reason, now the value is set to true. Something's going on with -SourceTemplateData mapping values from ResponseLaunchTemplateData to RequestLaunchTemplateData?

#Let's try to launch an EC2 instance using v3 launch template
$LaunchTemplateSpec.Version = 3
New-EC2Instance -LaunchTemplate $LaunchTemplateSpec -SubnetId subnet-0924382f5e3e147df
<# Exception caught
The parameter iops is not supported for gp2 volumes.
At MapLaunchTemplate1.ps1:47 char:1
+ New-EC2Instance -LaunchTemplate $LaunchTemplateSpec -SubnetId subnet- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Amazon.PowerShe...2InstanceCmdlet:NewEC2InstanceCmdlet) [New-EC2Instance], InvalidOperationException
    + FullyQualifiedErrorId : Amazon.EC2.AmazonEC2Exception,Amazon.PowerShell.Cmdlets.EC2.NewEC2InstanceCmdlet #>
````
The alternative is to manually map `Amazon.EC2.Model.ResponseLaunchTemplateData` to `Amazon.EC2.Model.RequestLaunchTemplateData` and use `-LaunchTemplateData` parameter instead, but we were under the impression that this is what `-SourceTemplateData` does.

Thoughts?

**Comment by matteo-prosperi** [comment] 2019-07-10 16:00
Duplicate of https://github.com/aws/aws-tools-for-powershell/issues/26. Closing in favor of the other issue because the root cause is in the code of the AWSPowerShell module.

**Comment by matteo-prosperi** [comment] 2019-07-10 16:01
Sorry, reopening because this is still a valid feature request: "Add a way to check if optional response fields (that are value types) are set"

**Comment by matteo-prosperi** [comment] 2019-07-19 15:36
AWSSDK.Core 3.3.103.12 (https://github.com/aws/aws-sdk-net/commit/ceaa9758f43e60814775c003220133ba3eea1713) has a new utility method `AWSSDKUtils.IsPropertySet` which allows checking whether a value-type (`int`, `long`, `bool`, `DateTime`...) response field has the default value (`0`, `false`...) or is unset (missing from the service response).

```
AWSSDKUtils.IsPropertySet(responseObject, nameof(responseObject.Field))
```

Please note:
- `AWSSDKUtils.IsPropertySet` can be used on nullable fields, but it is unnecessary because you could simply check for `!= null`
- `AWSSDKUtils.IsPropertySet` uses reflection so, even if we built in some caching, performances may be slower than expected
- at the moment `AWSSDKUtils.IsPropertySet` doesn't support objects from the S3 service model.

**Closed by matteo-prosperi** 2019-07-19 15:36 UTC
Labels: feature-request, guidance
