### ISSUE TITLE
Aws.Crt.Auth.AwsSigner is unable to sign a request using SigV4A when using Unity for Android and iOS

### ISSUE THREAD

**Issue by ivgnt** [aws/aws-sdk-net#2126] opened 2022-10-10 04:59 UTC
### Describe the bug

In my Unity project I am trying to access AWS multi-region access point using the following code:
```
Config = new AmazonS3Config();

Config.UseArnRegion = false;
Config.RegionEndpoint = RegionEndpoint.EUWest2;
                
Client = new AmazonS3Client(Config);
        
GetObjectRequest req = new GetObjectRequest
{                   
    BucketName = arn:aws:s3::123456789012:accesspoint/<MRAP_alias>,
    Key = filename                    
};

Client.GetObjectAsync(req).Wait();
```

The same code works in non-Unity projects apps with  .NET Core 3.5 and .NET Core 5.0, but when I'm trying to run it in Unity (both .NET Standard 2.1 and .NET Framework), the following error is raised:

> MarshalDirectiveException: Marshalling of non-string and non-blittable arrays to managed code is not implemented. (wrapper native-to-managed) Aws.Crt.Auth.AwsSigner.OnHttpRequestSigningComplete(ulong,int,intptr,ulong,intptr,intptr,unit)

There is also no error when I use a bucket name instead of an access point. 

### Expected Behavior

The requested file is returned

### Current Behavior

MarshalDirectiveException is raised

### Reproduction Steps

In Unity project:

```
Config = new AmazonS3Config();

Config.UseArnRegion = false;
Config.RegionEndpoint = RegionEndpoint.EUWest2;
                
Client = new AmazonS3Client(Config);
        
GetObjectRequest req = new GetObjectRequest
{                   
    BucketName = arn:aws:s3::123456789012:accesspoint/<MRAP_alias>,
    Key = filename                    
};

Client.GetObjectAsync(req).Wait();
```

### Additional Information/Context

Unity 2021.3.8

### AWS .NET SDK and/or Package version used

AWSSDK.Core.3.7.13.12 
AWSSDK.S3.3.7.9.61 
AWSSDK.Extensions.CrtIntegration.3.7.1.4

### Targeted .NET Platform

.NET Standard  2.1

### Operating System and version

Windows 11

**Comment by ashishdhingra** [comment] 2022-10-11 23:12
Needs review with the team since Unity is the special case.

**Comment by ivgnt** [comment] 2022-12-09 06:33
Any updates?

**Comment by peterrsongg** [comment] 2022-12-14 17:57
@ivgnt Hello, there is an open pull request here: https://github.com/awslabs/aws-crt-dotnet/pull/87 that should address the error you were seeing

**Comment by peterrsongg** [comment] 2023-01-26 03:05
@ivgnt  The update to target the new version of crt was included in version 3.7.230.0 . If this fixes your problem feel free to close this issue

**Comment by ivgnt** [comment] 2023-01-26 07:07
@peterrsongg Thank you! Just tested it, and everything works now. Thank you!

**Comment by ivgnt** [comment] 2023-01-30 04:55
So, everything worked fine on windows, but we see this error when building and installing the app on both Android and iOS devices

> CrtException: Could not detect a supported platform
>   at Aws.Crt.Platform.GetRuntimePlatformOS () [0x00000] in <00000000000000000000000000000000>:0
>    at Aws.Crt.CRT+PlatformBinding..ctor () [0x00000] in <00000000000000000000000000000000>:0
>    at Aws.Crt.CRT..cctor () [0x00000] in <00000000000000000000000000000000>:0
>    at Aws.Crt.NativeAPI..cctor () [0x00000] in <00000000000000000000000000000000>:0
>    at Aws.Crt.Auth.AwsSigner+API..cctor () [0x00000] in <00000000000000000000000000000000>:0
>    at Aws.Crt.Auth.AwsSigner.SignHttpRequest (Aws.Crt.Http.HttpRequest request, Aws.Crt.Auth.AwsSigningConfig signingConfig) [0x00000] in <00000000000000000000000000000000>:0
>    at Amazon.Extensions.CrtIntegration.CrtAWS4aSigner.SignRequest (Amazon.Runtime.Internal.IRequest request, Amazon.Runtime.IClientConfig clientConfig, Amazon.Runtime.Internal.Util.RequestMetrics metrics, Amazon.Runtime.ImmutableCredentials credentials) [0x00000] in <00000000000000000000000000000000>:0 
>    at Amazon.Runtime.Internal.Auth.S3Signer.Sign

**Comment by peterrsongg** [comment] 2023-01-30 20:55
@ivgnt thanks for bringing this to our attention. Since the issue is with the library, can you open up an issue there and reference this issue? This is the repo: https://github.com/awslabs/aws-crt-dotnet

**Comment by dscpinheiro** [comment] 2024-07-05 16:34
Closing this as the CRT is not planning to add Android support in .NET.

**Closed by dscpinheiro** 2024-07-05 16:34 UTC
Labels: bug, credentials, p2, queued
