### ISSUE TITLE
An exception occurred in Mobile Analytics Delivery Client : System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Jap9** [aws/aws-sdk-net#773] opened 2017-10-16 14:49 UTC
I am able to get Amazon Mobile Analytics working on Xamarin Android with 3.3.x.x packages but using same config with iOS, it never works and analytics are not reaching amazon dashboard.

I have a Xamarin iOS project, using latest 3.3.x.x packages lead to an empty console log and analytics are not reaching Amazon dashboard, using 3.1.x.x packages are the only ones where logs are working for us, when events are about to get submit, I receive following error:

`2017-10-16 11:14:48.724 awesome.Touch[17398:1264134] DeliveryClient 2|2017-10-16T11:14:48.724Z|DEBUG|7|Event ios_intermediate_threedottwo_awesome_touch_16_dill is queued for delivery
2017-10-16 11:14:48.726 awesome.Touch[17398:1264135] DeliveryClient 2|2017-10-16T11:14:48.724Z|DEBUG|7|Event ios_intermediate_threedottwo_awesome_touch_16_dill is queued for delivery
DeliveryClient 3|2017-10-16T11:14:48.726Z|DEBUG|8|Event _session.start is queued for delivery
2017-10-16 11:14:48.733 awesome.Touch[17398:1264136] DeliveryClient 4|2017-10-16T11:14:48.732Z|DEBUG|9|Event _session.stop is queued for delivery
Thread finished: <Thread Pool> #7
Thread finished: <Thread Pool> #8
Thread finished: <Thread Pool> #6
Thread finished: <Thread Pool> #11
Thread finished: <Thread Pool> #10
Thread started: <Thread Pool> #12
Thread started: <Thread Pool> #13
2017-10-16 11:15:45.851 awesome.Touch[17398:1264030] BackgroundRunner 5|2017-10-16T11:15:45.851Z|INFO|1|Mobile Analytics Manager is trying to deliver events in background thread.
2017-10-16 11:15:45.899 awesome.Touch[17398:1264030] BackgroundRunner 6|2017-10-16T11:15:45.898Z|ERROR|1|An exception occurred in Mobile Analytics Delivery Client : System.NullReferenceException: Object reference not set to an instance of an object
  at Amazon.Util.Internal.PlatformServices.ApplicationInfo.get_AppTitle () [0x0000f] in <49c99bf7d1c04614b8493b6d243339c1>:0 
  at Amazon.Runtime.Internal.ClientContext.ToJsonString () [0x00046] in <49c99bf7d1c04614b8493b6d243339c1>:0 
  at Amazon.MobileAnalytics.MobileAnalyticsManager.Internal.DeliveryClient+<SubmitEvents>d__14.MoveNext () [0x00022] in <226fb962ab5b420cac9af4cfce8049c5>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:447 
  at Amazon.MobileAnalytics.MobileAnalyticsManager.Internal.DeliveryClient+<AttemptDeliveryAsync>d__13.MoveNext () [0x0028c] in <226fb962ab5b420cac9af4cfce8049c5>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113 
  at Amazon.MobileAnalytics.MobileAnalyticsManager.Internal.BackgroundRunner+<DoWorkAsync>d__5.MoveNext () [0x00139] in <226fb962ab5b420cac9af4cfce8049c5>:0  --> System.NullReferenceException: Object reference not set to an instance of an object
  at Amazon.Util.Internal.PlatformServices.ApplicationInfo.get_AppTitle () [0x0000f] in <49c99bf7d1c04614b8493b6d243339c1>:0 
  at Amazon.Runtime.Internal.ClientContext.ToJsonString () [0x00046] in <49c99bf7d1c04614b8493b6d243339c1>:0 
  at Amazon.MobileAnalytics.MobileAnalyticsManager.Internal.DeliveryClient+<SubmitEvents>d__14.MoveNext () [0x00022] in <226fb962ab5b420cac9af4cfce8049c5>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:447 
  at Amazon.MobileAnalytics.MobileAnalyticsManager.Internal.DeliveryClient+<AttemptDeliveryAsync>d__13.MoveNext () [0x0028c] in <226fb962ab5b420cac9af4cfce8049c5>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.0.11/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113 
  at Amazon.MobileAnalytics.MobileAnalyticsManager.Internal.BackgroundRunner+<DoWorkAsync>d__5.MoveNext () [0x00139] in <226fb962ab5b420cac9af4cfce8049c5>:0 `

**Steps to Reproduce (for bugs)**
(Same as @ilpoimigee)
I am only able to reproduce this bug in my specific project environment. Working perfectly in sample and new projects I created to test this functionality.

**Context**
(Same as @ilpoimigee)
AWS Mobile Analytics is not working at all in my solution, and would be really important to be able to understand end user behavior etc.

**Your Environment**

Operating System and version: Mac OS 10.12.6
Visual Studio version: Mac Xamarin Studio 7.2 (build 636)
Targeted platform: Xamarin iOS

(Same as @ilpoimigee)
Following AWS SDK packages in project (note that I am using older versions of AWS SDK as in new versions logging is not working)

"AWSSDK.CognitoIdentity" version="3.1.0.1" targetFramework="xamarinios10"
"AWSSDK.Core" version="3.1.1.0" targetFramework="xamarinios10"
"AWSSDK.MobileAnalytics" version="3.1.1.0" targetFramework="xamarinios10"
"AWSSDK.SecurityToken" version="3.1.0.1" targetFramework="xamarinios10"

**Comment by muellerfr** [comment] 2018-10-09 16:52
Closing as duplicate of #730

**Closed by muellerfr** 2018-10-09 16:52 UTC
Labels: Mobile Analytics, Xamarin
