### ISSUE TITLE
Service URL is ignored if RegionEndpoint is set

### ISSUE THREAD

**Issue by ryancormack** [aws/aws-sdk-net#1781] opened 2021-01-27 10:36 UTC
## Description
When setting a `RegionEndpoint` on the base `ClientConfig` class, the `ServiceURL` [value is ignored](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/ClientConfig.cs#L147), and the clients instead use the `DetermineServiceURL()` method to determine the `ServiceURL`.

This is different behaviour from the CLI SDK, and I can't find this behaviour documented anywhere in the .NET SDK. I'm unsure if this is a bug, or undocumented expected behaviour.

When setting both values, the client will use the credentials passed in, or the FallbackCredentialFactory to grab some from config or env, and result in a `400` error when calling API's.

### .NET code
This is using the DDB Client and DynamoDB Local
```
async Task Main() {
	var clientConfig = new AmazonDynamoDBConfig 	{
		ServiceURL = "http://localhost:8000",
		RegionEndpoint = RegionEndpoint.EUWest1
	};
	var client = new AmazonDynamoDBClient(clientConfig);
	var tableRequest = new DescribeTableRequest 	{
		TableName = "ryan_demo"
	};
	
	var tableDetails = await client.DescribeTableAsync(tableRequest);	
	Console.WriteLine(tableDetails.Table.TableName);
}
```

Expected: "ryan_demo"
Actual: `UnrecognizedClientException` "The security token included in the request is invalid"

### CLI SDK
`>aws dynamodb describe-table --table-name ryan_demo --region eu-west-1 --endpoint-url http://localhost:8000`

Returns:

```
{
    "Table": {
        "AttributeDefinitions": [
            {
                "AttributeName": "pk",
                "AttributeType": "S"
            },
            {
                "AttributeName": "sk",
                "AttributeType": "S"
            }
        ],
        "TableName": "ryan_demo",
///Other properties
```

When removing the RegionEndpoint on the CLI SDK it returns an error saying you _must_ pass in a region endpoint.

### Logs
Will attach a stacktrace

### Environment

* SDK Version: DDB SDK: 3.5.4.20. AWS SDK Core: 3.5.2
* Package Version: 
* OS Info: Windows 10
* Build Environment Linqpad + terminal `dotnet`
* Targeted .NET Platform:  .NET Standard 2.0

## Resolution
- [X] :wave: I can/would-like-to implement a fix for this problem myself
- Remove the RegionEndpoint when using a custom ServiceURL in the .NET Clients

I'm happy to attempt to PR to fix the logic in the SDK Config base class, but unsure if it's actually broken or the CLI SDK is broken, or if it's expected differences in the SDKs, in which case it should be documented.

---

This is a :bug: bug-report

**Comment by ryancormack** [comment] 2021-01-27 10:39
[stacktrace.txt](https://github.com/aws/aws-sdk-net/files/5879539/stacktrace.txt)

**Comment by ashishdhingra** [comment] 2021-01-27 18:59
Hi @ryancormack,

Good morning.

Looking at high level, it appears that your default credentials are not valid. Before we investigate further, could you please check on how your default credentials are configured?

Kindly note that AWS CLI and .NET SDK have different order of precedence when searching for default credentials. More details could be found here:

- .NET SDK: https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/creds-assign.html
- AWS CLI: https://docs.aws.amazon.com/cli/latest/topic/config-vars.html

Thanks,
Ashish

**Comment by ryancormack** [comment] 2021-01-27 19:53
Hi @ashishdhingra 

I am actually having this specific issue when attempting to connect to [DynanmoDB Local](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html), which doesn't validate the signatures on the requests. 
That's why I was trying to set my ServiceURL to the localhost host address. 
But having a look through the SDK code, I can see that when setting a [RegionEndpoint, here](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/ClientConfig.cs#L147), it then sets the ServiceURL to be null.

When the Services go on to [DetermineServiceURL, here](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/ClientConfig.cs#L197), because the ServiceUrl was set to null, the value passed in to the Config is not used if a RegionEndpoint is set *after* settings the Service URL.

I've just tried another test changing the order in the object initializer of the DynamoConfig, and if the ServiceURL is declared after the RegionEndpoint it works as expected, but setting the RegionEndpoint after the ServiceURL it errors.

This works as expected:
```async Task Main() {
	var clientConfig = new AmazonDynamoDBConfig {
		RegionEndpoint = RegionEndpoint.EUWest1,
		ServiceURL = "http://localhost:8000"		
	};
	var client = new AmazonDynamoDBClient(clientConfig);
	var tableRequest = new DescribeTableRequest {
		TableName = "ryan_demo"
	};

	var tableDetails = await client.DescribeTableAsync(tableRequest);
	Console.WriteLine(tableDetails.Table.TableName);
}```

This errors
```async Task Main() {
	var clientConfig = new AmazonDynamoDBConfig {
		ServiceURL = "http://localhost:8000",
		RegionEndpoint = RegionEndpoint.EUWest1				
	};
	var client = new AmazonDynamoDBClient(clientConfig);
	var tableRequest = new DescribeTableRequest {
		TableName = "ryan_demo"
	};

	var tableDetails = await client.DescribeTableAsync(tableRequest);
	Console.WriteLine(tableDetails.Table.TableName);
}```

Again not sure if this is necessarily a bug, but I think it should be documented behaviour? Most services likely have a 1 to 1 mapping between a regionendpoint and a service url, but if you don't supply one, then a default would be used from the `FallbackRegionFactory`, which may have unintended side effects

**Comment by ashishdhingra** [comment] 2021-01-27 20:08
Hi @ryancormack,

I just checked, the behavior that `Service URL is ignored if RegionEndpoint is set` is documented in API reference at https://docs.aws.amazon.com/sdkfornet1/latest/apidocs/html/P_Amazon_Runtime_ClientConfig_ServiceURL.htm (not the latest reference). Unfortunately, it is not documented properly in the latest API reference https://docs.aws.amazon.com/sdkfornet/v3/apidocs/Index.html.

Following code reference in SDK could provide some pointers:
- https://github.com/aws/aws-sdk-net/blob/133eddb00a3fbd2ab395e01c3d84ac9fe1ff38b2/sdk/src/Core/Amazon.Runtime/ClientConfig.cs#L147
- https://github.com/aws/aws-sdk-net/blob/133eddb00a3fbd2ab395e01c3d84ac9fe1ff38b2/sdk/src/Core/Amazon.Runtime/ClientConfig.cs#L172

Setting either of them will negate (set to `null`) the other property and your further detailed testing (and above SDK code) validates this behavior. Based on above data points, this is not a bug. Let me know if this provides necessary guidance and if we could close this issue.

Thanks,
Ashish

**Comment by ryancormack** [comment] 2021-01-27 20:22
Hi @ashishdhingra ,

Thanks for the quick reply. Is there somewhere I could submit a PR to improve the documentation? Whilst it appears to not be a bug in this instance, it feels odd/unintended that depending on the order you set the properties, the clients will exhibit different behaviour, especially without being able to see this in any docs.

We can close the issue as it appears to be the intended behaviour :), 👍🏻 

Thanks,
Ryan

**Comment by ashishdhingra** [comment] 2021-01-27 20:59
Hi @ryancormack,

Thanks for the confirmation. I will take a note of this intended documentation change and discuss with the team. I will keep this issue open until discussion with the development and documentation team.

Regards,
Ashish

**Comment by ashishdhingra** [comment] 2021-02-19 16:59
Documentation at https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Runtime/TClientConfig.html is updated with the following additional text:
```
RegionEndpoint and ServiceURL are mutually exclusive properties. Whichever property is set last will cause the other to automatically be reset to null.
```

**Closed by ashishdhingra** 2021-02-19 16:59 UTC
Labels: bug, doc-apireference, documentation, low-effort, module/sdk-core

**Comment by russau** [comment] 2022-02-10 20:41
@ashishdhingra The boto sdk allows me to set a region AND an endpoint URL.

``` bash
AWS_DEFAULT_REGION=banana python3 - <<EOF
import boto3
ddb = boto3.client('dynamodb', endpoint_url='http://localhost:8000')
ddb.list_tables()
EOF
```

I see the `banana` region in the authorization header going to the Dynamo local server:

```
Authorization: AWS4-HMAC-SHA256 Credential=.../20220210/banana/dynamodb/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-security-token;x-amz-target, Signature=...
```
Dynamo local "remembers" the region where the resources live. It would be nice if I could use this with the .net SDK.  But (as you've said) the region is getting nulled when I set ServiceUrl.  So I have to treat everything as us-east-1.

**Comment by andy-g** [comment] 2022-09-28 11:52
Just for anyone else stumbling onto this thread, I ran into the same issue where setting the `RegionEndpojnt` stopped requests going to localstack, and setting the `ServiceURL` remove all references to the region. Even changing the order didn't work for me as setting the `ServiceURL` after the `RegionEndpoint` successfully got the request to localstack, but because the region info was lost, it didn't map to the correct region in localstack.

Turns out you can specify the `AuthenticationRegion`, which appears to work fine on localstack, and lets you set the `ServiceUrl` to point to localstack. I tested this with EventBridge& Lambda and it seemed to work fine.

**AuthenticationRegion** (https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Runtime/TClientConfig.html)
> Gets and sets the AuthenticationRegion property. Used in AWS4 request signing, this is an optional property; change it only if the region cannot be determined from the service endpoint.

Credit to:
https://stackoverflow.com/questions/71403539/aws-net-sdk-how-to-specify-region-when-using-localstack
