### ISSUE TITLE
describeIdentityAsync too slow in some wifi

### ISSUE THREAD

**Issue by Thaina** [aws/aws-sdk-net#1551] opened 2020-03-09 13:29 UTC
## Expected Behavior
DescribeIdentityAsync should be fast to execute in any wifi network

## Current Behavior
There was some possibility, such as wifi that might not have NAT punch through, to make a call to `describeIdentityAsync` in android unity to stuck for 2-5 minutes before it could return value. There was no other problem except slowness

## Possible Solution
I think there was underlying library, such as `okhttp`, that actually the cause but I don't have evidence. Could there be some way to bypass it from sdk?

Also lambda api and other cognito api work correctly, only DescribeIdentityAsync that have this behaviour

Switching to another wifi or mobile can avoid issue but it not practical for production

## Steps to Reproduce (for bugs)
Just try to call `DescribeIdentityAsync` to get information of identity with some wifi network

## Context
I use `DescribeIdentityAsync` to consider how user should login from android (unity) app. If user have login with facebook, their identityID will linked with facebook and so I could silently login with facebook immediately

## Your Environment
* AWSSDK.Core version used: 3.3.691.0
* Operating System and version: Android 10
* Targeted .NET platform: Unity3D

**Comment by klaytaybai** [comment] 2020-03-09 19:04
Hello @Thaina, I have a couple things that might be able to help, but if the issue is with the network on the client, there is not much we'll be able to do.

1. DescribeIdentityAsync requires AWS developer credentials, so this call should probably be in your server-side logic.  If you don't specify credentials, this code may be delayed by retry logic as it tries to find valid credentials.

2. We are in the process of deprecating support for the AWS SDK for Unity package in favor of having AWS .NET Unity customers migrate to targeting our AWS SDK for .NET v3.5+ dlls.  You can learn more about how to use our 3.5 preview [here](https://aws.amazon.com/blogs/developer/aws-sdk-for-net-v3-5-preview/).  This would allow you to use all AWS services in your Unity projects, improve async programming, and get the latest updates to the AWS SDK.

3. If you have Premium Support, consider opening a case with them.  They can help you work with the Cognito team to diagnose why some of your calls are taking too long and get better resolutions if the issue is caused by the AWS service.

**Comment by Thaina** [comment] 2020-03-10 02:16
@klaytaybai

1 - I have forge one special credential that only have permission for `DescribeIdentity` and put it into client. Also it could work properly in normal wifi and mobile network. Just only under some wifi (which as I said, suspiciously have problem about NAT)
It seem like it try to retry logic as you say. But in normal network condition it work perfectly. Only in some it try to retry for seemingly no reason, after waiting for 3 minutes it just work normally. This problem does not seem like it related to credentials as you say so

2 - Thanks

3 - I suspect that it was specifically a problem in SDK because in ios under the same condition it doesn't have this problem. So I am quite sure it was only a problem of dotnet SDK or android sdk (if dotnet SDK wrap over it internally)

**Comment by NGL321** [comment] 2020-09-17 04:02
Hi @Thaina,

I was wondering if klaytaybai's previous guidance helped you resolve your problem, and if not, if you are still experiencing it?

[As of SDK v3.5](https://aws.amazon.com/blogs/developer/aws-sdk-for-net-v3-5-now-generally-available/) we no longer separate Unity support from regular .NET support, if you are having trouble with this transition, please make sure you are [targeting ^.NET 4.0 or ^.NET Standard 2.0](https://docs.unity3d.com/2020.1/Documentation/Manual/dotnetProfileSupport.html) using Unity 2018.0 or later. This means that you can have full access to AWS services when using the .NET SDK with Unity, but if you would still like to use the legacy SDK for Unity, you can reference it from our [archive repo](https://github.com/aws/aws-sdk-unity-net)

Let me know if there is anything else I can help with!

😸 😷

**Comment by Thaina** [comment] 2020-09-17 04:19
@NGL321 Thanks. I was updated sdk in my project regularly and, I don't know since which update but, currently now it seem this problem was not present to me for such times. I am not sure it truly fixed but it might be already

**Comment by NGL321** [comment] 2020-09-17 04:22
Excellent! So glad to hear it! 😄 

I am going to close this issue for now then, but if you run into the problem again, don't hesitate to hit "reopen".

😸 😷

**Closed by NGL321** 2020-09-17 04:22 UTC
Labels: Unity, documentation, guidance, response-requested
