### ISSUE TITLE
Why can't we cancel requests?

### ISSUE THREAD

**Issue by helbize** [aws/aws-sdk-net#1309] opened 2019-06-07 21:07 UTC
[Other AWS SDKs can cancel requests](https://github.com/aws/aws-sdk-js/issues/1616)

[HttpClient supports cancelling requests](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.sendasync?view=netframework-4.8#System_Net_Http_HttpClient_SendAsync_System_Net_Http_HttpRequestMessage_System_Net_Http_HttpCompletionOption_System_Threading_CancellationToken_).

But every async call in the SDK that takes in a CancellationToken has the following comment:
> A cancellation token that can be used by other objects or threads to receive notice of cancellation.

And looking at the underlying code the cancellation token is never passed into the HttpClient. There are many different ways that doing an operation with S3 can fail, not allowing the client to cancel an operation and retry it after a period of time seems like a pretty big oversight.

**Comment by mbp** [comment] 2019-10-21 09:02
Would also like to know this.

**Comment by mbp** [comment] 2019-10-23 18:29
@helbize I have tested it, and it seems it is actually possible to cancel requests

E.g. do something like
```
using (var cts = new CancellationTokenSource(TimeSpan.FromSeconds(2)))
{
    var response = await client.UpdateItemAsync([...], cts.Token);
}
```

It will throw `TaskCanceledException` if it takes more than 2 seconds.

Internally the cancellation token is passed all the way to HttpClient.SendAsync: https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Pipeline/HttpHandler/_mobile/HttpRequestMessageFactory.cs#L524

**Comment by helbize** [comment] 2019-10-23 19:02
Hey @mbp.

I could have sworn it used to not pass it in, but I just stepped in and verified you are correct. 

I guess this bug is for clarification then because it seems like the API comments don't match the API implementation.

PS:
For me personally, I've had so many issues with the SDK (especially memory, check out the hashing functions if you want to have a laugh) that I've started the process of rewriting my own implementation for doing REST API calls to S3.

**Comment by lellis1936** [comment] 2020-06-25 19:44
Ability to efficiently cancel a pending upload/download is an obvious requirement, but I've not found any documentation on how to do it properly.  Very unfortunate this is not thoroughly documented by AWS.

But there seems to be a way.  The method requires that you create both the CancellationToken and a CancellationTokenSource, then use the Cancel method of the latter to cancel the request.  The idea for how to do this came from here: https://github.com/aws/aws-sdk-net/issues/938.

Create a transferTokenSource and then a transferToken:

    var transferTokenSource = new TransferTokenSource();
    var transferToken = new TransferToken(transferTokenSource);

Specify the token on your UploadAsync or DownloadAsync request, and issue 

    transferTokenSource.Cancel();

where you need to cancel.

Whether or not this is an officially sanctioned approach, I cannot say.  It would be nice if someone could validate it, but it seems to be working for me.

**Comment by philasmar** [comment] 2020-07-15 19:32
Hello,

I have tested the above issue with the code snippet mentioned using both the S3 Client and TransferUtility while incorporating a Cancellation Token, and the issue seems to be fixed as of the following versions:
AWSSDK.Core 3.3.107.24
AWSSDK.S3 3.3.111.25

I will proceed with closing the issue. 
If you think the issue is not resolved, feel free to reopen or create a new ticket.

**Closed by philasmar** 2020-07-15 19:32 UTC

**Comment by JamesWJPS** [comment] 2022-07-06 21:23
I seem to have a problem passing the cancellation again. If it is set the cancelled when the process start it doesn’t run. But if I’d changed during the process it doesn’t seem to have an effect!

**Comment by iforapsy** [comment] 2024-01-18 21:52
@JamesWJPS My coworker tested cancelling in-progress multipart uploads two days ago. He was using version 3.7.305.9 of AWSSDK.S3.dll and found the cancellation works as expected.

Some tips we discovered:
- When testing, use a low timeout value, like 100 milliseconds:
`CancellationTokenSource cts = new CancellationTokenSource(TimeSpan.FromMilliseconds(100))`
- Additionally, make sure the stream or file you are passing to TransferUtility is larger than [`_minSizeBeforePartUpload`](https://github.com/aws/aws-sdk-net/blob/main/sdk/src/Services/S3/Custom/Transfer/TransferUtilityConfig.cs#L43C1-L43C68), which is currently 16 MiB. Regardless if your stream is seekable or supports the `.Length` property, for efficiency TransferUtility will use a single s3:PutObject call for streams/files shorter than that threshold. Logically, if there's only a single HTTP request, the transfer is atomic and cannot be canceled partway. When he tested with streams large enough to use the multipart upload mode, my coworker found cancellation worked perfectly. It even threw the expected `System.Threading.Tasks.TaskCanceledException` when it was cancelled.
