### ISSUE TITLE
[S3Client] AddPartETags when completing multi-part copy should include all checksum values

### ISSUE THREAD

**Issue by dhhoang** [aws/aws-sdk-net#3059] opened 2023-09-28 07:00 UTC
### Describe the bug

I am trying to copy an S3 object (following the [user guide](https://docs.aws.amazon.com/AmazonS3/latest/userguide/CopyingObjectsMPUapi.html)) and set checksum as SHA256:
```csharp
var initResponse = await s3Client.InitiateMultipartUploadAsync(new InitiateMultipartUploadRequest
{
    BucketName = destinationBucket,
    Key = destinationKey,
    ChecksumAlgorithm = ChecksumAlgorithm.SHA256
});
```
However the error occurs when `CompleteMultipartUploadRequest` is called.

### Expected Behavior

The multi-part copy should succeed after all the parts are copied.

### Current Behavior

`CompleteMultipartUpload` failed with the following exception
```
failed: Amazon.S3.AmazonS3Exception: The upload was created using a sha256 checksum. The complete request must include the checksum for each part. It was missing for part 1 in the request.
 ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
```

### Reproduction Steps

Follow the [user guide](https://docs.aws.amazon.com/AmazonS3/latest/userguide/CopyingObjectsMPUapi.html) and set checksum function as SHA256

### Possible Solution

It turns out that `AddPartEtag` only add the `Etag` part of the `CopyPartResponse` object, and not the rest of the checksum:
https://github.com/aws/aws-sdk-net/blob/094b7c7e7c3237b5597647e2264ef4877ba5cec1/sdk/src/Services/S3/Custom/Model/CompleteMultipartUploadRequest.cs#L423

In my opinion this call should add all the checksum fields to the `PartETag` object.

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.205.2

### Targeted .NET Platform

net6.0

### Operating System and version

Windows, Linux, AWS Lambda

**Comment by ashishdhingra** [comment] 2023-09-28 19:17
Reproducible using customer's code. Below are the observations:
- [CompleteMultipartUploadRequest.AddPartETags(IEnumerable<CopyPartResponse> responses)](https://github.com/aws/aws-sdk-net/blob/5c2ad72816351c65a788578f36b7f8b822df56c6/sdk/src/Services/S3/Custom/Model/CompleteMultipartUploadRequest.cs#L423) uses [PartETag(int partNumber, string eTag)](https://github.com/aws/aws-sdk-net/blob/094b7c7e7c3237b5597647e2264ef4877ba5cec1/sdk/src/Services/S3/Custom/Model/PartEtag.cs#L53) constructor, which just sets `partNumber` and `eTag` properties. It does not set any of the checksum properties.
- Class [PartETag](https://github.com/aws/aws-sdk-net/blob/094b7c7e7c3237b5597647e2264ef4877ba5cec1/sdk/src/Services/S3/Custom/Model/PartEtag.cs#L31C18-L31C26) **does not** have an overloaded construction with `CopyPartResponse` type argument (similar to constructor with `UploadPartResponse` type).
  - Since S3 code is mostly hand-written, this appears to be a oversight for the checksum scenario.

**Possible Fix:**
Add overloaded constructor in PartETag](https://github.com/aws/aws-sdk-net/blob/094b7c7e7c3237b5597647e2264ef4877ba5cec1/sdk/src/Services/S3/Custom/Model/PartEtag.cs#L31C18-L31C26) class which accepts and uses `CopyPartResponse` type as parameter. Then use that overloaded constructor in [CompleteMultipartUploadRequest.AddPartETags(IEnumerable<CopyPartResponse> responses)](https://github.com/aws/aws-sdk-net/blob/5c2ad72816351c65a788578f36b7f8b822df56c6/sdk/src/Services/S3/Custom/Model/CompleteMultipartUploadRequest.cs#L423)

**Comment by ashishdhingra** [comment] 2023-10-06 11:13
Released in https://www.nuget.org/packages/AWSSDK.S3/3.7.205.8.

**Closed** 2023-10-06 11:13 UTC
Labels: bug, s3, p2, queued
