### ISSUE TITLE
Missing Models for SES

### ISSUE THREAD

**Issue by davhdavh** [aws/aws-sdk-net#3445] opened 2024-08-16 02:49 UTC
### Describe the feature

https://docs.aws.amazon.com/ses/latest/dg/notification-contents.html#top-level-json-object

These objects are not found in any Models

### Use Case

Those models are part of the aws ses API, and yet not included anywhere as an actual model object.

Therefore deserializing them currently requires manually creating these objects.

### Proposed Solution

Add them

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

Latest

### Targeted .NET Platform

NA

### Operating System and version

NA

**Comment by ashishdhingra** [comment] 2024-08-16 15:53
@davhdavh Good morning. Could you please share the following:
- SES [Amazon Simple Email Service](https://docs.aws.amazon.com/ses/latest/APIReference/index.html) and [Amazon Simple Email Service v2](https://docs.aws.amazon.com/ses/latest/APIReference-V2/Welcome.html) that specifies `Notification` shape/model. AWS SDK(s) are generated from service models and [ses](https://github.com/aws/aws-models/blob/master/sesv2/2019-09-27/api-2.json) API model doesn't specify any shape for notification type.
  
  Please share the SES API model which specifies details of notification type.

- Looking at [Receiving Amazon SES notifications using Amazon SNS](https://docs.aws.amazon.com/ses/latest/dg/monitor-sending-activity-using-notifications-sns.html), it appears to demonstrate sending SES notifications using SNS service. The link [Amazon SNS notification contents for Amazon SES](https://docs.aws.amazon.com/ses/latest/dg/notification-contents.html) mentions details about the JSON contents of notifications which could be processed by the receiver. As such, this JSON object is outside the control of SDK and cannot be used further to invoke service API operations using SDK. AWS SDK(s) are modeled to invoke service API operations using a request object and receiving the response object as a result of service API operation.

  As an example, Lambda repository https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src contain classes that model events for various service actions. These event classes are defined outside of the SDK. Refer [Java Lambda library](https://github.com/aws/aws-lambda-java-libs/tree/main/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events) as well.

- Reproducible code example that demonstrates how you are receiving and trying to deserialize SES notifications.

Thanks,
Ashish

**Comment by davhdavh** [comment] 2024-08-17 06:29
I would say that this object is generated as part of sending an email and just because it is delivered through sns due to the multi-day async nature of emails it is still a response object of sending said email

**Comment by normj** [comment] 2024-08-22 00:30
@davhdavh The SDK generator only generates types and serializers/deserializers for types that are used for making API calls with the service client. We have wanted to also support generation of these sort of auxiliary types used outside of the service client typically used for Lambda event objects or in this case SNS messages. We don't yet have the internal mechanisms setup for service teams to communicate these schemas with us and we have to figure out where to publish those types. It is a wider challenge then just the .NET SDK because we want to solve this for all SDKs. We want to provide a solution to this challenge but I can't provide a timeline when that will happen. Till then you have to manually parse the JSON or create your own version of the type and deserialize the JSON to it.

**Comment by ashishdhingra** [comment] 2024-08-22 15:59
@davhdavh Please review the inputs provided by Norm. Due to the same reason, we have hand written event POCO classes in https://github.com/aws/aws-lambda-dotnet repository. Closing this issue since the service API models are already generated for SES and the custom event or POCO classes need to be written by hand. The issue would be addressed automatically if SDK(s) come up with some mechanism to generate such types automatically.

**Closed by ashishdhingra** 2024-08-22 15:59 UTC
Labels: feature-request, response-requested, module/sdk-generated, p2
