### ISSUE TITLE
Xamarin AWSSDK.S3 System.NullReferenceException at Amazon.S3.Util.BucketRegionDetector.GetUsEast1ClientFromCredentials

### ISSUE THREAD

**Issue by MrClockOff** [aws/aws-sdk-net#1144] opened 2018-12-13 11:29 UTC
Using 
`TransferUtility.UploadAsync(string filePath, string bucketName, string objectKey, CancelationToken cancelationToken)` 
throws 
`System.NullReferenceException: Object reference not set to an instance of an object. at Amazon.S3.Util.BucketRegionDetector.GetUsEast1ClientFromCredentials` 
on both Android and iOS.

## Expected Behavior
File is transferred successfully.

## Current Behavior
The above exception is thrown when trying to upload the file.

## Possible Solution
Not known

## Steps to Reproduce (for bugs)
The way I'm getting credentials.:
User authenticates against User Pool and then exchanges user pool credentials into Identity Pool credentials through credentials provider:

```
var client = new AmazonCognitoIdentityProviderClient(new AnonymousAWSCredentials(), new AmazonCognitoIdentityProviderConfig
            {
                RegionEndpoint = RegionEndpoint.GetBySystemName("eu-west-1"),
                HttpClientFactory = new AndroidClientFactory()
            });
var userPool = new CognitoUserPool(UserPoolId, ClientId, client);
var cognitoUser = new CognitoUser(email, ClientId, userPool, client, username: userName);

cognitoUser.SessionTokens = new CognitoUserSession(idToken, accessToken, refreshToken, issuedTime, expirationTime);
          
var  credentials = cognitoUser.GetCognitoAWSCredentials(IdentityPoolId, RegionEndpoint.GetBySystemName("eu-west-1"));
```

The way I am creating transfer client:

```
var s3ClientConfig = new AmazonS3Config
            {
                HttpClientFactory = new AndroidClientFactory(),
                RegionEndpoint = RegionEndpoint.GetBySystemName("eu-west-1")
            };
            var s3Client = new AmazonS3Client(credentials, s3ClientConfig);

var transferUtility =  new TransferUtility(s3Client);
```

The way I'm using transfer utility:

```
transferUtility.UploadAsync(filePath, BucketName, key, cancelationToken);
```

Android Client factory:

```
    internal class AndroidClientFactory : IHttpClientFactory
    {
        public HttpClient CreateHttpClient(IClientConfig clientConfig)
        {
            return new HttpClient(new AndroidClientHandler());
        }
    }
```
## Context
Client app tries to upload the file to S3 bucket

## Your Environment

* AWSSDK.Core version used: 
```
AWSSDK.CognitoIdentity 3.3.2.55
AWSSDK.CognitoIdentityProvider 3.3.11.24
AWSSDK.Core 3.3.29.14
AWSSDK.Extensions.CognitoAuthentication 0.9.4
AWSSDK.S3 3.3.31.1
AWSSDK.SecurityToken 3.3.4.36
```

* Service assembly and version used: 
N/A

* Operating System and version: 
`OSX 10.13.6`

* Visual Studio version: 
```
Visual Studio Community 2017 for Mac
Version 7.7.1 (build 15)
Installation UUID: 7f52398b-6e25-47b7-9c1c-4ebc7cc2e695
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000221

Mono Framework MDK
Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221

NuGet
Version: 4.7.0.5148

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 10.1 (14460.46)
Build 10B61

Xamarin.Mac
Version: 5.2.1.12 (Visual Studio Community)
Hash: 65ec520f
Branch: 
Build date: 2018-12-05 12:06:09-0500

Xamarin.iOS
Version: 12.2.1.12 (Visual Studio Community)
Hash: 65ec520f
Branch: d15-9
Build date: 2018-12-05 12:06:09-0500

Xamarin.Android
Version: 9.1.4.2 (Visual Studio Community)
Android SDK: /Users/xxx/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.1

Java SDK: /Users/xxx/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
openjdk version "1.8.0-9"
OpenJDK Runtime Environment (build 1.8.0-9-microsoft-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 7.7.1.0
Hash: 06ceaea1

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 707010015
Git revision: a7ca4daaf7add8fe05ed137fdd51bd9eb77758a7
Build date: 2018-12-05 20:15:35+00
Build branch: release-7.7
Xamarin extensions: 40f5fc1b44727b10b1e7bb1ada3aae33516569ce

Operating System
Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```

* Targeted .NET platform: 
```
Xamarin.iOS 12.2.1.12
Xamarin.Android 9.1.4.2
```

## .NET Core Info

N/A

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment] 2018-12-13 18:14
Hi @MrClockOff, I think this issue is a duplicate of #1016.  Another user indicated that adjusting Trust relationships would help resolve the issue but didn't provide too many details.  When I learn more about this, I'll let you know.   I would appreciate it if you could do the same.  It seems to be a recurring issue, so hopefully we can start working on a better UX.

**Closed by klaytaybai** 2018-12-13 18:14 UTC
Labels: duplicate

**Comment by DhirajSonavane** [comment] 2019-10-17 01:24
I have managed to resolve this error by updating trust relationship in AWS console. 

1. Login to your AWS console
2. Go To IAM
3. On left tab, click 'Roles'
4. Now click on 'Trust Relationships' tab
5. Click on 'Edit Trust Relationship'

Basically your identity pool which is assigned to your cognito user pool should have access to S3.

eg. policy json:

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "cognito-identity.amazonaws.com"
      },
      "Action": "sts:AssumeRoleWithWebIdentity"
    }
  ]
}
