### ISSUE TITLE
DynamoDBContext SaveAsync doesn't update empty lists

### ISSUE THREAD

**Issue by antmeehan** [aws/aws-sdk-net#1995] opened 2022-03-15 03:59 UTC
## Description
When using SaveAsync from DynamoDBContext, fields that are an empty list (eg `List<string>`) are not included in the PUT request to DynamoDB and hence are not correctly updated.

## Reproduction Steps
```cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.DataModel;
using Xunit;

namespace AntMeehan.DynamoDbSaveEmptyList;

public class SaveEmptyListTests
{
    [Fact]
    public async Task EmptyListShouldBeSaved()
    {
        // Arrange
        //  aws dynamodb create-table --endpoint-url http://localhost:8000 --table-name TestModel --attribute-definitions AttributeName=HashKey,AttributeType=S --key-schema AttributeName=HashKey,KeyType=HASH --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5

        var context = new DynamoDBContext(new AmazonDynamoDBClient(new AmazonDynamoDBConfig() {ServiceURL = "http://localhost:8000"}));

        var model = new TestModel()
        {
            HashKey = "MyKey",
            MyList = new List<string>() {"Value1", "Value2"}
        };

        await context.SaveAsync(model);
        
        // Act
        model.MyList.RemoveAll(_ => true);

        await context.SaveAsync(model);
        
        // Assert
        var updatedModel = await context.LoadAsync<TestModel>("MyKey");
        
        Assert.Empty(updatedModel.MyList);
    }

    public class TestModel
    {
        [DynamoDBHashKey]
        public string HashKey { get; set; }
        
        public List<string> MyList { get; set; } 
    }
}
```

### Environment
See .csproj file:
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0"/>
        <PackageReference Include="xunit" Version="2.4.1"/>
        <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.0.83" />
    </ItemGroup>
</Project>
```

## Resolution
- [x] :wave: I can/would-like-to implement a fix for this problem myself

https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/DynamoDBv2/Custom/DataModel/ContextInternal.cs#L228 Needs to change so it doesn't consider the length of the list.

Note this would be a breaking change in behaviour, but I can't imagine why you wouldn't want to persist an empty list (rather than a `null` one).

---

This is a :bug: bug-report

**Comment by antmeehan** [comment] 2022-03-15 14:34
Created PR - https://github.com/aws/aws-sdk-net/pull/1997

**Comment by ashishdhingra** [comment] 2022-03-15 16:01
Needs review with the team.

**Comment by peterrsongg** [comment] 2022-11-08 17:07
@antmeehan Hello, there is a special parameter you can specify in the Config called `Conversion`. If you set this to V2, you will be able to send empty lists. This is because by default V1 uses sets, which can't be empty while V2 uses lists which can be empty.So if you want to be able to save empty lists and send empty lists, 
you need to specify V2 in your config like so:
```
            var config = new DynamoDBContextConfig
            {
                Conversion = DynamoDBEntryConversion.V2
            };

```
I'm going to close this issue out since this is not a bug, but if there's anything you'd like to add I'd be happy to reopen it :)

**Closed by peterrsongg** 2022-11-08 17:07 UTC
Labels: bug, pr/needs-review, module/dynamodb, p2, queued
